import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { buffer, point } from '@turf/turf';
import type { Feature, Polygon } from 'geojson';
import type { ProjectPackage, TouristAppealRating } from '../src/domain/models';
import { defaultMethodology } from '../src/domain/scoring';
import { townDogAccessScoreAdjustment, townScoreAfterDogAccess, townScoreBand } from '../src/domain/tourism';
import { validateFeatures } from '../src/domain/validation';

const reviewedAt='2026-08-30'; const createdAt=`${reviewedAt}T10:00:00.000Z`;
const osmCopyright='https://www.openstreetmap.org/copyright'; const outdoorCode='https://www.outdooraccess-scotland.scot/dog-owners';
const osm=(type:'node'|'way',id:number)=>`https://www.openstreetmap.org/${type}/${id}`;
interface Seed { id:string; requestedName:string; name:string; centre:[number,number]; radius:number; score:number; dogRating:TouristAppealRating; character:string; rationale:string; sourceUrl:string; boundaryConfidence?:ProjectPackage['project']['boundaryConfidence'] }
const seeds:Seed[]=[
  {id:'caldhame-scotland',requestedName:'Caldhame',name:'Caldhame',centre:[-2.8623405,56.6257973],radius:600,score:26,dogRating:1,character:'Small rural Angus hamlet',rationale:'Caldhame is retained as a distinct mapped hamlet without inheriting Forfar or Kingsmuir visitor interest.',sourceUrl:osm('node',3524633822)},
  {id:'kingsmuir-scotland',requestedName:'Kinsmuir',name:'Kingsmuir',centre:[-2.8514232,56.6327468],radius:800,score:40,dogRating:2,character:'Rural village north-east of Forfar',rationale:'The requested spelling resolves to Kingsmuir. It has genuine village identity but insufficient verified visitor depth for a 60+ town marker.',sourceUrl:osm('node',3524604372)},
  {id:'muir-of-lownie-scotland',requestedName:'Lownie Moor',name:'Muir of Lownie',centre:[-2.8436813,56.6250203],radius:550,score:20,dogRating:1,character:'Rural Angus locality',rationale:'The contextual request resolves to Muir of Lownie, a named rural locality rather than an independent visitor destination.',sourceUrl:osm('node',3524599658)},
  {id:'craichie-scotland',requestedName:'Craichie',name:'Craichie',centre:[-2.8112338,56.6146289],radius:700,score:32,dogRating:1,character:'Small rural Angus village',rationale:'Craichie remains selectable without borrowing attraction value from Forfar or neighbouring estates.',sourceUrl:osm('node',3524582668)},
  {id:'whigstreet-scotland',requestedName:'Whigstreet',name:'Whigstreet',centre:[-2.8447094,56.5862011],radius:700,score:34,dogRating:1,character:'Historic rural Angus village',rationale:'Whigstreet has a distinct mapped identity but no verified complete visitor-town offer.',sourceUrl:osm('node',3922238270)},
  {id:'kirkbuddo-scotland',requestedName:'Kirkbuddo',name:'Kirkbuddo',centre:[-2.8132232,56.5804359],radius:700,score:34,dogRating:1,character:'Historic rural Angus village',rationale:'Kirkbuddo remains a regional reference and does not inherit the value of attractions elsewhere in the parish.',sourceUrl:osm('node',3922238269)},
  {id:'gallowfauld-scotland',requestedName:'Gallowfaul',name:'Gallowfauld',centre:[-2.9104062,56.5694219],radius:550,score:20,dogRating:1,character:'Rural Inverarity property locality',rationale:'The requested spelling resolves to Gallowfauld near Inverarity and Gateside; it is not an independently visitable settlement.',sourceUrl:osm('node',5285130182)},
  {id:'inverarity-scotland',requestedName:'Imverarity',name:'Inverarity',centre:[-2.8948294,56.5861681],radius:850,score:46,dogRating:2,character:'Small historic Angus village',rationale:'The requested spelling resolves to Inverarity. The village has historic character but remains below 60 pending a complete destination audit.',sourceUrl:osm('node',3922238271)},
  {id:'gateside-inverarity-scotland',requestedName:'Gateside',name:'Gateside',centre:[-2.9156362,56.5871888],radius:650,score:28,dogRating:1,character:'Small hamlet beside Inverarity',rationale:'This resolves to Gateside beside Inverarity and Gallowfauld, not Gateside near Careston or Bowriefauld.',sourceUrl:osm('node',3922238272)},
  {id:'wester-foffarty-scotland',requestedName:'Foffarty',name:'Wester Foffarty',centre:[-2.9531860,56.5977702],radius:550,score:22,dogRating:1,character:'Rural Glamis estate locality',rationale:'The contextual request resolves to Wester Foffarty, a named rural locality rather than a tourist settlement.',sourceUrl:osm('node',4173565606)},
  {id:'kirkton-glamis-scotland',requestedName:'Kirkton',name:'Kirkton',centre:[-2.9436028,56.6082466],radius:700,score:32,dogRating:1,character:'Small Glamis-area village',rationale:'This resolves to Kirkton beside Foffarty and Douglastown, not the other Angus Kirktons. Nearby Glamis attractions do not inflate its score.',sourceUrl:osm('node',3911825747)},
  {id:'thornton-glamis-scotland',requestedName:'Thornton',name:'Thornton',centre:[-2.9818559,56.6063548],radius:550,score:22,dogRating:1,character:'Rural Glamis hamlet',rationale:'This resolves to Thornton near Glamis and is retained independently from Glamis village and castle.',sourceUrl:osm('node',4173564439)},
  {id:'douglastown-angus-scotland',requestedName:'Douglastown',name:'Douglastown',centre:[-2.9516408,56.6140626],radius:800,score:42,dogRating:2,character:'Historic planned Angus village',rationale:'Douglastown has a distinct planned-village character, but not enough independently verified visitor infrastructure for a town marker.',sourceUrl:osm('node',3911825746)},
];
function packageFor(seed:Seed):ProjectPackage{const boundary=buffer(point(seed.centre),seed.radius,{units:'metres',steps:48}) as Feature<Polygon>;const band=townScoreBand(seed.score);const pkg:ProjectPackage={project:{id:seed.id,name:seed.name,countryCode:'GB-SCT',country:'Scotland',region:'Angus',locality:seed.name,centre:seed.centre,boundary,boundarySource:'Mapped named-place location with a conservative editorial study buffer',boundaryConfidence:seed.boundaryConfidence??'high',sourceLanguage:'English',preferredBasemap:'voyager',createdAt,methodology:defaultMethodology,researchNotes:'Catalogue-addition settlement gate. Nearby attractions and heritage properties do not inflate the settlement score.',touristAppeal:{score:seed.score,dogOwnerScore:townScoreAfterDogAccess(seed.score,seed.dogRating),dogAccessScoreAdjustment:townDogAccessScoreAdjustment(seed.dogRating),rating:band.rating,label:band.label,summary:`${seed.name} is retained as an Angus regional reference pending any full destination audit.`,dogAccessRating:seed.dogRating,dogAccessSummary:'No destination-scale dog visit or dedicated dog facilities are verified.',methodVersion:'2026-08-30-strict-settlement-gate-v1',reviewedAt,sourceUrls:[seed.sourceUrl,osmCopyright,outdoorCode]},visitorHighlights:[],townGuide:{characterTag:seed.character,headline:'A recorded place pending any full destination audit',intro:seed.rationale,bestFor:['Regional reference'],perfectFor:['Identifying the locality while planning a wider Angus route'],dontMiss:[],suggestedTime:'Pass-through or pre-arranged visit only',visitorMood:'Kept in the selector with its assessed score, but deliberately absent from the tourist-town map below 60.',sourceUrls:[seed.sourceUrl,osmCopyright],lastReviewedAt:reviewedAt},townStudyArea:{localityName:seed.name,sourceName:'Mapped named-place location',sourceUrl:seed.sourceUrl,sourceVersion:reviewedAt,bufferMetres:seed.radius,localityBoundary:boundary,bufferedBoundary:boundary,notes:'Reference study area only; not an administrative boundary. Local HES records are selected against this transparent boundary.'}},features:[],sources:[{id:`${seed.id}-locality`,name:`${seed.name} place gate`,organisation:'OpenStreetMap contributors / cited mapping evidence',coverage:seed.name,accessMethod:'Mapped place identification and boundary-aware editorial review',sourceUrl:seed.sourceUrl,licence:'OpenStreetMap data under ODbL where used.',reliability:'secondary',limitations:'Preliminary catalogue gate; nearby attractions are not transferred into the settlement score.'}],historicMaps:[],settlementPolygons:[],validation:[]};pkg.validation=validateFeatures(pkg.project,pkg.features);return pkg;}
const packages=seeds.map(packageFor);for(const pkg of packages)await writeFile(resolve('data/projects',`${pkg.project.id.replace(/-scotland$/,'')}.json`),`${JSON.stringify(pkg,null,2)}\n`,'utf8');
const plannerPath=resolve('data/cairn-o-mount-visitor-planner-curation.json');const dogPath=resolve('data/cairn-o-mount-dog-access-curation.json');const planner=JSON.parse(await readFile(plannerPath,'utf8'));const dog=JSON.parse(await readFile(dogPath,'utf8'));for(const seed of seeds){planner.projects[seed.id]={};dog.projects[seed.id]={};}planner.reviewedAt=reviewedAt;dog.reviewedAt=reviewedAt;await Promise.all([writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`,'utf8'),writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`,'utf8')]);
await writeFile(resolve('data/review/inverarity-douglastown-locality-additions-2026-08-30.json'),`${JSON.stringify({schemaVersion:1,reviewedAt,threshold:60,rule:'Every resolved place remains selectable with its canonical score; only independently worthwhile settlements scoring 60 or more appear as town markers.',namingDecisions:['Kinsmuir resolves to Kingsmuir.','Lownie Moor resolves to Muir of Lownie.','Gallowfaul resolves to Gallowfauld.','Imverarity resolves to Inverarity.','Foffarty resolves to Wester Foffarty.','Gateside resolves to the Inverarity locality; Kirkton and Thornton resolve to the Glamis-area places.'],additions:seeds.map(seed=>({requestedName:seed.requestedName,resolvedName:seed.name,projectId:seed.id,region:'Angus',score:seed.score,dogOwnerScore:townScoreAfterDogAccess(seed.score,seed.dogRating),publishOnTownMap:seed.score>=60,rationale:seed.rationale,sourceUrl:seed.sourceUrl}))},null,2)}\n`,'utf8');console.log(`Added ${packages.length} Inverarity–Douglastown catalogue places; none publish on the town map.`);
