import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { circle } from '@turf/turf';
import type { ProjectPackage } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

// The boundaries below are deliberately small editorial study areas centred on
// the cited current place record. They are not asserted settlement, parish or
// estate boundaries and stop neighbouring visitor facilities being inherited.
const reviewedAt = '2026-09-03';
const sources = {
  hes: 'https://portal.historicenvironment.scot/downloads',
  pkcPaths: 'https://www.pkc.gov.uk/media/49518/Walking-the-Perth-Kinross-Council-Core-paths/pdf/WalkPKCPBookFINAL.pdf',
  outdoor: 'https://www.outdooraccess-scotland.scot/dog-owners',
  trails: 'https://www.treasuretrails.co.uk/collections/scotland',
};

type Place = {
  id: string; name: string; centre: [number, number]; radius: number; character: string;
  score: number; dogScore: number; summary: string; identity: string; exclusions: string[];
  sourceUrls: string[];
};

const places: Place[] = [
  { id: 'coupar-angus-scotland', name: 'Coupar Angus', centre: [-3.2674302, 56.5454171], radius: 850, character: 'Historic market town in Strathmore', score: 54, dogScore: 52, identity: 'Current OSM town record for Coupar Angus, Perth and Kinross.', summary: 'Coupar Angus is a genuine historic market town, but this conservative first-pass guide does not promote its heritage fabric, businesses or former abbey as an independently assessed visitor attraction until current access, interpretation and operator evidence are assembled.', exclusions: ['Private businesses and customer facilities are not treated as visitor provision without a current operator review.', 'The former abbey is not scored from historical importance alone.', 'Nearby Kettins, Burrelton and Blairgowrie facilities are not transferred.'], sourceUrls: [sources.hes, sources.pkcPaths, sources.trails] },
  { id: 'kettins-scotland', name: 'Kettins', centre: [-3.2382965, 56.5362084], radius: 500, character: 'Strathmore village and former parish centre', score: 38, dogScore: 36, identity: 'Current OSM village record for Kettins, Perth and Kinross.', summary: 'Kettins is retained as the parish village reference. Hallyburton House, Pitcur and estate features are separate places and are not represented as publicly visitable without evidence.', exclusions: ['Hallyburton House and Pitcur are separate records.', 'No public café, toilet, parking or named visitor trail was verified inside the strict study area.'], sourceUrls: [sources.hes, sources.pkcPaths, sources.trails] },
  { id: 'markethill-kettins-scotland', name: 'Markethill', centre: [-3.2566617, 56.5382697], radius: 250, character: 'Small Kettins-parish hamlet', score: 20, dogScore: 18, identity: 'Current OSM hamlet record for Markethill, Coupar Angus, Perth and Kinross.', summary: 'Markethill is a recognised rural hamlet, not a separately evidenced visitor stop.', exclusions: ['Coupar Angus amenities and the nearby solar-farm planning area are not visitor assets.', 'No public visitor category was verified.'], sourceUrls: [sources.hes, sources.trails] },
  { id: 'hallyburton-house-scotland', name: 'Hallyburton House', centre: [-3.2246319, 56.5335250], radius: 250, character: 'Private historic estate house', score: 28, dogScore: 26, identity: 'Current mapped estate-house record at Flatfield Road, Kettins.', summary: 'Hallyburton House has documented architectural interest, but no dependable public-admission, visitor facilities or public estate-walk evidence was found; it is not promoted as an attraction.', exclusions: ['Historic England archive imagery documents the house but does not establish visitor access.', 'Estate access, parking and grounds are not assumed public.'], sourceUrls: ['https://historicengland.org.uk/images-books/photos/item/BL10989', sources.hes, sources.trails] },
  { id: 'leys-kettins-scotland', name: 'Leys (Easter and Wester Leys)', centre: [-3.2154575, 56.5258190], radius: 420, character: 'Kettins-parish rural hamlet pair', score: 16, dogScore: 14, identity: 'Combined editorial record for the two current OSM hamlet records, Easter Leys and Wester Leys, in Kettins parish.', summary: 'Leys is retained as the paired rural Kettins-parish locality requested. No independently open attraction, visitor food stop, trail or public practical facility was verified.', exclusions: ['The record deliberately combines Easter and Wester Leys only; it does not cover the wider Hallyburton estate.', 'Farm and residential access is not promoted.'], sourceUrls: [sources.hes, sources.trails] },
  { id: 'pitcur-scotland', name: 'Pitcur', centre: [-3.2184080, 56.5197638], radius: 260, character: 'Historic Kettins-parish hamlet', score: 26, dogScore: 24, identity: 'Current OSM hamlet record for Pitcur, Kettins.', summary: 'Pitcur’s historic names and estate associations are retained without treating private land or unverified remains as a visitor attraction.', exclusions: ['Pitcur Castle and estate history are not published as an accessible visit without current access evidence.', 'No public visitor facility was verified.'], sourceUrls: [sources.hes, sources.trails] },
  { id: 'campmuir-scotland', name: 'Campmuir', centre: [-3.2730931, 56.5251364], radius: 350, character: 'Small Strathmore village', score: 22, dogScore: 20, identity: 'Current OSM village record for Campmuir, Perth and Kinross.', summary: 'Campmuir is a legitimate small village with a council-recorded school transport stop, but that does not establish a visitor transport or practical facility.', exclusions: ['The school-bus contract is not presented as public visitor transport.', 'No independent visitor attraction or public visitor facility was verified.'], sourceUrls: ['https://www.pkc.gov.uk/article/21087/Contract-XSB-008-Campmuir-Woodside-Burrelton-Kinrossie-Perth-Academy', sources.trails] },
  { id: 'woodside-burrelton-scotland', name: 'Woodside', centre: [-3.2877482, 56.5218852], radius: 330, character: 'Burrelton-adjoining village', score: 32, dogScore: 30, identity: 'Current mapped Woodside place record in the Burrelton/Cargill area.', summary: 'Woodside is a distinct historic village adjoining Burrelton. Its church, recreation and former railway context need separate access and facility checks before any visitor cards are published.', exclusions: ['Burrelton services are not duplicated.', 'The former railway station is not a current visitor attraction without access evidence.'], sourceUrls: ['https://burrelton.org/our-heritage/', sources.hes, sources.trails] },
  { id: 'burrelton-scotland', name: 'Burrelton', centre: [-3.3018001, 56.5185379], radius: 520, character: 'Planned Strathmore village', score: 40, dogScore: 38, identity: 'Current OSM village record for Burrelton, Perth and Kinross.', summary: 'Burrelton has a coherent village history and local recreation context, but this strict guide withholds cards until the present status of facilities, access and operators is independently evidenced.', exclusions: ['Village recreation provision is not automatically a visitor attraction.', 'Woodside is retained as a separate locality.'], sourceUrls: ['https://burrelton.org/our-heritage/', sources.pkcPaths, sources.trails] },
  { id: 'saucher-scotland', name: 'Saucher', centre: [-3.3068805, 56.4834952], radius: 250, character: 'Collace-parish hamlet', score: 18, dogScore: 16, identity: 'Current OSM hamlet record for Saucher, Collace.', summary: 'Saucher is a small Collace-parish hamlet. No independently accessible visitor asset, food stop, trail or public practical facility was verified within its strict study area.', exclusions: ['Dunsinane, Collace and Kinrossie are separate places.', 'Private rural access is not inferred from mapped tracks.'], sourceUrls: [sources.hes, sources.pkcPaths, sources.trails] },
  { id: 'collace-scotland', name: 'Collace', centre: [-3.2957613, 56.4774039], radius: 400, character: 'Sidlaw-foot village', score: 42, dogScore: 40, identity: 'Current OSM village record for Collace, Perth and Kinross.', summary: 'Collace has a distinct village identity and lies near Dunsinane, but nearby hill and archaeological interest are not assigned to the village without a verified in-boundary, responsible visitor route.', exclusions: ['Dunsinane Hill and Bandirran are separate records.', 'No qualifying café, public toilet or visitor parking was verified.'], sourceUrls: ['https://www.visionofbritain.org.uk/place/16643', sources.hes, sources.pkcPaths, sources.trails] },
  { id: 'kirkton-of-collace-scotland', name: 'Kirkton of Collace', centre: [-3.30559, 56.47326], radius: 360, character: 'Historic Collace-parish kirkton', score: 44, dogScore: 42, identity: 'Current geographic locality record for Kirkton of Collace, corroborated by historic gazetteer geography.', summary: 'Kirkton of Collace has a council-published circular core-path walk starting by the school and church. It is retained as a trail research candidate rather than published until route containment, current condition and access are checked in the next route pass.', exclusions: ['The core-path PDF is evidence of a route candidate, not proof of an all-year visitor trail card.', 'Dunsinane and Bandirran are not transferred.'], sourceUrls: ['https://www.visionofbritain.org.uk/place/16643', sources.pkcPaths, sources.hes, sources.trails] },
  { id: 'bandirran-scotland', name: 'Bandirran', centre: [-3.2945230, 56.4686116], radius: 300, character: 'Collace-parish hill locality', score: 30, dogScore: 28, identity: 'Current OSM Bandirran Hill place record used as the strict locality centre.', summary: 'Bandirran is retained for its documented stone-circle and hill-locality identity, but neither archaeological significance nor nearby core paths establishes public access or a full visitor experience.', exclusions: ['The stone circle requires a specific current access check before it can be recommended.', 'No food, toilets or public visitor parking was verified.'], sourceUrls: [sources.hes, sources.pkcPaths, sources.trails] },
  { id: 'abernyte-scotland', name: 'Abernyte', centre: [-3.2046028, 56.4671046], radius: 450, character: 'Sidlaw village and former parish centre', score: 42, dogScore: 40, identity: 'Current OSM village record for Abernyte, Perth and Kinross.', summary: 'Abernyte is a distinct Sidlaw village with historic church context, but no public visitor attraction, daytime food stop or practical visitor facility is published without a current operator or council source.', exclusions: ['Nearby Sidlaw walks and private estates are not assigned to the village.', 'Church access is not assumed from heritage status.'], sourceUrls: [sources.hes, sources.pkcPaths, sources.trails] },
  { id: 'rossie-priory-scotland', name: 'Rossie Priory', centre: [-3.1618791, 56.4639888], radius: 300, character: 'Private designed-landscape estate', score: 34, dogScore: 32, identity: 'Current OSM manor record for Rossie Priory, near Inchture.', summary: 'Rossie Priory is a nationally documented designed-landscape and historic estate, but the private house, grounds and associated facilities are not promoted as general visitor access.', exclusions: ['Estate sale material and historic description do not establish current public admission.', 'Knapp is separately represented.'], sourceUrls: ['https://canmore.org.uk/site/30646/rossie-priory', sources.hes, sources.trails] },
  { id: 'knapp-scotland', name: 'Knapp', centre: [-3.1565873, 56.4689466], radius: 250, character: 'Rossie estate hamlet', score: 22, dogScore: 20, identity: 'Current mapped Knapp Lodge/Knapp locality record near Rossie Priory.', summary: 'Knapp is a small hamlet beside the Rossie estate. Heritage references and conservation-area context do not create an open visitor offer.', exclusions: ['Rossie Priory grounds and private residences are not treated as public.', 'No visitor facility or named public trail was verified.'], sourceUrls: [sources.hes, sources.trails] },
  { id: 'littleton-inchture-scotland', name: 'Littleton', centre: [-3.1936964, 56.4932075], radius: 240, character: 'Small rural hamlet near Inchture', score: 16, dogScore: 14, identity: 'Current OSM hamlet record for Littleton, Perth and Kinross (PH14 9SZ).', summary: 'Littleton is retained as a named rural hamlet rather than being absorbed into Inchture; no independent visitor offer was verified.', exclusions: ['Inchture’s services and A90-accessible facilities are not transferred.', 'No public visitor facility was verified.'], sourceUrls: [sources.hes, sources.trails] },
  { id: 'lundie-scotland', name: 'Lundie', centre: [-3.1532765, 56.5157648], radius: 420, character: 'Sidlaw village west of Dundee', score: 38, dogScore: 36, identity: 'Current OSM village record for Lundie, Angus.', summary: 'Lundie is a distinct village in the Angus/Perthshire historic-border area. Its church and surrounding rural landscape are not promoted as a visitor trip without verified access, route and facility evidence.', exclusions: ['Lundie Craigs and private rural land are not automatically assigned to the village.', 'No current public visitor parking, toilets or daytime food stop was verified.'], sourceUrls: [sources.hes, sources.pkcPaths, sources.trails] },
];

function methodology(): ProjectPackage['project']['methodology'] {
  return { age: { before_1700: 1, '1700_1799': .9, '1800_1849': .8, '1850_1899': .65, '1900_1918': .5, '1919_1945': .4, '1946_1960': .25, after_1960: .15, unknown: .2 }, significance: { highest_national: 1, national: .85, regional: .65, local: .45, recognised: .3 }, confidence: { high: 1, medium: .75, low: .5, unknown: .35 }, survival: { substantially_intact: 1, altered_recognisable: .75, heavily_altered: .45, site_only_or_demolished: .2, unknown: .6 } };
}

for (const place of places) {
  const boundary = circle(place.centre, place.radius, { units: 'meters', steps: 32 });
  const project: ProjectPackage['project'] = {
    id: place.id, name: place.name, countryCode: 'GB-SCT', country: 'Scotland', region: place.id === 'lundie-scotland' ? 'Angus' : 'Perth and Kinross', locality: place.name, centre: place.centre,
    boundary: { ...boundary, properties: { sourceDataset: 'Current mapped place record plus reviewed editorial micro-locality study area', localityName: place.name } }, boundarySource: `${place.identity} A small circular editorial study area prevents adjacent settlements, estates and facilities being assigned to this guide.`, boundaryConfidence: 'low', sourceLanguage: 'en', preferredBasemap: 'voyager', createdAt: `${reviewedAt}T12:00:00.000Z`, timelineStart: 1000, timelineEnd: 2026, methodology: methodology(),
    researchNotes: `Sequential identity, boundary and provenance pass completed ${reviewedAt}; visitor categories remain provisional pending completed current operator, facility and wider-web trail research. ${place.exclusions.join(' ')} The study area is a transparent selection tool, not a legal, parish, estate or historic settlement boundary.`,
    touristAppeal: { score: place.score, dogOwnerScore: place.dogScore, dogAccessScoreAdjustment: place.dogScore - place.score, rating: 0, label: 'Minor Interest', summary: place.summary, dogAccessRating: 1, dogAccessSummary: 'No dedicated dog-welcoming visitor experience was verified. Use only lawful public access and follow the Scottish Outdoor Access Code.', methodVersion: '2026-09-03-kettins-collace-sequential-audit-v1', reviewedAt, sourceUrls: [...place.sourceUrls, sources.outdoor] },
    townGuide: { characterTag: place.character, headline: 'A source-labelled rural locality guide', intro: place.summary, bestFor: ['Regional reference'], perfectFor: ['Passing only when already using lawful public access'], suggestedFirstVisit: { title: 'No dedicated visitor itinerary published', summary: 'No independently verified attraction or visitor facility is currently promoted for this strict locality.' }, dontMiss: [], suggestedTime: 'Pass-through only', visitorMood: 'Selector-only; nearby value is not borrowed.', sourceUrls: [...place.sourceUrls, sources.outdoor], lastReviewedAt: reviewedAt },
    townStudyArea: { localityName: place.name, sourceName: 'Current OSM place record and editorial boundary review', sourceUrl: 'https://www.openstreetmap.org/copyright', sourceVersion: reviewedAt, bufferMetres: 0, localityBoundary: { ...boundary, properties: { source: place.identity } }, bufferedBoundary: { ...boundary, properties: { source: place.identity } }, visitorBoundary: { ...boundary, properties: { source: place.identity } }, notes: 'No statutory locality polygon was used for this micro-locality. The small reviewed study area is retained solely to prevent cross-settlement attribution.' },
  };
  const pkg: ProjectPackage = { project, features: [], sources: [
    { id: 'place-identity', name: 'Current mapped place identity', organisation: 'OpenStreetMap contributors', coverage: place.identity, accessMethod: 'Nominatim current-place lookup and manual identity review.', sourceUrl: 'https://www.openstreetmap.org/copyright', licence: 'Open Database Licence (ODbL) v1.0; © OpenStreetMap contributors.', reliability: 'discovery_only', limitations: 'Coordinates and current place names are a starting point only; they do not prove visitor access or historical claims.' },
    { id: 'hes-registers', name: 'Historic Environment Scotland registers', organisation: 'Historic Environment Scotland', coverage: `Statutory and NRHE research context for ${place.name}.`, accessMethod: 'Current official register and designation research.', sourceUrl: sources.hes, licence: 'Open Government Licence v3.0; retain Historic Environment Scotland attribution.', reliability: 'official_statutory', limitations: 'Designation and archive records do not establish visitor access, visitor facilities or construction dates unless separately evidenced.' },
    { id: 'visitor-trail-research', name: 'Current trail-provider and council-path research', organisation: 'Perth & Kinross Council and commercial providers', coverage: 'Place-specific trail and practical-facility screening.', accessMethod: 'Current council core-path publication plus provider catalogue queries.', sourceUrl: sources.pkcPaths, licence: 'Source-linked editorial evidence; retain source attribution.', reliability: 'local_authority', limitations: 'A mapped core path or catalogue search result is not published as a visitor trail until route, access and containment are checked.' }
  ], historicMaps: [], settlementPolygons: [], validation: [] };
  pkg.validation = validateFeatures(pkg.project, pkg.features);
  await writeFile(resolve(`data/projects/${place.id.replace(/-scotland$/, '')}.json`), `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');
  const audit = { schemaVersion: 1, reviewedAt, projectId: place.id, place: place.name, sequentialOrder: places.indexOf(place) + 1, completionStatus: 'provisional_pending_editorial_web_research', identity: place.identity, boundary: { type: 'strict_editorial_micro_locality', radiusMetres: place.radius, source: 'Current mapped place record; no parish, estate or adjoining-settlement geometry substituted.' }, categories: { see: { status: 'provisional_pending_current_research', published: 0 }, eat: { status: 'provisional_pending_current_research', published: 0 }, trails: { status: 'provisional_pending_wider_web_research', published: 0, providerSearches: ['Treasure Trails', 'Curious About', 'Mystery Guides', 'Go Quest Adventures', 'Perth & Kinross Council core paths'] }, parking: { status: 'provisional_pending_current_research', published: 0 }, toilets: { status: 'provisional_pending_current_research', published: 0 }, picnic: { status: 'provisional_pending_current_research', published: 0 } }, score: { visitor: place.score, dogOwner: place.dogScore, classification: 'Provisional selector-only score; not publishable editorial certification', rationale: place.summary }, dogs: { status: 'provisional_no_dedicated_visitor_experience_verified', sourceUrl: sources.outdoor }, sources: [...place.sourceUrls, sources.outdoor], exclusions: place.exclusions, validation: { errors: pkg.validation.filter((item) => item.severity === 'error').length, warnings: pkg.validation.filter((item) => item.severity === 'warning').length } };
  await writeFile(resolve(`data/review/${place.id.replace(/-scotland$/, '')}-full-visitor-audit-${reviewedAt}.json`), `${JSON.stringify(audit, null, 2)}\n`, 'utf8');
  console.log(`${place.id}: ${pkg.validation.length} validation findings`);
}
