import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const projectId = 'east-haven-scotland';
const reviewedDate = '2026-08-30';
const reviewedAt = '2026-08-30T23:59:59.000Z';
const projectPath = resolve('data/projects/east-haven.json');
const plannerPath = resolve('data/cairn-o-mount-visitor-planner-curation.json');
const dogPath = resolve('data/cairn-o-mount-dog-access-curation.json');
const reportPath = resolve('data/review/east-haven-full-visitor-audit-2026-08-30.json');
const correctionPath = resolve('data/review/strict-settlement-score-correction-2026-08-30.json');
type F = HeritageFeature & Record<string, any>;
type P = ProjectPackage & { project: ProjectPackage['project'] & Record<string, any>; features: F[] };
const urls = {
  place: 'https://www.openstreetmap.org/node/242940462',
  community: 'https://www.easthavenangus.com/',
  beach: 'https://www.easthavenangus.com/east-haven-beach',
  beachAward: 'https://www.keepscotlandbeautiful.org/scotlands-beach-awards/beach-map/east-haven/',
  heritage: 'https://www.easthavenangus.com/about-us-3',
  heritagePoint: 'https://www.easthavenangus.com/about-us',
  coastalPath: 'https://www.angus.gov.uk/sites/default/files/2020-10/Arbroath-carnoustie%20path%20network%20leaflet.pdf',
  paths: 'https://www.angus.gov.uk/directories/document_category/path_networks',
  toilets: 'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/easthaven_the_beach',
  parkingOsm: 'https://www.openstreetmap.org/way/409878064',
  picnicOsm: 'https://www.openstreetmap.org/way/651184446',
  toiletsOsm: 'https://www.openstreetmap.org/way/1387757433',
  informationOsm: 'https://www.openstreetmap.org/node/5313822847',
  treasure: 'https://www.treasuretrails.co.uk/collections/dundee-and-angus',
  curious: 'https://www.curiousabout.co.uk/',
  mystery: 'https://www.mysteryguides.co.uk/',
  goQuest: 'https://goquestadventures.com/',
  dogCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
};

const pkg = JSON.parse(await readFile(projectPath, 'utf8')) as P;
const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as any;
const dog = JSON.parse(await readFile(dogPath, 'utf8')) as any;
const correction = JSON.parse(await readFile(correctionPath, 'utf8')) as any;
const scoreAssessment = (score: number) => ({ experienceDepth: Math.round(score*.3), distinctiveness: Math.round(score*.2), presentation: Math.round(score*.2), journeyWorth: Math.round(score*.15), accessAndReliability: Math.round(score*.1), evidenceConfidence: score-Math.round(score*.3)-Math.round(score*.2)-Math.round(score*.2)-Math.round(score*.15)-Math.round(score*.1), visitability: 'full_visitor_experience' as const });
const source = (name: string, organisation: string, url: string, notes: string, reliability: any = 'official_non_statutory', sourceRecordId?: string) => ({ sourceName:name, sourceOrganisation:organisation, sourceUrl:url, sourceRecordId, accessedAt:reviewedAt, reliability, licence:url.includes('openstreetmap.org')?'Open Database Licence (ODbL) v1.0; © OpenStreetMap contributors.':'Source-linked editorial evidence; verify time-sensitive details before travel.', notes });
const make = (spec: Record<string, any>): F => ({
  id:spec.id, projectId, name:spec.name, alternativeNames:[], countryCode:'GB-SCT', region:'Angus', locality:'East Haven', featureType:spec.featureType,
  significance:spec.significance??'local', geometry:{type:'Point',coordinates:spec.coordinates}, locationType:'exact', locationConfidence:'high', dateBasis:'unknown', dateConfidence:'unknown', survival:'substantially_intact', shortDescription:spec.description, visitorWebsiteUrl:spec.website,
  editorialReview:spec.score?{status:'editorially_researched',category:spec.category,methodVersion:'2026-08-30-researched-visitor-value-v1',reviewedAt:reviewedDate,scoreRationale:spec.reason,evidenceUrls:spec.evidenceUrls,attractionAssessment:scoreAssessment(spec.score)}:undefined,
  sourceRecords:spec.evidenceUrls.map((url:string,index:number)=>source(index?`${spec.name} supporting evidence`:spec.sourceName,index?(url.includes('openstreetmap.org')?'OpenStreetMap contributors':'Supporting publisher'):spec.sourceOrganisation,url,`Current-place curation: visitor_place_type=${spec.placeType}; ${spec.score?`visit_score=${spec.score}; `:''}${spec.details}`,url.includes('angus.gov.uk')?'local_authority':url.includes('openstreetmap.org')?'discovery_only':'official_non_statutory',spec.sourceRecordIds?.[index])),
  tags:spec.tags, createdAt:reviewedAt, updatedAt:reviewedAt, reviewed:true, evidenceScope:'parish_evidence',
} as F);

const dates: Record<string,{text:string;earliest:number;latest:number;confidence:string;precision:string;notes:string}> = {
  'nrhe:34490': { text:'Medieval to post-medieval, broadly c. 1100–1800', earliest:1100, latest:1800, confidence:'low', precision:'period_range', notes:'NRHE assigns the rig and furrow to the medieval–post-medieval period; the possible ring ditch remains undated.' },
  'nrhe:34491': { text:'Medieval to post-medieval, broadly c. 1100–1800', earliest:1100, latest:1800, confidence:'low', precision:'period_range', notes:'Broad material period taken from the official NRHE classification.' },
  'nrhe:34492': { text:'Prehistoric, broadly c. 4000 BC–AD 400', earliest:-4000, latest:400, confidence:'low', precision:'period_range', notes:'The official record classifies the enclosure as prehistoric; no narrower material date is claimed.' },
  'nrhe:34493': { text:'Possible Roman camp with medieval–post-medieval cultivation, broadly AD 43–1800', earliest:43, latest:1800, confidence:'low', precision:'period_range', notes:'The official record combines a possible Roman camp with later rig and furrow; the broad range is deliberately low confidence.' },
  'nrhe:193997': { text:'1838–1967', earliest:1838, latest:1967, confidence:'high', precision:'year_range', notes:'The Dundee–Arbroath railway opened in 1838 and East Haven station closed on 4 September 1967; these are operational material dates, not database dates.' },
  'nrhe:268062': { text:'Medieval, broadly c. 1100–1599', earliest:1100, latest:1599, confidence:'medium', precision:'period_range', notes:'Material period of the medieval personal objects; the 21st-century find date is explicitly excluded.' },
  'nrhe:357603': { text:'12th century to post-medieval, broadly c. 1100–1800', earliest:1100, latest:1800, confidence:'medium', precision:'period_range', notes:'Material range from the 12th-century strap fitting through the post-medieval gilt ring.' },
  'nrhe:339467': { text:'Early medieval to post-medieval, broadly c. 500–1800', earliest:500, latest:1800, confidence:'medium', precision:'period_range', notes:'Material range represented by the officially classified early-medieval, medieval and post-medieval objects.' },
};
for (const feature of pkg.features.filter(f=>f.id.startsWith('hes-')||f.id.startsWith('nrhe:'))) {
  feature.tags=[...new Set([...feature.tags,'heritage-record-retained'])]; feature.reviewed=true; feature.updatedAt=reviewedAt;
  const date=dates[feature.id];
  if (!date) { feature.tags=[...new Set([...feature.tags,'map-hidden','date-reviewed'])]; feature.reviewNotes=feature.tags.includes('town-selection-heritage-buffer')?'Buffer record retained intact but hidden because it is outside East Haven and cannot support this village heat layer.':'Record retained intact. No defensible construction or material-period date was found, so it remains map-hidden rather than receiving a guessed date.'; continue; }
  feature.dateBasis=date.earliest===date.latest?'documented_date':'documented_date_range'; feature.dateConfidence=date.confidence; feature.datePrecision=date.precision; feature.documentedDateText=date.text; feature.earliestPossibleYear=date.earliest; feature.latestPossibleYear=date.latest; feature.reviewNotes=date.notes; feature.tags=[...new Set([...feature.tags,'date-reviewed'])].filter((tag:string)=>tag!=='map-hidden');
}

const attractions=[
  make({id:'curated-attraction:east-haven-beach',name:'East Haven Beach',score:82,coordinates:[-2.6657,56.5157],featureType:'coastal_feature',description:'Community-cared sandy and rocky beach with dunes, wildlife, family use, safety equipment and a long-running community beach award.',reason:'A distinctive, well-presented small coastal destination with verified facilities and strong community stewardship; limited parking and seasonal toilets constrain capacity.',website:urls.beach,sourceName:'East Haven Beach',sourceOrganisation:'East Haven Together',evidenceUrls:[urls.beach,urls.beachAward],placeType:'Attraction',category:'attraction',tags:['curated-visitor','current-context'],details:'beach=sandy and rocky; family=yes; wildlife=yes; rescue_equipment=yes; community_beach_award=yes; dog_access=restricted and exercise areas; access=free'}),
  make({id:'curated-attraction:east-haven-heritage-point',name:'East Haven Heritage Point and Coastal Gardens',score:72,coordinates:[-2.6678348,56.5164536],featureType:'interpretation_site',description:'Village interpretation point, Wee Gallery and community coastal gardens telling the story of one of Scotland’s earliest recorded fishing communities.',reason:'A small but unusually well-curated community heritage stop, strengthened by the 1214 fishing-port story and public interpretation but not a staffed museum.',website:urls.heritagePoint,sourceName:'East Haven Heritage Point',sourceOrganisation:'East Haven Together',evidenceUrls:[urls.heritagePoint,urls.heritage,urls.informationOsm],sourceRecordIds:[undefined,undefined,'node/5313822847'],placeType:'Attraction',category:'attraction',tags:['curated-visitor','current-context'],details:'interpretation=yes; wee_gallery=inside seasonal toilet building; community_gardens=yes; earliest_documentary_record=1214'}),
];
const trails=[make({id:'curated-trails:east-haven-coastal-path',name:'Angus Coastal Path via East Haven',score:76,coordinates:[-2.6698,56.5149],featureType:'walking_route',description:'Firm, mostly flat coastal walking and cycling route linking East Haven with Arbroath, Carnoustie and Monifieth, with a tide-dependent beach alternative.',reason:'A useful official linear coastal route with published distances, terrain, transport and facility information; the beach option needs tide and burn-crossing judgement.',website:urls.coastalPath,sourceName:'Angus coastal path: Arbroath to Carnoustie and Monifieth',sourceOrganisation:'Angus Council',evidenceUrls:[urls.coastalPath,urls.paths],placeType:'Trail',category:'trail',tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'],details:'distance=Arbroath to East Haven 7 km one way; walking_time=about 2 hours 15 minutes one way; terrain=firm even surface, mostly flat; cycling=yes; beach_alternative=tide dependent; route_link_checked=2026-08-30'})];
const facilities=[
  make({id:'curated-parking:east-haven-beach',name:'East Haven Beach Car Park',coordinates:[-2.6661303,56.516515],featureType:'parking',description:'Small community-managed beach car park immediately beside the Heritage Point.',website:urls.community,sourceName:'East Haven beach parking',sourceOrganisation:'East Haven Together / Keep Scotland Beautiful',evidenceUrls:[urls.community,urls.beachAward,urls.parkingOsm],sourceRecordIds:[undefined,undefined,'way/409878064'],placeType:'Parking',tags:['service-context-parking','current-context'],details:'access=public; fee=no; price_display=Free; payment_required=no; capacity=Limited, exact count not published; coordinate_source=OpenStreetMap car-park polygon centroid'}),
  make({id:'curated-picnic:east-haven-beach',name:'East Haven Beach Picnic Area',coordinates:[-2.6662889,56.5159924],featureType:'park',description:'Dedicated beach picnic area with tables and metal BBQ plates to protect the dunes.',website:urls.beach,sourceName:'East Haven beach picnic area',sourceOrganisation:'East Haven Together',evidenceUrls:[urls.beach,urls.picnicOsm],sourceRecordIds:[undefined,'way/651184446'],placeType:'Picnic',tags:['service-context-picnic','current-context'],details:'picnic_tables=yes; bbq_plates=yes; parking=adjacent free but limited; toilets=seasonal accessible facility; coordinate_source=OpenStreetMap picnic-area polygon centroid'}),
  make({id:'curated-toilets:east-haven-beach',name:'East Haven Beach Public Toilets',coordinates:[-2.6667292,56.5162558],featureType:'toilet',description:'Community partnership beach toilets with male, female and accessible provision.',website:urls.toilets,sourceName:'Easthaven (The Beach) public toilets',sourceOrganisation:'Angus Council',evidenceUrls:[urls.toilets,urls.heritagePoint,urls.toiletsOsm],sourceRecordIds:[undefined,undefined,'way/1387757433'],placeType:'Public toilets',tags:['service-context-toilets','current-context','seasonal'],details:'opening=mid-March to end of October; accessible_toilet=yes; male=yes; female=yes; community_partnership=yes; coordinate_source=OpenStreetMap toilet-building centroid'}),
];
pkg.features=[...pkg.features.filter(f=>!f.id.startsWith('curated-')),...attractions,...trails,...facilities];
const highlights:VisitorHighlight[]=attractions.map((feature,index)=>({rank:index+1,featureId:feature.id,name:feature.name,reason:feature.editorialReview!.scoreRationale,tagline:index?'Fishing-village history and community gardens':'Award-winning community beach and dunes',visitorScore:index?72:82,timeToSpend:index?'30–60 minutes':'1–2.5 hours',openingTimes:index?'Outdoor interpretation always available; Wee Gallery follows seasonal toilet opening':'Open access; toilets seasonal',admission:'Free',freeAdmission:true,visitorWebsiteUrl:feature.visitorWebsiteUrl,editorialReview:feature.editorialReview,sourceName:feature.sourceRecords[0].sourceName,sourceUrl:feature.visitorWebsiteUrl!,verifiedInBoundaryAt:reviewedDate}));

pkg.project.preferredBasemap='voyager';
pkg.project.touristAppeal={score:68,dogOwnerScore:67,dogAccessScoreAdjustment:-1,rating:1,label:'Good Local Option',summary:'A genuinely worthwhile small coastal village: an award-winning beach, distinctive fishing-community heritage, community gardens, a strong coastal route and unusually complete practical facilities. Its limited scale, seasonal toilets, very small car park and lack of café keep it in the 60–69 band.',dogAccessRating:2,dogAccessSummary:'The beach and coastal path are dog-friendly with signed restriction and exercise areas; keep dogs controlled around wildlife, dunes, families and livestock.',methodVersion:'2026-08-30-strict-settlement-full-audit-v3',reviewedAt:reviewedDate,sourceUrls:Object.values(urls)};
pkg.project.visitorHighlights=highlights;
pkg.project.townGuide={characterTag:'Historic Angus fishing village and community beach',headline:'A small, cared-for coastal stop with real depth',intro:'East Haven earns 68% on its own merits and appears on the main map. Combine its beach, fishing-village interpretation and gardens with a section of the Angus coastal path; bring refreshments because there is no café in the village.',bestFor:['Quiet beach time','Coastal walking and cycling','Fishing-village heritage','Wildlife and community gardens'],perfectFor:['A relaxed half-day coast visit without a commercial resort atmosphere'],dontMiss:['East Haven Beach','Heritage Point and coastal gardens','Angus Coastal Path'],suggestedTime:'2–4 hours',visitorMood:'Small-scale, welcoming and visibly cared for, with an unusually strong sense of community ownership.',sourceUrls:Object.values(urls),lastReviewedAt:reviewedDate};
pkg.project.researchNotes='Full strict-boundary audit completed from local HES Listed Buildings and NRHE datasets. All 16 imported heritage records remain intact: eight records with defensible material periods are visible and eight undated or external-buffer records are map-hidden. East Haven independently qualifies at 68 through its beach, historic fishing-village identity, interpretation, gardens and coastal route. Exact beach parking, picnic and seasonal accessible toilet locations are published; no café or light-lunch venue was found within the village.';
planner.projects[projectId]={eat:[],trails:trails.map(f=>f.id),picnic:facilities.filter(f=>f.id.startsWith('curated-picnic:')).map(f=>f.id),parking:facilities.filter(f=>f.id.startsWith('curated-parking:')).map(f=>f.id),toilets:facilities.filter(f=>f.id.startsWith('curated-toilets:')).map(f=>f.id)};
const dogRecord=(rating:number,status:string,label:string,summary:string,sourceUrl:string)=>({rating,status,label,summary,sourceName:'East Haven dog-access audit',sourceUrl,reviewedAt:reviewedDate});
dog.reviewedAt=reviewedDate; dog.projects[projectId]={attraction:{[attractions[0].id]:dogRecord(2,'restricted','Dog-friendly with signed zones','Use the signed dog exercise and restricted areas and keep dogs controlled around dunes, wildlife and families.',urls.beachAward),[attractions[1].id]:dogRecord(2,'managed','Dogs welcome under control','Keep dogs controlled through the compact gardens and interpretation area and clear all waste.',urls.community)},trail:{[trails[0].id]:dogRecord(2,'managed','Coastal route under close control','Use close control around wildlife, livestock, cyclists and the tide-dependent beach sections.',urls.dogCode)}};
pkg.validation=validateFeatures(pkg.project,pkg.features); const errors=pkg.validation.filter((entry:any)=>entry.severity==='error'); if(errors.length)throw new Error(errors.map((entry:any)=>entry.message).join('; '));
const heritage=pkg.features.filter(f=>f.id.startsWith('hes-')||f.id.startsWith('nrhe:')); const visible=heritage.filter(f=>!f.tags.includes('map-hidden')); const invalid=visible.filter(f=>!f.documentedDateText?.trim()||f.earliestPossibleYear==null||f.latestPossibleYear==null||f.dateBasis==='unknown'||f.name.includes(f.documentedDateText)); if(heritage.length!==16||visible.length!==8||invalid.length)throw new Error(`Heritage publication failure: records=${heritage.length}, visible=${visible.length}, invalid=${invalid.map(f=>f.id).join(',')}`);
const report={reviewedAt,projectId,status:'verified',settlementScore:68,previousScore:58,independentlyWorthwhile:true,publishOnTownMap:true,scoreRationale:pkg.project.touristAppeal.summary,publication:{see:2,eat:0,trails:1,picnic:1,parking:1,toilets:1},heritage:{localHesListedBuildings:3,localNrheRecords:13,totalRecordsRetained:16,visibleDatedHeritagePins:8,visibleUndatedHeritagePins:0,mapHiddenRecords:8,contextRecordsHidden:3,undatedRecordsHidden:5,dateRule:'Construction or material-period dates only; never designation, database, assessment or publication dates.'},namedTrailSearch:{TreasureTrails:'No exact East Haven product appears in the current Dundee and Angus collection.',CuriousAbout:'No exact East Haven product found.',MysteryGuides:'No exact East Haven product found.',GoQuestAdventures:'No exact East Haven product found.',AngusCouncil:'The official Angus coastal-path leaflet gives East Haven distances, terrain, public transport and facilities. The old East Haven–Panbride leaflet and Kidney Vetch signs lack a current downloadable route contract and are not published as separate trails.',retained:[trails[0].id]},practicalAudit:{see:'East Haven Beach and the Heritage Point/coastal gardens independently clear 60.',eat:'No café, coffee-and-cake stop, tearoom, bakery café or dependable light-lunch venue was verified in the village.',picnic:'One exact dedicated beach picnic area with tables and BBQ plates.',parking:'One exact free beach car park; the community warns capacity is limited and no count is invented.',toilets:'One exact community-partnership facility, open seasonally from mid-March to the end of October, with accessible provision.',accessibility:'The toilet is accessible and the council describes the coastal route as firm, even and mostly flat; beach surfaces remain naturally variable.',transport:'Bus services connect East Haven with Carnoustie and Arbroath; current timetables should be checked.'},exclusions:['Carnoustie cafés and attractions','Panbride church and Fairy Steps restoration','Hatton House buffer records as East Haven heat pins','Old route leaflets without a current downloadable route contract'],verification:{localListedBuildingImport:{added:3,refreshed:0,bufferCandidates:3},localNrheImport:{added:13,linked:0,excludedCandidates:0},allHeritageRecordsIntact:true,allVisibleHeritagePinsDated:true,datesStoredWithoutChangingMapNames:true,trailLinksChecked:[urls.coastalPath,urls.paths,urls.treasure,urls.curious,urls.mystery,urls.goQuest],practicalCoordinatesChecked:true}};
const row={projectId,name:'East Haven',region:'Angus',previousScore:58,correctedScore:68,changed:true,publishOnTownMap:true,rationale:pkg.project.touristAppeal.summary,sourceUrls:[urls.place,urls.beach,urls.beachAward,urls.coastalPath,urls.toilets]}; const existing=correction.results.find((item:any)=>item.projectId===projectId); if(existing)Object.assign(existing,row);else correction.results.push(row); correction.affectedProjects=correction.results.length; correction.changedScores=correction.results.filter((item:any)=>item.changed).length; correction.mappedAfterCorrection=correction.results.filter((item:any)=>item.correctedScore>=60).map((item:any)=>({projectId:item.projectId,name:item.name,score:item.correctedScore}));
await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`); await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`); await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`); await writeFile(reportPath,`${JSON.stringify(report,null,2)}\n`); await writeFile(correctionPath,`${JSON.stringify(correction,null,2)}\n`); console.log(JSON.stringify({status:report.status,score:report.settlementScore,publication:report.publication,heritage:report.heritage},null,2));
