import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { booleanPointInPolygon, point } from '@turf/turf';
import { editorialRatingMethodVersion } from '../src/domain/editorialResearch';
import { validateFeatures } from '../src/domain/validation';

const reviewedDate = '2026-09-01';
const reviewedAt = '2026-09-01T19:00:00.000Z';
const plannerPath = resolve('data/cairn-o-mount-visitor-planner-curation.json');
const dogPath = resolve('data/cairn-o-mount-dog-access-curation.json');
const planner: any = JSON.parse(await readFile(plannerPath, 'utf8'));
const dog: any = JSON.parse(await readFile(dogPath, 'utf8'));

const providers = {
  treasure: 'https://www.treasuretrails.co.uk/',
  curious: 'https://curiousabout.co.uk/',
  mystery: 'https://www.mysteryguides.co.uk/',
  goquest: 'https://goquestadventures.com/',
  visitAngusTrails: 'https://visitangus.com/things-to-see-do/trails/',
  toilets: 'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/all_public_toilets_listed_by_location',
  parking: 'https://www.angus.gov.uk/roads_parking_and_travel/parking/changes_to_parking_and_parking_review',
  parkingData: 'https://opendata.angus.gov.uk/dataset/car-parks',
  dogCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
};

type Category = 'attraction' | 'food' | 'trail';
interface PlaceSpec {
  id: string;
  name: string;
  coordinates: [number, number];
  featureType: string;
  description: string;
  website: string;
  placeType: 'Attraction' | 'Eat' | 'Trail' | 'Picnic' | 'Parking' | 'Toilets';
  tags: string[];
  score?: number;
  category?: Category;
  reason?: string;
  details?: string;
  relatedContext?: boolean;
  freeAdmission?: boolean;
  time?: string;
}

interface TownSpec {
  stem: string;
  score: number;
  summary: string;
  character: string;
  headline: string;
  intro: string;
  places: PlaceSpec[];
  exclusions: string[];
}

const specs: TownSpec[] = [
  {
    stem: 'carnoustie', score: 84,
    summary: 'A strong coastal town built around world-famous golf links, a family seafront, a substantial heritage trail and a genuine daytime café cluster.',
    character: 'Championship golf, beach paths and an unusually complete seafront',
    headline: 'A real coastal destination, not simply a golf stop',
    intro: 'Carnoustie independently clears the map threshold through its links, bay, seafront recreation, two-length heritage trail, rail access and well-supported coffee, cake and light-lunch offer. Barry Mill and Barry village are excluded from the town score.',
    exclusions: ['Barry Mill and Barry village', 'Barry Buddon outside the NRS Carnoustie locality', 'East Scryne Fruit Farm and other rural food venues', 'Dinner-led pubs and takeaways'],
    places: [
      { id:'curated-attraction:carnoustie-golf-links', name:'Carnoustie Golf Links', coordinates:[-2.7164537,56.4962853], featureType:'historic_site', description:'The internationally renowned public links complex, including the Championship Course and visitor golf facilities.', website:'https://visitangus.com/things-to-see-do/golf/carnoustie-championship/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context'], score:90, category:'attraction', reason:'A destination-scale sporting landscape with international distinctiveness, strong visitor infrastructure and deep golf heritage.', time:'2–5 hours' },
      { id:'curated-attraction:carnoustie-bay', name:'Carnoustie Bay', coordinates:[-2.7085,56.4973], featureType:'natural_landmark', description:'Sand-and-rock shore beside the golf links with water sports, rock pools and a long coastal outlook.', website:'https://visitangus.com/things-to-see-do/attractions/carnoustie-bay/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','coastal-access'], score:80, category:'attraction', reason:'A free, attractive and practical beach immediately beside the strict settlement boundary; it is published as related See context and is not used to inflate the town score.', relatedContext:true, freeAdmission:true, time:'45–120 minutes' },
      { id:'curated-attraction:carnoustie-sandy-sensation', name:'Sandy Sensation and Seafront', coordinates:[-2.7104,56.4982], featureType:'park', description:'Large seafront play area with climbing equipment, splash play, seasonal crazy golf and tennis.', website:'https://visitangus.com/things-to-see-do/attractions/playpark-trail/', placeType:'Attraction', tags:['curated-visitor','current-context','family-attraction'], score:74, category:'attraction', reason:'A substantial free family stop backed by nearby parking, toilets, café and beach access.', freeAdmission:true, time:'45–120 minutes' },
      { id:'curated-attraction:carnoustie-indoor-golf', name:'Carnoustie Indoor Golf Simulators', coordinates:[-2.7164,56.4965], featureType:'visitor_centre', description:'Bookable indoor golf simulators at Links House, adding a weather-independent experience to the links.', website:'https://visitangus.com/things-to-see-do/attractions/indoor-golf-simulators-at-carnoustie-golf-links/', placeType:'Attraction', tags:['curated-visitor','current-context','indoor-attraction'], score:66, category:'attraction', reason:'A useful bookable wet-weather golf experience with authentic links context, though narrower than the outdoor courses.', time:'1–2 hours' },
      { id:'curated-eat:carnoustie-gather', name:'Gather Kitchen & Deli', coordinates:[-2.7164919,56.5006916], featureType:'food_drink', description:'Independent daytime café serving speciality coffee, brunch, light lunches, sourdough sandwiches and fresh baking.', website:'https://visitangus.com/things-to-see-do/food-drink/gather-kitchen-deli/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:84, category:'food', reason:'The town’s standout café-led stop, with strong coffee, baking, lunch relevance and inclusive dietary choice.', details:'Tuesday–Saturday 10:00–15:00; accessible toilets and level access listed.' },
      { id:'curated-eat:carnoustie-rookery', name:'The Rookery', coordinates:[-2.7164537,56.4962853], featureType:'food_drink', description:'Links House restaurant with breakfast, lunch and afternoon tea overlooking the Championship Course.', website:'https://visitangus.com/things-to-see-do/food-drink/the-rookery/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:78, category:'food', reason:'A distinctive daytime food stop whose lunch and afternoon-tea offer, views and accessibility fit the visitor brief despite its restaurant format.' },
      { id:'curated-eat:carnoustie-tee-caddy', name:'Tee Caddy Takeaway & Café', coordinates:[-2.7227285,56.500705], featureType:'food_drink', description:'Town café and takeaway suitable for breakfast, hot drinks, baking and a quick light lunch.', website:'https://visitangus.com/things-to-see-do/food-drink/tee-caddy-takeaway-cafe/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:70, category:'food', reason:'A useful independent café stop with clear daytime relevance, scored below the destination cafés for depth and evidence detail.' },
      { id:'curated-eat:carnoustie-francos', name:'Franco’s Cafe', coordinates:[-2.7074549,56.5015314], featureType:'food_drink', description:'High Street café for coffee, snacks, baking and straightforward light meals.', website:'https://visitangus.com/things-to-see-do/food-drink/francos-cafe/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:68, category:'food', reason:'A practical in-town café option with appropriate daytime focus and convenient High Street location.' },
      { id:'curated-eat:carnoustie-jm-bakery', name:'J M Bakery', coordinates:[-2.7131701,56.5008023], featureType:'food_drink', description:'Traditional bakery counter for cakes, pastries, sandwiches and picnic supplies.', website:'https://visitangus.com/things-to-see-do/food-drink/j-m-bakery/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:64, category:'food', reason:'A useful bakery stop for cake, a quick light lunch or picnic supplies rather than a destination meal.' },
      { id:'curated-trails:carnoustie-heritage', name:'Carnoustie Heritage Trail', coordinates:[-2.7164,56.4965], featureType:'walking_route', description:'Official self-guided trail with 1.5-mile and 4-mile circular options through golf, town and seafront history.', website:'https://visitangus.com/get-inspired/heritage-trails/carnoustie-heritage-trail/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context'], score:82, category:'trail', reason:'A detailed, usable town trail with two distances, strong local stories and a verified current provider page.' },
      { id:'curated-trails:carnoustie-beach', name:'Angus Beach Trail: Carnoustie Bay', coordinates:[-2.7085,56.4973], featureType:'walking_route', description:'Official Angus beach-trail stop covering the bay, rock pools and seafront facilities.', website:'https://visitangus.com/things-to-see-do/attractions/beach-trail/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:66, category:'trail', reason:'A useful official coastal discovery resource, though it is a regional trail rather than a town-only route.', relatedContext:true },
      { id:'curated-trails:carnoustie-crombie-cycle', name:'Carnoustie to Crombie Park Cycle', coordinates:[-2.7164,56.4965], featureType:'cycling_route', description:'Official 46.5 km moderate cycle route from Carnoustie to Crombie Country Park.', website:'https://visitangus.com/things-to-see-do/trails/carnoustie-to-crombie-park/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:70, category:'trail', reason:'A substantial signed-planning resource with a genuine Carnoustie start, explicitly separated from Crombie’s attraction merit.' },
      { id:'curated-trails:carnoustie-forfar-cycle', name:'Carnoustie to Forfar Cycle', coordinates:[-2.7164,56.4965], featureType:'cycling_route', description:'Official 53 km moderate/difficult cycle route linking Carnoustie and Forfar.', website:'https://visitangus.com/things-to-see-do/trails/carnoustie-to-forfar/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:68, category:'trail', reason:'A verified longer cycling option that starts in town; Forfar’s separate attractions do not transfer to this score.' },
      { id:'curated-picnic:carnoustie-seafront', name:'Sandy Sensation Seafront Picnic Area', coordinates:[-2.7104,56.4982], featureType:'picnic_site', description:'Open seafront recreation space suitable for a packed picnic beside the beach and play park.', website:'https://visitangus.com/things-to-see-do/attractions/playpark-trail/', placeType:'Picnic', tags:['service-context-picnic','current-context'] },
      { id:'curated-picnic:carnoustie-bay', name:'Carnoustie Bay Picnic Stop', coordinates:[-2.7092,56.4977], featureType:'picnic_site', description:'Informal seafront picnic stop by the bay; no claim is made for a fixed-table count.', website:'https://visitangus.com/things-to-see-do/attractions/carnoustie-bay/', placeType:'Picnic', tags:['service-context-picnic','current-context'], relatedContext:true },
      { id:'curated-parking:carnoustie-links-avenue', name:'Links Avenue Car Park', coordinates:[-2.7175977823,56.5005940471], featureType:'parking', description:'Official council car park. Angus off-street charges were permanently removed from 1 April 2025; obey the posted maximum stay.', website:providers.parkingData, placeType:'Parking', tags:['service-context-parking','current-context'], details:'Official polygon centroid; current policy says no council charge, but posted short/long-stay limits still apply.' },
      { id:'curated-parking:carnoustie-park-avenue', name:'Park Avenue Car Park', coordinates:[-2.7104878179,56.5001683059], featureType:'parking', description:'Official council car park with current no-charge policy; check the posted maximum stay.', website:providers.parkingData, placeType:'Parking', tags:['service-context-parking','current-context'] },
      { id:'curated-parking:carnoustie-high-street', name:'High Street Car Park', coordinates:[-2.7093671182,56.5011509373], featureType:'parking', description:'Official council town-centre car park with current no-charge policy; check posted restrictions.', website:providers.parkingData, placeType:'Parking', tags:['service-context-parking','current-context'] },
      { id:'curated-toilets:carnoustie-library', name:'Carnoustie Library Public Toilets', coordinates:[-2.7082502,56.5012231], featureType:'toilets', description:'Council-listed public toilets available during library opening hours.', website:'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/carnoustie_toilets', placeType:'Toilets', tags:['service-context-toilets','current-context'] },
      { id:'curated-toilets:carnoustie-sports-centre', name:'Carnoustie Sports Centre Public Toilets', coordinates:[-2.70998,56.4993095], featureType:'toilets', description:'Council-listed toilets at the seafront sports centre, available during venue hours.', website:'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/carnoustie_toilets', placeType:'Toilets', tags:['service-context-toilets','current-context','accessible-toilet'] },
      { id:'curated-toilets:carnoustie-station-hotel', name:'Station Hotel Public Toilet Access', coordinates:[-2.7058,56.5011], featureType:'toilets', description:'Council-listed participating toilet location; availability follows the host venue.', website:'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/carnoustie_toilets', placeType:'Toilets', tags:['service-context-toilets','current-context'] },
    ],
  },
  {
    stem:'monifieth', score:76,
    summary:'A worthwhile Tay-coast town with a sandy beach, the well-equipped Blue Seaway, two golf courses, a detailed heritage trail and two verified café-led stops.',
    character:'Tay beach, Pictish roots and family seafront recreation',
    headline:'A complete coastal half-day with heritage and cake',
    intro:'Monifieth rises above the old exact-58 placeholder after a second-pass audit. Its own beach, Blue Seaway, golf links, heritage trail, cafés, picnic space, parking and seasonal toilets form a coherent visit; Monikie, Crombie and Ardestie remain excluded.',
    exclusions:['Monikie and Crombie Country Parks','Ardestie Earth House','Forbes of Kingennie and Piperdam','Out-of-town producers and accommodation restaurants'],
    places:[
      { id:'curated-attraction:monifieth-beach', name:'Monifieth Beach', coordinates:[-2.8139,56.4784], featureType:'natural_landmark', description:'Long sandy Tay beach with rock pools at low tide and views across the firth.', website:'https://visitangus.com/things-to-see-do/attractions/monifieth-beach/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','coastal-access'], score:82, category:'attraction', reason:'A strong free beach immediately beside the strict settlement boundary; it is published as related See context and is not used to inflate the town score.', relatedContext:true, freeAdmission:true, time:'45–120 minutes' },
      { id:'curated-attraction:monifieth-blue-seaway', name:'Blue Seaway', coordinates:[-2.8141985,56.4795901], featureType:'park', description:'Seafront recreation area with play equipment, skate park, tennis, bowling, viewpoints and public facilities.', website:'https://visitangus.com/things-to-see-do/attractions/blue-seaway/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','family-attraction'], score:80, category:'attraction', reason:'A substantial free family seafront anchor with a good range of activity and dependable transport, parking and toilet support.', freeAdmission:true, time:'1–2 hours' },
      { id:'curated-attraction:monifieth-golf-links', name:'Monifieth Golf Links', coordinates:[-2.8045,56.483], featureType:'historic_site', description:'Historic links complex with the Medal and Ashludie courses, including an Open qualifying course.', website:'https://visitangus.com/things-to-see-do/golf/monifieth-medal/', placeType:'Attraction', tags:['curated-visitor','current-context'], score:78, category:'attraction', reason:'A distinctive links-golf experience immediately east of the strict locality; it is published separately and is not used to inflate the town score.', relatedContext:true },
      { id:'curated-eat:monifieth-bowmans', name:'Bowmans Coffee House', coordinates:[-2.817,56.4826], featureType:'food_drink', description:'Independent coffee house serving speciality coffee, home baking, breakfast, lunch, snacks and afternoon tea.', website:'https://visitangus.com/things-to-see-do/food-drink/bowmans-coffee-house/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:82, category:'food', reason:'A strong all-round café for coffee, cake, light lunch and afternoon tea, with current hours and accessibility evidence.' },
      { id:'curated-eat:monifieth-bay-diner', name:'The Bay Diner', coordinates:[-2.8137094,56.4787728], featureType:'food_drink', description:'Beachside café at Tayview serving homemade food, home baking and drinks with outside seating.', website:'https://visitangus.com/things-to-see-do/food-drink/the-bay-diner/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:76, category:'food', reason:'A well-located daytime café that directly supports a beach or Blue Seaway visit with baking, light food and outdoor seating.' },
      { id:'curated-trails:monifieth-heritage', name:'Monifieth Heritage Trail', coordinates:[-2.816245,56.4826934], featureType:'walking_route', description:'Official self-guided trail through Monifieth’s burgh, industrial, tramway and Pictish history.', website:'https://visitangus.com/get-inspired/heritage-trails/monifieth-heritage-trail/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context'], score:80, category:'trail', reason:'A detailed town-specific route with a current web guide and downloadable PDF.' },
      { id:'curated-trails:monifieth-beach', name:'Angus Beach Trail: Monifieth', coordinates:[-2.8141985,56.4795901], featureType:'walking_route', description:'Official regional beach trail stop covering Monifieth Beach and Blue Seaway facilities.', website:'https://visitangus.com/things-to-see-do/attractions/beach-trail/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:66, category:'trail', reason:'A useful official beach-planning resource, explicitly treated as regional rather than town-only.' },
      { id:'curated-trails:monifieth-carrot-hill-cycle', name:'Monifieth to Carrot Hill Cycle', coordinates:[-2.8183561,56.479738], featureType:'cycling_route', description:'Official 35 km moderate/difficult cycle route starting in Monifieth and heading inland to Carrot Hill.', website:'https://visitangus.com/plan-your-trip/explore-our-towns/monifieth/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:68, category:'trail', reason:'A substantial current route with a genuine town start; out-of-town scenery is not transferred into the settlement score.' },
      { id:'curated-picnic:monifieth-blue-seaway', name:'Blue Seaway Picnic Area', coordinates:[-2.8141985,56.4795901], featureType:'picnic_site', description:'Promoted seafront park where visitors are explicitly invited to bring a picnic.', website:'https://visitangus.com/things-to-see-do/attractions/playpark-trail/', placeType:'Picnic', tags:['service-context-picnic','current-context'] },
      { id:'curated-parking:monifieth-blue-seaway', name:'Blue Seaway and Marine Drive Parking', coordinates:[-2.8139,56.4795], featureType:'parking', description:'Free parking promoted beside Blue Seaway and a short walk from the beach; obey local signs and marked-bay restrictions.', website:'https://visitangus.com/things-to-see-do/attractions/playpark-trail/', placeType:'Parking', tags:['service-context-parking','current-context'] },
      { id:'curated-toilets:monifieth-blue-seaway', name:'Blue Seaway Public Toilets', coordinates:[-2.8141985,56.4795901], featureType:'toilets', description:'Council-listed accessible public toilets at Riverview Drive; VisitAngus describes seasonal opening from April to mid-October.', website:'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/monifieth_toilets', placeType:'Toilets', tags:['service-context-toilets','current-context','accessible-toilet'] },
    ],
  },
  {
    stem:'montrose', score:88,
    summary:'A deep and varied Angus coast destination with two museums, a strong independent playhouse, beach and links, a dense historic centre, verified trails and substantial café and facility coverage.',
    character:'Museum town between the North Sea and a great tidal basin',
    headline:'One of Angus’s strongest full-day towns',
    intro:'Montrose earns its score from the town itself: museum, aviation heritage, playhouse, beach access, historic streets, named town trails, independent daytime food and practical facilities. House of Dun and the Basin Visitor Centre lie outside the NRS locality and are not used to inflate the town score.',
    exclusions:['House of Dun','Montrose Basin Visitor Centre at Rossie Braes','Dunninald and Charleton Farm','Arbikie and other rural food venues','Ferryden and Scurdie Ness'],
    places:[
      { id:'curated-attraction:montrose-air-station', name:'Montrose Air Station Heritage Centre', coordinates:[-2.4634039,56.7262537], featureType:'museum', description:'Independent aviation museum on Britain’s first operational military airfield, with historic buildings, aircraft and displays.', website:'https://visitangus.com/things-to-see-do/attractions/montrose-air-station-museum/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','indoor-attraction'], score:88, category:'attraction', reason:'A distinctive, substantial and destination-worthy museum rooted in nationally important aviation history.', time:'1.5–3 hours' },
      { id:'curated-attraction:montrose-museum', name:'Montrose Museum and Art Gallery', coordinates:[-2.4644722,56.7103933], featureType:'museum', description:'Free town museum with archaeology, natural history, Montrose collections and changing art exhibitions.', website:'https://angusalive.scot/museums-galleries/visit-a-museum-gallery/montrose-museum/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','indoor-attraction'], score:82, category:'attraction', reason:'A strong free indoor anchor with broad collections and direct town relevance.', freeAdmission:true, time:'60–120 minutes' },
      { id:'curated-attraction:montrose-playhouse', name:'The Montrose Playhouse', coordinates:[-2.4661902,56.7165811], featureType:'arts_centre', description:'Community-owned cinema and arts venue with screenings, live events, café/bar and accessibility support.', website:'https://visitangus.com/things-to-see-do/attractions/the-montrose-playhouse/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','indoor-attraction'], score:78, category:'attraction', reason:'A distinctive community cultural venue that provides real wet-weather depth and a daytime café stop.' },
      { id:'curated-attraction:montrose-beach', name:'Montrose Beach and Links', coordinates:[-2.4565,56.7154], featureType:'natural_landmark', description:'Wide sandy beach and links recreation area on the town’s eastern edge.', website:'https://visitangus.com/things-to-see-do/attractions/montrose-beach/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','coastal-access'], score:80, category:'attraction', reason:'A substantial free beach and links experience that combines naturally with the town centre and family facilities.', freeAdmission:true, time:'1–2 hours' },
      { id:'curated-eat:montrose-janes', name:'Jane’s Tearoom', coordinates:[-2.4688,56.7147], featureType:'food_drink', description:'Independent town-centre tearoom for coffee, home baking, breakfast and light lunches.', website:'https://visitangus.com/things-to-see-do/food-drink/janes-tearoom/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:80, category:'food', reason:'A classic café-led visitor stop with strong coffee, cake and light-lunch relevance.' },
      { id:'curated-eat:montrose-roamer', name:'Roamer Coffee', coordinates:[-2.468,56.7135], featureType:'food_drink', description:'Independent speciality-coffee stop with baking and a concise daytime offer.', website:'https://visitangus.com/things-to-see-do/food-drink/roamer-coffee/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake'], score:78, category:'food', reason:'A distinctive current coffee-led option with strong fit for a town visit.' },
      { id:'curated-eat:montrose-pavilion', name:'Pavilion Cafe', coordinates:[-2.4649889,56.7089007], featureType:'food_drink', description:'Popular park café serving drinks, baking, breakfast and light meals beside Mid Links.', website:'https://visitangus.com/things-to-see-do/food-drink/pavilion-cafe/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:76, category:'food', reason:'A reliable daytime café in a useful park setting, well suited to families and a picnic-or-walk visit.' },
      { id:'curated-eat:montrose-playhouse', name:'Montrose Playhouse Café Bar', coordinates:[-2.4661902,56.7165811], featureType:'food_drink', description:'Daytime café/bar within the community cinema, serving coffee, cakes and light food.', website:'https://visitangus.com/things-to-see-do/food-drink/the-montrose-playhouse/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:72, category:'food', reason:'A useful accessible café tied to a strong indoor attraction, with genuine daytime relevance.' },
      { id:'curated-eat:montrose-chic-rustic', name:'Chic Rustic Bistro & Gift Emporium', coordinates:[-2.469,56.7128], featureType:'food_drink', description:'Independent bistro and gift shop with coffee, baking and daytime meals.', website:'https://visitangus.com/things-to-see-do/food-drink/chic-rustic-bistro-gift-emporium/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:70, category:'food', reason:'A useful independent café-bistro option with visitor interest beyond a generic restaurant.' },
      { id:'curated-trails:montrose-heritage', name:'Montrose Heritage Trail', coordinates:[-2.468,56.712], featureType:'walking_route', description:'Official 90-minute self-guided circuit through the royal burgh’s streets, kirk, town walls and mercantile architecture.', website:'https://visitangus.com/get-inspired/heritage-trails/montrose-heritage-trail/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context'], score:84, category:'trail', reason:'A detailed, walkable and fully town-specific heritage route with current interpretation.' },
      { id:'curated-trails:montrose-treasure', name:'Montrose Town, Parks & Pavilion Treasure Trail', coordinates:[-2.468,56.712], featureType:'walking_route', description:'Current paid Treasure Trails puzzle route through Montrose town, parks and pavilion.', website:'https://www.treasuretrails.co.uk/products/things-to-do-montrose-angus', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','commercial-puzzle-trail'], score:80, category:'trail', reason:'A verified live Dundee and Angus product with a clear Montrose title, route and purchase page.' },
      { id:'curated-trails:montrose-burns', name:'Montrose Robert Burns Trail', coordinates:[-2.468,56.712], featureType:'walking_route', description:'Twelve-location Burns trail beginning in Montrose and continuing through Ferryden and rural Angus.', website:'https://visitangus.com/get-inspired/heritage-trails/montrose-robert-burns-trail/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:74, category:'trail', reason:'A distinctive current literary trail, clearly labelled as an 11-mile cross-boundary route.' },
      { id:'curated-trails:montrose-arbroath-cycle', name:'Arbroath to Montrose Cycle', coordinates:[-2.468,56.712], featureType:'cycling_route', description:'Official 55 km moderate cycle route linking the two coastal towns.', website:'https://visitangus.com/things-to-see-do/trails/arbroath-to-montrose/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:70, category:'trail', reason:'A substantial official coast route with Montrose as a genuine endpoint; Arbroath’s separate merit is excluded.' },
      { id:'curated-trails:montrose-edzell-cycle', name:'Montrose to Edzell via Fettercairn Cycle', coordinates:[-2.468,56.712], featureType:'cycling_route', description:'Official long-distance cycling route starting in Montrose and heading through the Mearns.', website:'https://visitangus.com/things-to-see-do/trails/montrose-to-edzell-via-fettercairn/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:68, category:'trail', reason:'A verified substantial route with a real Montrose start, explicitly separated from the attractions of other places.' },
      { id:'curated-picnic:montrose-mid-links', name:'Mid Links Picnic Area', coordinates:[-2.4649,56.7089], featureType:'picnic_site', description:'Public parkland beside Pavilion Cafe suitable for a picnic and family pause.', website:'https://visitangus.com/things-to-see-do/food-drink/pavilion-cafe/', placeType:'Picnic', tags:['service-context-picnic','current-context'] },
      { id:'curated-picnic:montrose-beach', name:'Montrose Beach Picnic Stop', coordinates:[-2.4565,56.7154], featureType:'picnic_site', description:'Informal packed-picnic stop on the beach-and-links edge; no fixed-table count is claimed.', website:'https://visitangus.com/things-to-see-do/attractions/montrose-beach/', placeType:'Picnic', tags:['service-context-picnic','current-context'] },
      { id:'curated-parking:montrose-lower-hall', name:'Lower Hall Street Car Park', coordinates:[-2.4709232294,56.7141712851], featureType:'parking', description:'Official council car park. Charges were permanently removed from 1 April 2025; posted maximum stays still apply.', website:providers.parkingData, placeType:'Parking', tags:['service-context-parking','current-context'] },
      { id:'curated-parking:montrose-murray-lane', name:'Murray Lane Car Park', coordinates:[-2.4682068319,56.7153007099], featureType:'parking', description:'Official council town-centre car park with current no-charge policy; check posted restrictions.', website:providers.parkingData, placeType:'Parking', tags:['service-context-parking','current-context'] },
      { id:'curated-parking:montrose-baltic-street', name:'Baltic Street Car Park', coordinates:[-2.4666967675,56.7103070843], featureType:'parking', description:'Official council car park with current no-charge policy and an adjoining public toilet.', website:providers.parkingData, placeType:'Parking', tags:['service-context-parking','current-context'] },
      ...[['sports-centre','Montrose Sports Centre Toilets',[-2.461,56.712]],['baltic-street','Baltic Street Car Park Toilets',[-2.4666967675,56.7103070843]],['museum','Montrose Museum Toilets',[-2.4644722,56.7103933]],['splash','The Splash Public Toilets',[-2.456,56.715]],['town-buildings','Montrose Town Buildings Toilets',[-2.468,56.7115]]].map(([slug,name,coordinates])=>({ id:`curated-toilets:montrose-${slug}`, name, coordinates:coordinates as [number,number], featureType:'toilets', description:'Council-listed Montrose public toilet location; check host-venue or seasonal opening hours.', website:'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/montrose_toilets', placeType:'Toilets' as const, tags:['service-context-toilets','current-context'] })),
    ],
  },
  {
    stem:'glamis', score:59,
    summary:'A handsome conservation village with a strong café and practical facilities, but the destination-scale castle lies outside the strict settlement boundary and is scored separately in See.',
    character:'Stone village square beside, but separate from, the famous castle estate',
    headline:'Worth browsing with coffee; the castle is a separate attraction',
    intro:'Glamis village has genuine charm, a café, church, parking and toilets, but it does not independently clear 60. Glamis Castle remains available as a separately scored See attraction and no longer inflates the village rating.',
    exclusions:['Glamis Castle from the settlement score','The Bothy Experience and Ogilvy Distillery outside the village','Rural accommodation dining'],
    places:[
      { id:'curated-attraction:glamis-castle', name:'Glamis Castle', coordinates:[-3.0019917,56.620378], featureType:'castle', description:'Major visitor castle with guided interiors, extensive gardens, four walking routes and a daytime restaurant.', website:'https://visitangus.com/things-to-see-do/attractions/glamis-castle/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','nearby-attraction'], score:94, category:'attraction', reason:'A destination-scale historic house and garden experience, deliberately scored separately from Glamis village.', relatedContext:true, time:'2–4 hours' },
      { id:'curated-eat:glamis-corner-shop', name:'Glamis Corner Shop & Café', coordinates:[-3.0031153,56.6085971], featureType:'food_drink', description:'Village café and shop serving coffee, home baking, snacks and light lunches.', website:'https://visitangus.com/things-to-see-do/food-drink/glamis-corner-shop-cafe/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], score:76, category:'food', reason:'A strong small-village coffee, cake and light-lunch stop with a central location.' },
      { id:'curated-eat:glamis-castle-kitchen', name:'Castle Kitchen at Glamis Castle', coordinates:[-3.0019917,56.620378], featureType:'food_drink', description:'Castle visitor restaurant serving coffee, cakes and lunch during the visitor season.', website:'https://visitangus.com/things-to-see-do/food-drink/castle-kitchen-at-glamis-castle/', placeType:'Eat', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch','nearby-attraction'], score:74, category:'food', reason:'A quality daytime stop attached to the separately scored castle; it does not count towards village merit.', relatedContext:true },
      { id:'curated-trails:glamis-castle-walks', name:'Glamis Castle Garden Walks', coordinates:[-3.0019917,56.620378], featureType:'walking_route', description:'Four scenic walking routes through the castle grounds and gardens, available with estate admission.', website:'https://visitangus.com/get-inspired/itineraries/explore-our-rich-heritage/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','nearby-attraction'], score:76, category:'trail', reason:'A substantial visitor walking offer within the separately scored castle estate.', relatedContext:true },
      { id:'curated-trails:glamis-cycle', name:'Cycle Ride to Glamis', coordinates:[-3.0031153,56.6085971], featureType:'cycling_route', description:'Official cross-boundary cycle route linking Forfar and Glamis.', website:'https://visitangus.com/things-to-see-do/trails/cycle-ride-to-glamis/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:68, category:'trail', reason:'A verified route for which Glamis is a genuine endpoint; Forfar’s attractions are excluded from the village score.' },
      { id:'curated-parking:glamis-village', name:'Glamis Car Park', coordinates:[-3.0031912567,56.6076056994], featureType:'parking', description:'Official council village car park with current no-charge policy; obey posted restrictions.', website:providers.parkingData, placeType:'Parking', tags:['service-context-parking','current-context'] },
      { id:'curated-toilets:glamis-main-street', name:'Glamis Main Street Public Toilets', coordinates:[-3.0032,56.6077], featureType:'toilets', description:'Council-listed village public toilets; check current opening information.', website:'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/glamis_toilets', placeType:'Toilets', tags:['service-context-toilets','current-context'] },
    ],
  },
  {
    stem:'st-vigeans', score:63,
    summary:'A tiny but genuinely distinctive Pictish and medieval village cluster centred on one of Scotland’s most important carved-stone collections.',
    character:'Pictish stones and a medieval kirk on a village mound',
    headline:'A focused heritage stop that just clears the town threshold',
    intro:'St Vigeans is small, but the museum, church setting, coherent historic village and Pictish Trail role create an independent visit. Arbroath’s cafés and facilities are not transferred into the score.',
    exclusions:['Arbroath town facilities and attractions','Nearby rural cafés','Unverified roadside or resident parking'],
    places:[
      { id:'curated-attraction:st-vigeans-stones', name:'St Vigeans Stones & Museum', coordinates:[-2.5903673,56.5770066], featureType:'museum', description:'Historic Environment Scotland museum displaying 38 carved stones from an important Pictish religious centre.', website:'https://visitangus.com/things-to-see-do/attractions/st-vigeans-stones-museum/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','indoor-attraction'], score:88, category:'attraction', reason:'One of Scotland’s most important Pictish carved-stone collections, with current 2026 opening, admission and accessibility information.', time:'60–90 minutes' },
      { id:'curated-attraction:st-vigeans-church', name:'St Vigeans Parish Church and Kirkyard', coordinates:[-2.5900321,56.5766745], featureType:'church', description:'Late-medieval parish church and historic kirkyard on the mound associated with the Pictish religious centre.', website:'https://visitangus.com/st-vigeans-doors-open-days/', placeType:'Attraction', tags:['curated-visitor','current-context','historic-setting'], score:68, category:'attraction', reason:'A highly atmospheric and historically important exterior setting, tempered by limited routine interior access.', freeAdmission:true, time:'30–45 minutes' },
      { id:'curated-trails:st-vigeans-pictish', name:'The Pictish Trail: St Vigeans', coordinates:[-2.5903673,56.5770066], featureType:'walking_route', description:'Official regional heritage trail linking St Vigeans to Angus’s other Pictish sites.', website:'https://visitangus.com/get-inspired/heritage-trails/the-pictish-trail/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:72, category:'trail', reason:'A verified official trail for which St Vigeans is a nationally important stop; other settlements’ merit is excluded.' },
      { id:'curated-parking:st-vigeans', name:'St Vigeans Car Park', coordinates:[-2.5888241079,56.5766737958], featureType:'parking', description:'Official Angus Council visitor car park polygon serving the village and museum; current council charges are removed, subject to signs.', website:providers.parkingData, placeType:'Parking', tags:['service-context-parking','current-context'] },
      { id:'curated-toilets:st-vigeans-museum', name:'St Vigeans Museum Visitor Toilets', coordinates:[-2.5903673,56.5770066], featureType:'toilets', description:'Accessible toilet available to museum visitors during the seasonal staffed opening period.', website:'https://visitangus.com/things-to-see-do/attractions/st-vigeans-stones-museum/', placeType:'Toilets', tags:['service-context-toilets','current-context','accessible-toilet'] },
    ],
  },
  {
    stem:'barry-angus', score:46,
    summary:'Barry remains selector-only: Barry Mill and Barry Buddon are worthwhile separate See attractions, but the settlement itself lacks the breadth and facilities required for a 60+ town score.',
    character:'Small settlement between a working mill and dune training ground',
    headline:'Two nearby attractions, but not a destination town in its own right',
    intro:'The audit separates attraction merit from settlement merit. Barry Mill and Barry Buddon remain in See, while the settlement stays below 60 because no verified café-led cluster, town trail, public picnic facility, council car park or public toilet was found inside the strict boundary.',
    exclusions:['Carnoustie’s beach, cafés and golf links','Barry Island Treasure Trail in South Wales','Arbroath-starting route merit beyond the Barry endpoint'],
    places:[
      { id:'curated-attraction:barry-mill', name:'Barry Mill', coordinates:[-2.7336,56.5038], featureType:'museum', description:'Seasonal National Trust for Scotland working watermill with machinery demonstrations and year-round grounds.', website:'https://visitangus.com/things-to-see-do/attractions/barry-mill/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','nearby-attraction'], score:84, category:'attraction', reason:'A rare working-mill experience with real interpretive depth, seasonal operations and accessible visitor facilities.', relatedContext:true, time:'1–2 hours' },
      { id:'curated-attraction:barry-buddon', name:'Barry Buddon', coordinates:[-2.744,56.485], featureType:'natural_landmark', description:'Large coastal dune and heath landscape with wildlife and access subject to military training restrictions.', website:'https://visitangus.com/things-to-see-do/attractions/barry-buddon/', placeType:'Attraction', tags:['curated-visitor','home-standalone-place','current-context','nearby-attraction'], score:70, category:'attraction', reason:'A distinctive coastal nature landscape, tempered by access restrictions and the need to check firing information.', relatedContext:true, time:'1–3 hours' },
      { id:'curated-trails:barry-harbour-cycle', name:'Arbroath Harbour to Barry Circuit', coordinates:[-2.7336,56.5038], featureType:'cycling_route', description:'Official 30 km easy cycle circuit beginning in Arbroath and reaching Barry.', website:'https://visitangus.com/things-to-see-do/trails/arbroath-harbour-to-barry-circuit/', placeType:'Trail', tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'], score:66, category:'trail', reason:'A verified regional route that reaches Barry; its Arbroath start and attractions do not inflate the settlement score.', relatedContext:true },
    ],
  },
];

function assessment(score: number, category: Category) {
  if (category === 'food') {
    const parts = [0.29,0.21,0.15,0.14,0.11].map((part)=>Math.round(score*part));
    return { foodAndDrinkQuality:parts[0], daytimeRelevance:parts[1], distinctiveness:parts[2], consistency:parts[3], visitorFit:parts[4], evidenceConfidence:score-parts.reduce((sum,value)=>sum+value,0) };
  }
  const parts = [0.30,0.20,0.20,0.15,0.10].map((part)=>Math.round(score*part));
  return { experienceDepth:parts[0], distinctiveness:parts[1], presentation:parts[2], journeyWorth:parts[3], accessAndReliability:parts[4], evidenceConfidence:score-parts.reduce((sum,value)=>sum+value,0), visitability:'full_visitor_experience' };
}

function rating(score: number) { return score >= 90 ? 3 : score >= 80 ? 2 : score >= 70 ? 1 : 0; }
function label(score: number) { return score >= 90 ? 'Exceptional Destination' : score >= 80 ? 'Strong Destination' : score >= 70 ? 'Worth a Visit' : score >= 60 ? 'Notable Stop' : 'Minor Interest'; }

for (const spec of specs) {
  const projectPath = resolve(`data/projects/${spec.stem}.json`);
  const pkg: any = JSON.parse(await readFile(projectPath, 'utf8'));
  const activeBoundary = pkg.project.townStudyArea?.visitorBoundary ?? pkg.project.boundary;
  const curated = spec.places.map((placeSpec) => {
    if (!placeSpec.relatedContext && !booleanPointInPolygon(point(placeSpec.coordinates), activeBoundary)) {
      throw new Error(`${pkg.project.name}: ${placeSpec.name} is outside the strict visitor boundary.`);
    }
    const visitorPlaceType = placeSpec.placeType === 'Toilets' ? 'Public toilets' : placeSpec.placeType;
    const openingInformation = placeSpec.category === 'food'
      ? 'Daytime service; current opening hours are published by the operator'
      : placeSpec.freeAdmission || placeSpec.tags.includes('coastal-access') || placeSpec.featureType === 'park'
        ? 'Open access at all times'
        : 'Current visitor opening is published on the linked operator page';
    const admissionInformation = placeSpec.freeAdmission ? 'Free' : 'Current admission prices are published by the operator';
    const sourceNotes = [
      `Current-place curation: visitor_place_type=${visitorPlaceType}`,
      ...(placeSpec.score ? [`visit_score=${placeSpec.score}`] : []),
      ...(placeSpec.category ? [`tagline=${placeSpec.name}`] : []),
      ...(placeSpec.category === 'food' ? [`food_score=${placeSpec.score}`, 'cuisine=Coffee, cakes and light lunches', 'price_band=££', `opening_hours:description=${openingInformation}`] : []),
      ...(placeSpec.category === 'attraction' ? [`opening_hours:description=${openingInformation}`, `entrance_fee=${admissionInformation}`] : []),
      ...(placeSpec.details ? [placeSpec.details] : []),
      `description=${placeSpec.category === 'food' ? `${placeSpec.name}: ${placeSpec.description}` : placeSpec.description}`,
    ].join('; ');
    return {
      id:placeSpec.id, projectId:pkg.project.id, name:placeSpec.name, alternativeNames:[],
      countryCode:pkg.project.countryCode, region:pkg.project.region, locality:pkg.project.locality,
      featureType:placeSpec.featureType, significance:placeSpec.score && placeSpec.score >= 85 ? 'national' : 'local',
      geometry:{ type:'Point', coordinates:placeSpec.coordinates }, locationType:'exact', locationConfidence:'high',
      dateBasis:'unknown', dateConfidence:'unknown', survival:'substantially_intact', shortDescription:placeSpec.description,
      visitorWebsiteUrl:placeSpec.website,
      editorialReview:placeSpec.score && placeSpec.category ? {
        status:'editorially_researched', category:placeSpec.category, methodVersion:editorialRatingMethodVersion,
        reviewedAt:reviewedDate, scoreRationale:placeSpec.reason, evidenceUrls:[placeSpec.website],
        ...(placeSpec.category === 'food' ? { foodAssessment:assessment(placeSpec.score, 'food') } : { attractionAssessment:assessment(placeSpec.score, placeSpec.category) }),
      } : undefined,
      sourceRecords:[{ sourceName:`${placeSpec.name} current visitor evidence`, sourceOrganisation:placeSpec.website.includes('angus.gov.uk') ? 'Angus Council' : placeSpec.website.includes('treasuretrails') ? 'Treasure Trails' : 'VisitAngus / current operator', sourceUrl:placeSpec.website, accessedAt:reviewedAt, reliability:placeSpec.website.includes('angus.gov.uk') ? 'local_authority' : 'official_non_statutory', licence:'Source-linked editorial evidence; verify time-sensitive details before travel.', notes:sourceNotes }],
      tags:[...new Set([...placeSpec.tags, ...(placeSpec.category === 'food' ? ['service-context-food','visitor-context-food'] : []), ...(placeSpec.relatedContext ? ['related-context'] : [])])],
      createdAt:reviewedAt, updatedAt:reviewedAt, reviewed:true, evidenceScope:placeSpec.relatedContext ? 'related_context' : 'parish_evidence',
      reviewNotes:placeSpec.relatedContext ? 'Separately scored nearby attraction or route. It is published in See/Trails but excluded from the settlement score.' : 'Current strict-boundary visitor audit item.',
    };
  });
  pkg.features = [...pkg.features.filter((feature: any) => !feature.id.startsWith('curated-')), ...curated];
  const attractions = curated.filter((feature:any)=>feature.editorialReview?.category === 'attraction');
  pkg.project.visitorHighlights = attractions.map((feature:any,index:number)=>{ const placeSpec=spec.places.find((item)=>item.id===feature.id)!; const outdoors=placeSpec.freeAdmission || placeSpec.tags.includes('coastal-access') || placeSpec.featureType === 'park'; return { rank:index+1, featureId:feature.id, name:feature.name, reason:feature.editorialReview.scoreRationale, tagline:feature.name, visitorScore:placeSpec.score, timeToSpend:placeSpec.time ?? '45–90 minutes', openingTimes:outdoors ? 'Open access at all times' : 'Current visitor opening is published on the linked operator page', admission:placeSpec.freeAdmission ? 'Free' : 'Current admission prices are published by the operator', freeAdmission:placeSpec.freeAdmission ?? false, visitorWebsiteUrl:feature.visitorWebsiteUrl, editorialReview:feature.editorialReview, sourceName:feature.sourceRecords[0].sourceName, sourceUrl:feature.visitorWebsiteUrl, verifiedInBoundaryAt:reviewedDate }; }).sort((a:any,b:any)=>b.visitorScore-a.visitorScore).map((item:any,index:number)=>({...item,rank:index+1}));
  pkg.project.preferredBasemap = 'voyager';
  pkg.project.touristAppeal = { score:spec.score, dogOwnerScore:Math.max(0,spec.score-2), dogAccessScoreAdjustment:-2, rating:rating(spec.score), label:label(spec.score), summary:spec.summary, dogAccessRating:3, dogAccessSummary:'Outdoor places follow the Scottish Outdoor Access Code; indoor attraction and café access varies and should be checked with the operator.', methodVersion:'2026-09-01-strict-settlement-full-audit-v4', reviewedAt:reviewedDate, sourceUrls:[...new Set([...spec.places.map((item)=>item.website),...Object.values(providers)])] };
  pkg.project.townGuide = { characterTag:spec.character, headline:spec.headline, intro:spec.intro, bestFor:spec.places.filter((item)=>item.score && item.score>=70).slice(0,4).map((item)=>item.name), perfectFor:['A source-checked half-day plan','Visitors prioritising heritage, walking and daytime refreshments'], suggestedFirstVisit:{ title:'Start with the strongest See place', summary:`Begin with ${attractions[0]?.name ?? 'the historic centre'}, add a named trail and use the audited café and facility pins to complete the visit.` }, dontMiss:attractions.slice(0,5).map((item:any)=>item.name), suggestedTime:spec.score>=80?'A full day; a focused half day also works':'Two to four hours', visitorMood:spec.summary, sourceUrls:pkg.project.touristAppeal.sourceUrls, lastReviewedAt:reviewedDate };
  pkg.project.researchNotes = `Full current-web strict-boundary audit completed 2026-09-01. ${spec.intro} Explicit exclusions: ${spec.exclusions.join('; ')}. Treasure Trails, CuriousAbout, Mystery Guides and GoQuest were searched as live named providers. Current VisitAngus, Angus Council toilet directory, official council car-park geometry and parking policy were checked. HES/NRHE records remain complete in the local catalogue; undated records remain retained but map-hidden.`;
  const byType = (type:string)=>curated.filter((feature:any)=>feature.sourceRecords[0].notes.includes(`visitor_place_type=${type === 'Toilets' ? 'Public toilets' : type}`)).map((feature:any)=>feature.id);
  planner.projects[pkg.project.id] = { eat:byType('Eat'), trails:byType('Trail'), picnic:byType('Picnic'), parking:byType('Parking'), toilets:byType('Toilets') };
  const dogEntry = (feature:any) => ({ rating:feature.editorialReview?.category === 'food' ? 1 : feature.tags.includes('indoor-attraction') ? 1 : 3, status:feature.editorialReview?.category === 'food' || feature.tags.includes('indoor-attraction') ? 'unconfirmed' : 'outdoor_only', label:feature.editorialReview?.category === 'food' || feature.tags.includes('indoor-attraction') ? 'Check current dog policy' : 'Responsible outdoor access', summary:feature.editorialReview?.category === 'food' || feature.tags.includes('indoor-attraction') ? 'No reliable current dog policy was published; contact the operator if dog access is essential.' : 'Use responsible outdoor access under the Scottish Outdoor Access Code and heed site-specific restrictions.', sourceName:'Current operator and Scottish Outdoor Access Code review', sourceUrl:feature.visitorWebsiteUrl || providers.dogCode, reviewedAt:reviewedDate });
  dog.projects[pkg.project.id] = { attraction:Object.fromEntries(attractions.map((feature:any)=>[feature.id,dogEntry(feature)])), trail:Object.fromEntries(curated.filter((feature:any)=>feature.editorialReview?.category==='trail').map((feature:any)=>[feature.id,dogEntry(feature)])), eat:Object.fromEntries(curated.filter((feature:any)=>feature.editorialReview?.category==='food').map((feature:any)=>[feature.id,dogEntry(feature)])) };
  pkg.validation = validateFeatures(pkg.project, pkg.features);
  const errors = pkg.validation.filter((result:any)=>result.severity==='error');
  if (errors.length) throw new Error(`${pkg.project.name}: ${errors.map((result:any)=>result.message).join('; ')}`);
  await writeFile(projectPath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');
}

await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`, 'utf8');
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`, 'utf8');
console.log(JSON.stringify(specs.map((spec)=>({ place:spec.stem, score:spec.score, published:spec.score>=60, curatedPlaces:spec.places.length })), null, 2));
