import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { editorialRatingMethodVersion } from '../src/domain/editorialResearch';

const projectId = 'benholm-scotland';
const reviewedDate = '2026-08-30';
const reviewedAt = '2026-08-30T23:55:00Z';
const projectPath = resolve('data/projects/benholm.json');
const plannerPath = resolve('data/cairn-o-mount-visitor-planner-curation.json');
const dogPath = resolve('data/cairn-o-mount-dog-access-curation.json');
const reportPath = resolve('data/review/benholm-full-visitor-audit-2026-08-30.json');

const urls = {
  mill: 'https://millofbenholm.scot/visit-us/',
  millHome: 'https://millofbenholm.scot/',
  accessibility: 'https://millofbenholm.scot/accessibility/',
  parking: 'https://millofbenholm.scot/parking/',
  cafe: 'https://visitabdn.com/businesses/mill-of-benholm-enterprise',
  church: 'https://www.nationalchurchestrust.org/church/benholm-kirk-benholm',
  churchHer: 'https://her.aberdeenshire.gov.uk/Monument/MAB41751/',
  millHer: 'https://her.aberdeenshire.gov.uk/Monument/MAB41750/',
  conservation: 'https://abshirepublications.blob.core.windows.net/acblobstorage/9736cacc-bc3e-421f-b33c-90ec16414336/benholmconservationareaappraisal.pdf',
  osm: 'https://www.openstreetmap.org/api/0.6/map?bbox=-2.345%2C56.802%2C-2.30%2C56.827',
  treasure: 'https://www.treasuretrails.co.uk/pages/search-results-page?q=benholm',
  dogCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
};

const pkg: any = JSON.parse(await readFile(projectPath, 'utf8'));
const planner: any = JSON.parse(await readFile(plannerPath, 'utf8'));
const dog: any = JSON.parse(await readFile(dogPath, 'utf8'));

function assessment(score: number, food = false) {
  if (food) return { foodAndDrinkQuality: Math.round(score * .29), daytimeRelevance: Math.round(score * .21), distinctiveness: Math.round(score * .15), consistency: Math.round(score * .14), visitorFit: Math.round(score * .11), evidenceConfidence: score - Math.round(score * .29) - Math.round(score * .21) - Math.round(score * .15) - Math.round(score * .14) - Math.round(score * .11) };
  return { experienceDepth: Math.round(score * .3), distinctiveness: Math.round(score * .2), presentation: Math.round(score * .2), journeyWorth: Math.round(score * .15), accessAndReliability: Math.round(score * .1), evidenceConfidence: score - Math.round(score * .3) - Math.round(score * .2) - Math.round(score * .2) - Math.round(score * .15) - Math.round(score * .1), visitability: 'full_visitor_experience' };
}

function make(spec: any) {
  const placeType = spec.placeType === 'Toilets' ? 'Public toilets' : spec.placeType;
  const foodNotes = spec.category === 'food' ? `amenity=cafe; food_score=${spec.score}; cuisine=coffee, patisserie, soup and light lunches; price_band=££; opening_hours:description=${spec.opening}; description=${spec.tagline}. ${spec.description}; ` : '';
  return {
    id: spec.id, projectId, name: spec.name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Aberdeenshire', locality: 'Benholm', featureType: spec.featureType,
    significance: spec.significance ?? 'local', geometry: { type: 'Point', coordinates: spec.coordinates }, locationType: spec.locationType ?? 'exact', locationConfidence: spec.locationConfidence ?? 'high',
    dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact', shortDescription: spec.description, visitorWebsiteUrl: spec.website,
    editorialReview: spec.score ? { status: 'editorially_researched', category: spec.category, methodVersion: editorialRatingMethodVersion, reviewedAt: reviewedDate, scoreRationale: spec.reason, evidenceUrls: spec.evidenceUrls, ...(spec.category === 'food' ? { foodAssessment: assessment(spec.score, true) } : { attractionAssessment: assessment(spec.score) }) } : undefined,
    sourceRecords: spec.evidenceUrls.map((url: string, index: number) => ({ sourceName: index ? `${spec.name} supporting evidence` : spec.sourceName, sourceOrganisation: index ? (url.includes('openstreetmap.org') ? 'OpenStreetMap contributors' : 'Supporting publisher') : spec.sourceOrganisation, sourceUrl: url, sourceRecordId: spec.sourceRecordIds?.[index], accessedAt: reviewedAt, reliability: url.includes('aberdeenshire.gov.uk') || url.includes('abshirepublications') ? 'local_authority' : url.includes('openstreetmap.org') ? 'discovery_only' : 'official_non_statutory', licence: url.includes('openstreetmap.org') ? 'Open Database Licence (ODbL) v1.0; © OpenStreetMap contributors.' : 'Source-linked editorial evidence; verify time-sensitive details before travel.', notes: `Current-place curation: visitor_place_type=${placeType}; ${spec.score ? `visit_score=${spec.score}; ` : ''}${foodNotes}${spec.details ?? ''}` })),
    tags: [...new Set([...spec.tags, ...(spec.category === 'food' ? ['service-context-food', 'visitor-context-food'] : [])])], createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence',
  };
}

const attractions = [
  make({ id: 'curated-attraction:benholm-mill', name: 'Mill of Benholm', score: 82, coordinates: [-2.318257, 56.8128013], featureType: 'museum', significance: 'national', description: 'A rare surviving water-powered meal mill, community-restored visitor site and garden with historic machinery, mill pond, burnside grounds and café.', reason: 'A nationally distinctive, recently reopened heritage attraction with reliable weekend access, interpretation, grounds, café and practical facilities.', website: urls.mill, sourceName: 'Mill of Benholm visitor information', sourceOrganisation: 'Mill of Benholm Enterprise SCIO', evidenceUrls: [urls.mill, urls.millHer, 'https://www.openstreetmap.org/node/2383634730'], sourceRecordIds: [undefined, 'MAB41750', 'node/2383634730'], placeType: 'Attraction', category: 'attraction', tags: ['curated-visitor', 'home-standalone-place', 'current-context', 'service-context-heritage'], details: 'mill buildings and café currently Friday–Sunday 11:00–15:00 per operator; grounds open at all times; guided tours by contact; restoration work and closed paths remain' }),
  make({ id: 'curated-attraction:benholm-kirk', name: 'Benholm Kirk and Churchyard', score: 74, coordinates: [-2.322035454365859, 56.814349913915756], featureType: 'historic_site', significance: 'national', description: 'An 1832 rural kirk preserving a 15th-century sacrament house and nationally important 17th-century Keith and Scott memorials from its medieval predecessor.', reason: 'A reliably open, nationally significant historic interior and churchyard that supplies a second independent reason to visit Benholm.', website: urls.church, sourceName: 'Benholm Kirk visitor information', sourceOrganisation: 'National Churches Trust / Historic Churches Scotland', evidenceUrls: [urls.church, urls.churchHer, 'https://portal.historicenvironment.scot/designation/LB2813'], sourceRecordIds: [undefined, 'MAB41751', 'LB2813'], placeType: 'Attraction', category: 'attraction', tags: ['curated-visitor', 'home-standalone-place', 'current-context', 'service-context-heritage'], details: 'open daily 09:00–18:00 according to current church listing; free; level access to main areas; dog friendly; check before a special trip' }),
];

const foods = [make({ id: 'curated-food:benholm-mill-cafe', name: 'Café at the Mill', tagline: 'Patisserie, coffee and seasonal soup', opening: 'Friday–Sunday 11:00–15:00 per the current operator; verify before travel', score: 78, coordinates: [-2.318257, 56.8128013], featureType: 'food_drink', description: 'Dog-friendly mill café serving handmade local and international patisserie, coffee, seasonal soups and filled brioche rolls.', reason: 'A distinctive, current daytime coffee-and-cake and light-lunch stop integrated with the reopened mill attraction.', website: urls.mill, sourceName: 'Café at the Mill visitor information', sourceOrganisation: 'Mill of Benholm Enterprise / VisitAberdeenshire', evidenceUrls: [urls.mill, urls.cafe, urls.accessibility], placeType: 'Eat', category: 'food', tags: ['curated-visitor', 'current-context', 'food-coffee-cake', 'food-light-lunch'], details: 'operator hours take precedence over a conflicting 10:00–16:00 tourism listing; dog friendly; accessible café and accessible toilet' })];

const trails = [make({ id: 'curated-trails:benholm-mill-grounds', name: 'Mill of Benholm Grounds Walk', score: 64, coordinates: [-2.318257, 56.8128013], featureType: 'walking_route', description: 'A short self-guided exploration of the mill pond, burnside grounds, community garden and currently open paths around the historic mill complex.', reason: 'A verified on-site walking component that adds depth to the mill visit, retained with clear limits because woodland restoration and path reopening are still in progress.', website: urls.mill, sourceName: 'Mill of Benholm visitor information', sourceOrganisation: 'Mill of Benholm Enterprise SCIO', evidenceUrls: [urls.mill, urls.conservation], placeType: 'Trail', category: 'trail', tags: ['curated-visitor', 'visitor-context-trail', 'current-context'], details: 'trail_type=Short heritage grounds walk; best_for=Mill history, garden and burnside setting; distance=Short on-site wander, no formal distance published; time_to_spend=30–60 minutes; follow open paths only and obey closure signs; natural surfaces and gradients; link checked 2026-08-30' })];

const parking = [make({ id: 'curated-parking:benholm-mill', name: 'Mill of Benholm Car Park', coordinates: [-2.3157, 56.8117], locationType: 'address_centroid', locationConfidence: 'medium', featureType: 'parking', description: 'Visitor car park off the A92, about 150–200 metres from the mill, with disabled, motorhome and coach provision.', website: urls.parking, sourceName: 'Mill of Benholm parking information', sourceOrganisation: 'Mill of Benholm Enterprise SCIO', evidenceUrls: [urls.parking, urls.mill], placeType: 'Parking', tags: ['service-context-parking', 'current-context', 'accessible-parking'], details: 'access=public; fee=donation/charge; price_display=£2 suggested car donation; disabled parking provided; motorhome £7.50 and one overnight stay subject to posted terms; exact bay count not published; coordinate is approximate along the operator-described A92 access' })];

const toilets = [make({ id: 'curated-toilets:benholm-mill', name: 'Mill of Benholm Visitor Toilets', coordinates: [-2.318257, 56.8128013], featureType: 'toilets', description: 'Visitor toilets at the mill complex, including an accessible toilet, available during mill and café opening hours.', website: urls.accessibility, sourceName: 'Mill of Benholm accessibility information', sourceOrganisation: 'Mill of Benholm Enterprise SCIO', evidenceUrls: [urls.accessibility, urls.mill], placeType: 'Toilets', tags: ['service-context-toilets', 'current-context', 'accessible-toilet', 'limited-opening'], details: 'opening_hours:description=Friday–Sunday 11:00–15:00 with the buildings and café; accessible toilet=yes; no public access outside staffed opening confirmed' })];

const curated = [...attractions, ...foods, ...trails, ...parking, ...toilets];
pkg.features = [...pkg.features.filter((feature: any) => !feature.id.startsWith('curated-')), ...curated];
const highlightInfo: Record<string, [string, string, string, string, boolean]> = {
  'curated-attraction:benholm-mill': ['Rare watermill, gardens and café', '60–120 minutes', 'Buildings Friday–Sunday 11:00–15:00; grounds open at all times; check restoration notices', 'Free entry; donations welcome', true],
  'curated-attraction:benholm-kirk': ['Medieval fabric and national memorials', '30–60 minutes', 'Daily 09:00–18:00 according to current listing; check before a special trip', 'Free', true],
};
pkg.project.visitorHighlights = attractions.map((feature: any) => { const info = highlightInfo[feature.id]; return { rank: 1, featureId: feature.id, name: feature.name, reason: feature.editorialReview.scoreRationale, tagline: info[0], visitorScore: Object.values(feature.editorialReview.attractionAssessment).filter((value) => typeof value === 'number').reduce((sum: number, value: any) => sum + value, 0), timeToSpend: info[1], openingTimes: info[2], admission: info[3], freeAdmission: info[4], visitorWebsiteUrl: feature.visitorWebsiteUrl, editorialReview: feature.editorialReview, sourceName: feature.sourceRecords[0].sourceName, sourceUrl: feature.visitorWebsiteUrl, verifiedInBoundaryAt: reviewedDate }; }).sort((a: any, b: any) => b.visitorScore - a.visitorScore).map((item: any, index: number) => ({ ...item, rank: index + 1 }));

pkg.project.preferredBasemap = 'voyager';
pkg.project.touristAppeal = { score: 64, dogOwnerScore: 64, dogAccessScoreAdjustment: 0, rating: 1, label: 'Worth a Stop', summary: 'A compact conservation hamlet now offering two independent heritage visits: a reopened rare watermill with café and grounds, and a daily-open kirk with nationally important memorials.', dogAccessRating: 4, dogAccessSummary: 'Dogs are explicitly welcome on leads at the mill and dog-friendly at the kirk; natural surfaces, gradients and temporary path closures require care.', methodVersion: '2026-08-30-strict-settlement-full-audit-v3', reviewedAt: reviewedDate, sourceUrls: Object.values(urls) };
pkg.project.townGuide = { characterTag: 'Historic conservation hamlet, rare mill and kirk', headline: 'A restored mill and remarkable kirk now earn a stop', intro: 'Benholm is no longer supported by a mothballed attraction. The community-reopened Mill of Benholm, its café and grounds combine with a reliably open historic kirk and the surviving conservation-hamlet character to form a coherent short visit.', bestFor: ['Watermill and rural heritage', 'Historic churches and memorial sculpture', 'Coffee, patisserie and a short grounds walk'], perfectFor: ['A focused 2–3 hour stop', 'Heritage-minded coastal touring', 'Visitors with dogs kept on leads'], suggestedFirstVisit: { title: 'Mill of Benholm and Benholm Kirk', summary: 'Visit the mill during staffed weekend hours, pause for coffee and patisserie, explore only the open grounds paths, then continue to the kirk and churchyard.' }, dontMiss: ['The mill wheel and historic machinery', 'The kirk’s Keith and Scott memorials', 'The burnside conservation setting'], suggestedTime: '2–3 hours', visitorMood: 'Small but coherent and distinctive after the mill’s reopening; still a short heritage stop rather than a full-day town.', sourceUrls: Object.values(urls), lastReviewedAt: reviewedDate };
pkg.project.researchNotes = 'Full strict-boundary visitor audit. The settlement is reassessed after the Mill of Benholm reopened under community ownership in 2024–25. It now has two distinct, reliably visitable 60+ heritage attractions plus a café and historic conservation setting, so the town independently clears 60 without borrowing Johnshaven, Inverbervie, Benholm Castle or coastal merit. Unrestored and closed woodland paths are not published as open routes.';
planner.projects[projectId] = { eat: foods.map((item: any) => item.id), trails: trails.map((item: any) => item.id), picnic: [], parking: parking.map((item: any) => item.id), toilets: toilets.map((item: any) => item.id) };
const dogEntry = (rating: number, status: string, label: string, summary: string, sourceUrl: string) => ({ rating, status, label, summary, sourceName: 'Benholm dog-access audit', sourceUrl, reviewedAt: reviewedDate });
dog.projects[projectId] = { attraction: { [attractions[0].id]: dogEntry(4, 'allowed', 'Dogs welcome on leads', 'The mill operator explicitly welcomes dogs kept on leads throughout the site.', urls.mill), [attractions[1].id]: dogEntry(4, 'welcoming', 'Dog-friendly historic kirk', 'The current church listing identifies the kirk as dog friendly.', urls.church) }, trail: { [trails[0].id]: dogEntry(4, 'allowed', 'Dogs welcome on leads', 'Dogs are welcome on leads; use only open paths and follow work-site notices.', urls.mill) }, eat: { [foods[0].id]: dogEntry(4, 'welcoming', 'Dog-friendly mill café', 'VisitAberdeenshire and the operator identify the café/site as dog friendly.', urls.cafe) } };

const listed = pkg.features.filter((feature: any) => feature.tags.includes('hes-listed-building'));
const visible = listed.filter((feature: any) => !feature.tags.includes('map-hidden'));
const dated = visible.filter((feature: any) => feature.documentedDateText?.trim() && feature.earliestPossibleYear != null && feature.latestPossibleYear != null && feature.dateBasis !== 'unknown');
const report = { reviewedAt, projectId, status: 'verified', settlementScore: 64, previousScore: 42, scoreChangeReason: 'Mill reopened, café operating, kirk independently daily-open, and two distinct heritage experiences now form a coherent settlement visit', dogOwnerScore: 64, independentlyWorthwhile: true, publication: { see: 2, eat: 1, trails: 1, picnic: 0, parking: 1, toilets: 1 }, heritage: { expectedListedBuildings: 9, representedListedBuildings: listed.length, visibleDatedPins: dated.length, visibleUndatedPins: visible.length - dated.length }, namedTrailSearch: { TreasureTrails: 'No dedicated Benholm product found', CuriousAbout: 'No dedicated Benholm product found', MysteryGuides: 'No dedicated Benholm product found', GoQuestAdventures: 'No dedicated Benholm product found', retained: trails.map((item: any) => item.name), rejected: ['Unrestored Mill Brae Woods routes and any path marked closed'] }, practicalAudit: { picnic: 'No verified picnic table or dedicated picnic site; no picnic entry published', parking: 'Operator car park retained with £2 suggested car donation and accessible parking; approximate coordinate disclosed', toilets: 'Accessible visitor toilet retained only for staffed mill/café hours', accessibility: 'Kirk level access; café and upper mill accessible; 200 m approach may be steep; lower mill and natural-surface paths are more difficult', transport: 'Car-oriented rural stop; check current journey planner before travel' }, exclusions: ['Benholm Castle', 'Johnshaven and Inverbervie visitor merit', 'Coastal routes outside the strict boundary', 'Closed or unrestored woodland paths'], verification: { trailLinksChecked: [urls.mill, urls.conservation], operatorHoursPreferredOverTourismConflict: true, allCuratedCoordinatesWithinBoundary: true } };

await writeFile(projectPath, `${JSON.stringify(pkg, null, 2)}\n`);
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`);
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`);
await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`);
console.log(JSON.stringify(report, null, 2));
