import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { editorialRatingMethodVersion } from '../src/domain/editorialResearch';

const projectId = 'brechin-scotland';
const reviewedDate = '2026-08-30';
const reviewedAt = '2026-08-30T23:58:00Z';
const projectPath = resolve('data/projects/brechin.json');
const plannerPath = resolve('data/cairn-o-mount-visitor-planner-curation.json');
const dogPath = resolve('data/cairn-o-mount-dog-access-curation.json');
const reportPath = resolve('data/review/brechin-full-visitor-audit-2026-08-30.json');

const urls = {
  visitAngus: 'https://visitangus.com/plan-your-trip/explore-our-towns/brechin/',
  glencadam: 'https://www.glencadamwhisky.com/pages/visitor-centre',
  glencadamAccess: 'https://www.glencadamwhisky.com/pages/contact',
  railway: 'https://www.caledonianrailway.com/',
  railwayFaq: 'https://www.caledonianrailway.com/faq',
  cathedral: 'https://brechincathedral.co.uk/',
  cathedralTrust: 'https://www.churchofscotland.org.uk/news-and-events/news/articles/community-trust-takes-over-ownership-of-brechin-cathedral',
  cathedralNct: 'https://www.nationalchurchestrust.org/church/brechin-cathedral-brechin',
  roundTower: 'https://www.historicenvironment.scot/visit/all/brechin-cathedral-round-tower/plan-your-visit/',
  maisonDieu: 'https://www.historicenvironment.scot/visit/all/masion-dieu-chapel/',
  pathNetwork: 'https://www.angus.gov.uk/media/brechin_path_network',
  pathPdf: 'https://www.angus.gov.uk/sites/angus-cms/files/2017-08/Brechin%20path%20network.pdf',
  dogVisit: 'https://visitangus.com/get-inspired/itineraries/a-dog-friendly-visit-to-brechin/',
  inchPark: 'https://www.wildsouthesk.org/places-to-explore/inch-park/',
  maisonCoffee: 'https://maisondieucoffee.co.uk/pages/brechin-cafe',
  whistleStop: 'https://visitangus.com/things-to-see-do/food-drink/whistle-stop-cafe/',
  auldBakehouse: 'https://restaurantguru.com/The-Auld-Bakehouse-Brechin',
  gourmetGrocer: 'https://gourmetgrocerbrechin.co.uk/',
  parking: 'https://www.angus.gov.uk/roads_parking_and_travel/parking/find_a_car_park?page_id=1184',
  parkingPolicy: 'https://www.angus.gov.uk/roads_parking_and_travel/parking/changes_to_parking_and_parking_review',
  parkingDataset: 'https://opendata.angus.gov.uk/dataset/car-parks',
  publicToilet: 'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/brechin_church_street',
  treasure: 'https://www.treasuretrails.co.uk/pages/search-results-page?q=brechin',
  castleCentre: 'https://www.brechincastlecentre.co.uk/country-park/',
  hesGarden: 'https://portal.historicenvironment.scot/designation/GDL00070',
  hesMaison: 'https://portal.historicenvironment.scot/designation/SM90040',
  hesRoundTower: 'https://portal.historicenvironment.scot/designation/SM90041',
};

const pkg: any = JSON.parse(await readFile(projectPath, 'utf8'));
const planner: any = JSON.parse(await readFile(plannerPath, 'utf8'));
const dog: any = JSON.parse(await readFile(dogPath, 'utf8'));

function assessment(score: number, food = false) {
  if (food) return { foodAndDrinkQuality: Math.round(score * .29), daytimeRelevance: Math.round(score * .21), distinctiveness: Math.round(score * .15), consistency: Math.round(score * .14), visitorFit: Math.round(score * .11), evidenceConfidence: score - Math.round(score * .29) - Math.round(score * .21) - Math.round(score * .15) - Math.round(score * .14) - Math.round(score * .11) };
  return { experienceDepth: Math.round(score * .3), distinctiveness: Math.round(score * .2), presentation: Math.round(score * .2), journeyWorth: Math.round(score * .15), accessAndReliability: Math.round(score * .1), evidenceConfidence: score - Math.round(score * .3) - Math.round(score * .2) - Math.round(score * .2) - Math.round(score * .15) - Math.round(score * .1), visitability: 'full_visitor_experience' };
}

function make(spec: any) {
  const placeType = spec.placeType === 'Toilets' ? 'Public toilets' : spec.placeType;
  const foodNotes = spec.category === 'food' ? `amenity=cafe; food_score=${spec.score}; cuisine=${spec.cuisine ?? 'coffee, cake and light lunches'}; price_band=${spec.price ?? '££'}; opening_hours:description=${spec.opening}; description=${spec.tagline}. ${spec.description}; ` : '';
  return {
    id: spec.id, projectId, name: spec.name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Angus', locality: 'Brechin', featureType: spec.featureType,
    significance: spec.significance ?? 'local', geometry: { type: 'Point', coordinates: spec.coordinates }, locationType: spec.locationType ?? 'exact', locationConfidence: spec.locationConfidence ?? 'high',
    dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact', shortDescription: spec.description, visitorWebsiteUrl: spec.website,
    editorialReview: spec.score ? { status: 'editorially_researched', category: spec.category, methodVersion: editorialRatingMethodVersion, reviewedAt: reviewedDate, scoreRationale: spec.reason, evidenceUrls: spec.evidenceUrls, ...(spec.category === 'food' ? { foodAssessment: assessment(spec.score, true) } : { attractionAssessment: assessment(spec.score) }) } : undefined,
    sourceRecords: spec.evidenceUrls.map((url: string, index: number) => ({ sourceName: index ? `${spec.name} supporting evidence` : spec.sourceName, sourceOrganisation: index ? (url.includes('openstreetmap.org') ? 'OpenStreetMap contributors' : 'Supporting publisher') : spec.sourceOrganisation, sourceUrl: url, sourceRecordId: spec.sourceRecordIds?.[index], accessedAt: reviewedAt, reliability: url.includes('angus.gov.uk') || url.includes('historicenvironment.scot') || url.includes('churchofscotland.org.uk') ? 'local_authority' : url.includes('openstreetmap.org') ? 'discovery_only' : 'official_non_statutory', licence: url.includes('openstreetmap.org') ? 'Open Database Licence (ODbL) v1.0; © OpenStreetMap contributors.' : 'Source-linked editorial evidence; verify time-sensitive details before travel.', notes: `Current-place curation: visitor_place_type=${placeType}; ${spec.score ? `visit_score=${spec.score}; ` : ''}${foodNotes}${spec.details ?? ''}` })),
    tags: [...new Set([...spec.tags, ...(spec.category === 'food' ? ['service-context-food', 'visitor-context-food'] : [])])], createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence',
  };
}

const attractions = [
  make({ id:'curated-attraction:brechin-glencadam', name:'Glencadam Distillery Visitor Centre', score:89, coordinates:[-2.6535092,56.7363112], featureType:'museum', significance:'national', description:'A daily-open visitor centre at the working 1825 distillery, with production and warehouse tours, tutored tastings, exhibition, whisky lounge, shop and panoramic café terrace.', reason:'A bookable, substantial and nationally distinctive whisky experience with daily access, strong interpretation and complete visitor facilities.', website:urls.glencadam, sourceName:'Glencadam visitor centre', sourceOrganisation:'Angus Dundee Distillers', evidenceUrls:[urls.glencadam,urls.glencadamAccess,'https://www.openstreetmap.org/way/411715378'], sourceRecordIds:[undefined,undefined,'way/411715378'], placeType:'Attraction', category:'attraction', tags:['curated-visitor','home-standalone-place','current-context','service-context-heritage'], details:'shop and café daily 09:00–17:00; tours daily 10:00–15:30, advance booking strongly recommended; standard tour 90 minutes and £22.50; visitor centre, warehouse and exhibition accessible' }),
  make({ id:'curated-attraction:brechin-caledonian-railway', name:'Caledonian Railway', score:87, coordinates:[-2.6529037,56.7316177], featureType:'museum', significance:'national', description:'A volunteer-run heritage railway operating steam and diesel journeys on the four-mile branch from its preserved 1848 Brechin station to Bridge of Dun.', reason:'A destination-scale, bookable heritage railway experience with an events programme, historic station, café, shop, toilets and accessible trains.', website:urls.railway, sourceName:'Caledonian Railway visitor information', sourceOrganisation:'Caledonian Railway Brechin Ltd', evidenceUrls:[urls.railway,urls.railwayFaq,'https://www.openstreetmap.org/way/503280522'], sourceRecordIds:[undefined,undefined,'way/503280522'], placeType:'Attraction', category:'attraction', tags:['curated-visitor','home-standalone-place','current-context','service-context-heritage'], details:'selected operating dates including summer weekends and special events; check and book current departures; adult Steam Sunday return currently £10; stations and trains wheelchair accessible with ramps' }),
  make({ id:'curated-attraction:brechin-cathedral-round-tower', name:'Brechin Cathedral and Round Tower', score:85, coordinates:[-2.6616419822410737,56.730619515347534], featureType:'historic_site', significance:'highest_national', description:'An exceptional medieval cathedral precinct with Pictish sculpture, stained glass and one of Scotland’s only two Irish-style round towers, built around 1100.', reason:'A nationally exceptional and highly distinctive historic complex with a substantial cathedral interior and rare scheduled round tower.', website:urls.cathedral, sourceName:'Brechin Cathedral and Round Tower visitor evidence', sourceOrganisation:'Brechin Cathedral Trust / Historic Environment Scotland', evidenceUrls:[urls.cathedralTrust,urls.roundTower,urls.cathedralNct,urls.hesRoundTower], placeType:'Attraction', category:'attraction', tags:['curated-visitor','home-standalone-place','current-context','service-context-heritage'], details:'ownership transferred to Brechin Cathedral Trust on 14 August 2026; tower exterior is free when cathedral grounds are open; confirm current cathedral interior opening before travel during the transition' }),
  make({ id:'curated-attraction:brechin-maison-dieu', name:'Maison Dieu Chapel', score:76, coordinates:[-2.6608695665099207,56.7328158788206], featureType:'historic_site', significance:'highest_national', description:'The rare standing remains of a hospital chapel founded in 1256 to serve Brechin’s poor, preserving fine Early Gothic windows and doorway in an unexpected urban setting.', reason:'A nationally important and reliably accessible medieval monument that adds a separate compact heritage visit to the town centre.', website:urls.maisonDieu, sourceName:'Maison Dieu Chapel visitor information', sourceOrganisation:'Historic Environment Scotland', evidenceUrls:[urls.maisonDieu,urls.hesMaison], placeType:'Attraction', category:'attraction', tags:['curated-visitor','home-standalone-place','current-context','service-context-heritage'], details:'open all year; free exterior monument; short stop on Maison Dieu Lane' }),
  make({ id:'curated-attraction:brechin-inch-park', name:'Inch Park and River South Esk', score:70, coordinates:[-2.6557771,56.7276445], featureType:'park', description:'Riverside woodland, wildflower meadow and open green space beside the South Esk, linked downstream to historic Brechin Bridge and its story mosaics.', reason:'A verified, coherent riverside park experience that supplies accessible outdoor depth within Brechin rather than borrowing a neighbouring attraction.', website:urls.inchPark, sourceName:'Inch Park visitor information', sourceOrganisation:'Wild South Esk / Visit Angus', evidenceUrls:[urls.inchPark,urls.dogVisit,'https://www.openstreetmap.org/way/90868693'], sourceRecordIds:[undefined,undefined,'way/90868693'], placeType:'Attraction', category:'attraction', tags:['curated-visitor','home-standalone-place','current-context','visitor-context-nature'], details:'free public open space; woodland and riverside surfaces vary; river conditions and flood damage can affect paths' }),
];

const foods = [
  make({ id:'curated-food:brechin-glencadam-cafe', name:'Glencadam Café', tagline:'Coffee and cake with a view', opening:'Daily 09:00–17:00', score:84, coordinates:[-2.6535092,56.7363112], featureType:'food_drink', description:'A top-floor distillery café using Angus produce, with cakes, light bites and a terrace overlooking Brechin.', reason:'A distinctive, daily and accessible coffee-and-cake stop integrated with the major new visitor centre.', website:urls.glencadam, sourceName:'Glencadam visitor centre', sourceOrganisation:'Angus Dundee Distillers', evidenceUrls:[urls.glencadam,urls.glencadamAccess], placeType:'Eat', category:'food', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], details:'visitor centre café; fully accessible exhibition and visitor spaces' }),
  make({ id:'curated-food:brechin-maison-dieu-coffee', name:'Maison Dieu Coffee Roasters', tagline:'Speciality coffee roasted here', opening:'Tuesday–Friday 07:00–15:00, Saturday 09:00–16:00, Sunday 10:00–15:00; Monday closed', score:82, coordinates:[-2.6382662,56.7266808], featureType:'food_drink', description:'The original Maison Dieu speciality-coffee café and working roastery, with outdoor seating, takeaway drinks and an ever-changing cake selection.', reason:'Brechin’s most distinctive dedicated coffee stop, backed by a current operator page and a seven-day-style schedule excluding Monday.', website:urls.maisonCoffee, sourceName:'Maison Dieu Brechin café', sourceOrganisation:'Maison Dieu Coffee Roasters', evidenceUrls:[urls.maisonCoffee], placeType:'Eat', category:'food', tags:['curated-visitor','current-context','food-coffee-cake'], details:'operator page contains a minor conflicting 07:00/08:00 weekday display; the detailed current location panel is recorded and visitors should verify' }),
  make({ id:'curated-food:brechin-whistle-stop', name:'The Whistle Stop Café', tagline:'Home baking on a heritage platform', opening:'Wednesday–Saturday 10:00–15:00 per current Visit Angus listing; railway-event dates may differ', score:78, coordinates:[-2.6529037,56.7316177], featureType:'food_drink', description:'A family-run café in Brechin’s historic railway station serving locally sourced drinks, home baking and light lunches.', reason:'A characterful and independently useful daytime café with verified accessibility and a strong connection to the railway visit.', website:urls.whistleStop, sourceName:'Whistle Stop Café visitor listing', sourceOrganisation:'Visit Angus / Caledonian Railway', evidenceUrls:[urls.whistleStop,urls.railwayFaq], placeType:'Eat', category:'food', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], details:'level access, accessible parking and toilets; dogs welcome on a lead and on the floor' }),
  make({ id:'curated-food:brechin-auld-bakehouse', name:'The Auld Bakehouse', tagline:'Soup, sandwiches and home baking', opening:'Tuesday–Saturday 09:30–15:00; Sunday and Monday closed on the checked listing', score:76, coordinates:[-2.660297164353873,56.731625033628724], featureType:'food_drink', description:'A well-established High Street café focused on soup, filled sandwiches, coffee, tea and cakes during daytime service.', reason:'A strong town-centre light-lunch and baking option, retained on current 2026 business evidence rather than dinner provision.', website:urls.auldBakehouse, sourceName:'Auld Bakehouse current business listing', sourceOrganisation:'Restaurant Guru / business operator listing', evidenceUrls:[urls.auldBakehouse,'https://portal.historicenvironment.scot/designation/LB22522'], sourceRecordIds:[undefined,'LB22522'], placeType:'Eat', category:'food', tags:['curated-visitor','current-context','food-coffee-cake','food-light-lunch'], details:'26 High Street; pin uses the exact HES building point; Sunday and Monday closed on the checked listing' }),
  make({ id:'curated-food:brechin-gourmet-grocer', name:'Gourmet Grocer at 29', tagline:'Local deli and picnic supplies', opening:'Monday–Saturday 09:00–15:00; Sunday closed', score:68, coordinates:[-2.661585,56.7319997], featureType:'food_drink', description:'An independent old-style grocer and deli with local produce, more than forty cheeses, meats, pâtés, groceries and gift hampers.', reason:'A useful and distinctive town-centre source for picnic supplies, included below the café-led stops and not presented as a full restaurant.', website:urls.gourmetGrocer, sourceName:'Gourmet Grocer at 29', sourceOrganisation:'Gourmet Grocer at 29', evidenceUrls:[urls.gourmetGrocer,'https://www.openstreetmap.org/node/8431784633'], sourceRecordIds:[undefined,'node/8431784633'], placeType:'Eat', category:'food', cuisine:'deli and picnic supplies', price:'££', tags:['curated-visitor','current-context','food-light-lunch','picnic-supplies'], details:'29 St David Street; exact OSM point; this is a deli/shop rather than a sit-down café' }),
];

const trailSpecs = [
  ['town-circuit','Brechin Town Circuit',76,[-2.6529037,56.7316177],'4 miles / about 2 hours','Former railway nature trail, historic centre, Town House exterior and cathedral precinct'],
  ['burghill-circuit','Brechin Burghill Circuit',74,[-2.6480239,56.7233578],'5.5 miles / about 2.75 hours','Riverside, woodland and elevated views south of the South Esk'],
  ['trinity-circuit','Brechin Trinity Circuit',73,[-2.6529037,56.7316177],'7 miles / about 3.5 hours on foot; about 1 hour cycling','Longer off-road circuit using old cattle raiks and the former railway'],
  ['maisondieu-circuit','Brechin Maisondieu Circuit',71,[-2.6608695665099207,56.7328158788206],'3.5 miles / about 1.75 hours','Tree-lined raik towards Trinity Muir with views to the Angus Glens'],
] as const;
const trails = trailSpecs.map(([slug,name,score,coordinates,distance,summary]) => make({ id:`curated-trails:brechin-${slug}`, name, score, coordinates, featureType:'walking_route', description:`An official Angus path-network route: ${summary.toLowerCase()}.`, reason:'A named, mapped and distance-graded council route starting in Brechin, retained after direct link validation.', website:urls.pathNetwork, sourceName:'Brechin Path Network', sourceOrganisation:'Angus Council', evidenceUrls:[urls.pathNetwork,urls.pathPdf], placeType:'Trail', category:'trail', tags:['curated-visitor','visitor-context-trail','current-context'], details:`trail_type=Official signed path-network circuit; best_for=${summary}; distance=${distance}; surfaces include hard paths, farm tracks, grass and potentially muddy sections; dogs under close control, especially around livestock; link checked ${reviewedDate}` }));

const parkingSpecs = [
  ['church-street','Church Street Car Park',[-2.6610429038674517,56.73165863183385],32,'short stay, maximum four hours'],
  ['maisondieu-east','Maisondieu Lane East Car Park',[-2.660978535673139,56.73257616020834],16,'short stay, maximum four hours'],
  ['market-street','Market Street Car Park',[-2.6607364575562737,56.73250918944022],18,'short stay, maximum four hours'],
  ['city-road-south','City Road South End Car Park',[-2.657092186186839,56.73053336520077],15,'long stay, maximum 72 hours'],
  ['maisondieu-west','Maisondieu Lane West Car Park',[-2.6616929497192086,56.7325361702997],63,'long stay, maximum 72 hours'],
  ['city-road-west','City Road West Side Car Park',[-2.658124289783331,56.7311384092099],29,'long stay, maximum 72 hours'],
] as const;
const parking = parkingSpecs.map(([slug,name,coordinates,bays,stay]) => make({ id:`curated-parking:brechin-${slug}`, name, coordinates, featureType:'parking', description:`Free Angus Council town-centre car park with ${bays} bays; ${stay}.`, website:urls.parking, sourceName:'Angus Council car park register and polygons', sourceOrganisation:'Angus Council', evidenceUrls:[urls.parking,urls.parkingPolicy,urls.parkingDataset], placeType:'Parking', tags:['service-context-parking','current-context'], details:`access=public; fee=no; payment_required=no; price_display=Free; capacity=${bays}; stay=${stay}; pin is the centroid of the official council car-park polygon transformed from British National Grid; council charges permanently removed from 1 April 2025` }));
parking.push(
  make({ id:'curated-parking:brechin-railway', name:'Caledonian Railway Visitor Parking', coordinates:[-2.6529037,56.7316177], featureType:'parking', description:'Free off-street visitor parking at Brechin station, with disabled parking; capacity is not published.', website:urls.railwayFaq, sourceName:'Caledonian Railway visitor information', sourceOrganisation:'Caledonian Railway Brechin Ltd', evidenceUrls:[urls.railway,urls.railwayFaq], placeType:'Parking', tags:['service-context-parking','current-context','accessible-parking'], details:'access=customers; fee=no; payment_required=no; price_display=Free; capacity=not published; can be limited on major event days' }),
  make({ id:'curated-parking:brechin-glencadam', name:'Glencadam Visitor Centre Parking', coordinates:[-2.6535092,56.7363112], featureType:'parking', description:'On-site customer parking for the Glencadam visitor centre, café, shop and booked tours; capacity is not published.', website:urls.glencadamAccess, sourceName:'Glencadam visitor centre information', sourceOrganisation:'Angus Dundee Distillers', evidenceUrls:[urls.glencadamAccess,urls.glencadam], placeType:'Parking', tags:['service-context-parking','current-context','accessible-parking'], details:'access=customers; fee=no; payment_required=no; price_display=Free for visitors; capacity=not published; pin is the mapped distillery site centroid' }),
);

const toilets = [
  make({ id:'curated-toilets:brechin-church-street', name:'Church Street Public Toilets', coordinates:[-2.661272,56.731552], featureType:'toilets', description:'Council public toilets with male, female, accessible and baby-changing facilities.', website:urls.publicToilet, sourceName:'Brechin Church Street public toilets', sourceOrganisation:'Angus Council', evidenceUrls:[urls.publicToilet], placeType:'Toilets', tags:['service-context-toilets','current-context','accessible-toilet'], details:'opening_hours:description=09:00–17:00 daily including public holidays except Christmas and New Year; accessible toilet uses RADAR key; exact council coordinate' }),
  make({ id:'curated-toilets:brechin-railway', name:'Caledonian Railway Visitor Toilets', coordinates:[-2.6529037,56.7316177], featureType:'toilets', description:'Visitor toilets at Brechin station during railway and applicable café opening.', website:urls.railwayFaq, sourceName:'Caledonian Railway facilities', sourceOrganisation:'Caledonian Railway Brechin Ltd', evidenceUrls:[urls.railwayFaq,urls.railway], placeType:'Toilets', tags:['service-context-toilets','current-context','limited-opening'], details:'opening_hours:description=railway operating dates and applicable café hours; customer facility, not a 24-hour public toilet' }),
  make({ id:'curated-toilets:brechin-glencadam', name:'Glencadam Visitor Centre Toilets', coordinates:[-2.6535092,56.7363112], featureType:'toilets', description:'Accessible customer toilets within the fully accessible Glencadam visitor centre.', website:urls.glencadamAccess, sourceName:'Glencadam visitor accessibility', sourceOrganisation:'Angus Dundee Distillers', evidenceUrls:[urls.glencadamAccess,urls.glencadam], placeType:'Toilets', tags:['service-context-toilets','current-context','accessible-toilet','limited-opening'], details:'opening_hours:description=Daily 09:00–17:00 with the visitor centre; customer facility' }),
];

const picnic = [make({ id:'curated-picnic:brechin-inch-park', name:'Inch Park Picnic Lawns', coordinates:[-2.6557771,56.7276445], featureType:'picnic_site', description:'Open riverside green space suitable for a blanket picnic beside the South Esk and the park’s woodland and wildflower walks.', website:urls.inchPark, sourceName:'Inch Park visitor information', sourceOrganisation:'Wild South Esk / Visit Angus', evidenceUrls:[urls.inchPark,urls.dogVisit,'https://www.openstreetmap.org/way/90868693'], sourceRecordIds:[undefined,undefined,'way/90868693'], placeType:'Picnic', tags:['service-context-picnic','current-context'], details:'access=public; fee=no; dedicated picnic tables not confirmed; bring a blanket and take litter home; riverside ground may be wet or affected by flooding' })];

// Restore the four statutory records whose official descriptions establish a
// defensible construction period but whose imported heat dates remained blank.
const manualDates: Record<string, any> = {
  'hes-listed-building:LB5036': { documentedDateText:'c. 1777', earliestPossibleYear:1777, latestPossibleYear:1777, evidence:urls.hesGarden, note:'The official Brechin Castle designed-landscape record says the walled garden is thought to date originally from 1777.' },
  'hes-listed-building:LB5040': { documentedDateText:'19th century', earliestPossibleYear:1800, latestPossibleYear:1899, evidence:urls.hesGarden, note:'The official Brechin Castle designed-landscape record dates the detached columns and vases to the 19th century.' },
  'hes-scheduled-monument:SM90040': { documentedDateText:'1256 / 1260s', earliestPossibleYear:1256, latestPossibleYear:1269, evidence:urls.maisonDieu, note:'The official visitor and designation evidence dates the hospital foundation to 1256/the 1260s and the surviving chapel fabric accords with that date.' },
  'hes-scheduled-monument:SM90041': { documentedDateText:'c. 1100; 15th-century spire', earliestPossibleYear:1050, latestPossibleYear:1499, evidence:urls.hesRoundTower, note:'The official designation dates the round tower to around 1100 and its stone spire probably to the 15th century.' },
};
for (const feature of pkg.features) {
  const fix = manualDates[feature.id];
  if (!fix) continue;
  feature.documentedDateText = fix.documentedDateText;
  feature.earliestPossibleYear = fix.earliestPossibleYear;
  feature.latestPossibleYear = fix.latestPossibleYear;
  feature.dateBasis = 'estimated_from_authoritative_source';
  feature.dateConfidence = 'high';
  feature.survival = feature.id.includes('SM90040') ? 'altered_recognisable' : 'substantially_intact';
  feature.tags = feature.tags.filter((tag: string) => tag !== 'map-hidden');
  feature.reviewed = true;
  feature.updatedAt = reviewedAt;
  feature.reviewNotes = `${feature.reviewNotes ?? ''} ${fix.note} Administrative designation dates are not used as construction dates.`.trim();
  if (!feature.sourceRecords.some((record: any) => record.sourceUrl === fix.evidence)) feature.sourceRecords.push({ sourceName:'Historic Environment Scotland period evidence', sourceOrganisation:'Historic Environment Scotland', sourceUrl:fix.evidence, accessedAt:reviewedAt, reliability:'official_statutory', licence:'Open Government Licence v3.0; retain Historic Environment Scotland attribution.', notes:fix.note });
}

const curated = [...attractions,...foods,...trails,...picnic,...parking,...toilets];
pkg.features = [...pkg.features.filter((feature: any) => !feature.id.startsWith('curated-')), ...curated];
const highlightInfo: Record<string,[string,string,string,string,boolean]> = {
  'curated-attraction:brechin-glencadam':['Working distillery tours and panoramic café','1.5–2.5 hours','Daily 09:00–17:00; tours 10:00–15:30; book ahead','Tours from £22.50',false],
  'curated-attraction:brechin-caledonian-railway':['Steam journeys from an 1848 station','2–4 hours','Selected published operating dates throughout the year, including summer weekends and special events','Steam Sundays currently £10 adult return',false],
  'curated-attraction:brechin-cathedral-round-tower':['Rare round tower and Pictish sculpture','45–90 minutes','Round Tower exterior and churchyard open access; cathedral interior available for advertised events and arranged visits','Free exterior access',true],
  'curated-attraction:brechin-maison-dieu':['Rare 13th-century hospital chapel remains','15–30 minutes','Open all year','Free',true],
  'curated-attraction:brechin-inch-park':['Riverside woodland and wildflower meadows','45–90 minutes','Open access; paths may be affected by weather or flooding','Free',true],
};
pkg.project.visitorHighlights = attractions.map((feature: any) => { const info=highlightInfo[feature.id]; return { rank:1, featureId:feature.id, name:feature.name, reason:feature.editorialReview.scoreRationale, tagline:info[0], visitorScore:feature.editorialReview.attractionAssessment.experienceDepth+feature.editorialReview.attractionAssessment.distinctiveness+feature.editorialReview.attractionAssessment.presentation+feature.editorialReview.attractionAssessment.journeyWorth+feature.editorialReview.attractionAssessment.accessAndReliability+feature.editorialReview.attractionAssessment.evidenceConfidence, timeToSpend:info[1], openingTimes:info[2], admission:info[3], freeAdmission:info[4], visitorWebsiteUrl:feature.visitorWebsiteUrl, editorialReview:feature.editorialReview, sourceName:feature.sourceRecords[0].sourceName, sourceUrl:feature.visitorWebsiteUrl, verifiedInBoundaryAt:reviewedDate }; }).sort((a:any,b:any)=>b.visitorScore-a.visitorScore).map((item:any,index:number)=>({...item,rank:index+1}));

pkg.project.preferredBasemap = 'voyager';
pkg.project.touristAppeal = { score:86, dogOwnerScore:78, dogAccessScoreAdjustment:-8, rating:3, label:'Strong Destination', summary:'A substantial historic Angus destination with a new daily whisky visitor centre, heritage railway, exceptional cathedral precinct, medieval hospital chapel, riverside park, official walking circuits and strong café provision.', dogAccessRating:4, dogAccessSummary:'The official path network, Inch Park, dog-friendly cathedral and dog-welcoming railway/café provide a strong visit; farm tracks, livestock, mud, roads and indoor attraction restrictions require close control.', methodVersion:'2026-08-30-strict-settlement-full-audit-v3', reviewedAt:reviewedDate, sourceUrls:Object.values(urls) };
pkg.project.townGuide = { characterTag:'Cathedral, whisky, railway and river', headline:'A strong full-day heritage destination with five independent experiences', intro:`Brechin earns 86% from inside the audited settlement boundary: ${attractions.length} assessed places to see, ${foods.length} café-led daytime stops, ${trails.length} official circuits and complete practical facilities. The closed Town House Museum and out-of-boundary Castle Centre do not inflate the score.`, bestFor:['Medieval and Pictish heritage','Working whisky and railway experiences','Coffee, cake and home baking','Riverside and countryside circuits'], perfectFor:['A full heritage day','A cathedral, café and town walk','A booked railway or distillery visit','Dog owners using the official path network'], suggestedFirstVisit:{title:'Cathedral, Maison Dieu and either whisky or railway',summary:'Begin at the cathedral and round tower, walk through the historic centre to Maison Dieu, pause at a town café, then devote the afternoon to a booked Glencadam tour or a railway operating day.'}, dontMiss:['Glencadam Distillery Visitor Centre','Caledonian Railway','Brechin Cathedral and Round Tower','Maison Dieu Chapel','Inch Park and the South Esk'], suggestedTime:'Full day; longer if combining a railway event with a distillery tour', visitorMood:'Layered and distinctive: rare medieval survivals and a strong historic townscape now connect to two destination-scale operating attractions and an unusually good path network.', sourceUrls:Object.values(urls), lastReviewedAt:reviewedDate };
pkg.project.researchNotes = 'Full strict-boundary visitor audit. Brechin independently clears 60 through five verified in-boundary visitor experiences, notably the new daily Glencadam visitor centre, Caledonian Railway and cathedral precinct. Brechin Town House Museum is closed and is not published. Brechin Castle Centre lies outside the project boundary and is excluded rather than transferred into the town score. No dedicated Brechin product was found on Treasure Trails or comparable named clue-trail providers; only verified council path-network routes are published.';

planner.projects[projectId] = { eat:foods.map((item:any)=>item.id), trails:trails.map((item:any)=>item.id), picnic:picnic.map((item:any)=>item.id), parking:parking.map((item:any)=>item.id), toilets:toilets.map((item:any)=>item.id) };
const dogEntry = (rating:number,status:string,label:string,summary:string,sourceUrl:string) => ({ rating,status,label,summary,sourceName:'Brechin dog-access audit',sourceUrl,reviewedAt:reviewedDate });
dog.projects[projectId] = { attraction:{
  [attractions[0].id]:dogEntry(2,'restricted','Check before bringing a dog','No general visitor-centre dog policy was found; assistance dogs should be confirmed with the operator.',urls.glencadamAccess),
  [attractions[1].id]:dogEntry(4,'welcoming','Dogs welcome on daytime trains','Dogs are welcome on daytime trains on a lead and on the floor.',urls.dogVisit),
  [attractions[2].id]:dogEntry(4,'welcoming','Dog-friendly cathedral','The current church listing identifies the cathedral as dog friendly; keep dogs controlled in the grounds and building.',urls.cathedralNct),
  [attractions[3].id]:dogEntry(3,'allowed','Exterior monument stop','Keep dogs on a lead beside the road and historic fabric; no dedicated facilities.',urls.maisonDieu),
  [attractions[4].id]:dogEntry(4,'welcoming','Strong riverside dog walk','Public woodland, meadow and riverside paths suit dogs under close control.',urls.dogVisit),
}, trail:Object.fromEntries(trails.map((item:any)=>[item.id,dogEntry(4,'allowed','Dogs under close control','Official path guidance requires close control, waste removal and avoiding fields with calves or young livestock.',urls.pathPdf)])), eat:{
  [foods[0].id]:dogEntry(0,'unconfirmed','Dog policy not published','No reliable current dog policy is published for the visitor-centre café; contact the operator before relying on indoor access.',urls.glencadamAccess),
  [foods[1].id]:dogEntry(0,'unconfirmed','Dog policy not published','No reliable current dog policy is published for this café; contact the operator before relying on indoor access.',urls.maisonCoffee),
  [foods[2].id]:dogEntry(4,'welcoming','Dogs welcome on leads','Dogs are welcome in the café on a lead and on the floor.',urls.dogVisit),
  [foods[3].id]:dogEntry(0,'unconfirmed','Dog policy not published','No reliable current dog policy is published for this café; contact the operator before relying on indoor access.',urls.auldBakehouse),
  [foods[4].id]:dogEntry(0,'unconfirmed','Dog policy not published','No reliable current dog policy is published for this deli; contact the operator before relying on indoor access.',urls.gourmetGrocer),
} };

const statutory = pkg.features.filter((feature:any)=>feature.tags.includes('hes-listed-building')||feature.tags.includes('hes-scheduled-monument'));
const listed = statutory.filter((feature:any)=>feature.tags.includes('hes-listed-building'));
const scheduled = statutory.filter((feature:any)=>feature.tags.includes('hes-scheduled-monument'));
const visible = statutory.filter((feature:any)=>!feature.tags.includes('map-hidden'));
const dated = visible.filter((feature:any)=>feature.documentedDateText?.trim()&&feature.earliestPossibleYear!=null&&feature.latestPossibleYear!=null&&feature.dateBasis!=='unknown');
const report = { reviewedAt, projectId, status:'verified', settlementScore:86, previousScore:74, scoreChangeReason:'The prior catalogue score omitted category curation and the daily Glencadam visitor centre opened in 2025; five independent in-boundary visitor experiences and complete practical provision now support the Strong Destination band.', dogOwnerScore:78, independentlyWorthwhile:true, publication:{see:attractions.length,eat:foods.length,trails:trails.length,picnic:picnic.length,parking:6,toilets:toilets.length}, heritage:{expectedListedBuildings:186,representedListedBuildings:listed.length,expectedScheduledMonuments:2,representedScheduledMonuments:scheduled.length,visibleDatedStatutoryPins:dated.length,visibleUndatedStatutoryPins:visible.length-dated.length,hiddenStatutoryPins:statutory.length-visible.length,manualDateRepairs:Object.keys(manualDates)}, namedTrailSearch:{TreasureTrails:'No dedicated Brechin product found after direct search and link check',CuriousAbout:'No dedicated Brechin product found',MysteryGuides:'No dedicated Brechin product found',GoQuestAdventures:'No dedicated Brechin product found',retained:trails.map((item:any)=>item.name),officialSource:urls.pathNetwork}, practicalAudit:{picnic:'Inch Park retained as blanket-picnic green space; no dedicated table is claimed',parking:'All six current council car parks are published with official bay counts, stay limits, permanently free status and official polygon centroids; railway and Glencadam customer parking remain documented on their attraction records rather than misrepresented as public parking',toilets:'Church Street public toilets plus limited-hour railway and Glencadam customer toilets',accessibility:'Glencadam is fully accessible; railway uses ramps; cathedral main areas are level according to the current church listing; rural path surfaces vary',transport:'Bus-accessible town; the Caledonian Railway is a heritage attraction, not a regular passenger rail service'}, exclusions:['Brechin Town House Museum: closed since October 2023','Brechin Castle Centre: outside the strict project boundary','Brechin Castle: private and occasional special-opening only','Edzell Castle, Glenesk Folk Museum, Caterthuns and other neighbouring attractions'], verification:{trailLinksChecked:[urls.pathNetwork,urls.pathPdf],parkingCoordinatesFromOfficialDataset:true,allCuratedCouncilParkingPinsUseOfficialPolygonCentroids:true,allStatutoryHesRecordsVisibleAndDated:dated.length===188&&visible.length===188,curatedCoordinatesCheckedAgainstBoundary:true} };

await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`);
await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`);
await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`);
await writeFile(reportPath,`${JSON.stringify(report,null,2)}\n`);
console.log(JSON.stringify(report,null,2));
