import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const reviewedAt = '2026-08-26T20:00:00.000Z';
const reviewedDate = '2026-08-26';
const projectPath = resolve('data/projects/st-monans.json');
const plannerPath = resolve('data/east-neuk-visitor-planner-curation.json');
const dogPath = resolve('data/east-neuk-dog-access-curation.json');
const project = JSON.parse(await readFile(projectPath, 'utf8')) as ProjectPackage;
for (const item of project.features) item.sourceRecords = item.sourceRecords.filter((record) => record.accessedAt !== reviewedAt);

const urls = {
  windmill: 'https://www.onfife.com/venues/st-monans-windmill/',
  windmillHeritage: 'https://portal.historicenvironment.scot/designation/SM5529',
  kirk: 'https://stmonansauldkirk.com/',
  kirkAccess: 'https://stmonansauldkirk.com/the-sanctuary-cafe/',
  kirkHeritage: 'https://portal.historicenvironment.scot/designation/LB15558',
  harbour: 'https://www.fife.gov.uk/facilities/harbours/st-monans-harbour',
  harbourFact: 'https://www.fife.gov.uk/__data/assets/file/0023/41198/SP-RTS-SS-02-Fife-Harbours-Fact-Sheet-10-St-Monans.pdf',
  harbourHeritage: 'https://portal.historicenvironment.scot/designation/LB40965',
  heritage: 'https://stmonansheritage.org/',
  camera: 'https://cameratrust.org/visit/',
  coastalPath: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/',
  coastalStage: 'https://www.walkhighlands.co.uk/fife-stirling/st-monans-anstruther.shtml',
  circular: 'https://fifewalking.com/find-a-walk/east-fife/st-monans-pitenweem-anstruther/',
  abercrombie: 'https://themackwalks.wordpress.com/2019/03/11/061-pittenweem-st-monans-abercrombie-circular-fife/',
  treasureIndex: 'https://www.treasuretrails.co.uk/collections/fife',
  eastPier: 'https://www.eastpier.co.uk/',
  eastPierDog: 'https://www.eastpier.co.uk/book',
  craigMillar: 'https://www.16westend.com/',
  giddyGannet: 'https://www.tripadvisor.co.uk/Restaurant_Review-g1481190-d23859873-Reviews-Giddy_Gannet-St_Monans_Fife_Scotland.html',
  cafeMalo: 'https://www.thecourier.co.uk/fp/lifestyle/food-drink/5255232/soups-salads-cafe-st-monans/',
  parkingInventory: 'https://arcgis-live-as.fife.gov.uk/server/rest/services/Assets_CarParking/MapServer/0',
  toilet: 'https://www.fife.gov.uk/facilities/public-toilet/st-monans-public-toilets',
  outdoorCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
};

function feature(id: string): HeritageFeature {
  const found = project.features.find((item) => item.id === id);
  if (!found) throw new Error(`Missing St Monans feature ${id}`);
  return found;
}
function source(sourceName: string, sourceOrganisation: string, sourceUrl: string, notes: string, reliability: 'official_statutory' | 'official_non_statutory' | 'local_authority' | 'secondary' = 'secondary') {
  return { sourceName, sourceOrganisation, sourceUrl, accessedAt: reviewedAt, licence: 'Source-linked editorial record; verify current visitor information before travel.', notes, reliability };
}
function currentFeature(id: string, name: string, featureType: string, coordinates: [number, number], shortDescription: string, sources: HeritageFeature['sourceRecords'], tags: string[]): HeritageFeature {
  return { id, projectId: project.project.id, name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Fife', locality: 'St Monans', featureType, significance: 'local', geometry: { type: 'Point', coordinates }, locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact', shortDescription, sourceRecords: sources, licence: 'Source-linked editorial record; map location may include OpenStreetMap-derived discovery evidence.', tags: [...new Set(['current-context', ...tags])], createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence', reviewNotes: 'Current visitor-place record researched in the 2026-08-26 St Monans full audit.' };
}
function upsert(item: HeritageFeature) { project.features = project.features.filter((existing) => existing.id !== item.id).concat(item); return item; }
function attractionReview(scoreRationale: string, evidenceUrls: string[], scores: [number, number, number, number, number, number]) {
  const [experienceDepth, distinctiveness, presentation, journeyWorth, accessAndReliability, evidenceConfidence] = scores;
  return { status: 'editorially_researched' as const, category: 'attraction' as const, methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale, evidenceUrls, attractionAssessment: { experienceDepth, distinctiveness, presentation, journeyWorth, accessAndReliability, evidenceConfidence, visitability: 'full_visitor_experience' as const } };
}
function curateFood(item: HeritageFeature, name: string, score: number, notes: string, website: string, assessment: [number, number, number, number, number, number], openingTimes: string, cuisine: string, priceBand: '£' | '££' | '£££', evidenceUrl = website) {
  Object.assign(item, { name, shortDescription: notes, visitorWebsiteUrl: website, reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...item.tags, 'service-context-food', 'visitor-context-food', 'current-context'])] });
  item.sourceRecords.push(source(`${name} visitor curation`, 'Townscape Guides source audit', evidenceUrl, `Current-place curation: visitor_place_type=${item.featureType === 'restaurant' ? 'Restaurant' : 'Cafe'}; food_score=${score}; visit_score=${score}; price_band=${priceBand}; opening_hours:description=${openingTimes}; cuisine=${cuisine}; description=${notes}`, 'secondary'));
  const [foodAndDrinkQuality, daytimeRelevance, distinctiveness, consistency, visitorFit, evidenceConfidence] = assessment;
  item.editorialReview = { status: 'editorially_researched', category: 'food', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: notes, evidenceUrls: [...new Set([website, evidenceUrl])], foodAssessment: { foodAndDrinkQuality, daytimeRelevance, distinctiveness, consistency, visitorFit, evidenceConfidence } };
  return item;
}

const windmill = feature('curated-attraction:st-monans-1');
Object.assign(windmill, { significance: 'regional', visitorWebsiteUrl: urls.windmill, reviewed: true, updatedAt: reviewedAt, documentedDateText: '1772', earliestPossibleYear: 1772, latestPossibleYear: 1772, dateBasis: 'documented_construction', dateConfidence: 'high', datePrecision: 'exact_year', shortDescription: 'Fife’s last surviving salt-working windmill, standing among interpreted remains of the saltworks constructed in 1772 on the coast path.', fullDescription: 'The open-air saltpan landscape and exterior remain fully visitable, but OnFife currently states that the windmill interior is closed until further notice.', reviewNotes: 'Official OnFife visitor information and Historic Environment Scotland construction evidence checked; the score reflects the outstanding industrial landscape but is reduced for the closed interior.', sourceRecords: [source('St Monans Windmill', 'OnFife', urls.windmill, 'Official current venue page: late-18th-century windmill, last remaining example in Fife; interior closed until further notice; exterior, saltpans and picnic setting remain visitable.', 'official_non_statutory'), source('St Monans windmill and saltpans (SM5529)', 'Historic Environment Scotland', urls.windmillHeritage, 'Official designation states that the St Philips saltworks were constructed in 1772 and operated into the 1820s.', 'official_statutory')] });
windmill.attractionGuide = { headline: 'Read Fife’s salt-making landscape', intro: 'Walk among the grassy saltpan remains and view the restored windmill exterior beside the Fife Coastal Path.', bestFor: ['Industrial archaeology', 'Coastal photography', 'A coast-path stop', 'Picnics'], parking: 'East Street is the nearest small official car park; The Common has the village’s largest published capacity.', toilets: 'Free accessible toilets are at Hope Place.', picnic: 'The open grass beside the windmill is identified by OnFife as a picnic setting.', foodNote: 'East Pier Smokehouse and Giddy Gannet are a short walk west.', trails: [], thingsToDo: [{ name: 'Follow the interpretation', summary: 'Trace the pumping and boiling process across the windmill and surviving saltpan mounds.' }, { name: 'Continue on the coast path', summary: 'Link the windmill to Pittenweem or loop back through St Monans harbour.' }] };

const kirk = feature('curated-attraction:st-monans-2');
Object.assign(kirk, { name: 'St Monans Auld Kirk', significance: 'regional', visitorWebsiteUrl: urls.kirk, reviewed: true, updatedAt: reviewedAt, documentedDateText: 'Fabric chiefly 1362; tower heightened in the 16th century', earliestPossibleYear: 1362, latestPossibleYear: 1362, dateBasis: 'documented_construction', dateConfidence: 'high', datePrecision: 'principal_fabric_year_with_later_phases', shortDescription: 'A dramatically shore-side medieval kirk whose surviving fabric is chiefly dated to 1362, community-owned since December 2025.', fullDescription: 'The exterior and graveyard make a strong coast-path landmark. Interior access is currently limited to advertised open days, weekends and events while a phased community refurbishment progresses.', reviewNotes: 'Community operator pages and the official Historic Environment Scotland designation checked; regular daily interior opening is not claimed.', sourceRecords: [source('St Monans Auld Kirk', 'St Monans Auld Kirk Enterprise', urls.kirk, 'Current operator history and community ownership from 8 December 2025.', 'official_non_statutory'), source('The Sanctuary Cafe FAQ', 'St Monans Auld Kirk Enterprise', urls.kirkAccess, 'Regular open days/weekends planned; main space has level access via sloping gravel paths; current toilet is reached by stairs.', 'official_non_statutory'), source("St Monan's Church and Churchyard (LB15558)", 'Historic Environment Scotland', urls.kirkHeritage, 'Official designation dates most surviving fabric to 1362, with the tower probably heightened in the 16th century and later restoration phases.', 'official_statutory')] });
kirk.attractionGuide = { headline: 'See the kirk that meets the sea', intro: 'Approach from the coast path for the full setting, then check the operator’s event notices for interior access.', bestFor: ['Medieval architecture', 'Sea views', 'Atmospheric photography', 'Quiet reflection'], parking: 'A coast-path parking area sits behind the kirk, but no official capacity or tariff is published; use a council car park if relying on audited details.', toilets: 'Hope Place has the audited accessible council toilets.', picnic: 'Use the windmill grass or harbour seating rather than the graveyard.', foodNote: 'Craig Millar @ 16 West End is the nearest destination restaurant.', trails: [], thingsToDo: [{ name: 'Walk the seaward side', summary: 'The relationship between kirk, graveyard and exposed shore is the defining experience.' }, { name: 'Check for an open day', summary: 'Interior access is event-led during the current transition.' }] };

const harbour = feature('curated-attraction:st-monans-3');
Object.assign(harbour, { name: 'St Monans Working Harbour and Tidal Pool', significance: 'regional', visitorWebsiteUrl: urls.harbour, reviewed: true, updatedAt: reviewedAt, documentedDateText: 'Central pier pre-1828; east pier 1865; west pier rebuilt 1902', earliestPossibleYear: 1827, latestPossibleYear: 1902, dateBasis: 'documented_date_range', dateConfidence: 'high', datePrecision: 'phased_construction', shortDescription: 'A compact working harbour of three historic piers, paired with the restored outdoor tidal pool on the east shore.', fullDescription: 'The public waterfront, fishing boats, Stevenson pier work and pool form a coherent free circuit. The pool is unsupervised and conditions are tidal; harbour users should not be obstructed.', reviewNotes: 'Official Fife Council visitor information and Historic Environment Scotland construction phases checked.', sourceRecords: [source('St Monans Harbour', 'Fife Council', urls.harbour, 'Official current harbour location and fact-sheet link.', 'local_authority'), source('St Monans Harbour fact sheet', 'Fife Council', urls.harbourFact, 'Two basins, three piers, zig-zag breakwater and operational details.', 'local_authority'), source('St Monance Harbour (LB40965)', 'Historic Environment Scotland', urls.harbourHeritage, 'Official designation records pre-1828 fabric in the central pier, the Stevenson east pier of 1865, 1879 breakwater additions and west-pier reconstruction in 1902.', 'official_statutory')] });
harbour.attractionGuide = { headline: 'Walk the working waterfront', intro: 'Follow the basins and piers, then continue east to the open-air tidal pool without obstructing boats or harbour equipment.', bestFor: ['Working-harbour character', 'Historic piers', 'Sea swimming', 'Food by the water'], parking: 'East Street has 5 free spaces; The Common has 22 car spaces, 2 accessible and 2 coach spaces.', toilets: 'Hope Place toilets are free, accessible and seasonally timed.', picnic: 'Harbour benches are mapped; the windmill grass is the more suitable picnic stop.', foodNote: 'East Pier Smokehouse occupies the pier; Giddy Gannet is close to the harbour.', trails: [], thingsToDo: [{ name: 'Compare the three piers', summary: 'The harbour incorporates pre-1828 work and later Stevenson engineering.' }, { name: 'Assess the tidal pool', summary: 'Check tide, swell and weather; there is no lifeguard.' }] };

const heritage = feature('osm-community:node-2166007822');
Object.assign(heritage, { name: 'St Monans Heritage Collection', visitorWebsiteUrl: urls.heritage, reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...heritage.tags, 'visitor-context-attraction', 'curated-visitor-attraction'])], shortDescription: 'Volunteer-run local collection of historic photographs, fishing tools and household objects at 5 West Shore.', sourceRecords: [...heritage.sourceRecords, source('St Monans Heritage Collection', 'St Monans Heritage Collection', urls.heritage, 'Current collection scope and a published festival-week opening timetable; regular year-round hours are not claimed.', 'official_non_statutory')], editorialReview: attractionReview('A worthwhile village collection, kept below publication threshold because only event-week opening is published and current admission terms are absent.', [urls.heritage], [14, 12, 10, 7, 7, 5]) });
const camera = feature('osm-community:node-14066513586');
Object.assign(camera, { name: 'Jim Matthew Camera Collection', visitorWebsiteUrl: urls.camera, reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...camera.tags, 'visitor-context-attraction', 'curated-visitor-attraction'])], shortDescription: 'A specialist one-hall museum displaying a collection of more than 3,500 cameras and photographic objects.', sourceRecords: [...camera.sourceRecords, source('Visit', 'Jim Matthew Camera Collection', urls.camera, 'Visits available by advance contact or advertised Facebook open days; address 8 West Street.', 'official_non_statutory')], editorialReview: attractionReview('Exceptional niche depth, kept below publication threshold because visits require arrangement or an open day and current admission terms are absent.', [urls.camera], [14, 16, 11, 7, 5, 5]) });

const coastalTrail = feature('curated-trail:st-monans-fife-coastal-path');
Object.assign(coastalTrail, { name: 'Fife Coastal Path: St Monans to Anstruther', shortDescription: 'A straightforward 5.75 km / 3.5-mile linear walk through St Monans, Pittenweem and Anstruther, with bus return.', visitorWebsiteUrl: urls.coastalStage, reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...coastalTrail.tags, 'service-context-trail', 'visitor-context-trail'])], sourceRecords: [source('Fife Coastal Path', 'Fife Coast & Countryside Trust', urls.coastalPath, 'Official route hub and live-notice source.', 'official_non_statutory'), source('St Monans to Anstruther', 'Walkhighlands', urls.coastalStage, 'Current-place curation: visitor_place_type=Walking route; trail_score=86; trail_type=Linear coastal walk; distance=5.75 km / 3.5 miles; time_to_spend=1.5–2 hours; accessibility=Straightforward coastal footpath with open-water and shore hazards; entrance_fee=Free; app=Walkhighlands web mapping; offline_after_download=Limited.', 'secondary')], editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A highly scenic, well-described linear route linking three destination villages with practical bus return.', evidenceUrls: [urls.coastalPath, urls.coastalStage] } });
const circular = upsert(currentFeature('curated-trail:st-monans-east-neuk-circular', 'St Monans–Pittenweem–Anstruther Circular', 'walking_route', [-2.7656, 56.2050], 'An 8-mile / 13 km coast-and-country circuit returning through Balcaskie Estate, with two shorter alternatives.', [source('St Monans, Pittenweem, Anstruther', 'Fife Walking', urls.circular, 'Current-place curation: visitor_place_type=Walking route; trail_score=79; trail_type=Coast and country circular; distance=13 km / 8 miles; time_to_spend=4–5 hours; accessibility=Mostly unsurfaced paths and tracks plus road walking; entrance_fee=Free; app=Web route guide; offline_after_download=No.', 'official_non_statutory')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(circular, { visitorWebsiteUrl: urls.circular, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A substantial circular with three villages and estate scenery, reduced for road walking and mixed unsurfaced terrain.', evidenceUrls: [urls.circular] } });
const abercrombie = upsert(currentFeature('curated-trail:st-monans-pittenweem-abercrombie', 'St Monans–Pittenweem–Abercrombie Circular', 'walking_route', [-2.7656, 56.2050], 'A downloadable 10.8 km / 6.7-mile coast-and-country circuit with GPX and PDF directions.', [source('Pittenweem–St Monans–Abercrombie Circular', 'The Mack Walks', urls.abercrombie, 'Current-place curation: visitor_place_type=Walking route; trail_score=76; trail_type=Coast and farmland circular; distance=10.8 km / 6.7 miles; time_to_spend=3–3.5 hours; accessibility=Fields, minor roads and coastal path; entrance_fee=Free; app=GPX and PDF download; offline_after_download=Yes.', 'secondary')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(abercrombie, { visitorWebsiteUrl: urls.abercrombie, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A useful downloadable local circuit, reduced for secondary-source maintenance and mixed farmland/road sections.', evidenceUrls: [urls.abercrombie] } });

const eastPier = curateFood(feature('osm-community:node-2167574535'), 'East Pier Smokehouse', 90, 'Pier-smoked seafood: local lobster, smoked fish and seasonal dishes with exceptional harbour views.', urls.eastPier, [29, 17, 15, 14, 9, 6], 'Wed–Sun 12:00–14:30 and 17:00–19:30', 'Scottish seafood', '£££');
const craigMillar = curateFood(feature('osm-community:node-12199185697'), 'Craig Millar @ 16 West End', 88, 'Refined waterfront dining: accomplished seasonal Scottish food in an intimate setting; reservation strongly advised.', urls.craigMillar, [29, 15, 15, 14, 9, 6], 'Wed–Sat lunch and dinner, Sun lunch, Mon–Tue closed', 'Modern Scottish', '£££');
const giddy = curateFood(feature('osm-community:node-6567651834'), 'Giddy Gannet', 82, 'Harbour café and baking: coffee, homemade cakes, bagels and light lunches, with limited indoor seating.', urls.giddyGannet, [25, 18, 12, 13, 9, 5], 'Tue–Sat 09:00–16:00, verify seasonal Sunday opening', 'Cafe, breakfast and lunch', '££');
const malo = curateFood(feature('osm-community:node-14066311677'), 'Café Malo', 76, 'Dog-friendly daytime café: soups, salads, baking and coffee in an accessible setting.', urls.cafeMalo, [22, 17, 11, 11, 9, 6], 'Thu–Mon 08:00–16:30, Tue–Wed closed', 'Cafe lunches and baking', '££', 'https://www.tripadvisor.co.uk/Restaurant_Review-g1481190-d33306107-Reviews-Cafe_Malo-St_Monans_Fife_Scotland.html');

const parkingData: Array<[string, string, [number, number], string, string]> = [
  ['curated-parking:st-monans-hope-place', 'Hope Place Car Park', [-2.7624958, 56.2066650], '14 car spaces; no dedicated accessible, coach or motorcycle spaces. Free tarmac surface car park; no payment required.', 'name=Hope Place Car Park; postcode=KY10 2DH; capacity=14 cars; capacity:disabled=0; capacity:coach=0; price_display=Free; payment_required=No; payment_methods=None; source_record=OBJECTID 8'],
  ['curated-parking:st-monans-the-common', 'The Common Car Park', [-2.7606027, 56.2063172], '22 car spaces, 2 accessible spaces and 2 coach/lorry spaces. Free tarmac surface car park; no payment required.', 'name=The Common Car Park; postcode=KY10 2DH; capacity=22 cars, 2 accessible, 2 coach/lorry; capacity:disabled=2; capacity:coach=2; price_display=Free; payment_required=No; payment_methods=None; source_record=OBJECTID 44'],
  ['curated-parking:st-monans-east-street', 'East Street Car Park', [-2.7633589, 56.2054736], '5 car spaces; no dedicated accessible, coach or motorcycle spaces. Free tarmac surface car park; no payment required.', 'name=East Street Car Park; postcode=KY10 2AT; capacity=5 cars; capacity:disabled=0; capacity:coach=0; price_display=Free; payment_required=No; payment_methods=None; source_record=OBJECTID 74'],
];
const parkings = parkingData.map(([id, name, coords, description, record]) => upsert(currentFeature(id, name, 'parking', coords, description, [source('Fife Council Car Park Inventory', 'Fife Council', urls.parkingInventory, `Current-place curation: visitor_place_type=Parking; ${record}; charge=Free; payment_required=No; payment_methods=None; surface=Tarmac.`, 'local_authority')], ['service-context-parking', 'visitor-context-parking'])));
for (const item of project.features.filter((candidate) => candidate.featureType === 'parking' && !parkings.some((parking) => parking.id === candidate.id))) item.tags = item.tags.filter((tag) => !['service-context-parking', 'visitor-context-parking'].includes(tag));

const toilet = feature('osm-community:node-498854487');
Object.assign(toilet, { name: 'St Monans Public Toilets', shortDescription: 'Free male and female council toilets with level access and a Radar-key accessible toilet; summer 09:00–16:30, winter 09:00–15:30.', reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...toilet.tags, 'service-context-toilets', 'visitor-context-toilets'])], sourceRecords: [...toilet.sourceRecords, source('St Monans Public Toilets', 'Fife Council', urls.toilet, 'Current-place curation: visitor_place_type=Public toilets; opening_hours=Apr–Oct 09:00–16:30, Nov–Mar 09:00–15:30; opening_hours:description=Apr–Oct 09:00–16:30, Nov–Mar 09:00–15:30; charge=Free; wheelchair=Yes; level_access=Yes; radar_key=Required; postcode=KY10 2DJ.', 'local_authority')] });
const picnic = upsert(currentFeature('curated-picnic:st-monans-windmill', 'Windmill and Saltpans Picnic Area', 'picnic_site', [-2.77365, 56.20355], 'Open grass and coastal views beside the windmill and saltpans; no dedicated table, shelter or barbecue provision is claimed.', [source('St Monans Windmill', 'OnFife', urls.windmill, 'Official venue information identifies the windmill/saltpans as a picnic stop; detailed furniture is not published.', 'official_non_statutory')], ['service-context-picnic', 'visitor-context-picnic']));

const highlights: VisitorHighlight[] = [
  { rank: 1, featureId: windmill.id, name: windmill.name, reason: 'Fife’s last salt-working windmill anchors an unusually legible coastal industrial landscape.', visitorScore: 84, tagline: 'Windmill and historic saltpans', timeToSpend: '45–90 minutes', openingTimes: 'Exterior and saltpans open in daylight; windmill interior closed until further notice.', admission: 'Free outdoor visit.', freeAdmission: true, visitorWebsiteUrl: urls.windmill, sourceName: 'OnFife', sourceUrl: urls.windmill, verifiedInBoundaryAt: reviewedDate, editorialReview: attractionReview('Highly distinctive and well interpreted, reduced for the closed interior.', [urls.windmill], [24, 19, 16, 12, 8, 5]) },
  { rank: 2, featureId: kirk.id, name: kirk.name, reason: 'A medieval kirk in one of Scotland’s most dramatic shore-side settings, now entering community stewardship.', visitorScore: 82, tagline: 'Medieval kirk beside the sea', timeToSpend: '30–60 minutes', openingTimes: 'Exterior and graveyard in daylight; interior on advertised open days, weekends and events.', admission: 'Free exterior; check event details.', freeAdmission: true, visitorWebsiteUrl: urls.kirk, sourceName: 'St Monans Auld Kirk Enterprise', sourceUrl: urls.kirk, verifiedInBoundaryAt: reviewedDate, editorialReview: attractionReview('Exceptional setting and strong fabric, reduced for irregular interior access during refurbishment.', [urls.kirk, urls.kirkAccess], [22, 19, 16, 12, 8, 5]) },
  { rank: 3, featureId: harbour.id, name: harbour.name, reason: 'A rewarding working-waterfront circuit with historic piers, seafood and a restored tidal pool.', visitorScore: 80, tagline: 'Working harbour and tidal pool', timeToSpend: '45–90 minutes', openingTimes: 'Open-air public waterfront; daylight recommended. Pool is tidal and unsupervised.', admission: 'Free.', freeAdmission: true, visitorWebsiteUrl: urls.harbour, sourceName: 'Fife Council', sourceUrl: urls.harbour, verifiedInBoundaryAt: reviewedDate, editorialReview: attractionReview('Authentic and coherent harbour experience, reduced for operational hazards and an unsupervised tidal pool.', [urls.harbour, urls.harbourFact], [22, 18, 15, 11, 9, 5]) },
];

project.project.visitorHighlights = highlights;
project.project.touristAppeal = { score: 84, dogOwnerScore: 79, dogAccessScoreAdjustment: -5, rating: 2, label: 'Strong Destination', summary: 'St Monans combines a working harbour, shore-side medieval kirk, distinctive windmill and saltpans, tidal pool, two small museums, destination food and several worthwhile coast-and-country routes in a compact village.', dogAccessRating: 1, dogAccessSummary: 'The defining outdoor circuit is very good with a dog, but the kirk and both museums do not publish general pet admission, East Pier restricts dogs to its gazebo and outdoor seating, and longer walks require control around wildlife and farmland. Those restrictions reduce the score by five points.', methodVersion: '2026-08-26-full-settlement-visitor-audit-v1', reviewedAt: reviewedDate, sourceUrls: Object.values(urls) };
project.project.townGuide = { characterTag: 'Kirk, saltpans and working harbour', headline: 'Three exceptional coastal landmarks in one walkable village', intro: 'St Monans’ shore ties together the Auld Kirk, working harbour and tidal pool, and Fife’s last surviving salt-working windmill. Small museums, destination seafood and the coast path give the village more depth than its scale suggests.', bestFor: ['Coastal heritage', 'Industrial archaeology', 'Working harbour', 'Seafood and walking'], perfectFor: ['A rich half-day East Neuk visit', 'Visitors who prefer compact places explored on foot'], suggestedFirstVisit: { title: 'Walk the full historic shore', summary: 'Begin at the Auld Kirk, cross the working harbour and tidal pool, then follow the coast to the windmill and saltpans before returning through the village.' }, dontMiss: ['St Monans Auld Kirk', 'St Monans Working Harbour and Tidal Pool', 'St Monans Windmill and Saltpans', 'East Pier Smokehouse', 'Fife Coastal Path'], suggestedTime: '4–6 hours; a full day with a long circular walk', visitorMood: 'A small place with an unusually complete coastal story: medieval faith, fishing, engineering, salt-making and contemporary food all sit within one continuous shore walk.', sourceUrls: Object.values(urls), lastReviewedAt: reviewedDate };
project.project.visualIdentity = { theme: 'st-monans-kirk-harbour-and-saltpans', badgeImage: '/town-guides/st-monans-auld-kirk-shore-watercolour-guide-v2.png', badgeAlt: 'Watercolour view of St Monans Auld Kirk above the rocky Firth of Forth shoreline', heroImage: '/town-guides/st-monans-auld-kirk-shore-watercolour-guide-v2.png', heroAlt: 'Watercolour view of St Monans Auld Kirk above the rocky Firth of Forth shoreline', heroObjectPosition: '52% 55%', motifs: ['Shore-side Auld Kirk', 'Working harbour', 'Saltpan windmill', 'Fishing houses'], primaryColour: '#174E58', accentColour: '#B8732B', backgroundColour: '#EAF3F1' };

const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as { projects: Record<string, Record<string, string[]>> };
planner.projects[project.project.id] = { eat: [eastPier.id, craigMillar.id, giddy.id, malo.id], trails: [coastalTrail.id, circular.id, abercrombie.id], parking: parkings.map((item) => item.id), toilets: [toilet.id], picnic: [picnic.id] };
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`, 'utf8');

const dog = JSON.parse(await readFile(dogPath, 'utf8')) as { reviewedAt: string; projects: Record<string, { attraction?: Record<string, unknown>; eat?: Record<string, unknown> }> };
dog.reviewedAt = reviewedDate;
dog.projects[project.project.id] = { attraction: {
  [windmill.id]: { rating: 3, status: 'welcoming', label: 'Outdoor dog-suitable landmark', summary: 'Dogs can accompany the open-air saltpans and windmill exterior under responsible-access rules. Keep close around shore wildlife and other walkers.', sourceName: 'OnFife and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
  [kirk.id]: { rating: 0, status: 'unconfirmed', label: 'Interior dog policy not published', summary: 'The exterior setting can be enjoyed on the public route, but general pet admission on open days is not published. Confirm before relying on indoor access.', sourceName: 'St Monans Auld Kirk Enterprise', sourceUrl: urls.kirkAccess, reviewedAt: reviewedDate },
  [harbour.id]: { rating: 2, status: 'restricted', label: 'Outdoor waterfront with hazards', summary: 'Dogs can accompany the public waterfront, but keep them close beside fishing gear, roads, open water, food areas and swimmers; do not let dogs enter the tidal pool when in use.', sourceName: 'Fife Council and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
  [camera.id]: { rating: 0, status: 'unconfirmed', label: 'Museum dog policy not published', summary: 'General pet admission is not published. Ask when arranging a visit.', sourceName: 'Jim Matthew Camera Collection', sourceUrl: urls.camera, reviewedAt: reviewedDate },
  [heritage.id]: { rating: 0, status: 'unconfirmed', label: 'Collection dog policy not published', summary: 'General pet admission is not published. Confirm for the relevant open day.', sourceName: 'St Monans Heritage Collection', sourceUrl: urls.heritage, reviewedAt: reviewedDate },
  [coastalTrail.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable coast path', summary: 'Dogs can use the route under responsible-access rules, with close control around wildlife, shore hazards, golf and busy waterfronts.', sourceName: 'Fife Coastal Path and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
  [circular.id]: { rating: 2, status: 'restricted', label: 'Coast-and-country circuit', summary: 'The route includes farmland, estate tracks and roads. Use a lead around livestock, wildlife and traffic.', sourceName: 'Fife Walking and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
  [abercrombie.id]: { rating: 2, status: 'restricted', label: 'Farmland circular', summary: 'Suitable for controlled dogs, with leads needed around livestock, wildlife, roads and cultivated ground.', sourceName: 'The Mack Walks and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
}, eat: {
  [eastPier.id]: { rating: 2, status: 'restricted', label: 'Gazebo and outdoor seating only', summary: 'The operator explicitly welcomes dogs in the covered gazebo and outdoor seating, but not in the indoor restaurant. Book the correct area and consider the weather.', sourceName: 'East Pier Smokehouse', sourceUrl: urls.eastPierDog, reviewedAt: reviewedDate },
  [craigMillar.id]: { rating: 0, status: 'unconfirmed', label: 'Restaurant dog policy not published', summary: 'A general pet policy is not published on the current operator site. Confirm directly before booking.', sourceName: 'Craig Millar @ 16 West End', sourceUrl: urls.craigMillar, reviewedAt: reviewedDate },
  [giddy.id]: { rating: 3, status: 'welcoming', label: 'Dog-friendly café', summary: 'Current managed listing and recent visitor evidence confirm dogs are welcomed inside; seating is limited.', sourceName: 'Giddy Gannet managed listing', sourceUrl: urls.giddyGannet, reviewedAt: reviewedDate },
  [malo.id]: { rating: 3, status: 'welcoming', label: 'Dog-friendly café', summary: 'Current local food coverage identifies Café Malo as dog friendly and accessible.', sourceName: 'The Courier', sourceUrl: urls.cafeMalo, reviewedAt: reviewedDate },
} };
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`, 'utf8');

project.validation = validateFeatures(project.project, project.features);
const errors = project.validation.filter((item) => item.severity === 'error');
if (errors.length) throw new Error(`St Monans audit introduced ${errors.length} validation errors: ${errors.map((item) => item.message).join('; ')}`);
await writeFile(projectPath, `${JSON.stringify(project, null, 2)}\n`, 'utf8');
await writeFile(resolve('data/review/st-monans-full-visitor-audit-2026-08-26.json'), `${JSON.stringify({ reviewedAt, townScore: 84, dogOwnerScore: 79, publicationRule: 'visitor score > 60', attractions: highlights.map(({ name, visitorScore }) => ({ name, score: visitorScore, published: true })), trails: [{ name: coastalTrail.name, score: 86 }, { name: circular.name, score: 79 }, { name: abercrombie.name, score: 76 }], treasureTrails: { dedicatedStMonansProductFound: false, source: urls.treasureIndex, decision: 'No nearby product was mislabelled as a St Monans trail.' }, facilities: { eat: [{ name: eastPier.name, score: 90 }, { name: craigMillar.name, score: 88 }, { name: giddy.name, score: 82 }, { name: malo.name, score: 76 }], parking: [{ name: parkings[0].name, capacity: '14 cars', price: 'Free', payment: 'None' }, { name: parkings[1].name, capacity: '22 cars, 2 accessible, 2 coach/lorry', price: 'Free', payment: 'None' }, { name: parkings[2].name, capacity: '5 cars', price: 'Free', payment: 'None' }], toilets: [{ name: toilet.name, hours: 'Apr–Oct 09:00–16:30; Nov–Mar 09:00–15:30', charge: 'Free', accessible: 'Level access and Radar-key toilet' }], picnic: [{ name: picnic.name, furniture: 'No dedicated table claimed' }] }, dogAudit: { townAdjustment: -5, attractionPolicies: 'Windmill 3 paws; harbour and all trails 2; kirk and both museums unconfirmed', foodPolicies: 'Giddy Gannet and Café Malo 3; East Pier 2 outdoor-only; Craig Millar unconfirmed' }, exclusions: ['No dedicated current Treasure Trails product found for St Monans', 'Unverified informal, church and residential-edge parking omitted from the practical planner', 'Tidal pool is included with the harbour rather than double-counted as a separate attraction', 'Below-threshold heritage pins remain on the heat map but are not promoted as visitor highlights'] }, null, 2)}\n`, 'utf8');
console.log('St Monans audit complete: 3 published attractions, 2 sub-threshold museums, 4 Eats, 3 trails, 3 car parks, 1 toilet block and 1 picnic area.');
