import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const reviewedAt = '2026-08-26T23:00:00.000Z';
const reviewedDate = '2026-08-26';
const projectPath = resolve('data/projects/elie.json');
const plannerPath = resolve('data/east-neuk-visitor-planner-curation.json');
const dogPath = resolve('data/east-neuk-dog-access-curation.json');
const project = JSON.parse(await readFile(projectPath, 'utf8')) as ProjectPackage;
for (const item of project.features) item.sourceRecords = item.sourceRecords.filter((record) => record.accessedAt !== reviewedAt);

const urls = {
  destination: 'https://www.welcometofife.com/destination/elie--earlsferry',
  harbourBeach: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-beaches/elie-harbour/',
  harbourParking: 'https://elieharbourtrust.org.uk/visiting-the-harbour/',
  watersports: 'https://www.eliewatersports.co.uk/about/',
  rubyBay: 'https://www.fife.gov.uk/facilities/beaches-and-harbours/ruby-bay%2C-elie',
  ladyTower: 'https://portal.historicenvironment.scot/designation/LB8999',
  coastalPath: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/',
  coastalStage: 'https://www.walkhighlands.co.uk/fife-stirling/elie-st-monans.shtml',
  rubyCircular: 'https://wildpackcollective.com/walk/elie-coastal-path-and-ruby-bay-circular/',
  treasure: 'https://www.treasuretrails.co.uk/products/things-to-do-elie-earlsferry-fife',
  shipInn: 'https://shipinn.scot/wine-dine-2/',
  elieDeli: 'https://www.eliedeli.co.uk/about',
  elieDeliContact: 'https://www.eliedeli.co.uk/contact',
  coffeeHatch: 'https://www.welcometofife.com/view-catering/elie-coffee-hatch',
  coffeeHours: 'https://eesc.org.uk/clubhouse',
  barnett: 'https://elieescapes.com/explore-elie-high-street/',
  rubyParking: 'https://fifecoastandcountrysidetrust.co.uk/plan-your-trip/fcct-managed-parking/',
  vennelCapacity: 'https://www.fife.gov.uk/__data/assets/pdf_file/0023/626162/Fife-Council-EV-Strategy-10-February-2025.pdf',
  stentonToilet: 'https://www.fife.gov.uk/facilities/public-toilet/elie-public-toilets',
  toiletOverview: 'https://www.fife191.com/view/elie--earlsferry',
  rubyToilet: 'https://fifecoastandcountrysidetrust.co.uk/new-toilet-block-opens-at-elie-ruby-bay/',
  outdoorCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
  beachDogPolicy: 'https://dogsonthebeach.co.uk/beaches/elie-harbour-beach/',
};

function feature(id: string): HeritageFeature {
  const found = project.features.find((item) => item.id === id);
  if (!found) throw new Error(`Missing Elie feature ${id}`);
  return found;
}
function source(sourceName: string, sourceOrganisation: string, sourceUrl: string, notes: string, reliability: 'official_statutory' | 'official_non_statutory' | 'local_authority' | 'secondary' = 'secondary') {
  return { sourceName, sourceOrganisation, sourceUrl, accessedAt: reviewedAt, licence: 'Source-linked editorial record; verify current visitor information before travel.', notes, reliability };
}
function currentFeature(id: string, name: string, featureType: string, coordinates: [number, number], shortDescription: string, sources: HeritageFeature['sourceRecords'], tags: string[]): HeritageFeature {
  return { id, projectId: project.project.id, name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Fife', locality: 'Elie', featureType, significance: 'local', geometry: { type: 'Point', coordinates }, locationType: 'exact', locationConfidence: 'medium', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact', shortDescription, sourceRecords: sources, licence: 'Source-linked editorial record; map location may include OpenStreetMap-derived discovery evidence.', tags: [...new Set(['current-context', ...tags])], createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence', reviewNotes: 'Current visitor-place record researched in the 2026-08-26 Elie full audit.' };
}
function upsert(item: HeritageFeature) { project.features = project.features.filter((existing) => existing.id !== item.id).concat(item); return item; }
function attractionReview(scoreRationale: string, evidenceUrls: string[], scores: [number, number, number, number, number, number]) {
  const [experienceDepth, distinctiveness, presentation, journeyWorth, accessAndReliability, evidenceConfidence] = scores;
  return { status: 'editorially_researched' as const, category: 'attraction' as const, methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale, evidenceUrls, attractionAssessment: { experienceDepth, distinctiveness, presentation, journeyWorth, accessAndReliability, evidenceConfidence, visitability: 'full_visitor_experience' as const } };
}
function curateFood(item: HeritageFeature, name: string, score: number, notes: string, website: string, assessment: [number, number, number, number, number, number], openingTimes: string, cuisine: string, priceBand: '£' | '££' | '£££', evidenceUrl = website) {
  Object.assign(item, { name, shortDescription: notes, visitorWebsiteUrl: website, reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...item.tags, 'service-context-food', 'visitor-context-food', 'current-context'])] });
  item.sourceRecords.push(source(`${name} visitor curation`, name, evidenceUrl, `Current-place curation: visitor_place_type=${item.featureType === 'restaurant' ? 'Restaurant' : 'Cafe or takeaway'}; food_score=${score}; visit_score=${score}; price_band=${priceBand}; opening_hours:description=${openingTimes}; cuisine=${cuisine}; description=${notes}`, 'official_non_statutory'));
  const [foodAndDrinkQuality, daytimeRelevance, distinctiveness, consistency, visitorFit, evidenceConfidence] = assessment;
  item.editorialReview = { status: 'editorially_researched', category: 'food', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: notes, evidenceUrls: [...new Set([website, evidenceUrl])], foodAssessment: { foodAndDrinkQuality, daytimeRelevance, distinctiveness, consistency, visitorFit, evidenceConfidence } };
  return item;
}

const harbour = feature('curated-attraction:elie-1');
Object.assign(harbour, { name: 'Elie Harbour and Beach', significance: 'regional', visitorWebsiteUrl: urls.harbourBeach, reviewed: true, updatedAt: reviewedAt, shortDescription: 'A broad sandy bathing beach beside Elie’s small working harbour, watersports base and seasonal lifeguard station.', fullDescription: 'The beach and harbour are the town’s primary visitor experience. Fife Coast & Countryside Trust confirms toilets, parking, disabled access and seasonal RNLI lifeguards; the harbour remains operational and water activity is at visitors’ own risk.', reviewNotes: 'Current beach, harbour, watersports and parking information checked; the experience is not inflated by counting watersports as a separate attraction.', sourceRecords: [source('Elie Harbour beach', 'Fife Coast & Countryside Trust', urls.harbourBeach, 'Official beach page: almost one mile of linked sand at low tide, watersports, toilets, parking, disabled access and seasonal RNLI lifeguards.', 'official_non_statutory'), source('Visiting the harbour', 'Elie Harbour Trust', urls.harbourParking, 'Official current harbour-use and car-parking tariffs; working-waterfront and water-safety cautions.', 'official_non_statutory'), source('About Elie Watersports', 'Elie Watersports', urls.watersports, 'Current operator page checked; waterskiing and inflatable rides are presently unavailable, so those activities were not promised.', 'official_non_statutory')] });
harbour.attractionGuide = { headline: 'Make the beach and harbour your base', intro: 'Walk the sand, watch the working harbour and book only the water activities the operator currently confirms.', bestFor: ['Families', 'Sand and sea', 'Harbour atmosphere', 'Watersports'], parking: 'Harbour Trust parking is £3.50 up to two hours or £6 for the day; capacity is not published. Ruby Bay is the audited lower-cost alternative.', toilets: 'Seasonal accessible toilets are by the harbour; Stenton Row and Ruby Bay provide year-round options.', picnic: 'The beach is suitable for an informal picnic; take litter away and leave harbour operations clear.', foodNote: 'The Ship Inn overlooks the beach; Elie Coffee Hatch is near the sailing club.', trails: [], thingsToDo: [{ name: 'Walk the linked sands', summary: 'At low tide the broad shore links towards Earlsferry; check tide and beach-control signs.' }, { name: 'Watch rather than obstruct', summary: 'The harbour is operational: keep slipways, equipment and boat movements clear.' }] };

const ness = feature('curated-attraction:elie-2');
Object.assign(ness, { name: 'Elie Ness, Lady’s Tower and Ruby Bay', significance: 'regional', visitorWebsiteUrl: urls.rubyBay, reviewed: true, updatedAt: reviewedAt, documentedDateText: 'Lady’s Tower: late 18th century (commonly dated 1770)', earliestPossibleYear: 1767, latestPossibleYear: 1799, dateBasis: 'estimated_from_authoritative_source', dateConfidence: 'high', datePrecision: 'late_century_with_secondary_exact_year', shortDescription: 'A rewarding headland circuit linking Ruby Bay, the late-18th-century Lady’s Tower and Elie Ness Lighthouse.', fullDescription: 'The free open-air circuit provides the town’s strongest coastal views. Lady’s Tower is a roofless former bathing-room shell; Ruby Bay is sheltered and sandy, but nesting skylarks and exposed shore edges require care.', reviewNotes: 'Fife Council, Welcome to Fife and the official HES designation checked. The Chain Walk lies in Earlsferry and is deliberately excluded from this Elie attraction.', sourceRecords: [source('Ruby Bay, Elie', 'Fife Council', urls.rubyBay, 'Official beach page: sheltered sandy bay, coastal path, rockpools and nesting skylarks from March to July.', 'local_authority'), source("Elie Ness Lady's Tower (LB8999)", 'Historic Environment Scotland', urls.ladyTower, 'Official designation: late-18th-century roofless Gothic summer house used as Lady Anstruther’s bathing dressing room.', 'official_statutory'), source('Elie and Earlsferry', 'Welcome to Fife', urls.destination, 'Official destination page identifies Lady’s Tower as built in 1770 and the lighthouse as the second headland landmark.', 'official_non_statutory')] });
ness.attractionGuide = { headline: 'Circle Elie’s landmark headland', intro: 'Start at Ruby Bay and follow the public coast route past Lady’s Tower and the lighthouse for wide Forth views.', bestFor: ['Coastal landmarks', 'Photography', 'Rockpools', 'Short walks'], parking: 'Ruby Bay Upper Car Park: first two hours free, then £2; cash or card at the machine. Seven overnight motorhome bays use RingGo at £15.', toilets: 'Ruby Bay has six cubicles, one overnight toilet and a 24-hour Radar-key accessible toilet.', picnic: 'Ruby Bay works well for a beach picnic; avoid the skylark nesting area and take litter away.', foodNote: 'Return to the High Street for Elie Deli and G.H. Barnett, or the harbour for The Ship Inn.', trails: [], thingsToDo: [{ name: 'Find Lady’s Tower', summary: 'Read the small roofless Gothic shell as an 18th-century bathing retreat rather than a defensive tower.' }, { name: 'Scan the shore carefully', summary: 'Explore rockpools without disturbing nesting birds or leaving the signed route.' }] };

// The coastal path is a trail, not a third attraction. Keep the old pin on the heat map without promoting it.
const formerPathAttraction = feature('curated-attraction:elie-3');
formerPathAttraction.tags = formerPathAttraction.tags.filter((tag) => tag !== 'curated-visitor-attraction').concat('visitor-context-trail-reference');
formerPathAttraction.editorialReview = { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'Not separately scored: the same experience is curated once in Trails to avoid double-counting.', evidenceUrls: [urls.coastalPath] };

const coastal = feature('curated-trail:elie-fife-coastal-path');
Object.assign(coastal, { name: 'Fife Coastal Path: Elie to St Monans', shortDescription: 'A scenic 6.5 km / 4-mile linear stage around Elie Ness, Ardross and Newark Castle to St Monans, with bus return.', visitorWebsiteUrl: urls.coastalStage, reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...coastal.tags, 'service-context-trail', 'visitor-context-trail'])], sourceRecords: [source('Fife Coastal Path', 'Fife Coast & Countryside Trust', urls.coastalPath, 'Official route hub and live-notice source.', 'official_non_statutory'), source('Elie to St Monans', 'Walkhighlands', urls.coastalStage, 'Current-place curation: visitor_place_type=Walking route; trail_score=86; trail_type=Linear coastal walk; distance=6.5 km / 4 miles; time_to_spend=2–2.5 hours; accessibility=Mostly clear coastal path with rough, exposed and tidal sections; entrance_fee=Free; app=Walkhighlands web mapping; offline_after_download=Limited.', 'secondary')], editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A high-quality coast stage with landmarks, beaches and a practical bus return.', evidenceUrls: [urls.coastalPath, urls.coastalStage] } });
const treasure = upsert(currentFeature('curated-trail:elie-ruby-bay-treasure-trail', 'Elie & Earlsferry – Ruby Bay & Back Treasure Trail', 'walking_route', [-2.8202, 56.1903], 'A 2.5-mile / 2.5-hour self-guided murder-mystery trail from Admiralty Lane, crossing both Elie and Earlsferry.', [source('Elie & Earlsferry – Ruby Bay & Back', 'Treasure Trails', urls.treasure, 'Current-place curation: visitor_place_type=Self-guided clue trail; trail_score=84; trail_type=Murder Mystery; distance=2.5 miles; time_to_spend=2.5 hours; accessibility=Accessible and pushchair accessible; entrance_fee=£9.99 per trail booklet/download; app=Treasure Trails; dog_friendly=Yes.', 'official_non_statutory')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(treasure, { visitorWebsiteUrl: urls.treasure, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A polished, dog-friendly clue trail with clear duration and accessibility; it is labelled jointly because the route intentionally crosses into Earlsferry.', evidenceUrls: [urls.treasure] } });
const circular = upsert(currentFeature('curated-trail:elie-ness-ruby-bay-circular', 'Elie Ness and Ruby Bay Circular', 'walking_route', [-2.8128, 56.1870], 'A compact 5 km / 3.1-mile circuit around the harbour, Elie Ness and Ruby Bay, allowing about 90 minutes.', [source('Elie Coastal Path and Ruby Bay Circular', 'Wild Pack Collective', urls.rubyCircular, 'Current-place curation: visitor_place_type=Walking route; trail_score=78; trail_type=Local coastal circular; distance=5 km / 3.1 miles; time_to_spend=90 minutes; accessibility=Coastal paths, beach and uneven ground; entrance_fee=Free; dog_access=Control needed around wildlife, livestock and seasonal beach rules.', 'secondary')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(circular, { visitorWebsiteUrl: urls.rubyCircular, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A useful short circuit joining Elie’s main landmarks, reduced for secondary-source maintenance and mixed surfaces.', evidenceUrls: [urls.rubyCircular] } });

const ship = curateFood(upsert(currentFeature('curated-food:elie-ship-inn', 'The Ship Inn', 'restaurant', [-2.8185, 56.1885], 'Beachfront Scottish pub and restaurant with seafood, a downstairs dog-friendly area and a dedicated dog menu.', [source('Wine & Dine', 'The Ship Inn', urls.shipInn, 'Official menu, current restaurant hours and access information.', 'official_non_statutory')], ['service-context-food', 'visitor-context-food'])), 'The Ship Inn', 92, 'Destination beachfront pub: strong Scottish cooking, seafood, beach views and unusually explicit provision for dogs.', urls.shipInn, [30, 18, 15, 14, 9, 6], 'Mon–Thu 12:00–14:45 and 17:00–20:30, Fri–Sat dinner to 21:30, Sun 12:00–20:00', 'Scottish pub and seafood', '£££');
const deli = curateFood(upsert(currentFeature('curated-food:elie-deli', 'Elie Deli', 'deli', [-2.8198274, 56.1905469], 'Village deli for pastries, filled rolls, baguettes, salad boxes, coffee and picnic supplies.', [source('About and contact', 'Elie Deli', urls.elieDeli, 'Official product range and current opening hours.', 'official_non_statutory')], ['service-context-food', 'visitor-context-food'])), 'Elie Deli', 84, 'Picnic-ready village deli: pastries, filled rolls, salads, coffee and dependable seven-day opening.', urls.elieDeli, [26, 18, 14, 12, 9, 5], 'Mon–Sat 08:00–17:00, Sun 08:00–16:00, later in July and August', 'Deli, bakery and takeaway', '££', urls.elieDeliContact);
const hatch = curateFood(feature('osm-community:node-11175497178'), 'Elie Coffee Hatch', 80, 'Dog-walker coffee stop: a seasonal sailing-club hatch for coffee, cakes and light bites.', urls.coffeeHatch, [22, 18, 14, 12, 9, 5], 'Usually 10:00–17:00, weekends Apr–Jun and Sep, daily Jul–Aug', 'Coffee, cakes and light bites', '£', urls.coffeeHours);
const barnett = curateFood(feature('osm-community:node-6918524368'), 'G.H. Barnett', 74, 'Traditional village bakery: sausage rolls, oatcakes, cakes and simple takeaway food.', urls.barnett, [23, 16, 12, 9, 9, 5], 'Daytime bakery, current hours should be checked locally', 'Bakery and takeaway', '£', urls.barnett);

const rubyParking = upsert(currentFeature('curated-parking:elie-ruby-bay-upper', 'Ruby Bay Upper Car Park', 'parking', [-2.8131587, 56.1875038], 'ANPR-managed beach parking: first two daytime hours free, then £2; cash/card machine. Seven RingGo-only overnight motorhome bays cost £15.', [source('FCCT managed parking', 'Fife Coast & Countryside Trust', urls.rubyParking, 'Current-place curation: visitor_place_type=Parking; capacity=General daytime capacity not published; overnight_capacity=7 motorhomes; charge=First 2 hours free, then £2 daytime; overnight £15; payment_methods=Cash or card machine daytime, RingGo overnight; opening_hours:description=06:00–23:00; disabled_parking=Free after registration; ANPR=Yes.', 'official_non_statutory')], ['service-context-parking', 'visitor-context-parking']));
const harbourParking = upsert(currentFeature('curated-parking:elie-harbour', 'Elie Harbour Car Park', 'parking', [-2.8180742, 56.1864459], 'Harbour Trust parking: £3.50 up to two hours or £6 day ticket; capacity and accessible-bay count are not published.', [source('Visiting the harbour', 'Elie Harbour Trust', urls.harbourParking, 'Current-place curation: visitor_place_type=Parking; capacity=Not published; charge=Up to 2 hours £3.50, day ticket £6; payment_methods=Harbour office or BACS as published by operator; overnight=No overnight camping.', 'official_non_statutory')], ['service-context-parking', 'visitor-context-parking']));
const vennel = upsert(currentFeature('curated-parking:elie-vennel', 'The Vennel Car Park', 'parking', [-2.8205247, 56.1910511], 'Small council village-centre car park with 12 spaces; the official strategy inventory lists one accessible and one EV bay.', [source('Fife Council EV Strategy', 'Fife Council', urls.vennelCapacity, 'Current-place curation: visitor_place_type=Parking; capacity=12 car spaces; capacity:disabled=1; capacity:charging=1; fee=no; payment_required=no.', 'local_authority')], ['service-context-parking', 'visitor-context-parking']));

const stenton = feature('osm-community:node-10697233791');
Object.assign(stenton, { name: 'Stenton Row Public Toilets', visitorWebsiteUrl: urls.stentonToilet, reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...stenton.tags, 'service-context-toilets', 'visitor-context-toilets'])], sourceRecords: [...stenton.sourceRecords, source('Elie Public Toilets', 'Fife Council', urls.stentonToilet, 'Current-place curation: visitor_place_type=Public toilets; opening_hours=Daily 09:00–17:00; charge=Free; wheelchair=Yes; level_access=Yes; radar_key=Required; closures=25–26 Dec and 1–2 Jan.', 'local_authority')] });
const harbourToilet = feature('osm-community:node-11146506414');
Object.assign(harbourToilet, { name: 'Elie Harbour Public Toilets', reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...harbourToilet.tags, 'service-context-toilets', 'visitor-context-toilets'])], sourceRecords: [...harbourToilet.sourceRecords, source('Elie facilities', 'Fife 191', urls.toiletOverview, 'Current-place curation: visitor_place_type=Public toilets; opening_hours=April–October, days and times vary; charge=Free; wheelchair=Yes; baby_changing=Yes.', 'official_non_statutory')] });
const rubyToilet = feature('osm-community:way-635420678');
Object.assign(rubyToilet, { name: 'Ruby Bay Public Toilets', reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...rubyToilet.tags, 'service-context-toilets', 'visitor-context-toilets'])], sourceRecords: [...rubyToilet.sourceRecords, source('Ruby Bay toilet block', 'Fife Coast & Countryside Trust', urls.rubyToilet, 'Current-place curation: visitor_place_type=Public toilets; cubicles=6; overnight_toilet=One unisex cubicle open overnight all year; wheelchair=24-hour Radar-key accessible toilet; chemical_disposal=10:00–12:00, honesty-box payment.', 'official_non_statutory')] });
const picnic = upsert(currentFeature('curated-picnic:elie-ruby-bay', 'Ruby Bay Beach Picnic Stop', 'picnic_site', [-2.8127, 56.1872], 'Informal beach picnic setting with nearby toilets and parking; no dedicated shelter, barbecue or table is promised.', [source('Ruby Bay, Elie', 'Fife Council', urls.rubyBay, 'Official beach and facility context; visitor curation does not claim furniture absent from the source.', 'local_authority')], ['service-context-picnic', 'visitor-context-picnic']));

const highlights: VisitorHighlight[] = [
  { rank: 1, featureId: harbour.id, name: harbour.name, reason: 'Elie’s broad sandy beach, compact working harbour and water activity make a complete coastal visit.', visitorScore: 88, tagline: 'Beach, harbour and watersports', timeToSpend: '1–3 hours', openingTimes: 'Open-air beach and harbour; daylight recommended. Seasonal lifeguard cover only.', admission: 'Free beach and harbour visit; parking and booked activities cost extra.', freeAdmission: true, visitorWebsiteUrl: urls.harbourBeach, sourceName: 'Fife Coast & Countryside Trust', sourceUrl: urls.harbourBeach, verifiedInBoundaryAt: reviewedDate, editorialReview: attractionReview('A deep, highly legible seaside experience with strong facilities; reduced slightly for seasonal services, working-harbour hazards and variable watersports availability.', [urls.harbourBeach, urls.harbourParking, urls.watersports], [27, 18, 17, 13, 8, 5]) },
  { rank: 2, featureId: ness.id, name: ness.name, reason: 'Ruby Bay, Lady’s Tower and the lighthouse form an unusually rewarding short headland circuit.', visitorScore: 85, tagline: 'Landmark headland and sheltered bay', timeToSpend: '60–120 minutes', openingTimes: 'Open-air coast and landmarks; daylight and suitable weather recommended.', admission: 'Free.', freeAdmission: true, visitorWebsiteUrl: urls.rubyBay, sourceName: 'Fife Council and Historic Environment Scotland', sourceUrl: urls.rubyBay, verifiedInBoundaryAt: reviewedDate, editorialReview: attractionReview('Excellent scenery and distinctive landmarks in a coherent free walk; reduced for exposed shore terrain, no interiors and wildlife sensitivity.', [urls.rubyBay, urls.ladyTower], [25, 19, 17, 13, 7, 4]) },
];
project.project.visitorHighlights = highlights;
project.project.touristAppeal = { score: 86, dogOwnerScore: 81, dogAccessScoreAdjustment: -5, rating: 2, label: 'Strong Destination', summary: 'Elie is a complete East Neuk coastal destination: broad beach and working harbour, a landmark headland circuit, strong destination food, three worthwhile trails and unusually useful visitor facilities.', dogAccessRating: 2, dogAccessSummary: 'Elie’s outdoor landmarks and several food stops work well with a dog, but seasonal controls apply on the main harbour beach, shore wildlife needs close control, the harbour has open-water and operational hazards, and not every indoor stop admits pets. Those limits reduce—not increase—the visitor score by five points.', methodVersion: '2026-08-26-full-settlement-visitor-audit-v1', reviewedAt: reviewedDate, sourceUrls: Object.values(urls) };
project.project.townGuide = { characterTag: 'Beach, harbour and landmark headland', headline: 'A polished seaside village with genuine depth beyond the beach', intro: 'Elie combines a broad sandy shore and small working harbour with Ruby Bay, Lady’s Tower and the lighthouse on Elie Ness. Destination food, practical facilities and routes ranging from a short headland circuit to a clue trail make it one of the East Neuk’s strongest all-round stops.', bestFor: ['Beach days', 'Coastal landmarks', 'Food by the sea', 'Short and long walks'], perfectFor: ['A full East Neuk day by the water', 'Families and walkers who value facilities'], suggestedFirstVisit: { title: 'Link harbour, Ness and Ruby Bay', summary: 'Begin at the harbour beach, circle Elie Ness past Lady’s Tower and the lighthouse, then return through Ruby Bay and the High Street.' }, dontMiss: ['Elie Harbour and Beach', 'Lady’s Tower', 'Elie Ness Lighthouse', 'Ruby Bay', 'The Ship Inn'], suggestedTime: '5–8 hours; longer with a beach day or coastal-path stage', visitorMood: 'A confident, well-equipped coastal village where sand, boats, landmarks, food and walking reinforce one another rather than competing for attention.', sourceUrls: Object.values(urls), lastReviewedAt: reviewedDate };
project.project.visualIdentity = { theme: 'elie-harbour-beach-and-ness', badgeImage: '/town-guides/elie-harbour-and-ness-watercolour-guide-v1.png', badgeAlt: 'Watercolour view across Elie harbour and beach towards the Elie Ness lighthouse and Lady’s Tower', heroImage: '/town-guides/elie-harbour-and-ness-watercolour-guide-v1.png', heroAlt: 'Watercolour view across Elie harbour and beach towards the Elie Ness lighthouse and Lady’s Tower', heroObjectPosition: '50% 54%', motifs: ['Sandy harbour beach', 'Whitewashed fishing houses', 'Elie Ness lighthouse', 'Lady’s Tower'], primaryColour: '#17566A', accentColour: '#C3842A', backgroundColour: '#EAF4F2' };

const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as { projects: Record<string, Record<string, string[]>> };
planner.projects[project.project.id] = { eat: [ship.id, deli.id, hatch.id, barnett.id], trails: [coastal.id, treasure.id, circular.id], parking: [rubyParking.id, harbourParking.id, vennel.id], toilets: [stenton.id, harbourToilet.id, rubyToilet.id], picnic: [picnic.id] };
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`, 'utf8');

const dog = JSON.parse(await readFile(dogPath, 'utf8')) as { reviewedAt: string; projects: Record<string, { attraction?: Record<string, unknown>; eat?: Record<string, unknown> }> };
dog.reviewedAt = reviewedDate;
dog.projects[project.project.id] = { attraction: {
  [harbour.id]: { rating: 2, status: 'restricted', label: 'Good with seasonal controls', summary: 'Dogs can share the outdoor beach and harbour visit, but the main beach has a signed lead-only zone from 1 May to 30 September, 10:00–18:00. Keep close beside boats, food areas, open water and other beach users.', sourceName: 'Published Fife beach-control summary and Scottish Outdoor Access Code', sourceUrl: urls.beachDogPolicy, reviewedAt: reviewedDate },
  [ness.id]: { rating: 2, status: 'restricted', label: 'Outdoor circuit with wildlife care', summary: 'The open-air headland and Ruby Bay suit controlled dogs, but leads are appropriate around nesting skylarks, livestock, cliff edges, rockpools and busy paths.', sourceName: 'Fife Council and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
  [coastal.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable coast stage', summary: 'Dogs can use the coast path under responsible-access rules; use a lead around livestock, nesting birds, shore hazards, golf and busy waterfronts.', sourceName: 'Fife Coastal Path and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
  [treasure.id]: { rating: 3, status: 'welcoming', label: 'Explicitly dog-friendly clue trail', summary: 'Treasure Trails marks this product dog friendly. Normal seasonal beach, road and wildlife controls still apply along the joint Elie–Earlsferry route.', sourceName: 'Treasure Trails', sourceUrl: urls.treasure, reviewedAt: reviewedDate },
  [circular.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable local circuit', summary: 'A practical dog walk with close control needed around seasonal beach zones, wildlife, livestock and coastal hazards.', sourceName: 'Wild Pack Collective and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
}, eat: {
  [ship.id]: { rating: 3, status: 'welcoming', label: 'Dogs welcomed downstairs', summary: 'The operator welcomes dogs in the downstairs restaurant, bar and beach bar and publishes a dog menu. Upstairs has no lift and is not the dog-friendly area.', sourceName: 'The Ship Inn', sourceUrl: urls.shipInn, reviewedAt: reviewedDate },
  [deli.id]: { rating: 1, status: 'restricted', label: 'Takeaway is the reliable option', summary: 'The operator does not publish general indoor pet admission. Use the deli as a takeaway stop and confirm before relying on indoor access.', sourceName: 'Elie Deli', sourceUrl: urls.elieDeli, reviewedAt: reviewedDate },
  [hatch.id]: { rating: 3, status: 'welcoming', label: 'Designed for dog walkers', summary: 'Welcome to Fife explicitly describes the outdoor hatch as designed to be enjoyed by dog walkers.', sourceName: 'Welcome to Fife', sourceUrl: urls.coffeeHatch, reviewedAt: reviewedDate },
  [barnett.id]: { rating: 1, status: 'unconfirmed', label: 'Takeaway bakery; indoor policy unconfirmed', summary: 'The bakery is useful for takeaway food, but a current general pet-admission policy is not published.', sourceName: 'Elie High Street guide', sourceUrl: urls.barnett, reviewedAt: reviewedDate },
} };
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`, 'utf8');

project.validation = validateFeatures(project.project, project.features);
const errors = project.validation.filter((item) => item.severity === 'error');
if (errors.length) throw new Error(`Elie audit introduced ${errors.length} validation errors: ${errors.map((item) => item.message).join('; ')}`);
await writeFile(projectPath, `${JSON.stringify(project, null, 2)}\n`, 'utf8');
await writeFile(resolve('data/review/elie-full-visitor-audit-2026-08-26.json'), `${JSON.stringify({ reviewedAt, townScore: 86, dogOwnerScore: 81, publicationRule: 'visitor score > 60', attractions: highlights.map(({ name, visitorScore }) => ({ name, score: visitorScore, published: true })), trails: [{ name: coastal.name, score: 86 }, { name: treasure.name, score: 84 }, { name: circular.name, score: 78 }], facilities: { eat: [{ name: ship.name, score: 92 }, { name: deli.name, score: 84 }, { name: hatch.name, score: 80 }, { name: barnett.name, score: 74 }], parking: [{ name: rubyParking.name, capacity: 'General daytime capacity not published; 7 overnight motorhome bays', price: 'First 2 hours free, then £2 daytime; £15 overnight', payment: 'Cash/card daytime; RingGo overnight' }, { name: harbourParking.name, capacity: 'Not published', price: '£3.50 up to 2 hours; £6 day', payment: 'Harbour office or BACS as published' }, { name: vennel.name, capacity: '12 spaces; 1 accessible; 1 EV', price: 'Free / no tariff published', payment: 'None' }], toilets: [{ name: stenton.name, hours: 'Daily 09:00–17:00', accessible: 'Level access and Radar key' }, { name: harbourToilet.name, hours: 'April–October; times vary', accessible: 'Yes; baby changing' }, { name: rubyToilet.name, hours: 'One cubicle overnight all year; accessible toilet 24/7 by Radar key', accessible: 'Yes' }] }, dogAudit: { townAdjustment: -5, attractionPolicies: 'Harbour/beach, Ness and standard walks 2 paws; Treasure Trail 3', foodPolicies: 'Ship Inn and Coffee Hatch 3; Deli and Barnett 1' }, exclusions: ['Earlsferry Pavilion and Chain Walk excluded from Elie', 'Coast path removed as a duplicate attraction and retained in Trails', 'Unverified parking capacity omitted rather than estimated', 'Below-threshold heritage pins remain on the heat map but are not promoted as attractions'] }, null, 2)}\n`, 'utf8');
console.log('Elie audit complete: 2 published attractions, 4 Eats, 3 trails, 3 car parks, 3 toilet blocks and 1 picnic stop.');
