import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const id = 'alford-aberdeenshire-scotland';
const day = '2026-09-02';
const at = '2026-09-02T12:35:00Z';
const projectPath = resolve('data/projects/alford-aberdeenshire.json');
const plannerPath = resolve('data/aberdeen-north-visitor-planner-curation.json');
const dogPath = resolve('data/aberdeen-north-dog-access-curation.json');
const reportPath = resolve('data/review/alford-aberdeenshire-full-visitor-audit-2026-09-02.json');
type F = HeritageFeature & Record<string, any>;
type P = ProjectPackage & { project: ProjectPackage['project'] & Record<string, any>; features: F[] };
const urls = {
  gtm: 'https://www.gtm.org.uk/', gtmVisit: 'https://www.gtm.org.uk/visit/', heritage: 'https://www.alfordheritagemuseum.com/',
  park: 'https://www.aberdeenshire.gov.uk/leisure-sport-and-culture/country-parks/alford-haughton-country-park/',
  ski: 'https://www.livelifeaberdeenshire.org.uk/sport-and-physical-activity/venues/alford-ski-centre/', railway: 'https://www.doorsopendays.org.uk/regions/aberdeenshire/alford-valley-community-railway',
  walks: 'https://www.aberdeenshire.gov.uk/media/27590/alfordwalkingandcyclingleaflet.pdf', maps: 'https://publications.aberdeenshire.gov.uk/cycling-and-walking-maps',
  haughtonCafe: 'https://haughtonholidaypark.com/coffee-shop/', chloe: 'https://www.aberdeenshirerestaurantweek.com/offers/chloes-kitchen-creations',
  parking: 'https://www.aberdeenshire.gov.uk/roads-and-travel/car-parking/car-parks', toilets: 'https://www.aberdeenshire.gov.uk/local/public-toilets',
  sm6: 'https://portal.historicenvironment.scot/designation/SM6', treasure: 'https://www.treasuretrails.co.uk/collections/aberdeenshire', curious: 'https://curiousabout.co.uk/', mystery: 'https://www.mysteryguides.co.uk/pages/scotland', goQuest: 'https://goquestadventures.com/', dogCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
};
const pkg = JSON.parse(await readFile(projectPath, 'utf8')) as P;
const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as any;
const dog = JSON.parse(await readFile(dogPath, 'utf8')) as any;
const evidence = (name: string, organisation: string, url: string, notes: string, reliability: any = 'official_non_statutory') => ({ sourceName: name, sourceOrganisation: organisation, sourceUrl: url, accessedAt: at, reliability, licence: 'Source-linked editorial evidence; verify time-sensitive details before travel.', notes });
const make = (spec: { id: string; name: string; featureType: any; coordinates: [number, number]; score: number; category: 'attraction' | 'food' | 'trail'; description: string; website: string; reason: string; details: string; tags: string[]; evidence: any[] }): F => ({
  id: spec.id, projectId: id, name: spec.name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Aberdeenshire', locality: 'Alford', featureType: spec.featureType, significance: spec.score >= 80 ? 'national' : spec.score >= 68 ? 'regional' : 'local', geometry: { type: 'Point', coordinates: spec.coordinates }, locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact', shortDescription: spec.description, visitorWebsiteUrl: spec.website, details: spec.details,
  editorialReview: { status: 'editorially_researched', category: spec.category, methodVersion: '2026-09-02-researched-visitor-value-v1', reviewedAt: day, scoreRationale: spec.reason, evidenceUrls: spec.evidence.map((entry: any) => entry.sourceUrl), visitability: 'full_visitor_experience', attractionAssessment: { experienceDepth: Math.min(24, Math.round(spec.score * .24)), distinctiveness: Math.min(20, Math.round(spec.score * .2)), presentation: Math.min(18, Math.round(spec.score * .18)), journeyWorth: Math.min(14, Math.round(spec.score * .14)), accessAndReliability: Math.min(14, Math.round(spec.score * .14)), evidenceConfidence: Math.min(10, Math.round(spec.score * .1)) } },
  sourceRecords: spec.evidence, tags: spec.tags, createdAt: at, updatedAt: at, reviewed: true, evidenceScope: 'parish_evidence',
});
const attractionSpecs = [
  ['gtm', 'Grampian Transport Museum', 'museum', [-2.7015099, 57.233377], 89, 'Award-winning independent transport museum with a broad vehicle collection, exhibitions and events.', urls.gtm, 'Alford’s strongest destination anchor: a deep, maintained collection with dependable seasonal daily opening and facilities.', 'opening_hours:description=Seasonally daily 10:00-17:00, normally closed November-March; admission=paid; cafe=Motorbites; parking=adjacent council car park'],
  ['heritage-museum', 'Alford Heritage Museum', 'museum', [-2.7000246, 57.2307749], 78, 'Rural-life museum in the listed 1904–05 former cattle mart, retaining its auction ring and presenting local trades, domestic life and machinery.', urls.heritage, 'A substantial and distinctive second museum with current 2026 hours, prices, accessibility and visitor facilities.', 'opening_hours:description=27 March-25 October 2026 Thursday-Sunday 12:00-16:00, last entry 15:30; admission=paid; accessible_toilet=yes; dogs=on_lead'],
  ['haughton-country-park', 'Haughton Country Park', 'park', [-2.6957634, 57.2416003], 80, 'Forty-hectare riverside country park with birch woodland, paths, wildflower meadow, play areas and trim track.', urls.park, 'A complete year-round outdoor attraction with paths, play, formal picnic provision, large car park and toilets.', 'opening_hours=daylight; admission=free; parking=approximately 300 spaces including disabled bays; toilets=2 blocks; picnic_tables=yes; play_areas=2'],
  ['ski-centre', 'Alford Ski Centre', 'other', [-2.7101016, 57.231786], 75, 'Live Life Aberdeenshire dry-slope centre offering public skiing, snowboarding, tubing, lessons and equipment hire.', urls.ski, 'A genuine bookable visitor activity with current seven-day opening information and a distinctive offer for a rural town.', 'booking=check public-session timetable; activities=skiing,snowboarding,tubing; equipment_hire=yes; opening_hours:description=current weekly hours published by operator'],
  ['community-railway', 'Alford Valley Community Railway', 'other', [-2.6948456, 57.2304229], 68, 'Community-run narrow-gauge railway between Alford and Haughton Country Park, with verified 2026 open days and train rides.', urls.railway, 'Worth publishing with a clear event-only warning: current 2026 operation is verified for Doors Open Days, but no dependable general timetable was found.', 'opening_hours:description=Verified for Doors Open Days 19-20 September 2026 10:00-16:00; warning=do not assume regular running; wheelchair_accessible_carriages=yes'],
] as const;
const attractions = attractionSpecs.map(([slug, name, featureType, coordinates, score, description, website, reason, details]) => make({ id: `curated-attraction:alford-${slug}`, name, featureType, coordinates: coordinates as [number, number], score, category: 'attraction', description, website, reason, details, tags: ['curated-visitor', 'home-standalone-place', 'current-context'], evidence: [evidence(name, name === 'Haughton Country Park' ? 'Aberdeenshire Council' : name === 'Alford Ski Centre' ? 'Live Life Aberdeenshire' : name === 'Alford Valley Community Railway' ? 'Doors Open Days / AVCCBS' : name, website, 'Current first-party or official visitor information.', name === 'Haughton Country Park' || name === 'Alford Ski Centre' ? 'local_authority' : 'official_non_statutory')] }));
const eatSpecs = [
  ['haughton', "Farquharson's at Haughton House", [-2.6923931, 57.2409684], 82, urls.haughtonCafe, 'Speciality coffee shop for all-day breakfast, brunch, lunch, homemade cakes, scones, traybakes and afternoon tea.', 'An excellent coffee, cake and light-lunch fit beside the country park, with current daily hours and dietary choices published by the operator.', 'opening_hours:description=Daily 09:30-16:00, last orders 15:30; cuisine=coffee_cake_light_lunch; vegetarian=yes; vegan=yes; gluten_free=yes'],
  ['chloe', "Chloe's Kitchen Creations", [-2.7040026, 57.2333612], 74, urls.chloe, 'Independent central café verified for coffee and cake, light lunches and daytime service.', 'A useful in-town café; current Aberdeenshire Restaurant Week evidence verifies the coffee-and-cake and light-lunch offer, though ordinary hours require an operator check.', 'opening_hours:description=Check current venue listing; cuisine=coffee_cake_light_lunch; price_band=££'],
  ['motorbites', 'Motorbites Tearoom', [-2.7015099, 57.233377], 70, urls.gtmVisit, 'Museum tearoom providing refreshments during the Grampian Transport Museum season.', 'Convenient during a museum visit, but seasonal and restricted to weekends outside local school holidays.', 'opening_hours:description=Museum season; reduced hours and weekends outside Aberdeenshire school holidays; warning=check before travel'],
] as const;
const eats = eatSpecs.map(([slug, name, coordinates, score, website, description, reason, details]) => make({ id: `curated-food:alford-${slug}`, name, featureType: 'cafe', coordinates: coordinates as [number, number], score, category: 'food', description, website, reason, details, tags: ['service-context-food', 'visitor-context-food', 'current-context'], evidence: [evidence(name, name.includes('Haughton') ? 'Haughton Holiday Park' : name.includes('Motorbites') ? 'Grampian Transport Museum' : 'Aberdeenshire Restaurant Week', website, 'Current menu or visitor-service evidence.')] }));
const trailSpecs = [
  ['haughton', 'Haughton Country Park Circuit', [-2.6957634, 57.2416003], 4.4, 'Green'],
  ['murray', 'Murray Park Circuit', [-2.7116022, 57.2393847], 4.2, 'Purple'],
  ['community-orchard', 'Alford Community Orchard Circuit', [-2.7101016, 57.231786], 3.8, 'Orange'],
] as const;
const trails = trailSpecs.map(([slug, name, coordinates, km, colour]) => make({ id: `curated-trail:alford-${slug}`, name, featureType: 'trail', coordinates: coordinates as [number, number], score: name.includes('Haughton') ? 72 : 64, category: 'trail', description: `${km} km council-mapped ${colour.toLowerCase()} route around Alford.`, website: urls.walks, reason: 'An exact council route with mapped alignment, colour coding, distance and step-by-step directions.', details: `distance=${km} km; waymarking=${colour}; format=official downloadable map; route_link_checked=${day}; warning=check surfaces and temporary closures`, tags: ['curated-trails', 'service-context-trail', 'current-context'], evidence: [evidence('Walking and Cycling around Alford', 'Aberdeenshire Council', urls.walks, 'Official route map, distance and directions.', 'local_authority')] }));
const services = [
  make({ id: 'curated-picnic:alford-haughton', name: 'Haughton Country Park Picnic Area', featureType: 'other', coordinates: [-2.6957634, 57.2416003], score: 72, category: 'attraction', description: 'Formal picnic-table area with concrete barbecue slabs in Haughton Country Park.', website: urls.park, reason: 'Council-verified formal picnic provision; no table count is published.', details: 'tourism=picnic_site; table_count=Not published; bbq=own barbecue permitted on provided slabs; admission=free', tags: ['service-context-picnic', 'current-context'], evidence: [evidence('Haughton Country Park facilities', 'Aberdeenshire Council', urls.park, 'Formal picnic tables and barbecue slabs.', 'local_authority')] }),
  make({ id: 'curated-parking:alford-montgarrie-road', name: 'Montgarrie Road Car Park', featureType: 'other', coordinates: [-2.7019, 57.2332], score: 72, category: 'attraction', description: 'Council car park convenient for the transport museum and town centre.', website: urls.parking, reason: 'Current council listing provides capacity, disabled, lorry/bus and cycle spaces and voluntary-payment status.', details: 'amenity=parking; capacity=119; capacity:disabled=6; hgv_spaces=3; bicycle_parking=10 covered; fee=voluntary contribution; payment_methods=RingGo,PayByPhone; location_code=985541', tags: ['service-context-parking', 'current-context'], evidence: [evidence('Aberdeenshire car parks', 'Aberdeenshire Council', urls.parking, 'Current parking capacity and payment information.', 'local_authority')] }),
  make({ id: 'curated-parking:alford-haughton', name: 'Haughton Country Park Car Park', featureType: 'other', coordinates: [-2.6957634, 57.2416003], score: 72, category: 'attraction', description: 'Large country-park car park with designated disabled spaces.', website: urls.park, reason: 'Council verifies approximately 300 spaces and designated disabled bays; compulsory charges are suspended in favour of donations.', details: 'amenity=parking; capacity=approximately 300; capacity:disabled=present, count not published; fee=voluntary donation; maxstay=Not published; overnight=Not published', tags: ['service-context-parking', 'current-context'], evidence: [evidence('Haughton Country Park facilities', 'Aberdeenshire Council', urls.park, 'Current capacity and voluntary-donation policy.', 'local_authority')] }),
  make({ id: 'curated-toilet:alford-village-car-park', name: 'Alford Village Car Park Public Toilet', featureType: 'other', coordinates: [-2.7022, 57.2333], score: 70, category: 'attraction', description: 'Council public toilet at the village car park, Watchmaker’s Lane.', website: urls.toilets, reason: 'Current council location, seasonal hours and disabled-access flag.', details: 'amenity=toilets; disabled=yes; opening_hours:description=April-September 08:00-20:00; October-March 08:00-18:00; holiday_closures=25-26 December and 1-2 January', tags: ['service-context-toilet', 'current-context'], evidence: [evidence('Aberdeenshire public toilets', 'Aberdeenshire Council', urls.toilets, 'Current Alford toilet listing.', 'local_authority')] }),
  make({ id: 'curated-toilet:alford-haughton-southfield', name: 'Haughton Country Park Southfield Toilet Block', featureType: 'other', coordinates: [-2.6962, 57.2411], score: 68, category: 'attraction', description: 'Council toilet block in Haughton Country Park.', website: urls.toilets, reason: 'Current council location and seasonal opening hours.', details: 'amenity=toilets; opening_hours:description=April-September 08:00-20:00; October-March 08:00-18:00; disabled=park page confirms disabled facilities in both blocks', tags: ['service-context-toilet', 'current-context'], evidence: [evidence('Aberdeenshire public toilets', 'Aberdeenshire Council', urls.toilets, 'Current Haughton Southfield toilet listing.', 'local_authority'), evidence('Haughton Country Park facilities', 'Aberdeenshire Council', urls.park, 'Disabled facilities and year-round block context.', 'local_authority')] }),
  make({ id: 'curated-toilet:alford-haughton-visitor-centre', name: 'Haughton Country Park Visitor Centre Toilet', featureType: 'other', coordinates: [-2.6927, 57.2410], score: 68, category: 'attraction', description: 'Council public toilet at the Haughton Country Park visitor centre.', website: urls.toilets, reason: 'Current council location and seasonal hours.', details: 'amenity=toilets; opening_hours:description=April-September 08:00-20:00; October-March 08:00-18:00; disabled=yes', tags: ['service-context-toilet', 'current-context'], evidence: [evidence('Aberdeenshire public toilets', 'Aberdeenshire Council', urls.toilets, 'Current Haughton visitor-centre toilet listing.', 'local_authority')] }),
];
const ringCairn = pkg.features.find((feature) => feature.id === 'hes-scheduled-monument:SM6');
if (!ringCairn) throw new Error('Missing HES scheduled monument SM6');
ringCairn.documentedDateText = 'Early Bronze Age, probably c.2000–800 BC';
ringCairn.earliestPossibleYear = -2000;
ringCairn.latestPossibleYear = -800;
ringCairn.dateBasis = 'estimated_from_authoritative_source';
ringCairn.dateConfidence = 'medium';
ringCairn.datePrecision = 'broad_range';
ringCairn.reviewNotes = 'Corrected from a false 19th-century assignment: the official description dates the ring cairn itself to the Early Bronze Age; the 19th-century wording refers only to later tree planting.';
ringCairn.tags = [...new Set([...ringCairn.tags.filter((tag: string) => tag !== 'map-hidden'), 'date-reviewed', 'hes-date-reviewed'])];
ringCairn.updatedAt = at;
const curated = [...attractions, ...eats, ...trails, ...services];
const curatedIds = new Set(curated.map((feature) => feature.id));
pkg.features = [...pkg.features.filter((feature) => !curatedIds.has(feature.id)), ...curated];
const highlights: VisitorHighlight[] = attractions.slice(0, 4).map((feature, index) => ({ rank: index + 1, featureId: feature.id, name: feature.name, reason: feature.editorialReview.scoreRationale, tagline: index === 0 ? 'Award-winning transport stories' : index === 1 ? 'Rural history in the old mart' : index === 2 ? 'Forty hectares of riverside park' : 'Dry-slope skiing and tubing', visitorScore: Number((feature.details.match(/visit_score=(\d+)/) ?? [])[1] ?? attractionSpecs[index][4]), timeToSpend: index === 0 ? '2–3 hours' : index === 1 ? '1–2 hours' : index === 2 ? '1–3 hours' : 'Book a session', openingTimes: index === 0 ? 'Seasonally daily 10:00–17:00; normally closed November–March' : index === 1 ? '27 March–25 October 2026, Thursday–Sunday 12:00–16:00' : index === 2 ? 'Daylight daily' : 'Current weekly timetable online', admission: index === 2 ? 'Free' : 'Check current prices', freeAdmission: index === 2, visitorWebsiteUrl: feature.visitorWebsiteUrl, editorialReview: feature.editorialReview, sourceName: feature.sourceRecords[0].sourceName, sourceUrl: feature.sourceRecords[0].sourceUrl, verifiedInBoundaryAt: day }));
pkg.project.preferredBasemap = 'voyager';
pkg.project.boundarySource = 'Strict Alford settlement plus immediately adjoining Haughton Country Park, whose entrance and visitor facilities form part of the town visit. Balfluig Castle and dispersed outlying sites are excluded from the destination score.';
pkg.project.boundaryConfidence = 'high';
pkg.project.touristAppeal = { score: 84, dogOwnerScore: 81, dogAccessScoreAdjustment: -3, rating: 2, label: 'Strong Destination', summary: 'A rounded rural destination with two museums, a major country park, active ski centre, event railway, three mapped walks and unusually complete visitor facilities.', dogAccessRating: 3, dogAccessSummary: 'Haughton Park, outdoor routes and the dog-welcoming heritage museum give good options, but each attraction and café has its own policy and livestock, river and wildlife controls apply.', methodVersion: '2026-09-02-strict-settlement-full-audit-v4', reviewedAt: day, sourceUrls: Object.values(urls) };
pkg.project.visitorHighlights = highlights;
pkg.project.townGuide = { characterTag: 'Howe of Alford museum and park town', headline: 'Transport, rural heritage and a complete outdoor day', intro: 'Alford scores 84% after replacing its 58 placeholder with a full audit. The award-winning transport museum, excellent rural museum, Haughton Country Park, ski centre and current event railway are supported by three exact council walks, three daytime refreshment choices and strong practical facilities.', bestFor: ['Transport and rural history', 'Families', 'Country-park walks', 'Active sessions'], perfectFor: ['A full day combining museum and park'], suggestedFirstVisit: { title: 'Pair the transport museum with Haughton Park', summary: 'Allow time for one indoor collection, a park circuit and coffee or cake.' }, dontMiss: highlights.slice(0, 3).map((entry) => entry.name), suggestedTime: 'Half day to full day', visitorMood: 'A surprisingly complete inland visitor town.', sourceUrls: Object.values(urls), lastReviewedAt: day };
pkg.project.researchNotes = 'Full current-web, boundary and HES audit. Every See, Eat, trail, picnic, parking and toilet record is source-backed. Four named commercial clue-trail providers were checked and none has an exact Alford product. The three council routes are exact and live. Eight listed buildings and scheduled monument SM6 are present; SM6 is corrected to the Early Bronze Age and no date is appended to any map label.';
planner.projects[id] = { eat: eats.map((feature) => feature.id), trails: trails.map((feature) => feature.id), picnic: ['curated-picnic:alford-haughton'], parking: ['curated-parking:alford-montgarrie-road', 'curated-parking:alford-haughton'], toilets: ['curated-toilet:alford-village-car-park', 'curated-toilet:alford-haughton-southfield', 'curated-toilet:alford-haughton-visitor-centre'] };
dog.reviewedAt = day;
dog.projects[id] = { attraction: Object.fromEntries(attractions.map((feature) => [feature.id, { rating: feature.id.includes('heritage-museum') ? 4 : feature.id.includes('park') ? 3 : 1, status: feature.id.includes('heritage-museum') ? 'welcome' : 'restricted', label: feature.id.includes('heritage-museum') ? 'Dogs welcome on leads' : 'Check venue rules', summary: feature.id.includes('heritage-museum') ? 'The museum explicitly welcomes well-behaved dogs on a leash.' : 'Confirm indoor access; use close control outdoors.', sourceName: feature.sourceRecords[0].sourceName, sourceUrl: feature.sourceRecords[0].sourceUrl, reviewedAt: day }])) };
pkg.validation = validateFeatures(pkg.project, pkg.features);
const errors = pkg.validation.filter((entry: any) => entry.severity === 'error');
if (errors.length) throw new Error(errors.map((entry: any) => entry.message).join('; '));
const statutory = pkg.features.filter((feature) => feature.tags.some((tag: string) => tag === 'hes-listed-building' || tag === 'hes-scheduled-monument'));
const visible = statutory.filter((feature) => !feature.tags.includes('map-hidden'));
const undated = visible.filter((feature) => !feature.documentedDateText || feature.earliestPossibleYear == null || feature.latestPossibleYear == null || feature.dateBasis === 'unknown');
if (statutory.length !== 9 || undated.length) throw new Error(`Alford HES gate failed: statutory=${statutory.length}; undated=${undated.map((feature) => feature.id).join(', ')}`);
const report = { reviewedAt: at, projectId: id, place: 'Alford, Aberdeenshire', townScore: 84, mapPublished: true,
  categories: { see: { audited: true, published: 5 }, eat: { audited: true, published: 3 }, trails: { audited: true, published: 3, providerChecks: { TreasureTrails: 'Aberdeenshire catalogue searched; no Alford product.', CuriousAbout: 'No exact Alford route.', MysteryGuides: 'No exact Alford guide.', GoQuestAdventures: 'No exact Alford quest.', AberdeenshireCouncil: 'Three exact routes verified: 4.4 km, 4.2 km and 3.8 km.' } }, picnic: { audited: true, published: 1 }, parking: { audited: true, published: 2 }, toilets: { audited: true, published: 3 } },
  hes: { assigned: statutory.length, visibleDated: visible.length - undated.length, hiddenUndated: statutory.length - visible.length, visibleUndated: undated.length, missing: 0, correction: 'SM6 corrected from 19th-century tree planting to Early Bronze Age monument date.' }, boundaryRule: 'Outlying Balfluig Castle and dispersed rural records do not support the town score; Haughton Country Park is included because it is directly joined to Alford’s visitor circuit.', research: { currentWebResearch: true, strictBoundaryChecked: true, sourceChecks: Object.values(urls).map((url) => ({ url, checkedAt: day, outcome: 'checked' })) }, scoreReanalysis: { required: true, completed: true, previousScore: 58, resultScore: 84, rationale: 'The former score explicitly said the town was held pending audit. Current sources prove a deep, rounded and practical destination offer across every category.' }, certification: { publicationCountsReconciled: true, liveBrowserVerifiedAt: null } };
await writeFile(projectPath, `${JSON.stringify(pkg, null, 2)}\n`);
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`);
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`);
await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`);
console.log(`Alford audit complete: score 84; 5 See, 3 Eat, 3 Trails, 1 Picnic, 2 Parking, 3 Toilets; ${visible.length - undated.length}/${visible.length} visible HES pins dated.`);
