import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const projectId='panbride-scotland'; const reviewedDate='2026-08-30'; const reviewedAt='2026-08-30T23:59:59.000Z';
const projectPath=resolve('data/projects/panbride.json'); const plannerPath=resolve('data/cairn-o-mount-visitor-planner-curation.json'); const dogPath=resolve('data/cairn-o-mount-dog-access-curation.json'); const correctionPath=resolve('data/review/strict-settlement-score-correction-2026-08-30.json'); const reportPath=resolve('data/review/panbride-full-visitor-audit-2026-08-30.json');
type F=HeritageFeature&Record<string,any>; type P=ProjectPackage&{project:ProjectPackage['project']&Record<string,any>;features:F[]};
const urls={place:'https://www.openstreetmap.org/node/343291184',church:'https://portal.historicenvironment.scot/designation/LB18434',aisle:'https://portal.historicenvironment.scot/designation/LB18435',school:'https://portal.historicenvironment.scot/designation/LB18437',bridge:'https://portal.historicenvironment.scot/designation/LB19879',house:'https://portal.historicenvironment.scot/designation/LB18422',stables:'https://portal.historicenvironment.scot/designation/LB18423',her:'https://her.aberdeenshire.gov.uk/Monument/MAB36019',heritageTrail:'https://visitangus.com/get-inspired/heritage-trails/carnoustie-heritage-trail/',path:'https://www.angus.gov.uk/sites/default/files/2017-08/Carnoustie%20path%20network.pdf',paths:'https://www.angus.gov.uk/directories/document_category/path_networks',treasure:'https://www.treasuretrails.co.uk/collections/dundee-and-angus',curious:'https://www.curiousabout.co.uk/',mystery:'https://www.mysteryguides.co.uk/',goQuest:'https://goquestadventures.com/',dogCode:'https://www.outdooraccess-scotland.scot/dog-owners'};
const pkg=JSON.parse(await readFile(projectPath,'utf8')) as P; const planner=JSON.parse(await readFile(plannerPath,'utf8')) as any; const dog=JSON.parse(await readFile(dogPath,'utf8')) as any; const correction=JSON.parse(await readFile(correctionPath,'utf8')) as any;
const assessment=(score:number)=>({experienceDepth:Math.round(score*.3),distinctiveness:Math.round(score*.2),presentation:Math.round(score*.2),journeyWorth:Math.round(score*.15),accessAndReliability:Math.round(score*.1),evidenceConfidence:score-Math.round(score*.3)-Math.round(score*.2)-Math.round(score*.2)-Math.round(score*.15)-Math.round(score*.1),visitability:'full_visitor_experience' as const});
const source=(name:string,org:string,url:string,notes:string,reliability:any='official_non_statutory')=>({sourceName:name,sourceOrganisation:org,sourceUrl:url,accessedAt:reviewedAt,reliability,licence:'Source-linked editorial evidence; verify time-sensitive details before travel.',notes});
const make=(s:Record<string,any>):F=>({id:s.id,projectId,name:s.name,alternativeNames:[],countryCode:'GB-SCT',region:'Angus',locality:'Panbride',featureType:s.featureType,significance:'local',geometry:{type:'Point',coordinates:s.coordinates},locationType:'exact',locationConfidence:'high',dateBasis:'unknown',dateConfidence:'unknown',survival:'substantially_intact',shortDescription:s.description,visitorWebsiteUrl:s.website,editorialReview:{status:'editorially_researched',category:s.category,methodVersion:'2026-08-30-researched-visitor-value-v1',reviewedAt:reviewedDate,scoreRationale:s.reason,evidenceUrls:s.evidenceUrls,attractionAssessment:assessment(s.score)},sourceRecords:s.evidenceUrls.map((u:string,i:number)=>source(i?`${s.name} supporting evidence`:s.sourceName,i?'Supporting publisher':s.sourceOrganisation,u,`Current curation: visitor_place_type=${s.placeType}; visit_score=${s.score}; ${s.details}`,u.includes('angus.gov.uk')?'local_authority':'official_non_statutory')),tags:s.tags,createdAt:reviewedAt,updatedAt:reviewedAt,reviewed:true,evidenceScope:'parish_evidence'} as F);

const dates:Record<string,{text:string;earliest:number;latest:number;confidence:string;precision:string;notes:string}>={
 'hes-listed-building:LB18434':{text:'1851 (bell dated 1664)',earliest:1851,latest:1851,confidence:'high',precision:'year',notes:'HES dates the present Gothic church to 1851 and records its bell as 1664.'},
 'hes-listed-building:LB18435':{text:'1681; renovated 1851',earliest:1681,latest:1851,confidence:'high',precision:'year_range',notes:'HES dates the gable spire to 1681 and records the 1851 renovation.'},
 'hes-listed-building:LB18436':{text:'Probably 18th century, c. 1700–1799',earliest:1700,latest:1799,confidence:'medium',precision:'century',notes:'HES describes the mounting block as probably 18th century.'},
 'hes-listed-building:LB18437':{text:'1799, with later porch',earliest:1799,latest:1799,confidence:'high',precision:'year',notes:'HES records a dated 1799 upper-floor window and a later projecting porch.'},
 'hes-listed-building:LB19879':{text:'1774',earliest:1774,latest:1774,confidence:'high',precision:'year',notes:'HES records 1774 on the raised keystone.'},
 'hes-listed-building:LB18422':{text:'1856',earliest:1856,latest:1856,confidence:'high',precision:'year',notes:'HES records Panbride House as designed by James McLaren and completed in 1856.'},
 'hes-listed-building:LB18423':{text:'After 1856 and by 1896',earliest:1857,latest:1896,confidence:'medium',precision:'year_range',notes:'HES states the stables post-date the 1856 house and were in use by an 1896 coachman advertisement.'},
 'nrhe:34495':{text:'Prehistoric, broadly c. 4000 BC–AD 400',earliest:-4000,latest:400,confidence:'low',precision:'period_range',notes:'Broad material period from the official prehistoric-fort classification.'},
 'nrhe:34511':{text:'Medieval to post-medieval, broadly c. 1100–1800',earliest:1100,latest:1800,confidence:'low',precision:'period_range',notes:'The dated component is medieval–post-medieval rig and furrow; the enclosure remains undated.'},
 'nrhe:163227':{text:'Prehistoric to post-medieval, broadly c. 4000 BC–1800',earliest:-4000,latest:1800,confidence:'low',precision:'period_range',notes:'Broad range covering the possible prehistoric settlement and medieval–post-medieval cultivation.'},
 'nrhe:162986':{text:'Prehistoric to post-medieval, broadly c. 4000 BC–1800',earliest:-4000,latest:1800,confidence:'low',precision:'period_range',notes:'Broad range covering the possible prehistoric pit circle and medieval–post-medieval cultivation.'},
 'nrhe:227340':{text:'Post-medieval, broadly c. 1600–1800',earliest:1600,latest:1800,confidence:'low',precision:'period_range',notes:'Broad material period from the official post-medieval mounting-block classification.'},
 'nrhe:313477':{text:'Medieval to post-medieval, broadly c. 1100–1800',earliest:1100,latest:1800,confidence:'low',precision:'period_range',notes:'Broad material period from the official rig-and-furrow classification.'}
};
for(const f of pkg.features.filter(f=>f.id.startsWith('hes-')||f.id.startsWith('nrhe:'))){f.tags=[...new Set([...f.tags,'heritage-record-retained','date-reviewed'])];f.reviewed=true;f.updatedAt=reviewedAt;const d=dates[f.id];if(!d){f.tags=[...new Set([...f.tags,'map-hidden'])];f.reviewNotes='Record retained intact. No defensible construction or material-period date was found, so it remains map-hidden rather than receiving a guessed date.';continue;}f.dateBasis=d.earliest===d.latest?'documented_date':'documented_date_range';f.dateConfidence=d.confidence;f.datePrecision=d.precision;f.documentedDateText=d.text;f.earliestPossibleYear=d.earliest;f.latestPossibleYear=d.latest;f.reviewNotes=d.notes;const context=f.tags.includes('town-selection-heritage-buffer');f.tags=context?[...new Set([...f.tags,'map-hidden'])]:f.tags.filter((t:string)=>t!=='map-hidden');}
const attractions=[
 make({id:'curated-attraction:panbride-parish-church',name:'Panbride Parish Church and Burial Aisle',score:69,coordinates:[-2.6979961,56.5123439],featureType:'church',description:'Historic parish-kirk group with medieval origins, an aisle dated 1681, an 18th-century mounting block and the present 1851 church.',reason:'A compact, distinctive heritage group with strong official records and a meaningful parish story, but limited visitor interpretation and no guaranteed daily interior access.',website:urls.church,sourceName:'Panbride Parish Kirk',sourceOrganisation:'Historic Environment Scotland',evidenceUrls:[urls.church,urls.aisle,urls.her,urls.heritageTrail],placeType:'Attraction',category:'attraction',tags:['curated-visitor','current-context'],details:'medieval_origins=yes; burial_aisle=1681; present_church=1851; mounting_block=18th_century; exterior_visit=reliable; interior_access=not_guaranteed'}),
 make({id:'curated-attraction:craigmill-den',name:'Craigmill Den',score:64,coordinates:[-2.6918,56.5138],featureType:'natural_feature',description:'Leafy burn-side den east of Carnoustie, with traces of the lade and weir that served Panbride Bleachfield.',reason:'A pleasant and historically textured local nature stop on an official route, though small, lightly interpreted and potentially muddy in winter.',website:urls.path,sourceName:'Craigmill Den and Panbride',sourceOrganisation:'Angus Council',evidenceUrls:[urls.path,urls.heritageTrail],placeType:'Attraction',category:'attraction',tags:['curated-visitor','current-context'],details:'burn_side_den=yes; industrial_remains=weir and lade; winter_surface=may be muddy'})
];
const trails=[make({id:'curated-trails:craigmill-den-panbride',name:'Craigmill Den and Panbride Walk',score:72,coordinates:[-2.6964,56.5128],featureType:'walking_route',description:'Official 3.5-mile circular-style outing from Carnoustie through Craigmill Den and the hamlet of Panbride.',reason:'A clearly documented council route with distance, time and terrain, linking the den and church group; its start is in Carnoustie rather than the hamlet.',website:urls.path,sourceName:'Carnoustie Path Network: Craigmill Den and Panbride',sourceOrganisation:'Angus Council',evidenceUrls:[urls.path,urls.paths,urls.heritageTrail],placeType:'Trail',category:'trail',tags:['curated-visitor','visitor-context-trail','current-context','cross-boundary-route'],details:'distance=3.5 miles/5.5 km round trip; time=1 hour 45 minutes; start=Tayside Street Carnoustie; terrain=surfaced paths, pavements and quiet road; winter=muddy in den; route_link_checked=2026-08-30'})];
pkg.features=[...pkg.features.filter(f=>!f.id.startsWith('curated-')),...attractions,...trails];
const highlights:VisitorHighlight[]=attractions.map((f,i)=>({rank:i+1,featureId:f.id,name:f.name,reason:f.editorialReview!.scoreRationale,tagline:i?'Woodland, burn and bleachfield traces':'Medieval roots and an 1851 kirk',visitorScore:i?64:69,timeToSpend:'30–60 minutes',openingTimes:'Outdoor access during daylight hours',admission:'Free',freeAdmission:true,visitorWebsiteUrl:f.visitorWebsiteUrl,editorialReview:f.editorialReview,sourceName:f.sourceRecords[0].sourceName,sourceUrl:f.visitorWebsiteUrl!,verifiedInBoundaryAt:reviewedDate}));
pkg.project.preferredBasemap='voyager';pkg.project.touristAppeal={score:54,dogOwnerScore:54,dogAccessScoreAdjustment:0,rating:0,label:'Selector only',summary:'Panbride has a rewarding churchyard group and Craigmill Den on a verified council walk, but it remains a very small hamlet without a café, public toilet, picnic facility or dedicated visitor car park. These attractions support a worthwhile local detour, not a 60+ town destination.',dogAccessRating:2,dogAccessSummary:'The den walk is suitable for controlled dogs, with care on roads, around livestock and in the churchyard.',methodVersion:'2026-08-30-strict-settlement-full-audit-v3',reviewedAt:reviewedDate,sourceUrls:Object.values(urls)};pkg.project.visitorHighlights=highlights;pkg.project.townGuide={characterTag:'Historic Angus hamlet beside Craigmill Den',headline:'A churchyard-and-den detour rather than a full destination',intro:'Panbride scores 54% and remains selector-only. Its church group and the official Craigmill Den walk are worthwhile, but practical visitor infrastructure belongs chiefly to neighbouring Carnoustie.',bestFor:['Church history','Short woodland walking','Quiet local heritage'],perfectFor:['A short extension from Carnoustie'],dontMiss:['Panbride Parish Church group','Craigmill Den'],suggestedTime:'1–2 hours',visitorMood:'Rural, quiet and historically layered.',sourceUrls:Object.values(urls),lastReviewedAt:reviewedDate};pkg.project.researchNotes='Full strict-boundary audit. All 20 local HES/NRHE records are retained. Eleven defensibly dated records are visible; two dated external-buffer records and seven undated records are map-hidden. The score is not inherited from Carnoustie facilities.';
planner.projects[projectId]={eat:[],trails:trails.map(f=>f.id),picnic:[],parking:[],toilets:[]};dog.reviewedAt=reviewedDate;dog.projects[projectId]={attraction:{[attractions[0].id]:{rating:null,status:'unconfirmed',label:'Dog policy not published',summary:'No reliable current dog policy for the churchyard was found; observe signs and keep dogs closely controlled.',sourceName:'Panbride visitor audit',sourceUrl:urls.heritageTrail,reviewedAt:reviewedDate},[attractions[1].id]:{rating:2,status:'managed',label:'Dogs under close control',summary:'Use close control around wildlife, livestock and other path users, and clear all waste.',sourceName:'Scottish Outdoor Access Code',sourceUrl:urls.dogCode,reviewedAt:reviewedDate}},trail:{[trails[0].id]:{rating:2,status:'managed',label:'Rural route under close control',summary:'Use close control around livestock, roads, wildlife and the churchyard, and clear all waste.',sourceName:'Scottish Outdoor Access Code',sourceUrl:urls.dogCode,reviewedAt:reviewedDate}}};
pkg.validation=validateFeatures(pkg.project,pkg.features);const errors=pkg.validation.filter((e:any)=>e.severity==='error');if(errors.length)throw new Error(errors.map((e:any)=>e.message).join('; '));const heritage=pkg.features.filter(f=>f.id.startsWith('hes-')||f.id.startsWith('nrhe:'));const visible=heritage.filter(f=>!f.tags.includes('map-hidden'));const invalid=visible.filter(f=>!f.documentedDateText?.trim()||f.earliestPossibleYear==null||f.latestPossibleYear==null||f.name.includes(f.documentedDateText));if(heritage.length!==20||visible.length!==11||invalid.length)throw new Error(`Heritage publication failure ${heritage.length}/${visible.length}/${invalid.map(f=>f.id)}`);
const report={reviewedAt,projectId,status:'verified',settlementScore:54,previousScore:48,independentlyWorthwhile:false,publishOnTownMap:false,publication:{see:2,eat:0,trails:1,picnic:0,parking:0,toilets:0},heritage:{localHesListedBuildings:5,contextHesListedBuildings:2,localNrheRecords:13,totalRecordsRetained:20,visibleDatedHeritagePins:11,visibleUndatedHeritagePins:0,mapHiddenRecords:9,datedContextRecordsHidden:2,undatedRecordsHidden:7,dateRule:'Construction or material-period dates only; never designation, database, assessment or publication dates.'},namedTrailSearch:{TreasureTrails:'No exact Panbride product found in the current Dundee and Angus collection.',CuriousAbout:'No exact Panbride product found.',MysteryGuides:'No exact Panbride product found.',GoQuestAdventures:'No exact Panbride product found.',AngusCouncil:'Craigmill Den and Panbride is a current official path-network route with a working PDF.',retained:[trails[0].id]},practicalAudit:{see:'The church group and Craigmill Den independently clear the attraction threshold.',eat:'No café, tearoom, bakery café, coffee-and-cake stop or dependable light lunch was verified in the hamlet.',picnic:'No dedicated public picnic facility verified.',parking:'No dedicated public visitor car park verified; school/customer spaces are excluded.',toilets:'No public toilet verified.',accessibility:'Surfaces include pavements, quiet road and den paths that may be muddy in winter.'},exclusions:['Carnoustie cafés, toilets and car parks','Carlogie Primary School customer parking','Panbride House holiday-accommodation facilities','Fairy Steps while restoration status is unresolved'],verification:{allHeritageRecordsIntact:true,allVisibleHeritagePinsDated:true,datesStoredWithoutChangingMapNames:true,trailLinksChecked:[urls.path,urls.paths,urls.treasure,urls.curious,urls.mystery,urls.goQuest],practicalCoordinatesChecked:true}};
const row={projectId,name:'Panbride',region:'Angus',previousScore:48,correctedScore:54,changed:true,publishOnTownMap:false,rationale:pkg.project.touristAppeal.summary,sourceUrls:[urls.place,urls.church,urls.path,urls.heritageTrail]};const old=correction.results.find((x:any)=>x.projectId===projectId);if(old)Object.assign(old,row);else correction.results.push(row);correction.affectedProjects=correction.results.length;correction.changedScores=correction.results.filter((x:any)=>x.changed).length;correction.mappedAfterCorrection=correction.results.filter((x:any)=>x.correctedScore>=60).map((x:any)=>({projectId:x.projectId,name:x.name,score:x.correctedScore}));
await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`);await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`);await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`);await writeFile(reportPath,`${JSON.stringify(report,null,2)}\n`);await writeFile(correctionPath,`${JSON.stringify(correction,null,2)}\n`);console.log(JSON.stringify({status:report.status,score:report.settlementScore,publication:report.publication,heritage:report.heritage},null,2));
