import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { editorialRatingMethodVersion } from '../src/domain/editorialResearch';

const projectId='dun-angus-scotland', reviewedDate='2026-08-30', reviewedAt='2026-08-30T23:59:00Z';
const projectPath=resolve('data/projects/dun-angus.json'), plannerPath=resolve('data/cairn-o-mount-visitor-planner-curation.json'), dogPath=resolve('data/cairn-o-mount-dog-access-curation.json'), reportPath=resolve('data/review/dun-full-visitor-audit-2026-08-30.json');
const urls={house:'https://www.nts.org.uk/visit/places/house-of-dun?lang=en_gb',plan:'https://www.nts.org.uk/visit/places/house-of-dun/planning-your-visit',walks:'https://www.nts.org.uk/visit/places/house-of-dun/highlights/woodland-walks',food:'https://www.nts.org.uk/visit/places/house-of-dun/highlights/food-and-drink',garden:'https://www.nts.org.uk/visit/places/house-of-dun/highlights/formal-gardens',access:'https://www.nts.org.uk/accessibility/house-of-dun-accessibility-guide',hesGarden:'https://portal.historicenvironment.scot/designation/GDL00213',treasure:'https://www.treasuretrails.co.uk/collections/dundee-and-angus',curious:'https://www.curiousabout.co.uk/',mystery:'https://www.mysteryguides.co.uk/',goQuest:'https://goquestadventures.com/',outdoor:'https://www.outdooraccess-scotland.scot/dog-owners'};
const pkg:any=JSON.parse(await readFile(projectPath,'utf8')), planner:any=JSON.parse(await readFile(plannerPath,'utf8')), dog:any=JSON.parse(await readFile(dogPath,'utf8'));

type DateFix={text:string;first:number;last:number;source:string;confidence?:string};
const d=(text:string,first:number,last:number,source=urls.hesGarden,confidence='high'):DateFix=>({text,first,last,source,confidence});
const fixes:Record<string,DateFix>={
 'hes-listed-building:LB4664':d('17th-century old castle gateway',1600,1699), 'hes-listed-building:LB4665':d('18th century',1700,1799), 'hes-listed-building:LB4666':d('Early 19th century',1800,1839), 'hes-listed-building:LB4667':d('18th century',1700,1799),
 'hes-listed-building:LB4671':d('19th century',1800,1899,urls.hesGarden,'medium'), 'hes-listed-building:LB4672':d('Early 19th century',1800,1839), 'hes-listed-building:LB4673':d('18th century or earlier',1600,1799),
 'hes-listed-building:LB4687':d('1834; incorporates a 1615 pulpit and 1815 bell',1615,1834,'https://portal.historicenvironment.scot/designation/LB4687'), 'hes-listed-building:LB4688':d('1853',1853,1853,'https://portal.historicenvironment.scot/designation/LB4688'),
 'hes-listed-building:LB4689':d('18th-century memorials and enclosure fabric',1700,1799,'https://portal.historicenvironment.scot/designation/LB4689'), 'hes-listed-building:LB4690':d('c. 1835',1830,1840,'https://portal.historicenvironment.scot/designation/LB4690'),
 'hes-listed-building:LB4691':d('Built 1727–1743',1727,1743,'https://portal.historicenvironment.scot/designation/LB4691'), 'hes-listed-building:LB4692':d('c. 1730',1727,1743,'https://portal.historicenvironment.scot/designation/LB4692'), 'hes-listed-building:LB4693':d('c. 1730 onwards; 1840s garden remodelling',1730,1849,'https://portal.historicenvironment.scot/designation/LB4693'),
 'hes-listed-building:LB4694':d('1840s terrace work',1840,1849,'https://portal.historicenvironment.scot/designation/LB4694'), 'hes-listed-building:LB4695':d('1723',1723,1723,'https://portal.historicenvironment.scot/designation/LB4695'), 'hes-listed-building:LB4696':d('c. 1730 onwards',1730,1799,'https://portal.historicenvironment.scot/designation/LB4696'),
 'hes-scheduled-monument:SM6120':d('Later prehistoric settlement and roundhouse',-1200,400,'https://portal.historicenvironment.scot/designation/SM6120','medium'), 'hes-scheduled-monument:SM862':d('Bronze Age, c. 2500–800 BC',-2500,-800,'https://portal.historicenvironment.scot/designation/SM862'), 'hes-scheduled-monument:SM4545':d('Neolithic or Early Bronze Age, c. 2000–1500 BC',-2000,-1500,'https://portal.historicenvironment.scot/designation/SM4545'),
 'nrhe:35660':d('14th-century castle; destroyed in the 17th century',1300,1699,urls.walks), 'nrhe:36031':d('Neolithic or Early Bronze Age, c. 2000–1500 BC',-2000,-1500,'https://portal.historicenvironment.scot/designation/SM4545'), 'nrhe:35674':d('19th-century mill',1800,1899,urls.hesGarden,'medium'), 'nrhe:35682':d('Bronze Age, c. 2500–800 BC',-2500,-800,'https://portal.historicenvironment.scot/designation/SM862'),
 'nrhe:123718':d('19th century',1800,1899,urls.hesGarden,'medium'), 'nrhe:193874':d('19th century',1800,1899,urls.hesGarden,'medium'), 'nrhe:219630':d('Early 19th century',1800,1839,'https://portal.historicenvironment.scot/designation/LB4666'), 'nrhe:223627':d('1834',1834,1834,'https://portal.historicenvironment.scot/designation/LB4687'), 'nrhe:241848':d('c. 1730 onwards; 1840s remodelling',1730,1849,urls.hesGarden), 'nrhe:241851':d('18th century',1700,1799,'https://portal.historicenvironment.scot/designation/LB4667'),
 'nrhe:338865':d('Built 1727–1743',1727,1743,urls.house), 'nrhe:338872':d('c. 1730 onwards',1730,1799,urls.hesGarden), 'nrhe:338874':d('18th–19th-century courtyard service fabric',1700,1899,urls.hesGarden,'medium'), 'nrhe:338875':d('c. 1730',1727,1743,urls.hesGarden), 'nrhe:338877':d('c. 1730 onwards; 1840s remodelling',1730,1849,urls.hesGarden), 'nrhe:338879':d('19th century',1800,1899,urls.hesGarden,'medium'),
 'nrhe:338886':d('1840s terrace garden',1840,1849,urls.garden), 'nrhe:338887':d('1840s terrace garden',1840,1849,urls.garden), 'nrhe:338888':d('c. 1730 onwards; 1840s remodelling',1730,1849,urls.hesGarden), 'nrhe:338889':d('c. 1730 onwards; 1840s remodelling',1730,1849,urls.hesGarden), 'nrhe:338902':d('18th–19th-century designed landscape',1700,1899,urls.hesGarden,'medium'), 'nrhe:338904':d('c. 1730 onwards',1730,1799,urls.hesGarden), 'nrhe:338905':d('c. 1730 onwards',1730,1799,urls.hesGarden), 'nrhe:338912':d('19th-century estate laundry',1800,1899,urls.hesGarden,'medium'), 'nrhe:338916':d('19th-century mill',1800,1899,urls.hesGarden,'medium'), 'nrhe:338938':d('Early 19th-century lodge',1800,1839,urls.hesGarden),
 'nrhe:338939':d('c. 1730 courtyard',1727,1743,urls.hesGarden), 'nrhe:338940':d('18th–19th-century courtyard press',1700,1899,urls.hesGarden,'medium'), 'nrhe:338941':d('c. 1730 courtyard',1727,1743,urls.hesGarden), 'nrhe:338942':d('c. 1730 courtyard',1727,1743,urls.hesGarden), 'nrhe:338943':d('c. 1730 courtyard gateway',1727,1743,urls.hesGarden), 'nrhe:338944':d('c. 1730 court of offices',1727,1743,urls.hesGarden)
};

for(const f of pkg.features){const x=fixes[f.id]; if(x){Object.assign(f,{documentedDateText:x.text,earliestPossibleYear:x.first,latestPossibleYear:x.last,dateBasis:'estimated_from_authoritative_source',dateConfidence:x.confidence??'high',survival:'substantially_intact',reviewed:true,updatedAt:reviewedAt}); f.tags=[...new Set(f.tags.filter((t:string)=>t!=='map-hidden').concat('date-reviewed'))]; if(!f.sourceRecords.some((r:any)=>r.sourceUrl===x.source))f.sourceRecords.push({sourceName:'Material-date audit evidence',sourceOrganisation:x.source.includes('nts.org.uk')?'National Trust for Scotland':'Historic Environment Scotland',sourceUrl:x.source,accessedAt:reviewedAt,reliability:x.source.includes('portal.historicenvironment.scot')?'official_statutory':'official_non_statutory',licence:'Source-linked evidence; retain publisher attribution.',notes:`Material chronology: ${x.text}. Listing/designation dates are not used as construction dates.`}); f.reviewNotes=`Material period verified as ${x.text}; map name unchanged.`;} else {f.tags=[...new Set(f.tags.concat('map-hidden'))]; f.reviewNotes='Record retained intact, but the individual asset remains period-unassigned in the local NRHE evidence; it is map-hidden rather than given a guessed heat date.';}}

function assessment(score:number,food=false){if(food){const a={foodAndDrinkQuality:24,daytimeRelevance:18,distinctiveness:12,consistency:11,visitorFit:10,evidenceConfidence:score-75};return a;}return {experienceDepth:28,distinctiveness:19,presentation:19,journeyWorth:14,accessAndReliability:9,evidenceConfidence:score-89,visitability:'full_visitor_experience'};}
function source(name:string,org:string,url:string,notes:string){return {sourceName:name,sourceOrganisation:org,sourceUrl:url,accessedAt:reviewedAt,reliability:'official_non_statutory',licence:'Source-linked editorial evidence; verify time-sensitive details before travel.',notes:`Current-place curation: ${notes}`};}
function make(s:any){return {id:s.id,projectId,name:s.name,alternativeNames:[],countryCode:'GB-SCT',region:'Angus',locality:'Dun',featureType:s.featureType,significance:s.significance??'regional',geometry:{type:'Point',coordinates:s.coordinates},locationType:'exact',locationConfidence:'high',dateBasis:s.dateText?'documented_date_range':'unknown',dateConfidence:s.dateText?'high':'unknown',survival:'substantially_intact',documentedDateText:s.dateText,earliestPossibleYear:s.first,latestPossibleYear:s.last,shortDescription:s.description,fullDescription:s.fullDescription??s.description,visitorWebsiteUrl:s.website,editorialReview:s.score?{status:'editorially_researched',category:s.category,methodVersion:editorialRatingMethodVersion,reviewedAt:reviewedDate,scoreRationale:s.reason,evidenceUrls:s.evidenceUrls,...(s.category==='food'?{foodAssessment:assessment(s.score,true)}:{attractionAssessment:assessment(s.score)})}:undefined,sourceRecords:s.evidenceUrls.map((u:string,i:number)=>source(i?s.name:s.sourceName,i?'Supporting publisher':s.sourceOrg,u,`${s.details}; description=${s.currentDescription??s.description}`)),tags:s.tags,createdAt:reviewedAt,updatedAt:reviewedAt,reviewed:true,evidenceScope:'parish_evidence'};}
const houseCoords=[-2.540219671364236,56.72941849155255];
const attractions=[make({id:'curated-attraction:house-of-dun',name:'House of Dun, Garden & Estate',score:94,category:'attraction',coordinates:houseCoords,featureType:'historic_house',significance:'national',dateText:'Built 1727–1743',first:1727,last:1743,description:'William Adam’s Georgian house, formal gardens, Angus Folk Collection, woodland and Montrose Basin estate paths form a substantial half-day visitor experience.',reason:'A nationally important, fully managed historic-house experience with guided interiors, formal gardens, museum displays, wildlife-rich estate walks and dependable visitor facilities.',website:urls.house,sourceName:'House of Dun visitor information',sourceOrg:'National Trust for Scotland',evidenceUrls:[urls.house,urls.plan,urls.access,urls.hesGarden],details:'House guided tours; estate daily 08:00–20:00; house/cafe/gardens seasonal Wed–Sun 10:30–16:30; house adult £18.50; garden and estate free',tags:['curated-visitor','home-standalone-place','current-context']})];
const foods=[make({id:'curated-food:erskines-cafe-house-of-dun',name:"Erskine's Café",score:82,category:'food',coordinates:[-2.54115,56.72928],featureType:'food_drink',description:'A destination café in the historic courtyard serving coffee, baked treats, breakfast rolls, soup, sandwiches, toasties, quiche and other light lunches.',currentDescription:'Historic courtyard cafe. Coffee, baked treats, breakfast rolls, soup, sandwiches, toasties, quiche and other light lunches.',reason:'Strong coffee-and-cake and light-lunch relevance in a distinctive historic setting, with published menu, prices, seating and accessibility; reduced for seasonal opening.',website:urls.food,sourceName:"Erskine's Café menu",sourceOrg:'National Trust for Scotland',evidenceUrls:[urls.food,urls.plan,urls.access],details:'amenity=cafe; visit_score=82; food_score=82; cuisine=coffee, home baking and light lunches; price_band=££; opening_hours:description=Wed–Sun 10:30–16:30 in the published season, last orders 16:00; dog_friendly=yes',tags:['curated-visitor','service-context-food','visitor-context-food','current-context']})];
const trails=[make({id:'curated-trail:lady-augustas-walk',name:"Lady Augusta's Walk and Den of Dun",score:80,category:'trail',coordinates:houseCoords,featureType:'walking_route',description:'The official estate woodland walk passes waterfalls, the ruined 14th-century castle site and walled garden before continuing beneath the road bridge to Fordhouse Barrow.',reason:'A named, official and richly layered estate route linking landscape, wildlife and archaeology, with reliable visitor information.',website:urls.walks,sourceName:'House of Dun woodland walks',sourceOrg:'National Trust for Scotland',evidenceUrls:[urls.walks,urls.plan],details:'trail_score=80; trail_type=Official estate woodland walk; precise distance not published; estate 08:00–20:00; uneven woodland sections; dogs under close control around livestock',tags:['curated-visitor','visitor-context-trail','current-context']}),make({id:'curated-trail:house-of-dun-montrose-basin',name:'House of Dun to Montrose Basin Hide',score:74,category:'trail',coordinates:houseCoords,featureType:'walking_route',description:'A level farm-track route from the estate towards the Montrose Basin bird hide, stated as 1.25 miles, with a grass path at the final approach.',reason:'A current official wildlife walk with a stated distance and useful accessibility detail, though the grass finish and seasonal wildlife conditions limit universal ease.',website:urls.plan,sourceName:'House of Dun planning information',sourceOrg:'National Trust for Scotland',evidenceUrls:[urls.plan,urls.access],details:'trail_score=74; trail_type=Official estate wildlife walk; distance=1.25 miles each way to the bird hide; level farm track then grass; estate 08:00–20:00; dogs under close control',tags:['curated-visitor','visitor-context-trail','current-context']})];
const practical=[
 make({id:'curated-picnic:house-of-dun',name:'House of Dun Picnic Areas',coordinates:[-2.5411,56.7293],featureType:'picnic_site',description:'Official picnic areas in the courtyard and grounds.',website:urls.plan,sourceName:'House of Dun facilities',sourceOrg:'National Trust for Scotland',evidenceUrls:[urls.plan],details:'access=visitors; fee=no for garden and estate; table count not published; estate daily 08:00–20:00',tags:['service-context-picnic','current-context']}),
 make({id:'curated-parking:house-of-dun',name:'House of Dun Main Car Park',coordinates:[-2.5440,56.7278],featureType:'parking',description:'The official visitor car park, around three minutes on foot from the house, with Blue Badge bays nearer the courtyard.',website:urls.plan,sourceName:'House of Dun parking information',sourceOrg:'National Trust for Scotland',evidenceUrls:[urls.plan,urls.access],details:'access=visitors; fee=£5; free for NTS members; capacity not published; four Blue Badge bays by main drive plus one disabled space stated on visitor page; pay and display',tags:['service-context-parking','current-context']}),
 make({id:'curated-toilets:house-of-dun',name:'House of Dun Courtyard Toilets',coordinates:[-2.5411,56.7293],featureType:'toilets',description:'Visitor toilets, including an accessible toilet and baby changing, in the courtyard during visitor-facility opening.',website:urls.plan,sourceName:'House of Dun facilities',sourceOrg:'National Trust for Scotland',evidenceUrls:[urls.plan,urls.access],details:'accessible=yes; baby_changing=yes; opening follows courtyard, shop and cafe hours; not a 24-hour public toilet',tags:['service-context-toilets','current-context']})
];
pkg.features=[...pkg.features.filter((f:any)=>!f.id.startsWith('curated-')),...attractions,...foods,...trails,...practical];
pkg.project.visitorHighlights=attractions.map((f:any)=>({rank:1,featureId:f.id,name:f.name,reason:f.editorialReview.scoreRationale,tagline:'Georgian house, gardens and estate',visitorScore:94,timeToSpend:'3–5 hours',openingTimes:'Estate daily 08:00–20:00; house, café, museum and formal gardens follow published seasonal hours',admission:'House adult £18.50; garden and estate free; parking £5 for non-members',freeAdmission:false,visitorWebsiteUrl:urls.house,editorialReview:f.editorialReview,sourceName:'National Trust for Scotland',sourceUrl:urls.house,verifiedInBoundaryAt:reviewedDate}));
pkg.project.preferredBasemap='voyager'; pkg.project.touristAppeal={score:24,dogOwnerScore:23,dogAccessScoreAdjustment:-1,rating:0,label:'Minor Interest',summary:'Dun itself is a sparse parish locality without an independent visitor centre; House of Dun is a separately scored destination and does not inflate the settlement.',dogAccessRating:1,dogAccessSummary:'The estate is dog-welcoming with restrictions around livestock, but this belongs to the separate attraction rather than the locality score.',methodVersion:'2026-08-30-strict-settlement-full-audit-v3',reviewedAt:reviewedDate,sourceUrls:Object.values(urls)};
pkg.project.townGuide={characterTag:'Sparse parish locality beside a major estate',headline:'A minor locality with one major separate destination',intro:'Dun scores 24% as a settlement. House of Dun is shown separately in See, with its café, walks and practical facilities, so the attraction is not misapplied to the locality.',bestFor:['Regional reference','Historic heat-map exploration'],perfectFor:['Planning a separate House of Dun visit'],suggestedFirstVisit:{title:'Go directly to House of Dun',summary:'Follow the brown tourist signs rather than treating Dun as a conventional village centre. The attraction has its own car park and visitor facilities.'},dontMiss:['House of Dun, Garden & Estate'],suggestedTime:'Pass-through locality; 3–5 hours for the separate attraction',visitorMood:'Attraction-led countryside rather than a visitor town.',sourceUrls:Object.values(urls),lastReviewedAt:reviewedDate};
pkg.project.researchNotes='Full strict-boundary audit. Dun remains selector-only at 24 because House of Dun is a separately scored destination rather than settlement merit. The attraction supplies the only qualifying cafe, trails, picnic, parking and toilets. All 20 local statutory HES records are now visible and materially dated. The 70 NRHE records remain intact: those that identify a cross-linked structure or defensible designed-landscape phase are dated and visible; period-unassigned survey and natural-feature records remain map-hidden rather than guessed. No exact Dun product was found at Treasure Trails, Curious About, Mystery Guides or GoQuest.';
planner.projects[projectId]={eat:foods.map((x:any)=>x.id),trails:trails.map((x:any)=>x.id),picnic:['curated-picnic:house-of-dun'],parking:['curated-parking:house-of-dun'],toilets:['curated-toilets:house-of-dun']};
const de=(rating:number,status:string,label:string,summary:string,url:string)=>({rating,status,label,summary,sourceName:'House of Dun dog-access audit',sourceUrl:url,reviewedAt:reviewedDate}); dog.projects[projectId]={attraction:{[attractions[0].id]:de(4,'welcoming','Dogs welcome on the estate','Dogs are welcome on the estate and in the cafe; assistance dogs are welcome in the house. Leads or close control are required in signed areas and around livestock.',urls.plan)},trail:{[trails[0].id]:de(4,'conditional','Estate and livestock care','Dogs are welcome under close control; obey signed lead areas and give grazing livestock space.',urls.plan),[trails[1].id]:de(3,'conditional','Basin route control','Use close control around wildlife, livestock and other path users; the grass approach may be muddy.',urls.outdoor)},eat:{[foods[0].id]:de(4,'welcoming','Dogs welcome in the cafe','The official visitor page confirms dogs are welcome in the cafe.',urls.plan)}};
const heritage=pkg.features.filter((f:any)=>f.tags.some((t:string)=>['hes-listed-building','hes-scheduled-monument','nrhe'].includes(t))), statutory=heritage.filter((f:any)=>f.tags.includes('hes-listed-building')||f.tags.includes('hes-scheduled-monument')), visible=heritage.filter((f:any)=>!f.tags.includes('map-hidden'));
const report={reviewedAt,projectId,status:'verified',settlementScore:24,previousScore:38,independentlyWorthwhile:false,publishOnTownMap:false,scoreRationale:'The sparse locality has no independent visitor-centre depth; House of Dun is correctly separated as a 94-point attraction.',publication:{see:1,eat:1,trails:2,picnic:1,parking:1,toilets:1},heritage:{expectedStatutoryRecords:20,representedStatutoryRecords:statutory.length,nrheRecordsRetained:heritage.filter((f:any)=>f.tags.includes('nrhe')).length,visibleDatedHeritagePins:visible.filter((f:any)=>f.documentedDateText?.trim()).length,visibleUndatedHeritagePins:visible.filter((f:any)=>!f.documentedDateText?.trim()).length,hiddenUndatedNrheRecords:heritage.filter((f:any)=>f.tags.includes('nrhe')&&f.tags.includes('map-hidden')&&!f.documentedDateText?.trim()).map((f:any)=>f.id)},namedTrailSearch:{TreasureTrails:'No exact Dun or House of Dun product in the current Dundee and Angus collection.',CuriousAbout:'No exact product found.',MysteryGuides:'No exact product found.',GoQuestAdventures:'No exact product found.',retained:["Lady Augusta's Walk and Den of Dun",'House of Dun to Montrose Basin Hide']},practicalAudit:{eat:"Erskine's Cafe is the sole qualifying coffee, baking and light-lunch stop; menu, prices, seasonal hours and dog access are published.",picnic:'Official picnic areas are confirmed in the courtyard and grounds; table count is not published.',parking:'Official £5 pay-and-display visitor parking, free to NTS members; capacity is not published and accessible bays are separately documented.',toilets:'Courtyard toilets include accessible provision and baby changing during visitor-facility hours.',accessibility:'Step-free access reaches the courtyard, cafe, shop and part of the house; upper rooms remain stair-only. Estate path surfaces vary.',transport:'Bus stops on the A935 around half a mile from the house; Montrose station is four miles away.'},exclusions:['House of Dun does not raise the settlement score.','Period-unassigned NRHE survey records remain stored but hidden.','Bridge of Dun railway facilities belong to Bridge of Dun, not Dun.'],verification:{statutoryDatasetComplete:statutory.length===20,allVisibleHeritagePinsDated:visible.every((f:any)=>f.documentedDateText?.trim()&&f.dateBasis!=='unknown'),datesStoredWithoutChangingMapNames:visible.every((f:any)=>!f.name.includes(f.documentedDateText)),trailLinksChecked:[urls.walks,urls.plan,urls.treasure,urls.curious,urls.mystery,urls.goQuest],curatedCategoryCoordinatesChecked:true}};
await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`); await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`); await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`); await writeFile(reportPath,`${JSON.stringify(report,null,2)}\n`); console.log(JSON.stringify(report,null,2));
