import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const projectId = 'aberdeen-scotland';
const reviewedDate = '2026-08-27';
const reviewedAt = '2026-08-27T23:30:00Z';
const projectPath = resolve('data/projects/aberdeen.json');
const plannerPath = resolve('data/aberdeen-north-visitor-planner-curation.json');
const dogPath = resolve('data/aberdeen-north-dog-access-curation.json');
const reportPath = resolve('data/review/aberdeen-full-visitor-audit-2026-08-27.json');
type MutableFeature = HeritageFeature & Record<string, any>;
type MutablePackage = ProjectPackage & { project: ProjectPackage['project'] & Record<string, any>; features: MutableFeature[] };

const urls = {
  city: 'https://visitabdn.com/regions/city', gallery: 'https://sites.aberdeencity.gov.uk/AAGM/plan-your-visit/art-gallery',
  galleryHistory: 'https://sites.aberdeencity.gov.uk/AAGM/about-us/organisation-and-history', maritime: 'https://sites.aberdeencity.gov.uk/AAGM/plan-your-visit/maritime-museum',
  skene: 'https://sites.aberdeencity.gov.uk/AAGM/plan-your-visit/provost-skenes-house', science: 'https://aberdeensciencecentre.org/visit/',
  duthie: 'https://visitabdn.com/listing/duthie-park', unionTerrace: 'https://www.aberdeencity.gov.uk/news/archive?page=3&topics=726',
  hesGallery: 'https://portal.historicenvironment.scot/designation/LB19978', hesTownHouse: 'https://portal.historicenvironment.scot/designation/LB19990',
  hesSkene: 'https://portal.historicenvironment.scot/designation/LB20156', hesMaritime: 'https://portal.historicenvironment.scot/designation/LB20484',
  hesCross: 'https://portal.historicenvironment.scot/designation/LB19999', hesMusicHall: 'https://portal.historicenvironment.scot/designation/LB19991',
  hesKirk: 'https://portal.historicenvironment.scot/designation/LB19966', hesMarischal: 'https://portal.historicenvironment.scot/designation/LB20096',
  trails: 'https://sites.aberdeencity.gov.uk/AAGM/local-history/heritage-trails', granite: 'https://sites.aberdeencity.gov.uk/sites/default/files/2020-09/Aberdeen%20Granite%20Trail.pdf',
  maritimeTrail: 'https://sites.aberdeencity.gov.uk/sites/default/files/2020-09/Maritime%20Heritage%20Trail.pdf', greenTrail: 'https://sites.aberdeencity.gov.uk/sites/default/files/2020-09/The%20Green%20Trail.pdf',
  treasure: 'https://www.treasuretrails.co.uk/products/things-to-do-aberdeen-aberdeenshire', nuart: 'https://visitabdn.com/itineraries/your-ultimate-guide-to-nuart-aberdeen',
  foodstory: 'https://foodstorycafe.co.uk/', booksBeans: 'https://booksandbeans.co.uk/', cup: 'https://www.cupteasalon.com/', galleryCafe: 'https://www.aberdeencity.gov.uk/AAGM/gallery-cafes',
  parking: 'https://sites.aberdeencity.gov.uk/Council-Services/roads-parking-and-travel/parking/find-a-car-park/local-area/car-parks', unionSquare: 'https://unionsquareaberdeen.com/visit/parking/',
  galleryAccess: 'https://sites.aberdeencity.gov.uk/AAGM/plan-your-visit/access/art-gallery-access-guide-text-only', toilets: 'https://www.aberdeencity.gov.uk/services/people-and-communities/public-toilets',
  dogCode: 'https://www.outdooraccess-scotland.scot/dog-owners', curious: 'https://curiousabout.co.uk/', mystery: 'https://www.mysteryguides.co.uk/', goQuest: 'https://goquestadventures.com/',
};

const pkg = JSON.parse(await readFile(projectPath, 'utf8')) as MutablePackage;
const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as any;
const dog = JSON.parse(await readFile(dogPath, 'utf8')) as any;
const assessment = (score: number) => ({ experienceDepth: Math.round(score*.3), distinctiveness: Math.round(score*.2), presentation: Math.round(score*.2), journeyWorth: Math.round(score*.15), accessAndReliability: Math.round(score*.1), evidenceConfidence: score-Math.round(score*.3)-Math.round(score*.2)-Math.round(score*.2)-Math.round(score*.15)-Math.round(score*.1), visitability: 'full_visitor_experience' as const });
const foodAssessment = (score: number) => ({ foodAndDrinkQuality: Math.round(score*.29), daytimeRelevance: Math.round(score*.21), distinctiveness: Math.round(score*.15), consistency: Math.round(score*.14), visitorFit: Math.round(score*.11), evidenceConfidence: score-Math.round(score*.29)-Math.round(score*.21)-Math.round(score*.15)-Math.round(score*.14)-Math.round(score*.11) });
const source = (name: string, organisation: string, url: string, notes: string, reliability: any = 'official_non_statutory') => ({ sourceName:name, sourceOrganisation:organisation, sourceUrl:url, accessedAt:reviewedAt, reliability, licence:'Source-linked editorial evidence; verify time-sensitive details before travel.', notes });
const review = (category: 'attraction'|'trail'|'food', score: number, rationale: string, evidenceUrls: string[]) => ({ status:'editorially_researched', category, methodVersion:'2026-08-13-researched-visitor-value-v1', reviewedAt:reviewedDate, scoreRationale:rationale, evidenceUrls, ...(category==='food'?{foodAssessment:foodAssessment(score)}:{attractionAssessment:assessment(score)}) });
const make = (s: Record<string, any>): MutableFeature => ({ id:s.id, projectId, name:s.name, alternativeNames:[], countryCode:'GB-SCT', region:'Aberdeen City', locality:'Aberdeen', featureType:s.featureType, significance:s.significance??'local', geometry:{type:'Point',coordinates:s.coordinates}, locationType:s.locationType??'exact', locationConfidence:'high', dateBasis:s.dateBasis??'unknown', dateConfidence:s.dateConfidence??'unknown', survival:s.survival??'substantially_intact', documentedDateText:s.dateText, earliestPossibleYear:s.earliest, latestPossibleYear:s.latest, datePrecision:s.datePrecision, shortDescription:s.description, fullDescription:s.fullDescription, visitorWebsiteUrl:s.website, attractionGuide:s.guide, editorialReview:s.category?review(s.category,s.score,s.reason,s.evidenceUrls):undefined, sourceRecords:s.evidenceUrls.map((url:string,i:number)=>source(i?`${s.name} supporting evidence`:s.sourceName,i?'Supporting publisher':s.sourceOrganisation,url,`Current-place curation: visitor_place_type=${s.placeType}; ${s.score?`visit_score=${s.score}; `:''}${s.details??''}; description=${s.description}`,url.includes('historicenvironment.scot')?'official_statutory':url.includes('aberdeencity.gov.uk')?'local_authority':'official_non_statutory')), tags:s.tags, createdAt:reviewedAt, updatedAt:reviewedAt, reviewed:true, evidenceScope:'parish_evidence' }) as MutableFeature;

const heritageSpecs = [
  ['hes-listed-building:LB19978','Aberdeen Art Gallery','civic_building',[-2.102721,57.1481374],urls.hesGallery,'Opened 1885; Sculpture Court added 1905; War Memorial and Cowdray Hall completed 1925; redeveloped 2015–19',1885,2019],
  ['hes-listed-building:LB19990','Aberdeen Town House and Tolbooth','civic_building',[-2.0939533,57.1479809],urls.hesTownHouse,'Tolbooth built 1615–29; Town House built 1868–74; City Chambers added 1975',1615,1975],
  ['hes-listed-building:LB20156','Provost Skene’s House','house',[-2.0975907,57.1482612],urls.hesSkene,'16th-century origins, with south-west extension dated 1626 and remodelling in 1670',1500,1670],
  ['hes-listed-building:LB20484','Provost Ross’s House and Aberdeen Maritime Museum','house',[-2.0949554,57.1464845],urls.hesMaritime,'Provost Ross’s House dated 1593; restored 1954; incorporated into the museum complex opened in 1997',1593,1997],
  ['hes-listed-building:LB19999','Aberdeen Mercat Cross','monument',[-2.0926027,57.1482521],urls.hesCross,'Built 1686; repaired 1821–22; moved and repaired 1841–42; column replaced 1995–96',1686,1996],
  ['hes-listed-building:LB19991','Aberdeen Music Hall','civic_building',[-2.1050564,57.1453568],urls.hesMusicHall,'Assembly Rooms built 1820; Music Hall added 1858–59; murals installed 1899–circa 1909; restored 1986',1820,1986],
  ['hes-listed-building:LB19966','Kirk of St Nicholas','church',[-2.1001,57.14645],urls.hesKirk,'Church origins documented from 1151; crypt built 1438; West Kirk 1755; East Kirk 1835–37 and rebuilt after the 1874 fire',1151,1877],
  ['hes-listed-building:LB20096','Marischal College','school',[-2.0968447,57.1495305],urls.hesMarischal,'Friary founded 1469; college founded 1593; Simpson quadrangle 1837; present granite frontage completed 1903–06',1469,1906],
] as const;
const heritage = heritageSpecs.map(([id,name,featureType,coordinates,website,dateText,earliest,latest])=>make({id,name,featureType,coordinates,website,dateText,earliest,latest,dateBasis:'documented_date_range',dateConfidence:'high',datePrecision:'multi_period',description:`A dated Aberdeen heritage landmark; the public pin records construction history rather than the later listing date.`,evidenceUrls:[website],sourceName:'Historic Environment Scotland designation',sourceOrganisation:'Historic Environment Scotland',placeType:'Heritage',tags:['hes-listed-building','date-reviewed']}));
const additionalOfficialPointLocations: Record<string, Array<{type:'Point';coordinates:[number,number]}>> = {
  'hes-listed-building:LB19990': [{type:'Point',coordinates:[-2.0956396042395626,57.14816954946756]}],
  'hes-listed-building:LB19966': [{type:'Point',coordinates:[-2.099587865299363,57.147564607916884]}],
};
for (const feature of heritage) feature.additionalPointLocations = additionalOfficialPointLocations[feature.id];
const byId = (id:string)=>heritage.find((f)=>f.id===id)!;

const attractions = [
  { feature:byId('hes-listed-building:LB19978'), score:90, reason:'A nationally important, free gallery with strong permanent collections, landmark architecture and dependable all-year access.', website:urls.gallery, time:'1.5–3 hours', opening:'Mon–Sat 10:00–17:00; Sun 11:00–16:00', admission:'Free', guide:{headline:'Art, design and Aberdeen history in a landmark granite gallery',parking:'Use city-centre parking; no dedicated visitor car park.',toilets:'Accessible toilets and a Changing Places facility are available.',picnic:'No formal indoor picnic area.',foodNote:'Two gallery cafés serve coffee, homebakes and light meals.'}},
  { feature:byId('hes-listed-building:LB20484'), score:88, reason:'Four floors of maritime, harbour and North Sea industry displays in a compelling historic harbour-side complex, free to enter.', website:urls.maritime, time:'1.5–2.5 hours', opening:'Mon–Sat 10:00–17:00; Sun 11:00–16:00', admission:'Free', guide:{headline:'Aberdeen’s harbour, fishing and offshore story',parking:'No dedicated visitor car park; use city-centre parking.',toilets:'Visitor and accessible toilets are available.',picnic:'No formal picnic provision.',foodNote:'Plan a café stop in the city centre.'}},
  { feature:make({id:'curated-attraction:duthie-park',name:'Duthie Park and David Welch Winter Gardens',featureType:'park',coordinates:[-2.1031544,57.1306317],website:urls.duthie,dateText:'Land gifted in 1881; park officially opened on 27 September 1883; present Winter Gardens date from 1970',earliest:1881,latest:1970,dateBasis:'documented_date_range',dateConfidence:'high',datePrecision:'multi_period',description:'A 44-acre riverside park with formal gardens, one of Europe’s largest indoor garden displays, lawns, play and café facilities.',evidenceUrls:[urls.duthie],sourceName:'Duthie Park visitor listing',sourceOrganisation:'VisitAberdeenshire',placeType:'Attraction',tags:['curated-visitor','home-standalone-place','date-reviewed']}), score:88, reason:'A substantial free park and indoor-garden experience with picnic lawns, play, café and broad family appeal.', website:urls.duthie,time:'1.5–3 hours',opening:'Park generally open daily; check current Winter Gardens hours',admission:'Free',guide:{headline:'Formal parkland and landmark indoor gardens beside the Dee',parking:'On-site parking exists; verify current restrictions and bay availability on arrival.',toilets:'Public facilities are provided; live status should be checked.',picnic:'Extensive lawns support picnics; no verified fixed-table count.',foodNote:'The park café provides refreshments.'}},
  { feature:byId('hes-listed-building:LB20156'), score:82, reason:'A free, well-presented city-history museum in one of Aberdeen’s most atmospheric surviving historic houses.',website:urls.skene,time:'1–1.5 hours',opening:'Apr–Oct Thu–Mon 10:00–17:00; Sun 11:00–16:00; seasonal closure applies',admission:'Free',guide:{headline:'Stories of Aberdeen people inside a rare historic house',parking:'Use city-centre parking.',toilets:'Visitor facilities are available; check the access guide for historic-building constraints.',picnic:'No formal picnic provision.',foodNote:'Use nearby city-centre cafés.'}},
  { feature:make({id:'curated-attraction:aberdeen-science-centre',name:'Aberdeen Science Centre',featureType:'other',coordinates:[-2.0850204,57.1532457],website:urls.science,description:'A hands-on science centre with more than 65 interactive exhibits and demonstrations.',evidenceUrls:[urls.science],sourceName:'Plan your visit',sourceOrganisation:'Aberdeen Science Centre',placeType:'Attraction',tags:['curated-visitor','home-standalone-place']}),score:80,reason:'A strong indoor family attraction with more than 65 hands-on exhibits, reduced slightly for paid admission and a specialist family focus.',website:urls.science,time:'2–3 hours',opening:'Daily 10:00–16:30; check event and holiday changes',admission:'Adult £12.03 with donation (£10.94 without); concessions available',guide:{headline:'Hands-on science for families and curious visitors',parking:'The centre publishes visitor travel information; check live parking arrangements before travel.',toilets:'Visitor and accessible facilities are available.',picnic:'No formal picnic provision verified.',foodNote:'Check the centre’s current café offer before travel.'}},
  { feature:make({id:'curated-attraction:union-terrace-gardens',name:'Union Terrace Gardens',featureType:'garden',coordinates:[-2.1032638,57.1465325],website:urls.unionTerrace,dateText:'Opened in 1878; major restoration completed and gardens reopened in December 2022',earliest:1878,latest:2022,dateBasis:'documented_date_range',dateConfidence:'high',datePrecision:'multi_period',description:'Restored city-centre gardens with lawns, accessible routes, play, heritage features and public toilets.',evidenceUrls:[urls.unionTerrace],sourceName:'Union Terrace Gardens reopening',sourceOrganisation:'Aberdeen City Council',placeType:'Attraction',tags:['curated-visitor','home-standalone-place','date-reviewed']}),score:74,reason:'A useful, attractive free green pause in the city centre, with restored heritage and practical facilities but limited experience depth.',website:urls.unionTerrace,time:'30–60 minutes',opening:'Public garden; check current gate hours',admission:'Free',guide:{headline:'A restored green amphitheatre in the granite city centre',parking:'Use nearby city-centre car parks.',toilets:'Public toilets were included in the restored gardens.',picnic:'Lawns suit an informal picnic; no fixed-table count verified.',foodNote:'Cafés are available around Union Street and Belmont Street.'}},
  { feature:byId('hes-listed-building:LB19999'),score:68,reason:'A richly carved 1686 civic monument that rewards a short Castlegate stop but is not a deep standalone visit.',website:urls.trails,time:'10–20 minutes',opening:'Open-air public landmark',admission:'Free',guide:{headline:'The carved 1686 centrepiece of the Castlegate',parking:'Use city-centre parking.',toilets:'No dedicated facility.',picnic:'No dedicated provision.',foodNote:'Nearby city-centre cafés.'}},
];
for (const a of attractions) { Object.assign(a.feature,{visitorWebsiteUrl:a.website,attractionGuide:a.guide,editorialReview:review('attraction',a.score,a.reason,[a.website,a.feature.sourceRecords[0].sourceUrl]),tags:[...new Set([...a.feature.tags,'curated-visitor','home-standalone-place'])]}); }

const trailSpecs = [
  ['curated-trails:aberdeen-treasure-trail','Aberdeen City Centre and Castlegate Treasure Trail',76,[-2.0978,57.1476],urls.treasure,'A paid 2-mile, roughly 1½-hour circular clue trail; provider marks it dog friendly but not wheelchair or pushchair accessible.'],
  ['curated-trails:aberdeen-granite-trail','Aberdeen Granite Trail',74,[-2.101,57.1477],urls.granite,'A free council PDF exploring the buildings, quarries and craft behind the Granite City.'],
  ['curated-trails:aberdeen-maritime-trail','Aberdeen Maritime Heritage Trail',72,[-2.0948,57.1464],urls.maritimeTrail,'A free council route in north and south sections of about 2.5 km and 3 km around the working harbour.'],
  ['curated-trails:aberdeen-nuart','Nuart Aberdeen Street Art Trail',72,[-2.099,57.147],urls.nuart,'A free current guide to large-scale street art across the city centre, suitable for a flexible 2–3-hour exploration.'],
  ['curated-trails:aberdeen-green-trail','The Green Heritage Trail',66,[-2.099,57.1438],urls.greenTrail,'A free council PDF exploring the medieval Green and the city’s transport and commercial history.'],
];
const trails = trailSpecs.map(([id,name,score,coordinates,website,description])=>make({id,name,score,coordinates,website,featureType:'other',locationType:'representative_point',description,reason:`A verified, Aberdeen-specific self-guided route with a live planning link; score reflects route depth, distinctiveness and practical presentation.`,evidenceUrls:[website],sourceName:name,sourceOrganisation:id.includes('treasure')?'Treasure Trails':id.includes('nuart')?'VisitAberdeenshire':'Aberdeen City Council',placeType:'Trail',details:'Link checked during the audit; route conditions and attraction opening hours may change',category:'trail',tags:['curated-visitor','service-context-trail','visitor-context-trail','current-context']}));
const foodSpecs = [
  ['curated-eat:aberdeen-foodstory','Foodstory',84,[-2.1106857,57.1440088],urls.foodstory,'Plant-powered coffee and baking: Independent vegetarian café for speciality coffee, tea, baking, brunch and light lunches.','opening_hours:description=Mon, Tue, Thu, Fri, Sat and Sun 08:00–16:30; Wed 08:00–20:00; price_band=££; cuisine=Speciality coffee, home baking, brunch and vegetarian light lunches'],
  ['curated-eat:aberdeen-books-and-beans','Books and Beans',80,[-2.1012594,57.1469421],urls.booksBeans,'Coffee among second-hand books: Fairtrade café and bookshop serving coffee, soup, toasties, pancakes, cakes and scones.','opening_hours:description=Daily 09:30–16:00; price_band=££; cuisine=Fairtrade coffee, soup, toasties, pancakes, cakes and scones'],
  ['curated-eat:aberdeen-cup','Cup Tea Salon',78,[-2.10175,57.14708],urls.cup,'Tea and homemade cake: A tea salon for brunch, homemade cakes, traybakes and afternoon tea.','opening_hours:description=Operator page lists daytime opening daily but currently displays conflicting closing times; confirm on the day; price_band=££; cuisine=Tea, brunch, homemade cakes, traybakes and afternoon tea'],
  ['curated-eat:aberdeen-gallery-cafes','Aberdeen Art Gallery Cafés',72,[-2.10262,57.1482],urls.galleryCafe,'Gallery coffee and homebakes: Convenient museum cafés serving coffee, homebakes, breakfast, brunch and light lunches.','opening_hours:description=Available during Aberdeen Art Gallery opening hours, Mon–Sat 10:00–17:00 and Sun 11:00–16:00; price_band=££; cuisine=Coffee, homebakes, breakfast, brunch and light lunches'],
];
const foods = foodSpecs.map(([id,name,score,coordinates,website,description,details])=>make({id,name,score,coordinates,website,featureType:'commercial_building',description,reason:'A current café-led choice suited to coffee, cake, baking, brunch or light lunch rather than a full evening-meal list.',evidenceUrls:[website],sourceName:name,sourceOrganisation:name,placeType:'Eat',details,category:'food',tags:['curated-visitor','service-context-food','visitor-context-food','current-context']}));
const parkingSpecs = [
 ['curated-parking:aberdeen-union-square-college-street','Union Square College Street Car Park',[-2.099,57.143],urls.unionSquare,'Ticketless ANPR car park; 2.1 m height limit, six accessible bays on level 6, card/contactless only, up to 24 hours £11 and evening rate £2.50 on the audited operator page.'],
 ['curated-parking:aberdeen-chapel-street','Chapel Street Car Park',[-2.1091,57.1456],urls.parking,'Council city-centre car park; 100 public weekday spaces were retained during refurbishment, with wider weekend availability. Current tariff, payment and bay signs must be checked on arrival.'],
 ['curated-parking:aberdeen-denburn','Denburn Car Park',[-2.1072747,57.1485247],urls.parking,'Council long-stay city-centre parking, open 24 hours with charging periods; capacity and accessible-bay count were not established from the current public listing.'],
 ['curated-parking:aberdeen-frederick-street','Frederick Street Car Park',[-2.092376,57.150493],urls.parking,'Council city-centre parking, open 24 hours with charging periods; verify current tariff, payment methods, maximum stay and accessible bays on arrival.'],
];
const parking = parkingSpecs.map(([id,name,coordinates,website,description])=>make({id,name,coordinates,website,featureType:'other',description,evidenceUrls:[website],sourceName:name,sourceOrganisation:id.includes('union-square')?'Union Square Aberdeen':'Aberdeen City Council',placeType:'Parking',details:'No unpublished capacity, accessible-bay count or payment detail has been inferred',tags:['service-context-parking','current-context']}));
const toiletSpecs = [
 ['curated-toilets:aberdeen-art-gallery','Aberdeen Art Gallery Toilets',[-2.102721,57.1481374],urls.galleryAccess,'Accessible visitor toilets and a Changing Places facility on level 2; available during gallery opening hours.'],
 ['curated-toilets:aberdeen-maritime-museum','Aberdeen Maritime Museum Toilets',[-2.0949554,57.1464845],urls.maritime,'Visitor toilets, accessible toilet and baby-changing provision; available during museum opening hours.'],
 ['curated-toilets:aberdeen-union-terrace','Union Terrace Gardens Toilets',[-2.1032638,57.1465325],urls.unionTerrace,'Public toilets included in the restored gardens; check current opening status at the site.'],
 ['curated-toilets:aberdeen-duthie-park','Duthie Park Toilets',[-2.1031544,57.1306317],urls.toilets,'Public park toilet provision; check the council’s live facility status before relying on it.'],
];
const toilets = toiletSpecs.map(([id,name,coordinates,website,description])=>make({id,name,coordinates,website,featureType:'toilets',description,evidenceUrls:[website],sourceName:name,sourceOrganisation:'Aberdeen City Council',placeType:'Public toilets',details:'Opening follows venue or park arrangements; live status should be checked',tags:['service-context-toilets','current-context']}));
const picnic = [make({id:'curated-picnic:aberdeen-duthie-park',name:'Duthie Park Picnic Lawns',coordinates:[-2.1027,57.131],website:urls.duthie,featureType:'park',description:'Spacious public lawns for an informal picnic; no fixed-table count was verified.',evidenceUrls:[urls.duthie],sourceName:'Duthie Park',sourceOrganisation:'VisitAberdeenshire',placeType:'Picnic',details:'Free outdoor picnic lawns; take litter away and observe park rules',tags:['service-context-picnic','current-context']})];

const auditedFeatures = [...heritage,...attractions.map(a=>a.feature).filter(f=>!heritage.includes(f)),...trails,...foods,...parking,...toilets,...picnic];
const auditedFeatureIds = new Set(auditedFeatures.map(feature=>feature.id));
pkg.features = [...auditedFeatures,...pkg.features.filter(feature=>feature.tags.some((tag:string)=>['hes-listed-building','hes-scheduled-monument'].includes(tag))&&!auditedFeatureIds.has(feature.id))];
const highlightTaglines = ['National art collection','Harbour and offshore story','Park and indoor gardens','Historic city stories','Hands-on family science','Restored city-centre gardens','Carved 1686 landmark'];
const highlights: VisitorHighlight[] = attractions.map((a,index)=>({rank:index+1,featureId:a.feature.id,name:a.feature.name,reason:a.reason,tagline:highlightTaglines[index],visitorScore:a.score,timeToSpend:a.time,openingTimes:a.opening,admission:a.admission,freeAdmission:a.admission==='Free',visitorWebsiteUrl:a.website,attractionGuide:a.guide,editorialReview:a.feature.editorialReview,sourceName:a.feature.sourceRecords[0].sourceName,sourceUrl:a.website,verifiedInBoundaryAt:reviewedDate}));
pkg.project.preferredBasemap='voyager';
pkg.project.boundary={type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[-2.124,57.134],[-2.106,57.127],[-2.098,57.129],[-2.093,57.139],[-2.079,57.146],[-2.079,57.157],[-2.093,57.159],[-2.116,57.157],[-2.124,57.134]]]}};
pkg.project.boundarySource='Explicit editorial Aberdeen city-core polygon: Old Aberdeen, Bridge of Don, Torry and other separately catalogued districts are excluded rather than used to inflate the city-centre audit'; pkg.project.boundaryConfidence='medium';
pkg.project.touristAppeal={score:94,dogOwnerScore:88,dogAccessScoreAdjustment:-6,rating:3,label:'Exceptional Destination',summary:'A major Scottish city break with nationally important museums, granite architecture, maritime heritage, parks, culture and a deep self-guided trail offer.',dogAccessRating:2,dogAccessSummary:'Excellent outdoor parks, public-realm trails and a dog-friendly commercial clue trail support a dog visit, but the principal indoor museums admit assistance dogs rather than ordinary pets.',methodVersion:'2026-08-27-strict-settlement-full-audit-v2',reviewedAt:reviewedDate,sourceUrls:Object.values(urls)};
pkg.project.visitorHighlights=highlights;
pkg.project.townGuide={characterTag:'Granite city, historic port and cultural capital',headline:'Scotland’s granite city rewards a full museum, architecture and park break',intro:'Aberdeen is a 94% Exceptional Destination on its own city-core merits. The audit keeps Old Aberdeen, Torry, Bridge of Don and other named districts in their own records, while concentrating here on the gallery, maritime story, historic civic centre, Duthie Park and proven self-guided trails.',bestFor:['Art and museums','Maritime and granite architecture','Coffee and cake','Parks and self-guided city trails'],perfectFor:['A full weekend city break','A museum-and-heritage day','A wet-weather cultural visit'],suggestedFirstVisit:{title:'Gallery, Castlegate and harbour',summary:'Begin at the Art Gallery, follow the granite civic core to Provost Skene’s House and the Castlegate, then descend to the Maritime Museum and harbour.'},dontMiss:['Aberdeen Art Gallery','Aberdeen Maritime Museum','Duthie Park and David Welch Winter Gardens','Provost Skene’s House'],suggestedTime:'1–2 full days',visitorMood:'A substantial urban destination with genuine national-level collections, dramatic granite streets and restorative green spaces.',practicalNote:'Four public or visitor toilet locations, four parking options and Duthie Park picnic lawns are recorded. Unpublished parking capacities, accessible bay counts or payment methods are explicitly left unknown.',transportNote:'Rail and bus stations at Union Square make the audited city core practical without a car.',accessibilityNote:'Major museums publish access information; historic streets and older buildings vary, while restored Union Terrace Gardens provides step-free routes.',sourceUrls:Object.values(urls),lastReviewedAt:reviewedDate};
planner.projects[projectId]={eat:foods.map(f=>f.id),trails:trails.map(f=>f.id),parking:parking.map(f=>f.id),toilets:toilets.map(f=>f.id),picnic:picnic.map(f=>f.id)};
const dogRecord=(rating:number,status:string,label:string,summary:string,sourceUrl:string)=>({rating,status,label,summary,sourceName:'Aberdeen dog-access audit',sourceUrl,reviewedAt:reviewedDate});
dog.reviewedAt=reviewedDate; dog.projects[projectId]={
 attraction:Object.fromEntries(attractions.map(a=>[a.feature.id,a.feature.id.includes('duthie')?dogRecord(3,'welcoming','Strong outdoor dog visit','Dogs can use the extensive outdoor park under normal close-control rules; do not assume access to every indoor area.',urls.dogCode):a.feature.id.includes('union-terrace')||a.feature.id.includes('LB19999')?dogRecord(2,'restricted','Outdoor public realm with close control','Suitable for dogs on public routes, with close control around crowds, roads and planted areas.',urls.dogCode):dogRecord(0,'restricted','Assistance dogs only indoors','The principal indoor visitor experience does not publish ordinary pet-dog admission; assistance dogs are accommodated.',a.website)])),
 trail:Object.fromEntries(trails.map(f=>[f.id,f.id.includes('treasure')?dogRecord(3,'welcoming','Provider marks this trail dog friendly','The provider explicitly marks the outdoor clue trail dog friendly; keep dogs close on urban streets.',urls.treasure):dogRecord(2,'restricted','Urban trail with close control','Dogs can accompany the public route, subject to ordinary close-control rules beside roads, harbour edges, wildlife and crowds.',urls.dogCode)])),
 eat:{[foods[0].id]:dogRecord(1,'unknown','Current pet policy not established','No dependable first-party pet-dog policy was found; confirm before entering.',urls.foodstory),[foods[1].id]:dogRecord(2,'restricted','Secondary sources report dog welcome','A current operator statement was not located; confirm the reported pet-dog welcome before travel.',urls.booksBeans),[foods[2].id]:dogRecord(2,'restricted','Dog friendly reported, confirm first','A specialist local listing reports dog-friendly access, but confirm with the salon before travel.',urls.cup),[foods[3].id]:dogRecord(0,'restricted','Assistance dogs only in gallery','Ordinary pet dogs should not be assumed inside the gallery café.',urls.galleryAccess)}
};
pkg.validation=validateFeatures(pkg.project,pkg.features); const errors=pkg.validation.filter((v:any)=>v.severity==='error'); if(errors.length) throw new Error(`Aberdeen audit validation errors: ${errors.map((e:any)=>e.message).join('; ')}`);
const visibleHistoric=pkg.features.filter(f=>f.tags.some((t:string)=>['hes-listed-building','hes-scheduled-monument'].includes(t))&&!f.tags.includes('map-hidden'));
const undated=visibleHistoric.filter(f=>!f.documentedDateText?.trim()||f.earliestPossibleYear==null||f.latestPossibleYear==null||f.dateBasis==='unknown'); if(undated.length) throw new Error(`Undated Aberdeen historic pins: ${undated.map(f=>f.id).join(', ')}`);
await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`,'utf8'); await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`,'utf8'); await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`,'utf8');
await writeFile(reportPath,`${JSON.stringify({reviewedAt,townScore:94,dogOwnerScore:88,dogAccessRating:2,publicationRule:'Only independently assessed 60+ attractions, trails and café-led food places are published.',categoryCounts:{see:highlights.length,eat:foods.length,trails:trails.length,picnic:picnic.length,parking:parking.length,toilets:toilets.length,heritage:visibleHistoric.length},heritageDateAudit:{visiblePins:visibleHistoric.length,dated:visibleHistoric.length-undated.length,undated:undated.map(f=>f.id),dateRule:'Construction dates and periods are taken from HES descriptions; designation dates are never substituted.'},trailProviderSearches:[{provider:'TreasureTrails.co.uk',result:'Exact Aberdeen City Centre and Castlegate trail found and linked.'},{provider:'Aberdeen City Council',result:'Granite, Maritime and Green heritage trail PDFs found and linked.'},{provider:'Nuart Aberdeen',result:'Current street-art trail guide found and linked.'},{provider:'Curious About',result:'No exact current Aberdeen product established.'},{provider:'Mystery Guides',result:'No exact current Aberdeen product established.'},{provider:'Go Quest Adventures',result:'No exact current Aberdeen product established.'}],parking:parking.map(f=>({name:f.name,detail:f.shortDescription,source:f.visitorWebsiteUrl})),toilets:toilets.map(f=>({name:f.name,detail:f.shortDescription,source:f.visitorWebsiteUrl})),picnic:picnic.map(f=>({name:f.name,detail:f.shortDescription,source:f.visitorWebsiteUrl})),boundaryExclusions:['Old Aberdeen','Bridge of Don','Torry','Footdee and separately catalogued districts'],verification:{heritagePinsDated:`${visibleHistoric.length-undated.length}/${visibleHistoric.length}`,undatedHistoricPins:undated.length}},null,2)}\n`,'utf8');
console.log(`Aberdeen full audit complete: ${highlights.length} See, ${foods.length} Eats, ${trails.length} Trails, ${picnic.length} Picnic, ${parking.length} Parking, ${toilets.length} Toilets; ${visibleHistoric.length-undated.length}/${visibleHistoric.length} historic pins dated.`);
