import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const reviewedAt = '2026-08-26T11:00:00.000Z';
const reviewedDate = '2026-08-26';
const projectPath = resolve('data/projects/cellardyke.json');
const plannerPath = resolve('data/east-neuk-visitor-planner-curation.json');
const dogPath = resolve('data/east-neuk-dog-access-curation.json');
const project = JSON.parse(await readFile(projectPath, 'utf8')) as ProjectPackage;

// Make the audit safe to rerun without stacking duplicate editorial source records.
for (const item of project.features) {
  item.sourceRecords = item.sourceRecords.filter((record) => record.accessedAt !== reviewedAt);
}
if (project.project.townStudyArea?.bufferedBoundary && !project.project.townStudyArea.visitorBoundary) {
  project.project.townStudyArea.visitorBoundary = {
    ...project.project.townStudyArea.bufferedBoundary,
    properties: {
      ...project.project.townStudyArea.bufferedBoundary.properties,
      visitorBoundary: true,
      sourceDataset: 'Cellardyke conservation area with reviewed 300m visitor buffer',
    },
  };
}

const harbourUrl = 'https://www.fife.gov.uk/facilities/harbours/cellardyke-harbour-skinfast-haven';
const poolUrl = 'https://www.cellardyketidalpool.com/services-4';
const saunaUrl = 'https://scottishseasidesaunas.com/locations/cellardyke/';
const outdoorsUrl = 'https://eastneukoutdoors.co.uk/';
const outdoorsLicenceUrl = 'https://aala.hse.gov.uk/aala/provider_detail.php?ref_no=R2391';
const boardsUrl = 'https://www.cellardyke.org/';
const galleryUrl = 'https://www.cellardyketrust.org/cellardyke-phone-boxes/gallery-495-cellardyke-cellardyke-harbour-phone-box/';
const coastalPathUrl = 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/';
const walkStageUrl = 'https://www.walkhighlands.co.uk/Forum/viewtopic.php?f=9&t=119484';
const havenUrl = 'https://www.havencommunityinn.co.uk/';
const amenitiesUrl = 'https://cellardyke.org/local-amenities/';
const havenHoursUrl = 'https://www.tripadvisor.co.uk/Restaurant_Review-g4764106-d1500868-Reviews-The_Haven_Cellardyke-Cellardyke_Fife_Scotland.html';
const barnettHoursUrl = 'https://www.bizseek.co.uk/barnetts-bakery_3y-01333-310205';
const fortuneHoursUrl = 'https://restaurantguru.com/Fortune-House-Cellardyke';
const parkingUrl = 'https://www.fife.gov.uk/roads-travel-parking/parking-and-car-parks/car-park-list';
const parkingArcGisUrl = 'https://arcgis-live-as.fife.gov.uk/server/rest/services/Assets_CarParking/MapServer/0';
const toiletsUrl = 'https://www.fife.gov.uk/facilities/public-toilet/public-toilets';
const outdoorCodeUrl = 'https://www.outdooraccess-scotland.scot/dog-owners';

function feature(id: string): HeritageFeature {
  const found = project.features.find((item) => item.id === id);
  if (!found) throw new Error(`Missing Cellardyke feature ${id}`);
  return found;
}

function source(sourceName: string, sourceOrganisation: string, sourceUrl: string, notes: string, reliability: 'official_statutory' | 'official_non_statutory' | 'local_authority' | 'secondary' = 'secondary') {
  return { sourceName, sourceOrganisation, sourceUrl, accessedAt: reviewedAt, licence: 'Source-linked editorial record; verify current visitor information before travel.', notes, reliability };
}

function upsert(item: HeritageFeature): HeritageFeature {
  project.features = project.features.filter((existing) => existing.id !== item.id).concat(item);
  return item;
}

function currentFeature(id: string, name: string, featureType: HeritageFeature['featureType'], coordinates: [number, number], shortDescription: string, sources: HeritageFeature['sourceRecords'], tags: string[]): HeritageFeature {
  return {
    id, projectId: project.project.id, name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Fife', locality: 'Cellardyke', featureType, significance: 'local',
    geometry: { type: 'Point', coordinates }, locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact',
    shortDescription, sourceRecords: sources, licence: 'Source-linked editorial record; map location may include OpenStreetMap-derived discovery evidence.', tags: [...new Set(['current-context', ...tags])],
    createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence', reviewNotes: 'Current visitor-place record researched in the 2026-08-26 Cellardyke full audit.',
  };
}

const harbour = feature('curated-attraction:cellardyke-1');
Object.assign(harbour, {
  name: 'Cellardyke Harbour (Skinfast Haven)', featureType: 'harbour', significance: 'national',
  documentedDateText: 'Harbour origins traditionally dated to 1452; major 19th-century rebuilding', earliestPossibleYear: 1452, latestPossibleYear: 1452, dateBasis: 'estimated_from_authoritative_source', dateConfidence: 'medium',
  shortDescription: 'The tight stone basin of Skinfast Haven, framed by close-built fishing houses and the black-net-drying dykes that define Cellardyke.',
  fullDescription: 'Cellardyke Harbour is the compact historic core of the former fishing burgh. The community’s interpretation records medieval origins associated with Bishop Kennedy, later rebuilding and the harbour’s role as workplace, meeting place and centre of a village whose houses and lanes turn closely around the shore.',
  sourceRecords: [source('Cellardyke Harbour', 'Fife Council', harbourUrl, 'Official current harbour record confirms Cellardyke Harbour, also known as Skinfast Haven, at Shore Street.', 'local_authority'), source('Cellardyke historical boards', 'Cellardyke community researchers', boardsUrl, 'Community-authored interpretation documents the harbour, fishing industry, black dykes, houses and seafaring history.', 'secondary')],
  visitorWebsiteUrl: harbourUrl, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Researched as a free open-air historic harbour. Working edges and water require normal care.',
  attractionGuide: { headline: 'The stone heart of an old fishing burgh', intro: 'Walk the small basin, read the harbour boards and look back into the close-set Shore Street houses.', bestFor: ['Fishing heritage', 'Harbour photography', 'Historic townscape', 'A short coastal stop'], parking: 'George Street, James Street and John Street each provide seven free council spaces. George Street is the closest but the approach is very narrow.', toilets: 'The nearest verified public toilet block is beside the tidal pool, about 650 metres east; opening times are not published.', picnic: 'Picnic tables stand beside the tidal pool; the harbour itself has limited sitting space.', foodNote: 'The Haven is beside the harbour; The Grind is beside the tidal pool.', trails: [{ name: 'Cellardyke Historical Boards Walk', summary: 'Use six community interpretation boards to trace the harbour, town hall, fishing industry, Toon’s Green and windmill story.', routeType: 'Self-guided heritage walk', duration: '45–75 minutes', difficulty: 'Easy village streets, with some narrow pavements and gradients.', externalUrl: boardsUrl }], thingsToDo: [{ name: 'Read the harbour boards', summary: 'Trace Skinfast Haven’s evolution and working fishing history.' }, { name: 'Find the black dykes', summary: 'Look for the walls once used to dry barked and tarred nets.' }, { name: 'Walk Shore Street', summary: 'Notice how houses, closes and harbour walls form one compact townscape.' }] },
});

const pool = feature('curated-attraction:cellardyke-2');
Object.assign(pool, {
  name: 'Cellardyke Tidal Pool', featureType: 'other', significance: 'regional', documentedDateText: 'Built in the 1930s; community restoration led from 2019', earliestPossibleYear: 1930, latestPossibleYear: 1939, dateBasis: 'estimated_from_authoritative_source', dateConfidence: 'medium',
  shortDescription: 'A restored open-air seawater pool facing the Isle of May, usable across the tidal cycle when sea and weather conditions are safe.',
  fullDescription: 'The Cardinal Steps bathing pool was created by local improvement fundraising in the 1930s and revived through a community-led restoration campaign. The pool can be used at any tide in suitable conditions, but high water and rough seas can cover the hardstanding; cold water, slippery rock, jellyfish and the no-diving rule all matter.',
  sourceRecords: [source('Cellardyke Tidal Pool visit and safety information', 'Cellardyke Tidal Pool Community Interest Company', poolUrl, 'Current safety guidance confirms all-tide swimming in suitable conditions, no diving, slippery rock and stone, cold-water risk and unsafe hardstanding at high or rough water.', 'official_non_statutory'), source('The Toon’s Green historical board', 'Cellardyke community researchers', 'https://www.cellardyke.org/interpretation-boards/board-5-the-toons-green/', 'Community history dates the Cardinal Steps Bathing Pool to the 1930s and documents its role in the Sea Queen Festival.', 'secondary')],
  visitorWebsiteUrl: poolUrl, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'High-value free coastal experience; score includes strong distinctiveness and restored presentation, tempered by weather, cold-water and accessibility constraints.',
  attractionGuide: { headline: 'A restored sea pool with an Isle of May horizon', intro: 'Come for the coastal setting even if you do not swim; swimmers must judge tide, swell, temperature and their own ability.', bestFor: ['Sea swimming', 'Sunrise and sunset', 'Coastal views', 'Sauna pairing'], parking: 'The three council car parks provide 21 spaces in total, but summer demand is high and the final roads are narrow. Car sharing is advised.', toilets: 'A public toilet block is mapped just north-west of the pool and corroborated by the sauna operator; no current opening hours or charge are published.', picnic: 'Three mapped picnic tables stand beside the pool.', foodNote: 'The Grind serves hot drinks and snacks nearby; summer wood-fired pizza is advertised by the sauna operator.', trails: [{ name: 'Fife Coastal Path: Cellardyke to Crail', summary: 'Continue east past the pool on the signed coast path towards Caiplie Caves and Crail.', routeType: 'Linear coastal walk', distance: 'About 6.75 km / 4.25 miles', duration: 'About 2–2½ hours one way', difficulty: 'Coastal surfaces and exposed sections; check weather and route notices.', externalUrl: coastalPathUrl }], thingsToDo: [{ name: 'Swim only in safe conditions', summary: 'Read the current pool safety guidance before entering the water.' }, { name: 'Pair a swim with the sauna', summary: 'Book the neighbouring wood-fired sauna separately.' }, { name: 'Watch the Forth', summary: 'Use the open outlook for seabirds, changing light and Isle of May views.' }] },
});

const streets = feature('curated-attraction:cellardyke-3');
Object.assign(streets, {
  name: 'Cellardyke Historic Streets and Boards', featureType: 'street', significance: 'regional', documentedDateText: 'Fishing-burgh townscape chiefly 16th–19th century', earliestPossibleYear: 1500, latestPossibleYear: 1899, dateBasis: 'estimated_from_authoritative_source', dateConfidence: 'medium',
  shortDescription: 'A six-board self-guided circuit through Shore Street, the town hall, harbour, Toon’s Green and windmill story.',
  fullDescription: 'Cellardyke’s close-built historic core is best understood on foot. Six community interpretation boards connect James Street, the town hall, both sides of the harbour, Toon’s Green and the windmill story, explaining the fishing industry, seafaring families, black dykes and development of the former burgh.',
  sourceRecords: [source('Cellardyke historical boards', 'Cellardyke community researchers', boardsUrl, 'Current six-board heritage resource: James Street, Town Hall, Harbour West, Harbour East, Toon’s Green and Windmill.', 'secondary'), source('Cellardyke Conservation Area Appraisal', 'Fife Council', 'https://www.fife.gov.uk/__data/assets/pdf_file/0029/155909/Cellardyke-Conservation-Area-Appraisal-and-Management-Plan.pdf', 'Official appraisal documents the street pattern, architecture, harbour interpretation and special historic character.', 'local_authority')],
  visitorWebsiteUrl: boardsUrl, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Published above 60 as an interpreted historic-townscape experience, not merely attractive streets.',
  attractionGuide: { headline: 'Six boards turn the old lanes into a readable story', intro: 'Follow the community’s interpretation points and use the linked site for deeper accounts at each stop.', bestFor: ['Local history', 'Fishing heritage', 'Architecture', 'A free village walk'], parking: 'Use the three small council car parks; do not rely on finding kerb space in the narrow historic core.', toilets: 'Public toilets are beside the tidal pool, not in the central lanes.', picnic: 'Continue to the tidal-pool picnic tables for an outdoor break.', foodNote: 'The Haven, Barnett Bakery and Fortune House provide local options; check current hours.', trails: [{ name: 'Cellardyke Historical Boards Walk', summary: 'A flexible six-stop heritage circuit through the old burgh.', routeType: 'Self-guided heritage trail', duration: '45–75 minutes', difficulty: 'Easy urban walking; narrow pavements and some gradients.', externalUrl: boardsUrl }], thingsToDo: [{ name: 'Start at James Street', summary: 'Follow the board sequence east through the old burgh.' }, { name: 'Read the town hall and Mercat Cross', summary: 'Connect the fishing settlement with its civic history.' }, { name: 'Finish at Toon’s Green', summary: 'End with the tidal pool, war memorial and sea-facing story.' }] },
});

const outdoors = upsert(currentFeature('curated-attraction:cellardyke-east-neuk-outdoors', 'East Neuk Outdoors', 'other', [-2.68261, 56.22584], 'A licensed family-run activity centre offering kayaking, canoeing, SUP, archery, climbing, bushcraft and bookable group sessions.', [source('East Neuk Outdoors', 'East Neuk Outdoors', outdoorsUrl, 'Current operator site confirms bookable come-and-try, half-day, full-day and multi-day outdoor activities.', 'official_non_statutory'), source('Adventure Activities Licensing Service record R2391', 'Health and Safety Executive', outdoorsLicenceUrl, 'Licence L165348 was issued 15 July 2025 and expires 14 July 2028; covered activities include canoeing, kayaking, SUP, off-road cycling and trekking.', 'official_statutory')], ['curated-visitor-attraction', 'town-selection-inside-locality']));
Object.assign(outdoors, { visitorWebsiteUrl: outdoorsUrl, attractionGuide: { headline: 'Book a coached coastal adventure', intro: 'Choose a come-and-try or longer coached session from a broad programme of water and land activities.', bestFor: ['Families', 'Kayaking and SUP', 'Active days', 'Small groups'], parking: 'Use the centre’s visit directions and allow time; nearby public capacity is small.', toilets: 'Confirm session facilities when booking; the public pool toilet block is nearby.', picnic: 'Pool-side picnic tables are close to the activity area.', foodNote: 'The Grind is the nearest casual food and drink stop.', trails: [], thingsToDo: [{ name: 'Try a watersport', summary: 'Kayaking, canoeing and SUP sessions are core licensed activities.' }, { name: 'Choose a land activity', summary: 'Options include archery, climbing, bushcraft and team challenges.' }, { name: 'Book before travelling', summary: 'Activities are organised sessions rather than a walk-in attraction.' }] } });

const sauna = upsert(currentFeature('curated-attraction:cellardyke-seaside-sauna', 'Cellardyke Seaside Sauna', 'other', [-2.68005, 56.22805], 'A bookable wood-fired sauna beside the tidal pool, with floor-to-ceiling sea views and individual or private sessions.', [source('Cellardyke Seaside Sauna', 'Scottish Seaside Saunas', saunaUrl, 'Current operator information: £16 individual seat, £96 private hire, one-hour sessions, capacity six, wood-fired 70–100°C, online booking and no indoor changing facilities.', 'official_non_statutory')], ['curated-visitor-attraction', 'town-selection-inside-locality']));
Object.assign(sauna, { visitorWebsiteUrl: saunaUrl, attractionGuide: { headline: 'Wood-fired heat beside the restored sea pool', intro: 'Book a one-hour seat or private session and bring swimwear, two towels, water and beach shoes.', bestFor: ['Cold-water swimmers', 'Wellness', 'Sea views', 'Small groups'], parking: 'Parking is limited and the approach roads are narrow or steep; the operator asks visitors to car share and arrive early.', toilets: 'Public toilets are nearby, but there are no internal changing rooms or showers.', picnic: 'Pool-side picnic tables are nearby.', foodNote: 'The Grind serves hot drinks and snacks behind the sauna; summer pizza may also operate.', trails: [], thingsToDo: [{ name: 'Book an individual seat', summary: 'One-hour community sessions cost £16.' }, { name: 'Reserve private hire', summary: 'Private sessions start at £96 for up to six people.' }, { name: 'Combine sauna and pool', summary: 'Use the pool only when sea and weather conditions are safe.' }] } });

const gallery = feature('osm-community:node-9445996008');
Object.assign(gallery, { name: 'Gallery 495', featureType: 'art_gallery', significance: 'local', shortDescription: 'A changing contemporary-art display inside the former red telephone box beside Cellardyke Harbour.', fullDescription: 'Gallery 495 makes a very small but distinctive public-art stop from a redundant harbour telephone box. The Cellardyke Trust publishes the changing programme; the 2026 display featured new work responding to East Neuk coastal forms and ecology.', visitorWebsiteUrl: galleryUrl, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Published at 63 as a genuinely distinctive, free micro-gallery, with its very short visit depth reflected in the score.', sourceRecords: [...gallery.sourceRecords, source('Gallery 495 current programme', 'The Cellardyke Trust', galleryUrl, 'Current 2026 exhibition programme confirms the harbour phone-box gallery and changing artist displays.', 'official_non_statutory')], tags: [...new Set([...gallery.tags, 'curated-visitor-attraction'])], attractionGuide: { headline: 'A harbour phone box turned micro-gallery', intro: 'Pause for the current display while walking between the harbour and Toon’s Green.', bestFor: ['Contemporary art', 'Quirky discoveries', 'A five-minute stop', 'Free culture'], parking: 'Use George Street car park or visit as part of the harbour walk.', toilets: 'Nearest verified public toilets are beside the tidal pool.', picnic: 'Continue east to the pool-side picnic tables.', foodNote: 'The Haven is beside the harbour.', trails: [], thingsToDo: [{ name: 'See the current installation', summary: 'The programme changes, so check the Trust page for the latest artist.' }, { name: 'Pair it with the heritage boards', summary: 'The gallery sits naturally on the harbour-to-Toon’s Green walk.' }] } });

const coastalTrail = feature('curated-trail:cellardyke-fife-coastal-path');
Object.assign(coastalTrail, { name: 'Fife Coastal Path: Cellardyke to Crail', shortDescription: 'A signed coastal walk of about 6.75 km linking Cellardyke’s tidal pool with Caiplie Caves and Crail.', visitorWebsiteUrl: coastalPathUrl, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Official route network combined with a current stage description for useful distance and duration.', sourceRecords: [source('Fife Coastal Path', 'Fife Coast & Countryside Trust', coastalPathUrl, 'Current official route hub; check live notices before setting out.', 'official_non_statutory'), source('Crail to Anstruther walk stage', 'Walkhighlands community report', walkStageUrl, 'Published stage distance 6.75 km / 4.25 miles and confirms passage through Cellardyke and Caiplie Caves.', 'secondary'), source('Cellardyke coastal-path curation', 'Townscape Guides editorial audit', coastalPathUrl, 'Current-place curation: visitor_place_type=Walking route; trail_score=82; trail_type=Linear coastal walk; distance=6.75 km / 4.25 miles; time_to_spend=2–2.5 hours one way; accessibility=Coastal surfaces and exposed sections; check weather and official route notices; entrance_fee=Free; description=Signed coast path from Cellardyke tidal pool towards Caiplie Caves and Crail.', 'secondary')], tags: [...new Set([...coastalTrail.tags, 'service-context-trail', 'visitor-context-trail'])], editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A nationally recognised signed route with a highly scenic and useful village-to-village stage, clear distance and strong onward transport options.', evidenceUrls: [coastalPathUrl, walkStageUrl] } });

const boardTrail = upsert(currentFeature('curated-trail:cellardyke-historical-boards', 'Cellardyke Historical Boards Walk', 'walking_route', [-2.68860, 56.22458], 'A flexible six-stop heritage walk linking James Street, the town hall, harbour, Toon’s Green and windmill story.', [source('Cellardyke historical boards', 'Cellardyke community researchers', boardsUrl, 'Current-place curation: visitor_place_type=Walking route; trail_score=74; trail_type=Self-guided heritage walk; time_to_spend=45–75 minutes; accessibility=Village streets with narrow pavements and some gradients; entrance_fee=Free; app=Mobile web interpretation; app_note=Six physical boards link to expanded online stories; offline_after_download=No; description=Six community-authored boards explain Cellardyke’s fishing, civic and seafaring history.', 'secondary')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(boardTrail, { visitorWebsiteUrl: boardsUrl, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A real six-stop local interpretation trail with physical boards and deeper mobile web content; reduced because no formal distance, GPX or offline app is published.', evidenceUrls: [boardsUrl] } });

function curateFood(item: HeritageFeature, name: string, score: number, notes: string, website: string, foodAssessment: NonNullable<HeritageFeature['editorialReview']>['foodAssessment'], openingTimes: string, cuisine: string, priceBand: '£' | '££' | '£££', evidenceUrl = website, coordinates?: [number, number]) {
  item.name = name;
  if (coordinates) item.geometry = { type: 'Point', coordinates };
  item.shortDescription = notes;
  item.visitorWebsiteUrl = website;
  item.reviewed = true;
  item.updatedAt = reviewedAt;
  item.tags = [...new Set([...item.tags, 'service-context-food', 'visitor-context-food', 'current-context'])];
  item.sourceRecords.push(source(`${name} visitor curation`, 'Townscape Guides source audit', evidenceUrl, `Current daytime food curation: visitor_place_type=${item.featureType === 'restaurant' ? 'Restaurant' : 'Cafe'}; food_score=${score}; visit_score=${score}; price_band=${priceBand}; opening_hours:description=${openingTimes}; cuisine=${cuisine}; description=${notes}`, 'secondary'));
  item.editorialReview = { status: 'editorially_researched', category: 'food', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: notes, evidenceUrls: [website, evidenceUrl, amenitiesUrl], foodAssessment };
  return item;
}

const haven = curateFood(feature('osm-community:node-2803322114'), 'The Haven Bar & Restaurant', 78, 'Harbour pub and restaurant: British food, drinks and a beer garden beside Skinfast Haven.', havenUrl, { foodAndDrinkQuality: 25, daytimeRelevance: 15, distinctiveness: 10, consistency: 13, visitorFit: 8, evidenceConfidence: 7 }, 'Mon–Sat 12:00–23:45; Sun 12:30–23:45', 'British pub food', '££', havenHoursUrl);
const fortune = curateFood(feature('osm-community:node-9444627426'), 'Fortune House', 63, 'Evening Chinese takeaway: A straightforward local collection and delivery option on John Street.', amenitiesUrl, { foodAndDrinkQuality: 20, daytimeRelevance: 8, distinctiveness: 7, consistency: 12, visitorFit: 10, evidenceConfidence: 6 }, 'Daily 16:30–22:00', 'Chinese takeaway', '££', fortuneHoursUrl);
const grind = upsert(curateFood(currentFeature('curated-food:cellardyke-the-grind', 'The Grind', 'cafe', [-2.6798078, 56.2286513], 'An outdoor Airstream coffee and snack stop beside the tidal pool, with seasonal wood-fired pizza advertised on site.', [source('Cellardyke Seaside Sauna food and drink information', 'Scottish Seaside Saunas', saunaUrl, 'Operator confirms The Grind serves hot drinks and snacks behind the sauna, with summer wood-fired pizza.', 'official_non_statutory')], ['service-context-food', 'visitor-context-food']), 'The Grind', 82, 'Poolside Airstream: Coffee, hot drinks and snacks naturally paired with a swim, sauna or coastal walk.', saunaUrl, { foodAndDrinkQuality: 24, daytimeRelevance: 18, distinctiveness: 13, consistency: 11, visitorFit: 9, evidenceConfidence: 7 }, 'Outdoor daytime counter; summer pizza is seasonal', 'Coffee, snacks and seasonal pizza', '£'));
const barnett = upsert(curateFood(currentFeature('curated-food:cellardyke-barnett-bakery', 'G. H. Barnett Bakery', 'commercial_building', [-2.69196, 56.22431], 'A traditional local bakery on Rodger Street for pies, sausage rolls, bread and takeaway provisions.', [source('Cellardyke local amenities', 'Cellardyke community website', amenitiesUrl, 'Current community amenities list confirms G. H. Barnett Bakery at 35 Rodger Street.', 'secondary')], ['service-context-food', 'visitor-context-food']), 'G. H. Barnett Bakery', 68, 'Traditional village bakery: Pies, sausage rolls, bread and simple takeaway provisions.', amenitiesUrl, { foodAndDrinkQuality: 22, daytimeRelevance: 14, distinctiveness: 8, consistency: 10, visitorFit: 8, evidenceConfidence: 6 }, 'Mon–Sat 08:00–16:00; closed Sun', 'Bakery', '£', barnettHoursUrl));

const parkingSpecs = [
  ['osm-community:way-1065294255', 'George Street Car Park', 'KY10 3AU', 'No', -2.685401, 56.2245842],
  ['osm-community:way-685977007', 'James Street Car Park', 'KY10 3AY', 'No', -2.6915114, 56.2228789],
  ['osm-community:way-685977008', 'John Street Car Park', 'KY10 3BB', 'Council facility record flags accessible access, but the inventory records zero dedicated accessible spaces', -2.6869055, 56.2238898],
] as const;
for (const [id, name, postcode, accessibleNote] of parkingSpecs) {
  const item = feature(id);
  Object.assign(item, { name, shortDescription: `A free Fife Council surface car park with seven standard spaces. ${accessibleNote === 'No' ? 'No dedicated accessible, coach or motorcycle spaces are recorded.' : accessibleNote + '.'}`, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Official Fife Council inventory checked for capacity, ownership, surface and fee status; no payment is required because the car park is free.', tags: [...new Set([...item.tags, 'service-context-parking', 'visitor-context-parking'])] });
  item.sourceRecords.push(source('Fife Council car-park inventory', 'Fife Council', parkingArcGisUrl, `Current-place curation: visitor_place_type=Parking; operator=Fife Council; parking=surface; capacity=7; capacity:disabled=0; capacity:charging=0; coach_spaces=0; motorcycle_spaces=0; charge=Free; price_display=Free; payment_required=No payment required; payment_methods=None; surface=Tarmac; postcode=${postcode}; opening_hours:description=No restriction published in the council inventory; confidence=Official council inventory.`, 'local_authority'));
}

const toilet = feature('osm-community:way-361665173');
Object.assign(toilet, { name: 'Cellardyke Tidal Pool Public Toilets', shortDescription: 'A public toilet block beside the tidal pool, corroborated by the sauna operator. Opening hours, charge and accessible specification are not currently published.', reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Published because its physical presence is corroborated by the current pool-side operator. Fife Council’s main public-toilet list does not currently include a Cellardyke entry, so operational details remain cautious.', tags: [...new Set([...toilet.tags, 'service-context-toilets', 'visitor-context-toilets'])], sourceRecords: [...toilet.sourceRecords, source('Cellardyke Seaside Sauna visitor information', 'Scottish Seaside Saunas', 'https://cellardykeseasidesauna.com/about/', 'Current-context curation: visitor_place_type=Public toilets; access=public; opening_hours:description=Not published; charge=Not published; wheelchair=Not published; description=Public toilet block a short distance from the sauna and tidal pool; no current council-list operational details.', 'official_non_statutory')] });
feature('osm-community:node-3134022496').tags = feature('osm-community:node-3134022496').tags.filter((tag) => !['service-context-toilets', 'visitor-context-toilets'].includes(tag));

for (const [id, number] of [['osm-community:node-3660871289', 'West'], ['osm-community:node-3660871290', 'Centre'], ['osm-community:node-3660871291', 'East']] as const) {
  const item = feature(id);
  item.name = `Cellardyke Tidal Pool Picnic Table – ${number}`;
  item.shortDescription = 'A mapped picnic table beside the tidal pool, sauna and coastal path.';
  item.reviewed = true;
  item.updatedAt = reviewedAt;
  item.tags = [...new Set([...item.tags, 'service-context-picnic', 'visitor-context-picnic'])];
}

const highlights: VisitorHighlight[] = [
  { rank: 1, featureId: pool.id, name: pool.name, reason: 'A restored and genuinely usable sea pool with a strong coastal setting, practical companion facilities and an active community programme.', visitorScore: 84, tagline: 'Restored Isle of May sea pool', timeToSpend: '30–90 minutes', openingTimes: 'Open-air site. Check tide, swell and weather; high or rough water can make the hardstanding unsafe.', admission: 'Free.', freeAdmission: true, visitorWebsiteUrl: poolUrl, sourceName: 'Cellardyke Tidal Pool CIC', sourceUrl: poolUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A distinctive restored sea-bathing experience with strong presentation and companion facilities, reduced for weather dependence and physical access constraints.', evidenceUrls: [poolUrl, saunaUrl], attractionAssessment: { experienceDepth: 28, distinctiveness: 18, presentation: 17, journeyWorth: 12, accessAndReliability: 5, evidenceConfidence: 4, visitability: 'full_visitor_experience' } } },
  { rank: 2, featureId: outdoors.id, name: outdoors.name, reason: 'A broad, bookable activity offer backed by a current Adventure Activities Licence and qualified instruction.', visitorScore: 82, tagline: 'Bookable coastal adventures', timeToSpend: 'From a come-and-try session to a full day', openingTimes: 'Pre-booked sessions; programme varies by date and conditions.', admission: 'Paid activity sessions; individual prices are shown on the live booking page.', freeAdmission: false, visitorWebsiteUrl: outdoorsUrl, sourceName: 'East Neuk Outdoors and HSE AALA', sourceUrl: outdoorsUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'Strong activity depth, qualified delivery and bookable reliability; reduced because sessions need advance planning and the mapped point is postcode-representative.', evidenceUrls: [outdoorsUrl, outdoorsLicenceUrl], attractionAssessment: { experienceDepth: 29, distinctiveness: 16, presentation: 16, journeyWorth: 12, accessAndReliability: 5, evidenceConfidence: 4, visitability: 'full_visitor_experience' } } },
  { rank: 3, featureId: harbour.id, name: harbour.name, reason: 'A compact and unusually coherent historic fishing harbour with community interpretation woven into the surrounding townscape.', visitorScore: 78, tagline: 'Skinfast Haven and the black dykes', timeToSpend: '35–60 minutes', openingTimes: 'Open-air harbour; daylight visit recommended.', admission: 'Free.', freeAdmission: true, visitorWebsiteUrl: harbourUrl, sourceName: 'Fife Council and Cellardyke historical boards', sourceUrl: harbourUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'Strong townscape distinctiveness and historical interpretation, reduced because it is a small working open-air harbour rather than a managed attraction.', evidenceUrls: [harbourUrl, boardsUrl], attractionAssessment: { experienceDepth: 23, distinctiveness: 17, presentation: 17, journeyWorth: 12, accessAndReliability: 5, evidenceConfidence: 4, visitability: 'full_visitor_experience' } } },
  { rank: 4, featureId: sauna.id, name: sauna.name, reason: 'A polished, bookable wood-fired sauna experience directly paired with the restored tidal pool and open sea view.', visitorScore: 76, tagline: 'Wood-fired sauna above the pool', timeToSpend: 'One-hour session', openingTimes: 'Book online; session times vary.', admission: '£16 individual seat; private hire from £96.', freeAdmission: false, visitorWebsiteUrl: saunaUrl, sourceName: 'Scottish Seaside Saunas', sourceUrl: saunaUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A distinctive and well-presented bookable experience with transparent price and capacity, reduced for limited parking, lack of changing facilities and narrow audience.', evidenceUrls: [saunaUrl], attractionAssessment: { experienceDepth: 25, distinctiveness: 15, presentation: 16, journeyWorth: 10, accessAndReliability: 6, evidenceConfidence: 4, visitability: 'full_visitor_experience' } } },
  { rank: 5, featureId: streets.id, name: streets.name, reason: 'Six physical boards and deeper online stories turn the historic lanes into a coherent self-guided fishing-burgh experience.', visitorScore: 68, tagline: 'Six-stop fishing-burgh story', timeToSpend: '45–75 minutes', openingTimes: 'Public streets; best in daylight.', admission: 'Free.', freeAdmission: true, visitorWebsiteUrl: boardsUrl, sourceName: 'Cellardyke historical boards and Fife Council', sourceUrl: boardsUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A genuine interpreted townscape walk with distinctive local material, but modest infrastructure and no formal downloadable route.', evidenceUrls: [boardsUrl], attractionAssessment: { experienceDepth: 19, distinctiveness: 15, presentation: 14, journeyWorth: 9, accessAndReliability: 7, evidenceConfidence: 4, visitability: 'full_visitor_experience' } } },
  { rank: 6, featureId: gallery.id, name: gallery.name, reason: 'A changing contemporary-art programme gives the harbour phone box a tiny but memorable second life.', visitorScore: 63, tagline: 'Harbour phone-box gallery', timeToSpend: '5–15 minutes', openingTimes: 'Visible from the public realm; check the current programme online.', admission: 'Free.', freeAdmission: true, visitorWebsiteUrl: galleryUrl, sourceName: 'The Cellardyke Trust', sourceUrl: galleryUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'Very distinctive and current, but necessarily a micro-attraction with little visit depth.', evidenceUrls: [galleryUrl], attractionAssessment: { experienceDepth: 12, distinctiveness: 16, presentation: 14, journeyWorth: 8, accessAndReliability: 9, evidenceConfidence: 4, visitability: 'full_visitor_experience' } } },
];

project.project.visitorHighlights = highlights;
project.project.touristAppeal = { score: 78, dogOwnerScore: 74, dogAccessScoreAdjustment: -4, rating: 0, label: 'Notable Stop', summary: 'Cellardyke now supports a substantial half-day visit: a restored tidal pool, bookable sauna and outdoor activities reinforce an unusually coherent fishing-burgh harbour, interpreted lanes, local food and two real walking routes.', dogAccessRating: 2, dogAccessSummary: 'The harbour, historic streets and coast path work well with a controlled dog, but dog policies are not published for the pool, sauna, activity centre or gallery and indoor food access is limited or unconfirmed.', methodVersion: '2026-08-26-full-settlement-visitor-audit-v1', reviewedAt: reviewedDate, sourceUrls: [harbourUrl, poolUrl, saunaUrl, outdoorsUrl, boardsUrl, coastalPathUrl, parkingUrl, toiletsUrl, outdoorCodeUrl] };
project.project.townGuide = { characterTag: 'Fishing burgh, sea pool and active coast', headline: 'A working harbour village with a restored bathing culture', intro: 'Cellardyke is more than Anstruther’s eastern edge. Its tiny Skinfast Haven, black dykes and close-built lanes tell the fishing-burgh story, while the restored tidal pool, seaside sauna and East Neuk Outdoors make the eastern shore an active visitor hub.', bestFor: ['Sea swimming and sauna', 'Fishing heritage', 'Coastal walking', 'Outdoor activities'], perfectFor: ['A substantial half-day East Neuk visit', 'Visitors combining heritage with an outdoor activity'], suggestedFirstVisit: { title: 'Start at Skinfast Haven and walk east', summary: 'Read the harbour boards and Gallery 495, follow the historic lanes towards Toon’s Green, then finish at the tidal pool, sauna and The Grind.' }, dontMiss: ['Cellardyke Tidal Pool', 'East Neuk Outdoors', 'Cellardyke Harbour (Skinfast Haven)', 'Cellardyke Seaside Sauna', 'Cellardyke Historical Boards Walk'], suggestedTime: '3–5 hours; longer with a booked activity or the Crail coastal-path stage', visitorMood: 'A notably complete small coastal stop: intimate rather than grand, but with enough real experiences, food and walking to justify planning several hours.', sourceUrls: [harbourUrl, poolUrl, saunaUrl, outdoorsUrl, boardsUrl, galleryUrl, coastalPathUrl, havenUrl, amenitiesUrl, parkingUrl, toiletsUrl, outdoorCodeUrl], lastReviewedAt: reviewedDate };
project.project.visualIdentity = { theme: 'east-neuk-harbour', badgeImage: '/town-guides/cellardyke-harbour-watercolour-guide.png', badgeAlt: 'Watercolour illustration of Cellardyke’s compact stone harbour and close-built fishing houses', heroImage: '/town-guides/cellardyke-harbour-watercolour-guide.png', heroAlt: 'Watercolour illustration of Cellardyke’s compact stone harbour and close-built fishing houses', heroObjectPosition: '50% 56%', motifs: ['Skinfast Haven', 'Fishing burgh', 'Stone harbour', 'East Neuk coast'], primaryColour: '#17464A', accentColour: '#B27713', backgroundColour: '#EAF2F0' };

const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as { projects: Record<string, Record<string, string[]>> };
planner.projects[project.project.id] = { eat: [grind.id, haven.id, barnett.id, fortune.id], trails: [coastalTrail.id, boardTrail.id], parking: parkingSpecs.map(([id]) => id), toilets: [toilet.id], picnic: ['osm-community:node-3660871289', 'osm-community:node-3660871290', 'osm-community:node-3660871291'] };
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`, 'utf8');

const dog = JSON.parse(await readFile(dogPath, 'utf8')) as { reviewedAt: string; projects: Record<string, { attraction?: Record<string, unknown>; eat?: Record<string, unknown> }> };
dog.reviewedAt = reviewedDate;
dog.projects[project.project.id] = { attraction: {
  [pool.id]: { rating: 0, status: 'unconfirmed', label: 'Pool dog policy not published', summary: 'A current dog-swimming or poolside policy is not published. The surrounding coast can be visited with a controlled dog, but do not rely on dog access to the water.', sourceName: 'Cellardyke Tidal Pool safety information review', sourceUrl: poolUrl, reviewedAt: reviewedDate },
  [outdoors.id]: { rating: 0, status: 'unconfirmed', label: 'Activity dog policy not published', summary: 'A current participant dog policy is not published for the bookable activity programme. Confirm directly before bringing a dog to a session.', sourceName: 'East Neuk Outdoors current website review', sourceUrl: outdoorsUrl, reviewedAt: reviewedDate },
  [harbour.id]: { rating: 3, status: 'welcoming', label: 'Outdoor harbour walk', summary: 'Dogs can accompany the outdoor harbour and Shore Street walk under responsible-access rules. Keep them close beside working edges, traffic and open water.', sourceName: 'Fife Council harbour information and Scottish Outdoor Access Code', sourceUrl: outdoorCodeUrl, reviewedAt: reviewedDate },
  [sauna.id]: { rating: 0, status: 'unconfirmed', label: 'Sauna pet policy not published', summary: 'A current sauna pet policy is not published. Treat the booked sauna itself as unconfirmed even though the surrounding coast is an outdoor dog walk.', sourceName: 'Scottish Seaside Saunas current website review', sourceUrl: saunaUrl, reviewedAt: reviewedDate },
  [streets.id]: { rating: 3, status: 'welcoming', label: 'Outdoor heritage circuit', summary: 'The six-board experience uses public streets and the harbour. Keep dogs close on narrow pavements and beside traffic or working harbour edges.', sourceName: 'Cellardyke historical boards and Scottish Outdoor Access Code', sourceUrl: outdoorCodeUrl, reviewedAt: reviewedDate },
  [gallery.id]: { rating: 2, status: 'restricted', label: 'Outdoor micro-gallery stop', summary: 'The artwork is viewed from the public harbour side, so a dog can accompany the stop, but the tiny phone-box installation is not a space to enter with a dog.', sourceName: 'The Cellardyke Trust current programme review', sourceUrl: galleryUrl, reviewedAt: reviewedDate },
  [coastalTrail.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable coastal route', summary: 'Dogs can use the coast path under responsible-access rules, with close control required around livestock, wildlife, cliff or shore hazards and other path users.', sourceName: 'Fife Coastal Path and Scottish Outdoor Access Code', sourceUrl: outdoorCodeUrl, reviewedAt: reviewedDate },
  [boardTrail.id]: { rating: 3, status: 'welcoming', label: 'Outdoor village trail', summary: 'All six board stops are outdoors. Use a lead on narrow streets and beside traffic, the harbour and busy visitor areas.', sourceName: 'Cellardyke historical boards and Scottish Outdoor Access Code', sourceUrl: outdoorCodeUrl, reviewedAt: reviewedDate },
}, eat: {
  [grind.id]: { rating: 3, status: 'welcoming', label: 'Outdoor dog-friendly stop', summary: 'The Grind is an outdoor Airstream stop used by coastal walkers and local dog walkers; keep dogs controlled around food queues and the pool.', sourceName: 'Scottish Seaside Saunas and independent East Neuk dog-friendly guide review', sourceUrl: saunaUrl, reviewedAt: reviewedDate },
  [haven.id]: { rating: 2, status: 'restricted', label: 'Beer-garden access; check indoors', summary: 'Dog-friendly local guides support the beer-garden stop, while recent visitor information conflicts on indoor access. Use the outdoor area and confirm indoor policy directly.', sourceName: 'The Haven and current dog-friendly visitor source review', sourceUrl: havenUrl, reviewedAt: reviewedDate },
  [barnett.id]: { rating: 0, status: 'unconfirmed', label: 'Bakery pet policy not published', summary: 'A current bakery pet policy is not published; plan for one person to wait outside with the dog.', sourceName: 'Cellardyke amenities review', sourceUrl: amenitiesUrl, reviewedAt: reviewedDate },
  [fortune.id]: { rating: 0, status: 'unconfirmed', label: 'Restaurant pet policy not published', summary: 'A current dog policy is not published for the restaurant or takeaway. Confirm directly before relying on access.', sourceName: 'Cellardyke amenities review', sourceUrl: amenitiesUrl, reviewedAt: reviewedDate },
} };
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`, 'utf8');

project.validation = validateFeatures(project.project, project.features);
const errors = project.validation.filter((item) => item.severity === 'error');
if (errors.length) throw new Error(`Cellardyke audit introduced ${errors.length} validation errors: ${errors.map((item) => item.message).join('; ')}`);
await writeFile(projectPath, `${JSON.stringify(project, null, 2)}\n`, 'utf8');
await writeFile(resolve('data/review/cellardyke-full-visitor-audit-2026-08-26.json'), `${JSON.stringify({ reviewedAt, townScore: 78, dogOwnerScore: 74, publicationRule: 'visitor score > 60', attractions: highlights.map(({ name, visitorScore }) => ({ name, score: visitorScore, published: true })), trails: [{ name: coastalTrail.name, score: 82 }, { name: boardTrail.name, score: 74, treasureTrailsApp: 'No Cellardyke-specific Treasure Trails product verified; physical boards use mobile web interpretation.' }], facilities: { eat: [{ name: grind.name, score: 82 }, { name: haven.name, score: 78 }, { name: barnett.name, score: 68 }, { name: fortune.name, score: 63 }], parking: parkingSpecs.map(([, name, postcode, accessible]) => ({ name, postcode, spaces: 7, price: 'Free', payment: 'None required', accessibleSpaces: 0, accessibilityNote: accessible })), toilets: [{ name: toilet.name, hours: 'Not published', charge: 'Not published', accessible: 'Not published' }], picnic: ['Three tables beside the tidal pool'] }, dogAudit: { townAdjustment: -4, attractionPolicies: 'Two welcoming, two restricted, three unconfirmed plus two trails', foodPolicies: 'The Grind 3 paws; The Haven 2 paws; bakery and Fortune House unconfirmed' }, exclusions: ['No Cellardyke-specific Treasure Trails app product verified', 'Anstruther Scottish Fisheries Museum toilet excluded from Cellardyke facilities', 'Street and private parking without an official public-car-park record excluded', 'Memorials retained on the heritage map but below the >60 standalone visitor-experience threshold'] }, null, 2)}\n`, 'utf8');
console.log('Cellardyke audit complete: 6 attractions, 4 Eats, 2 trails, 3 official car parks, 1 public toilet block and 3 picnic tables.');
