import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const id = 'ferryhill-aberdeen-scotland';
const day = '2026-09-02';
const at = '2026-09-02T10:45:00Z';
const pp = resolve('data/projects/ferryhill-aberdeen.json');
const plp = resolve('data/aberdeen-north-visitor-planner-curation.json');
const dp = resolve('data/aberdeen-north-dog-access-curation.json');
const rp = resolve('data/review/ferryhill-aberdeen-full-visitor-audit-2026-09-02.json');
type F = HeritageFeature & Record<string, any>;
type P = ProjectPackage & { project: ProjectPackage['project'] & Record<string, any>; features: F[] };
const u = {
  duthie: 'https://visitabdn.com/businesses/duthie-park', duthieTrail: 'https://www.visitabdn.com/what-to-do/history-and-heritage/view/duthie-park-trail-and-guide', duthiePdf: 'https://www.visitabdn.com/assets/Duthie-Park-Trail.pdf',
  treasure: 'https://www.treasuretrails.co.uk/products/things-to-do-duthie-park-aberdeenshire', deeside: 'https://visitabdn.com/businesses/the-deeside-way', cafe: 'https://park-cafe.co.uk/gallery/',
  rail: 'https://frht.org.uk/', railHes: 'https://portal.historicenvironment.scot/designation/LB20617', toilets: 'https://committees.aberdeencity.gov.uk/documents/s7161/Public%20Toilet%20Review.pdf?txtonly=1', picnic: 'https://www.aberdeencity.gov.uk/news/city-plans-mark-queens-platinum-jubilee-duthie-park-family-picnic-and-city-centre-beacon',
  cityTrails: 'https://sites.aberdeencity.gov.uk/AAGM/local-history/heritage-trails', curious: 'https://curiousabout.co.uk/', mystery: 'https://www.mysteryguides.co.uk/pages/scotland', goQuest: 'https://goquestadventures.com/', dogCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
};
const p = JSON.parse(await readFile(pp, 'utf8')) as P;
const pl = JSON.parse(await readFile(plp, 'utf8')) as any;
const d = JSON.parse(await readFile(dp, 'utf8')) as any;
const src = (name: string, organisation: string, url: string, notes: string, reliability: any = 'official_non_statutory') => ({ sourceName: name, sourceOrganisation: organisation, sourceUrl: url, accessedAt: at, reliability, licence: 'Source-linked editorial evidence; verify time-sensitive details before travel.', notes });
const assess = (score: number) => ({ experienceDepth: Math.round(score * .27), distinctiveness: Math.round(score * .21), presentation: Math.round(score * .18), journeyWorth: Math.round(score * .14), accessAndReliability: Math.round(score * .12), evidenceConfidence: score - Math.round(score * .27) - Math.round(score * .21) - Math.round(score * .18) - Math.round(score * .14) - Math.round(score * .12), visitability: 'full_visitor_experience' as const });
const make = (spec: any): F => ({
  id: spec.id, projectId: id, name: spec.name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Aberdeen City', locality: 'Ferryhill', featureType: spec.featureType, significance: spec.significance ?? 'local',
  geometry: { type: 'Point', coordinates: spec.coordinates }, locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact', shortDescription: spec.description, visitorWebsiteUrl: spec.url,
  attractionGuide: spec.guide,
  editorialReview: spec.category ? { status: 'editorially_researched', category: spec.category, methodVersion: '2026-09-02-researched-visitor-value-v1', reviewedAt: day, scoreRationale: spec.reason, evidenceUrls: spec.evidence, ...(spec.category === 'food' ? { foodAssessment: { foodAndDrinkQuality: 18, daytimeRelevance: 18, distinctiveness: 8, consistency: 12, visitorFit: 10, evidenceConfidence: 6 } } : { attractionAssessment: assess(spec.score) }) } : undefined,
  sourceRecords: spec.evidence.map((url: string, index: number) => src(index ? `${spec.name} supporting evidence` : spec.name, url.includes('aberdeencity') ? 'Aberdeen City Council' : url.includes('treasuretrails') ? 'TreasureTrails.co.uk' : spec.organisation, url, spec.notes, url.includes('historicenvironment.scot') ? 'official_statutory' : url.includes('aberdeencity') ? 'local_authority' : 'official_non_statutory')),
  tags: spec.tags, createdAt: at, updatedAt: at, reviewed: true, evidenceScope: 'parish_evidence',
});
const duthie = make({ id: 'curated-attraction:ferryhill-duthie-park', name: 'Duthie Park and David Welch Winter Gardens', featureType: 'park', significance: 'regional', coordinates: [-2.1031544, 57.1306317], url: u.duthie, score: 87, category: 'attraction', organisation: 'VisitAberdeenshire / Aberdeen City Council', evidence: [u.duthie, u.duthieTrail], description: 'A 44-acre restored Victorian park with free Winter Gardens, formal features, play, lawns and riverside access.', reason: 'A substantial, free and dependable city attraction, kept separate from Ferryhill’s settlement score.', notes: 'Official visitor evidence for the park, Winter Gardens and accessibility.', tags: ['curated-visitor', 'home-standalone-place', 'current-context'], guide: { headline: 'Explore one of Aberdeen’s strongest free attractions', intro: 'The park combines Victorian design, one of Europe’s largest indoor gardens, family play and riverside walking.', bestFor: ['Gardens', 'Families', 'A free half-day'], parking: 'Visitor parking and disabled parking are available; no dependable capacity or current charging detail is published on the destination page.', toilets: 'A 24-hour automatic public convenience is listed by Aberdeen City Council; check current status before relying on it.', picnic: 'The public lawns are suitable for an informal picnic; no fixed-table count is claimed.', foodNote: 'The Park Café serves hot drinks, cakes, breakfast and light lunches.' } });
const railway = make({ id: 'curated-attraction:ferryhill-railway-heritage-centre', name: 'Ferryhill Railway Heritage Centre', featureType: 'railway', significance: 'regional', coordinates: [-2.098489332171124, 57.13223145998621], url: u.rail, score: 71, category: 'attraction', organisation: 'Ferryhill Railway Heritage Trust', evidence: [u.rail, u.railHes], description: 'A developing railway museum in the listed former engine shed, opened on specific event days with demonstrations, tours and museum access.', reason: 'Authentic railway heritage and event-day activity, reduced for a narrow, changeable public-opening calendar and uneven developing site.', notes: 'Operator event information and official listed-building history.', tags: ['curated-visitor', 'home-standalone-place', 'current-context'], guide: { headline: 'See Aberdeen railway history on a published open day', intro: 'The trust is restoring the former depot, turntable and museum site.', bestFor: ['Railway enthusiasts', 'Event-day family visits'], parking: 'No dependable public visitor-parking specification was found on the operator page.', toilets: 'Event facilities should be confirmed with the operator.', picnic: 'No general picnic provision is claimed.', foodNote: 'Refreshments are advertised for selected events only.' } });
const trailTreasure = make({ id: 'curated-trails:ferryhill-duthie-park-treasure-trail', name: 'Duthie Park – Exotic Floral Paradise Treasure Trail', featureType: 'walking_route', coordinates: [-2.1031544, 57.1306317], url: u.treasure, score: 78, category: 'trail', organisation: 'TreasureTrails.co.uk', evidence: [u.treasure], description: 'A current 1.5-mile, roughly 1.5-hour circular clue trail around Duthie Park, suitable for pushchairs and assisted wheelchairs.', reason: 'An exact live clue-trail product with route length, duration and accessibility notes.', notes: 'Provider-verified route details.', tags: ['curated-visitor', 'visitor-context-trail', 'current-context'] });
const trailGuide = make({ id: 'curated-trails:ferryhill-duthie-park-guide', name: 'Duthie Park Trail and Guide', featureType: 'walking_route', coordinates: [-2.1031544, 57.1306317], url: u.duthieTrail, score: 72, category: 'trail', organisation: 'VisitAberdeenshire / Aberdeen City Council', evidence: [u.duthieTrail, u.duthiePdf], description: 'A free self-guided route through the park’s history, art, Victorian structures and gardens.', reason: 'A useful official interpretive circuit, reduced because it is attraction-bound rather than a Ferryhill neighbourhood trail.', notes: 'Official trail page and guide PDF.', tags: ['curated-visitor', 'visitor-context-trail', 'current-context'] });
const deeside = make({ id: 'curated-trails:ferryhill-deeside-way', name: 'Deeside Way from Duthie Park', featureType: 'walking_route', coordinates: [-2.1042, 57.1298], url: u.deeside, score: 76, category: 'trail', organisation: 'VisitAberdeenshire', evidence: [u.deeside, u.duthieTrail], description: 'The long-distance Deeside Way begins at Duthie Park and follows the former railway west towards Ballater.', reason: 'A major walking and cycling route with a clear Ferryhill-area start, but almost all route depth lies outside the district.', notes: 'Official destination route evidence.', tags: ['curated-visitor', 'visitor-context-trail', 'current-context'] });
const cafe = make({ id: 'curated-eat:ferryhill-duthie-park-cafe', name: 'Duthie Park Café', featureType: 'commercial_building', coordinates: [-2.1029, 57.1312], url: u.cafe, category: 'food', organisation: 'The Park Café', evidence: [u.cafe, u.duthieTrail], description: 'Park café with hot drinks, cakes, breakfast and light lunches, with indoor and outdoor seating.', reason: 'A strong visitor-fit coffee, cake and light-lunch stop within the attraction; included for its daytime offer, not restaurant dining.', notes: 'Current operator hours and destination trail evidence.', tags: ['curated-visitor', 'service-context-food', 'visitor-context-food', 'current-context'] });
const parking = make({ id: 'curated-parking:ferryhill-duthie-park', name: 'Duthie Park Visitor Parking', featureType: 'parking', coordinates: [-2.1041, 57.1299], url: u.duthie, organisation: 'VisitAberdeenshire / Aberdeen City Council', evidence: [u.duthie], description: 'Visitor parking with disabled parking; capacity, charges, maximum stay and overnight rules were not established.', notes: 'Destination page verifies disabled parking but does not publish full operational detail.', tags: ['service-context-parking', 'current-context'] });
const toilet = make({ id: 'curated-toilets:ferryhill-duthie-park', name: 'Duthie Park Automatic Public Convenience', featureType: 'toilet', coordinates: [-2.1038, 57.1302], url: u.toilets, organisation: 'Aberdeen City Council', evidence: [u.toilets], description: 'Council-listed 24-hour automatic public convenience; live operational status should be checked.', notes: 'Council public-toilet review identifies Duthie Park and a 24-hour automatic convenience.', tags: ['service-context-toilets', 'current-context'] });
const picnic = make({ id: 'curated-picnic:ferryhill-duthie-park-lawns', name: 'Duthie Park Picnic Lawns', featureType: 'park', coordinates: [-2.1027, 57.131], url: u.picnic, organisation: 'Aberdeen City Council', evidence: [u.picnic, u.duthie], description: 'Public park lawns suitable for an informal picnic; no fixed-table count is claimed.', notes: 'Council has explicitly hosted and invited public bring-your-own picnic use.', tags: ['service-context-picnic', 'current-context'] });
const curated = [duthie, railway, trailTreasure, trailGuide, deeside, cafe, parking, toilet, picnic];
p.features = [...p.features.filter((feature) => !curated.some((item) => item.id === feature.id)), ...curated];
const highlights: VisitorHighlight[] = [duthie, railway].map((feature, index) => ({ rank: index + 1, featureId: feature.id, name: feature.name, reason: feature.editorialReview!.scoreRationale, tagline: index ? 'Event-led railway museum and turntable' : 'Free Victorian park and Winter Gardens', visitorScore: index ? 71 : 87, timeToSpend: index ? '1–2 hours on an open day' : '2–4 hours', openingTimes: index ? 'Published event days only; check operator calendar' : 'Park open-air; check current Winter Gardens hours', admission: index ? 'Event pricing varies' : 'Free', freeAdmission: index ? undefined : true, visitorWebsiteUrl: feature.visitorWebsiteUrl, editorialReview: feature.editorialReview, sourceName: feature.sourceRecords[0].sourceName, sourceUrl: feature.visitorWebsiteUrl!, verifiedInBoundaryAt: day, homeMapEligible: false }));
p.project.preferredBasemap = 'voyager';
p.project.boundarySource = 'Strict Ferryhill district review. Duthie Park and the railway centre remain separately scored See attractions and contribute no points to the residential district score.';
p.project.boundaryConfidence = 'medium';
p.project.touristAppeal = { score: 52, dogOwnerScore: 50, dogAccessScoreAdjustment: -2, rating: 0, label: 'Limited Interest', summary: 'An attractive granite residential district with an unusually rich dated townscape. Duthie Park and the railway centre are separately scored attractions and do not make Ferryhill itself a map-worthy town.', dogAccessRating: 2, dogAccessSummary: 'Duthie Park and the outdoor trails work well for controlled dogs; assistance dogs only are admitted to the Winter Gardens and railway event rules should be checked.', methodVersion: '2026-09-02-strict-settlement-full-audit-v3', reviewedAt: day, sourceUrls: Object.values(u) };
p.project.visitorHighlights = highlights;
p.project.townGuide = { characterTag: 'Granite neighbourhood beside Duthie Park', headline: 'Two worthwhile attractions, but not an independent town visit', intro: 'Ferryhill scores 52% and remains selector-only. Its streets have a substantial, fully dated historic layer, while Duthie Park and Ferryhill Railway Heritage Centre appear properly in See without inflating the neighbourhood score.', bestFor: ['Granite townscape', 'A Duthie Park visit', 'Railway open days'], perfectFor: ['Using Ferryhill as the approach to a named attraction'], suggestedFirstVisit: { title: 'Choose the attraction first', summary: 'Use Duthie Park year-round or plan around a published railway open day; neither requires treating the surrounding district as a separate destination.' }, dontMiss: ['Duthie Park and David Welch Winter Gardens', 'Ferryhill Railway Heritage Centre on open days'], suggestedTime: 'No separate district visit; 2–4 hours for Duthie Park', visitorMood: 'Residential, handsome and close to major city attractions.', sourceUrls: Object.values(u), lastReviewedAt: day };
p.project.researchNotes = 'Full current-web audit. All six visitor categories and named clue-trail providers checked. Duthie Park and the railway centre are separately scored See attractions; their facilities are published with limits but excluded from Ferryhill town merit. All 120 local HES listed-building records remain visible and materially dated with no dates appended to names.';
pl.projects[id] = { eat: [cafe.id], trails: [trailTreasure.id, trailGuide.id, deeside.id], picnic: [picnic.id], parking: [parking.id], toilets: [toilet.id] };
d.reviewedAt = day;
d.projects[id] = { attraction: { [duthie.id]: { rating: 2, status: 'restricted', label: 'Park welcoming; Winter Gardens restricted', summary: 'Dogs are welcome in the park; assistance dogs only inside the Winter Gardens.', sourceName: 'VisitAberdeenshire', sourceUrl: u.duthie, reviewedAt: day }, [railway.id]: { rating: 1, status: 'unconfirmed', label: 'Event policy unconfirmed', summary: 'Confirm before bringing a dog to an operating railway event.', sourceName: 'Ferryhill Railway Heritage Trust', sourceUrl: u.rail, reviewedAt: day } }, trail: Object.fromEntries([trailTreasure, trailGuide, deeside].map((feature) => [feature.id, { rating: 2, status: 'restricted', label: 'Outdoor close control', summary: 'Use a lead near roads, water, wildlife and other park users.', sourceName: 'Scottish Outdoor Access Code', sourceUrl: u.dogCode, reviewedAt: day }])) };
p.validation = validateFeatures(p.project, p.features);
const errors = p.validation.filter((entry: any) => entry.severity === 'error'); if (errors.length) throw new Error(errors.map((entry: any) => entry.message).join('; '));
const statutory = p.features.filter((feature) => feature.tags.includes('hes-listed-building')); const visible = statutory.filter((feature) => !feature.tags.includes('map-hidden')); const undated = visible.filter((feature) => !feature.documentedDateText || feature.earliestPossibleYear == null || feature.latestPossibleYear == null || feature.dateBasis === 'unknown'); if (undated.length) throw new Error(`Undated Ferryhill HES pins: ${undated.map((feature) => feature.id).join(', ')}`);
const report = { reviewedAt: at, projectId: id, place: 'Ferryhill', townScore: 52, mapPublished: false, categories: { see: { audited: true, published: 2, note: 'Both are separately scored attractions and excluded from the district score.' }, eat: { audited: true, published: 1 }, trails: { audited: true, published: 3, providerChecks: { TreasureTrails: 'Exact live Duthie Park product verified: 1.5 miles, 1.5 hours.', CuriousAbout: 'No exact Ferryhill product found.', MysteryGuides: 'No exact Ferryhill product found.', GoQuestAdventures: 'No exact Ferryhill quest found.', officialCouncilRoutes: 'Duthie Park Trail and Deeside Way start verified.' } }, picnic: { audited: true, published: 1 }, parking: { audited: true, published: 1, note: 'Parking and disabled parking verified; unavailable capacity/charge rules explicitly withheld.' }, toilets: { audited: true, published: 1 } }, hes: { assigned: statutory.length, visibleDated: visible.length - undated.length, hiddenUndated: statutory.length - visible.length, visibleUndated: undated.length, missing: 0 }, boundaryRule: 'Duthie Park and railway centre are See attractions, not town-score evidence. Aberdeen city-centre services are not borrowed.', research: { currentWebResearch: true, strictBoundaryChecked: true, sourceChecks: Object.values(u).map((url) => ({ url, checkedAt: day, outcome: 'checked' })) }, scoreReanalysis: { required: true, completed: true, previousScore: 58, resultScore: 52, rationale: 'The prior 58 conflated attraction value with residential-district merit. Ferryhill remains an attractive historic neighbourhood, while the two reasons to travel are now correctly separated under See.' }, certification: { publicationCountsReconciled: true, liveBrowserVerifiedAt: null } };
await writeFile(pp, `${JSON.stringify(p, null, 2)}\n`); await writeFile(plp, `${JSON.stringify(pl, null, 2)}\n`); await writeFile(dp, `${JSON.stringify(d, null, 2)}\n`); await writeFile(rp, `${JSON.stringify(report, null, 2)}\n`);
console.log(`Ferryhill audit complete: score 52; 2 See, 1 Eat, 3 Trails, 1 Picnic, 1 Parking, 1 Toilet; ${visible.length - undated.length}/${visible.length} visible HES pins dated.`);
