import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const projectId='old-aberdeen-scotland', reviewedDate='2026-08-27', reviewedAt='2026-08-27T23:55:00Z';
const projectPath=resolve('data/projects/old-aberdeen.json'), plannerPath=resolve('data/aberdeen-north-visitor-planner-curation.json'), dogPath=resolve('data/aberdeen-north-dog-access-curation.json'), reportPath=resolve('data/review/old-aberdeen-full-visitor-audit-2026-08-27.json');
type F=HeritageFeature&Record<string,any>; type P=ProjectPackage&{project:ProjectPackage['project']&Record<string,any>;features:F[]};
const urls={
 oldAberdeen:'https://visit.oldaberdeen.org.uk/what-to-see/', localServices:'https://visit.oldaberdeen.org.uk/local-shops-and-services/', heritageTrails:'https://sites.aberdeencity.gov.uk/AAGM/local-history/heritage-trails', oldTrail:'https://www.visit.oldaberdeen.org.uk/wp-content/uploads/2020/05/Old%20Aberdeen%20Trail.pdf',
 treasure:'https://www.treasuretrails.co.uk/products/what-to-do-aberdeen-aberdeenshire', walkingHistory:'https://www.abdn.ac.uk/media/site/events/documents/history.pdf', cathedralVisit:'https://www.historicenvironment.scot/visit-a-place/places/st-machars-cathedral-transepts/plan-your-visit/',
 hesCathedral:'https://portal.historicenvironment.scot/designation/LB19957', hesCathedralSite:'https://portal.historicenvironment.scot/designation/SM90001', hesCathedralGates:'https://portal.historicenvironment.scot/designation/LB19959', hesChapel:'https://portal.historicenvironment.scot/designation/LB19943', hesKings:'https://portal.historicenvironment.scot/designation/LB20092', hesNewKings:'https://portal.historicenvironment.scot/designation/LB20093', hesTownHouse:'https://portal.historicenvironment.scot/designation/LB19992', hesMarketCross:'https://portal.historicenvironment.scot/designation/LB20000', hesPowis:'https://portal.historicenvironment.scot/designation/LB20219',
 garden:'https://www.fcbgaberdeen.org.uk/visit', gardenDog:'https://www.fcbgaberdeen.org.uk/', zoology:'https://www.doorsopendays.org.uk/regions/aberdeen-city/the-zoology-museum', library:'https://www.abdn.ac.uk/library/', kilau:'https://kilaucoffee.wordpress.com/about/', shelter:'https://visit.oldaberdeen.org.uk/local-shops-and-services/', jgRoss:'https://www.jg-ross.co.uk/', foodstory:'https://foodstorycafe.co.uk/', grub:'https://www.grubfreshfood.co.uk/about', shakes:'https://www.shakesncakesaberdeen.co.uk/', unionBrew:'https://www.ausa.org.uk/unionbrew/', hardback:'https://www.abdn.ac.uk/media/site/library/documents/guides/Library_Tour_-_Introduction.pdf',
 parking:'https://www.aberdeencity.gov.uk/services/roads-transport-and-parking/parking/find-car-park/cashless-parking', toilet:'https://committees.aberdeencity.gov.uk/documents/s7161/Public%20Toilet%20Review.pdf', dogCode:'https://www.outdooraccess-scotland.scot/dog-owners', curious:'https://curiousabout.co.uk/', mystery:'https://www.mysteryguides.co.uk/', goQuest:'https://goquestadventures.com/' };
const hesMoteHillUrl='https://portal.historicenvironment.scot/designation/SM1907';
const pkg=JSON.parse(await readFile(projectPath,'utf8')) as P, planner=JSON.parse(await readFile(plannerPath,'utf8')) as any, dog=JSON.parse(await readFile(dogPath,'utf8')) as any;
const assess=(score:number)=>({experienceDepth:Math.round(score*.3),distinctiveness:Math.round(score*.2),presentation:Math.round(score*.2),journeyWorth:Math.round(score*.15),accessAndReliability:Math.round(score*.1),evidenceConfidence:score-Math.round(score*.3)-Math.round(score*.2)-Math.round(score*.2)-Math.round(score*.15)-Math.round(score*.1),visitability:'full_visitor_experience' as const});
const foodAssess=(score:number)=>({foodAndDrinkQuality:Math.round(score*.29),daytimeRelevance:Math.round(score*.21),distinctiveness:Math.round(score*.15),consistency:Math.round(score*.14),visitorFit:Math.round(score*.11),evidenceConfidence:score-Math.round(score*.29)-Math.round(score*.21)-Math.round(score*.15)-Math.round(score*.14)-Math.round(score*.11)});
const src=(name:string,org:string,url:string,notes:string,reliability:any='official_non_statutory')=>({sourceName:name,sourceOrganisation:org,sourceUrl:url,accessedAt:reviewedAt,reliability,licence:'Source-linked editorial evidence; verify time-sensitive details before travel.',notes});
const review=(category:'attraction'|'trail'|'food',score:number,reason:string,evidenceUrls:string[])=>({status:'editorially_researched',category,methodVersion:'2026-08-13-researched-visitor-value-v1',reviewedAt:reviewedDate,scoreRationale:reason,evidenceUrls,...(category==='food'?{foodAssessment:foodAssess(score)}:{attractionAssessment:assess(score)})});
const make=(s:Record<string,any>):F=>({id:s.id,projectId,name:s.name,alternativeNames:[],countryCode:'GB-SCT',region:'Aberdeen City',locality:'Old Aberdeen',featureType:s.featureType,significance:s.significance??'local',geometry:{type:'Point',coordinates:s.coordinates},locationType:s.locationType??'exact',locationConfidence:'high',dateBasis:s.dateBasis??'unknown',dateConfidence:s.dateConfidence??'unknown',survival:s.survival??'substantially_intact',documentedDateText:s.dateText,earliestPossibleYear:s.earliest,latestPossibleYear:s.latest,datePrecision:s.datePrecision,shortDescription:s.description,visitorWebsiteUrl:s.website,attractionGuide:s.guide,editorialReview:s.category?review(s.category,s.score,s.reason,s.evidenceUrls):undefined,sourceRecords:s.evidenceUrls.map((url:string,i:number)=>src(i?`${s.name} supporting evidence`:s.sourceName,i?'Supporting publisher':s.sourceOrganisation,url,`Current-place curation: visitor_place_type=${s.placeType}; ${s.score?`visit_score=${s.score}; `:''}${s.details??''}; description=${s.description}`,url.includes('historicenvironment.scot')?'official_statutory':url.includes('aberdeencity.gov.uk')?'local_authority':'official_non_statutory')),tags:s.tags,createdAt:reviewedAt,updatedAt:reviewedAt,reviewed:true,evidenceScope:'parish_evidence'}) as F;

const hs=[
 ['hes-listed-building:LB19957','St Machar’s Cathedral','cathedral',[-2.1023658,57.1698025],urls.hesCathedral,'Main fabric built 1422–40; heraldic ceiling 1518–31; altered 1832; restored 1867 and 1926–29',1422,1929],
 ['hes-listed-building:LB19959','St Machar’s Cathedral Gate Lodges','house',[-2.1027,57.16915],urls.hesCathedralGates,'Gate lodges built in 1832 around earlier structures; gatepiers probably 18th century',1700,1832],
 ['hes-listed-building:LB19943','King’s College Chapel','chapel',[-2.10055,57.16482],urls.hesChapel,'Begun in 1500, dated 1504 and roofed in lead in 1506; crown replaced 1634; restorations 1873, 1890–91 and 1931',1500,1931],
 ['hes-listed-building:LB20092','King’s College Quadrangle and Elphinstone Hall','school',[-2.1002,57.16495],urls.hesKings,'Cromwell Tower begun 1657; west frontage 1825–26; quadrangle and library 1860–73 with additions to 1914; Elphinstone Hall 1927–29',1657,1929],
 ['hes-listed-building:LB20093','New King’s and Sacrist’s House','school',[-2.10055,57.16565],urls.hesNewKings,'Built in 1912 by A. Marshall Mackenzie',1912,1912],
 ['hes-listed-building:LB19992','Old Aberdeen Town House','civic_building',[-2.1022573,57.1671241],urls.hesTownHouse,'Built in 1788 by George Jaffrey, incorporating a 1721 coat of arms from the previous building',1721,1788],
 ['hes-listed-building:LB20000','Old Aberdeen Market Cross','monument',[-2.10218,57.16696],urls.hesMarketCross,'Original surviving knop dates from the first quarter of the 16th century; shaft renewed 1951 and cross returned here in 1993',1500,1993],
 ['hes-listed-building:LB20219','Powis Gates','monument',[-2.1020809,57.1634876],urls.hesPowis,'Main minaret gateway built in 1834; adjacent foot gate dated 1697',1697,1834],
] as const;
const heritage=hs.map(([id,name,featureType,coordinates,website,dateText,earliest,latest])=>make({id,name,featureType,coordinates,website,dateText,earliest,latest,dateBasis:'documented_date_range',dateConfidence:'high',datePrecision:earliest===latest?'exact_year':'multi_period',description:'A dated Old Aberdeen landmark; the public chronology records construction and alteration periods rather than its later designation date.',evidenceUrls:[website],sourceName:'Historic Environment Scotland designation',sourceOrganisation:'Historic Environment Scotland',placeType:'Heritage',tags:['hes-listed-building','date-reviewed']}));
const scheduledHeritage=[
 make({id:'hes-scheduled-monument:SM90001',name:'St Machar’s Cathedral Transepts and Graveyard',featureType:'scheduled_monument',coordinates:[-2.1022011,57.1696267],website:urls.hesCathedralSite,dateText:'First cathedral begun circa 1130–1165; surviving scheduled transepts date from the later 14th century, with work of 1424 and 1522',earliest:1130,latest:1522,dateBasis:'documented_date_range',dateConfidence:'high',datePrecision:'multi_period',description:'The independently scheduled medieval transept remains, buried cathedral archaeology and surrounding graveyard.',evidenceUrls:[urls.hesCathedralSite],sourceName:'St Machar’s Cathedral and graveyard scheduled monument',sourceOrganisation:'Historic Environment Scotland',placeType:'Heritage',tags:['hes-scheduled-monument','date-reviewed']}),
 make({id:'hes-scheduled-monument:SM1907',name:'Mote Hill Palisaded Settlement and Cairn',featureType:'archaeological_site',coordinates:[-2.1063825,57.1706009],website:hesMoteHillUrl,dateText:'Possible late-Neolithic or Bronze-Age ring cairn; Iron-Age palisaded settlement occupied in the 2nd century AD',earliest:-3000,latest:199,dateBasis:'estimated_from_authoritative_source',dateConfidence:'medium',datePrecision:'multi_period',description:'A prominent Seaton Park mound preserving evidence of a possible prehistoric ring cairn and a 2nd-century AD palisaded settlement.',evidenceUrls:[hesMoteHillUrl],sourceName:'Mote Hill scheduled monument',sourceOrganisation:'Historic Environment Scotland',placeType:'Heritage',tags:['hes-scheduled-monument','date-reviewed']}),
];
const h=(id:string)=>heritage.find(f=>f.id===id)!;
const attractions=[
 {f:h('hes-listed-building:LB19957'),score:90,tag:'Medieval cathedral and heraldic ceiling',reason:'The district’s outstanding interior and architectural experience, with free daily access to the HES-managed transepts and a nationally important medieval story.',web:urls.cathedralVisit,time:'1–1.5 hours',open:'Apr–Oct daily 09:30–16:30; Nov–Mar daily 10:00–16:00',admission:'Free',guide:{headline:'A granite medieval cathedral with an extraordinary heraldic ceiling',parking:'Limited on-street parking nearby; Seaton Park is the most clearly identified visitor car park.',toilets:'No dedicated public toilet is listed by HES.',picnic:'Seaton Park is immediately north.',foodNote:'Return along the High Street for cafés.'}},
 {f:make({id:'curated-attraction:old-aberdeen-seaton-park',name:'Seaton Park',featureType:'park',coordinates:[-2.1006935,57.1738383],website:urls.oldAberdeen,dateText:'Purchased by Aberdeen Corporation and opened as a public park in 1947',earliest:1947,latest:1947,dateBasis:'documented_construction',dateConfidence:'medium',datePrecision:'exact_year',description:'A major riverside park with formal beds, Cathedral Walk, walled garden, play area and broad lawns.',evidenceUrls:[urls.oldAberdeen],sourceName:'Old Aberdeen visitor guide',sourceOrganisation:'Visit Old Aberdeen',placeType:'Attraction',tags:['curated-visitor','home-standalone-place','date-reviewed']}),score:84,tag:'Cathedral Walk and riverside lawns',reason:'A substantial free park that extends the historic visit with formal planting, play, picnic lawns and a river setting.',web:urls.oldAberdeen,time:'1–2 hours',open:'Public park; use in daylight and check local gate or event notices',admission:'Free',guide:{headline:'Formal gardens and river lawns below St Machar’s',parking:'Parking is available from Don Street; capacity, accessible-bay count, payment and maximum stay are not published.',toilets:'A public convenience is recorded in the car park; verify live status.',picnic:'Large lawns are suitable for picnics; no fixed-table count verified.',foodNote:'One Eyed Jack’s is seasonal and is not relied upon as a scored café.'}},
 {f:h('hes-listed-building:LB19943'),score:82,tag:'University founded in 1495',reason:'The chapel, crown tower and surrounding quadrangle form one of Scotland’s most distinctive university ensembles; interior access depends on services, tours and university use.',web:urls.oldAberdeen,time:'45–90 minutes',open:'Quadrangle and exterior generally viewable; chapel interior access varies with worship, events and university use',admission:'Free exterior; no general admission charge published',guide:{headline:'The crown-towered heart of Scotland’s third-oldest university',parking:'No general visitor parking on campus; use public transport or signed public parking.',toilets:'Use publicly accessible university facilities only when buildings are open.',picnic:'Campus lawns are not recorded as a formal public picnic site.',foodNote:'High Street cafés are nearby.'}},
 {f:make({id:'curated-attraction:old-aberdeen-cruickshank-garden',name:'Cruickshank Botanic Garden',featureType:'garden',coordinates:[-2.1051862,57.168649],website:urls.garden,dateText:'Founded in 1898 from a gift by Anne Cruickshank in memory of Dr Alexander Cruickshank',earliest:1898,latest:1898,dateBasis:'documented_construction',dateConfidence:'high',datePrecision:'exact_year',description:'An 11-acre university botanic garden with arboretum, sunken garden, rose garden, lawns and ponds.',evidenceUrls:[urls.garden],sourceName:'Visit the Garden',sourceOrganisation:'Friends of the Cruickshank Botanic Garden',placeType:'Attraction',tags:['curated-visitor','home-standalone-place','date-reviewed']}),score:80,tag:'Free university botanic garden',reason:'A beautiful, free and unusually varied garden that materially deepens an Old Aberdeen visit, with some wheelchair limitations clearly published.',web:urls.garden,time:'45–90 minutes',open:'Apr–Sep 09:00–19:00; Oct–Mar 09:00–16:30; closed 24 Dec–6 Jan',admission:'Free',guide:{headline:'Eleven acres of specialist planting beside the cathedral precinct',parking:'On-street parking is limited; the operator points to spaces near the cathedral or Tillydrone Avenue.',toilets:'No independently verified public toilet inside the garden.',picnic:'No formal public picnic provision verified.',foodNote:'Use nearby High Street cafés.'}},
 {f:make({id:'curated-attraction:old-aberdeen-rice-library',name:'Sir Duncan Rice Library',featureType:'other',coordinates:[-2.1058937,57.1656485],website:urls.library,dateText:'Opened by Queen Elizabeth II on 24 September 2012',earliest:2012,latest:2012,dateBasis:'documented_construction',dateConfidence:'high',datePrecision:'exact_year',description:'A striking modern university library with public ground-floor art and archaeology displays; access beyond public areas follows university rules.',evidenceUrls:[urls.library],sourceName:'University Library',sourceOrganisation:'University of Aberdeen',placeType:'Attraction',tags:['curated-visitor','home-standalone-place','date-reviewed']}),score:72,tag:'Modern library and public displays',reason:'A notable contemporary counterpoint with worthwhile public displays, reduced because it remains a working university library with access conditions.',web:urls.library,time:'30–60 minutes',open:'Public access and exhibition hours follow current University Library arrangements; check the official library page before travel',admission:'Free public areas',guide:{headline:'A luminous modern landmark with collection displays',parking:'No general visitor parking on campus; designated Blue Badge parking is available.',toilets:'Visitor toilets are available when public access is permitted.',picnic:'No formal picnic provision.',foodNote:'The ground-floor Hardback Café operates to university schedules.'}},
 {f:h('hes-listed-building:LB19992'),score:70,tag:'Old burgh civic landmark',reason:'The elegant 1788 Town House and reconstructed market cross make an excellent High Street focal point, but King’s Museum inside remains closed.',web:urls.oldAberdeen,time:'15–30 minutes',open:'Exterior always visible; King’s Museum is not treated as open',admission:'Free exterior',guide:{headline:'The 1788 civic centre of the former burgh',parking:'Use signed on-street or Seaton Park parking.',toilets:'No dedicated public toilet.',picnic:'No picnic provision.',foodNote:'Shelter Coffee is immediately beside it.'}},
 {f:h('hes-listed-building:LB20219'),score:66,tag:'Minaret gateway from 1834',reason:'A highly distinctive and photogenic gateway worth including on the walk, but it is an exterior-only short stop.',web:urls.oldAberdeen,time:'10–20 minutes',open:'Open-air exterior landmark',admission:'Free',guide:{headline:'An unexpected minaret-like gateway on College Bounds',parking:'No dedicated visitor parking.',toilets:'No dedicated facility.',picnic:'No dedicated provision.',foodNote:'Kilau Coffee is nearby.'}},
];
for(const a of attractions)Object.assign(a.f,{visitorWebsiteUrl:a.web,attractionGuide:a.guide,editorialReview:review('attraction',a.score,a.reason,[a.web,a.f.sourceRecords[0].sourceUrl]),tags:[...new Set([...a.f.tags,'curated-visitor','home-standalone-place'])]});
const trailData=[
 ['curated-trails:old-aberdeen-treasure','Seaton Park and Old City Treasure Trail',78,[-2.1007,57.1735],urls.treasure,'A £10.99, 2-mile circular detective trail taking about 2 hours; dog friendly but not wheelchair or pushchair accessible.'],
 ['curated-trails:old-aberdeen-heritage','Old Aberdeen Heritage Trail',76,[-2.1022,57.1671],urls.oldTrail,'A free council-supported PDF route through the High Street, university precinct, cathedral and Seaton Park.'],
 ['curated-trails:old-aberdeen-walking-history','Walking with History: King’s College',70,[-2.1004,57.1649],urls.walkingHistory,'A free University self-guided history tour concentrating on King’s College and the Old Town House.'],
 ['curated-trails:old-aberdeen-wayfinder','Old Aberdeen Wayfinder Walk',66,[-2.102,57.167],urls.oldAberdeen,'A short 0.4-mile orientation route through the historic town core, useful as an accessible introduction rather than a deep trail.'],
];
const trails=trailData.map(([id,name,score,coordinates,website,description])=>make({id,name,score,coordinates,website,featureType:'walking_route',locationType:'representative_point',description,reason:'A verified Old Aberdeen-specific route with a current public planning page or downloadable guide.',evidenceUrls:[website],sourceName:name,sourceOrganisation:id.includes('treasure')?'Treasure Trails':id.includes('walking-history')?'University of Aberdeen':'Aberdeen City Council / Visit Old Aberdeen',placeType:'Trail',details:'Route link checked; individual venue access and conditions can change',category:'trail',tags:['curated-visitor','service-context-trail','visitor-context-trail','current-context']}));
const foodData=[
 ['curated-eat:old-aberdeen-kilau','Kilau Coffee',80,[-2.1022841,57.165639],urls.kilau,'Independent campus coffee: Speciality coffee, crepes, baguettes, baking and light meals in the historic High Street.','opening_hours:description=Mon–Fri 08:00–20:00; Sat 10:00–17:00; Sun closed; price_band=££; cuisine=Coffee, baking, crepes, baguettes and light lunches'],
 ['curated-eat:old-aberdeen-shelter','Shelter Coffee',76,[-2.1019549,57.1670533],urls.shelter,'Coffee beside the Town House: Coffee, soup, panini, sandwiches and cakes in a carefully converted High Street building.','opening_hours:description=Current listings show weekday opening from 08:30 and weekend opening from 09:00 or 11:00, generally closing 17:00; confirm on the day; price_band=££; cuisine=Coffee, soup, panini, sandwiches and cakes'],
 ['curated-eat:old-aberdeen-foodstory','Foodstory University',78,[-2.1012221,57.1651474],urls.foodstory,'Campus speciality coffee: Vegetarian and vegan baking, sourdough, coffee, tea and light lunches at Foodstory’s University counter.','opening_hours:description=Mon–Fri 09:30–16:00; Sat–Sun closed; price_band=££; cuisine=Speciality coffee, handmade bakes, sourdough and light lunches'],
 ['curated-eat:old-aberdeen-grub','Grub Fresh Food, Spital',74,[-2.1004503,57.1605692],urls.grub,'Fresh Spital lunches: A long-running local café for baguettes, panini, wraps, salads, soup, coffee and baking.','opening_hours:description=Current operator confirms the 148 Spital branch; check live social channels for daily hours; price_band=££; cuisine=Baguettes, panini, wraps, salads, soup, coffee and bakes'],
 ['curated-eat:old-aberdeen-union-brew','Union Brew',72,[-2.1040555,57.1669871],urls.unionBrew,'Student-run campus café: Hot and cold drinks, sandwiches and traybakes in a welcoming space explicitly open to campus visitors.','opening_hours:description=Mon–Fri during published campus hours; out-of-term hours vary and should be checked on operator social channels; price_band=£; cuisine=Coffee, tea, sandwiches and traybakes'],
 ['curated-eat:old-aberdeen-shakes-cakes','Shakes ’n’ Cakes, Spital',70,[-2.100761,57.160539],urls.shakes,'Old Aberdeen sweet stop: A seated dessert café for cakes, ice cream, waffles, crepes, pancakes, milkshakes and hot drinks.','opening_hours:description=Daily 12:00–23:30 according to the current operator site; price_band=££; cuisine=Cakes, desserts, ice cream, shakes and hot drinks'],
 ['curated-eat:old-aberdeen-hardback','Hardback Café',68,[-2.1058527,57.1653153],urls.hardback,'Library coffee stop: A publicly accessible ground-floor café serving hot and cold drinks, snacks and light food inside the Sir Duncan Rice Library.','opening_hours:description=Follows current University Library and hospitality schedules; confirm before travel, especially outside term; price_band=£; cuisine=Coffee, hot and cold drinks, snacks and light food'],
 ['curated-eat:old-aberdeen-jg-ross','J. G. Ross, High Street',66,[-2.1022,57.16575],urls.jgRoss,'Bakery picnic supplies: A traditional bakery and coffee shop for bread, cakes, sandwiches and takeaway coffee.','opening_hours:description=Mon–Fri 07:00–17:30; Sat–Sun closed; price_band=£; cuisine=Bakery, cakes, sandwiches and takeaway coffee'],
];
const foods=foodData.map(([id,name,score,coordinates,website,description,details])=>make({id,name,score,coordinates,website,featureType:'commercial_building',description,reason:'A current café-led Old Aberdeen option suited to coffee, cake, baking or light lunch.',evidenceUrls:[website,urls.localServices],sourceName:name,sourceOrganisation:name,placeType:'Eat',details,category:'food',tags:['curated-visitor','service-context-food','visitor-context-food','current-context']}));
const parking=[
 make({id:'curated-parking:old-aberdeen-seaton-park',name:'Seaton Park Car Park',coordinates:[-2.0979,57.1728],website:urls.oldAberdeen,featureType:'other',description:'Visitor parking accessed from Don Street. Capacity, accessible bays, fees, payment methods, maximum stay and overnight rules are not published by the visitor source; check signs.',evidenceUrls:[urls.oldAberdeen,urls.treasure],sourceName:'Seaton Park visitor access',sourceOrganisation:'Visit Old Aberdeen',placeType:'Parking',details:'amenity=parking; capacity=Not published; capacity:disabled=Not published; fee=Not established; payment_methods=Not established; maxstay=Not published; restrictions=Check signs on arrival',tags:['service-context-parking','current-context']}),
 make({id:'curated-parking:old-aberdeen-bedford-tillydrone',name:'Bedford Road and Tillydrone Avenue Visitor Bays',coordinates:[-2.1085,57.1658],website:urls.parking,featureType:'other',description:'A total of 44 controlled on-street bays were designated for stays up to six hours. Aberdeen supports RingGo and PayByPhone; check the bay sign for the current tariff and eligibility.',evidenceUrls:[urls.parking],sourceName:'Aberdeen cashless and controlled parking information',sourceOrganisation:'Aberdeen City Council',placeType:'Parking',details:'amenity=parking; parking=street_side; capacity=44; capacity:disabled=Not published; fee=yes; payment_methods=RingGo or PayByPhone where indicated; maxstay=6 hours; restrictions=Check the individual bay sign',tags:['service-context-parking','current-context']}),
];
const toilets=[make({id:'curated-toilets:old-aberdeen-seaton-park',name:'Seaton Park Public Toilet',coordinates:[-2.098,57.17275],website:urls.toilet,featureType:'toilets',description:'An automatic public convenience in the Seaton Park car park, recorded by the council as a 24-hour facility; verify live status before relying on it.',evidenceUrls:[urls.toilet],sourceName:'Aberdeen public toilet review',sourceOrganisation:'Aberdeen City Council',placeType:'Public toilets',details:'amenity=toilets; opening_hours:description=Recorded as 24 hours; access=public; live_status=Check before travel',tags:['service-context-toilets','current-context']})];
const picnic=[make({id:'curated-picnic:old-aberdeen-seaton-park',name:'Seaton Park Picnic Lawns',coordinates:[-2.1006,57.1733],website:urls.oldAberdeen,featureType:'park',description:'Large public lawns suitable for an informal picnic beside the formal gardens; no fixed-table count was verified.',evidenceUrls:[urls.oldAberdeen],sourceName:'Seaton Park visitor guide',sourceOrganisation:'Visit Old Aberdeen',placeType:'Picnic area',details:'tourism=picnic_site; fee=no; capacity=Not published; table_count=Not verified',tags:['service-context-picnic','current-context']})];
const auditedFeatures=[...heritage,...scheduledHeritage,...attractions.map(a=>a.f).filter(f=>!heritage.includes(f)),...trails,...foods,...parking,...toilets,...picnic];
const auditedFeatureIds=new Set(auditedFeatures.map(feature=>feature.id));
pkg.features=[...auditedFeatures,...pkg.features.filter(feature=>feature.tags.some((tag:string)=>['hes-listed-building','hes-scheduled-monument'].includes(tag))&&!auditedFeatureIds.has(feature.id))];
const highlights:VisitorHighlight[]=attractions.map((a,i)=>({rank:i+1,featureId:a.f.id,name:a.f.name,reason:a.reason,tagline:a.tag,visitorScore:a.score,timeToSpend:a.time,openingTimes:a.open,admission:a.admission,freeAdmission:/^Free/.test(a.admission),visitorWebsiteUrl:a.web,attractionGuide:a.guide,editorialReview:a.f.editorialReview,sourceName:a.f.sourceRecords[0].sourceName,sourceUrl:a.web,verifiedInBoundaryAt:reviewedDate}));
pkg.project.preferredBasemap='voyager'; pkg.project.boundary={type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[-2.112,57.159],[-2.095,57.159],[-2.0935,57.170],[-2.096,57.176],[-2.105,57.176],[-2.111,57.171],[-2.112,57.159]]]}}; pkg.project.boundarySource='Explicit Old Aberdeen visitor-district polygon covering the High Street, King’s campus, cathedral precinct and Seaton Park; Tillydrone, Bridge of Don and central Aberdeen remain separate records'; pkg.project.boundaryConfidence='medium';
pkg.project.touristAppeal={score:86,dogOwnerScore:80,dogAccessScoreAdjustment:-6,rating:2,label:'Strong Destination',summary:'A remarkably complete historic district with a medieval cathedral, crown-towered university, botanic garden, major park and unusually strong self-guided trail offer.',dogAccessRating:2,dogAccessSummary:'Seaton Park, the botanic garden and outdoor trails make a rewarding dog visit, but St Machar’s transepts allow assistance dogs only and access to other interiors varies.',methodVersion:'2026-08-27-strict-settlement-full-audit-v2',reviewedAt:reviewedDate,sourceUrls:Object.values(urls)}; pkg.project.visitorHighlights=highlights;
pkg.project.townGuide={characterTag:'Medieval cathedral and university burgh',headline:'A crown-towered university quarter between cathedral, gardens and river park',intro:'Old Aberdeen is an 86% Strong Destination on its own compact merits. Its visit combines St Machar’s Cathedral, King’s College, Cruickshank Botanic Garden, the historic High Street and Seaton Park without borrowing central Aberdeen or Bridge of Don attractions.',bestFor:['Medieval and university architecture','Botanic gardens and park walks','Coffee and cake','Self-guided heritage trails'],perfectFor:['A full heritage day','A cathedral-and-garden half day','An atmospheric walking visit'],suggestedFirstVisit:{title:'Start at King’s College and walk north',summary:'Explore the crown-towered college, pause at the Town House, continue through Cruickshank Garden to St Machar’s Cathedral, then finish in Seaton Park.'},dontMiss:['St Machar’s Cathedral','King’s College Chapel and quadrangle','Cruickshank Botanic Garden','Seaton Park'],suggestedTime:'Half day to a full day',visitorMood:'A concentrated historic quarter whose collegiate streets, medieval fabric and green spaces feel distinct from the modern city centre.',practicalNote:'Seaton Park provides the clearest visitor car park, public toilet and picnic lawns. Campus parking is not presented as general visitor parking; unknown parking capacities, tariffs and bay details remain explicit.',transportNote:'Bus route 20 serves the High Street, with more frequent routes on Bedford Road, Tillydrone Avenue and King Street.',accessibilityNote:'The core streets are compact, but cobbles and historic interiors vary. The botanic garden identifies several areas that are not wheelchair accessible, and the Treasure Trail is not wheelchair or pushchair accessible.',sourceUrls:Object.values(urls),lastReviewedAt:reviewedDate};
planner.projects[projectId]={eat:foods.map(f=>f.id),trails:trails.map(f=>f.id),parking:parking.map(f=>f.id),toilets:toilets.map(f=>f.id),picnic:picnic.map(f=>f.id)};
const dr=(rating:number,status:string,label:string,summary:string,sourceUrl:string)=>({rating,status,label,summary,sourceName:'Old Aberdeen dog-access audit',sourceUrl,reviewedAt:reviewedDate}); dog.reviewedAt=reviewedDate; dog.projects[projectId]={attraction:Object.fromEntries(attractions.map(a=>[a.f.id,a.f.id.includes('seaton')?dr(3,'welcoming','Excellent outdoor dog stop','Broad park paths and lawns suit a dog visit under normal close-control rules.',urls.dogCode):a.f.id.includes('cruickshank')?dr(2,'restricted','Dogs welcome on leads','The garden publishes a dog-walker notice; keep dogs on a lead and protect planted areas.',urls.gardenDog):a.f.id.includes('LB19957')?dr(0,'restricted','Assistance dogs only in HES transepts','Historic Environment Scotland explicitly permits assistance dogs only in the managed transepts.',urls.cathedralVisit):a.f.id.includes('LB20219')||a.f.id.includes('LB19992')?dr(2,'restricted','Outdoor landmark with close control','Dogs can accompany the outdoor stop; use close control around roads and other visitors.',urls.dogCode):dr(1,'unknown','Interior pet policy not established','Outdoor viewing is practical, but no dependable current ordinary pet-dog policy was found for the interior.',a.web)])),trail:Object.fromEntries(trails.map(f=>[f.id,f.id.includes('treasure')?dr(3,'welcoming','Provider marks the trail dog friendly','The provider explicitly marks this outdoor route dog friendly; urban close control still applies.',urls.treasure):dr(2,'restricted','Public route with close control','Dogs can accompany the outdoor route, with a short lead around roads, cathedral grounds, gardens and wildlife.',urls.dogCode)])),eat:Object.fromEntries(foods.map(f=>[f.id,dr(1,'unknown','Pet policy not established','No dependable current operator statement on ordinary pet-dog access was found; confirm before entering.',f.visitorWebsiteUrl!)]))};
pkg.validation=validateFeatures(pkg.project,pkg.features); const errors=pkg.validation.filter((v:any)=>v.severity==='error'); if(errors.length)throw new Error(errors.map((e:any)=>e.message).join('; ')); const hp=pkg.features.filter(f=>f.tags.some((t:string)=>['hes-listed-building','hes-scheduled-monument'].includes(t))&&!f.tags.includes('map-hidden')); const undated=hp.filter(f=>!f.documentedDateText?.trim()||f.earliestPossibleYear==null||f.latestPossibleYear==null||f.dateBasis==='unknown'); if(undated.length)throw new Error(`Undated Old Aberdeen pins: ${undated.map(f=>f.id).join(', ')}`);
await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`); await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`); await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`); await writeFile(reportPath,`${JSON.stringify({reviewedAt,townScore:86,dogOwnerScore:80,dogAccessRating:2,categoryCounts:{see:highlights.length,eat:foods.length,trails:trails.length,picnic:picnic.length,parking:parking.length,toilets:toilets.length,heritage:hp.length},heritageDateAudit:{visiblePins:hp.length,dated:hp.length-undated.length,undated:undated.map(f=>f.id),scheduledMonuments:['SM1907','SM90001'],dateRule:'Construction and alteration dates, never designation dates.'},trailProviderSearches:[{provider:'TreasureTrails.co.uk',result:'Exact Seaton Park and Old City trail found: £10.99, 2 miles, 2 hours, dog friendly, not wheelchair or pushchair accessible.'},{provider:'Aberdeen City Council / Visit Old Aberdeen',result:'Exact Old Aberdeen Heritage Trail found.'},{provider:'University of Aberdeen',result:'Walking with History self-guided King’s route found.'},{provider:'Curious About',result:'No exact Old Aberdeen route established.'},{provider:'Mystery Guides',result:'No exact Old Aberdeen product established.'},{provider:'Go Quest Adventures',result:'No exact Old Aberdeen product established.'}],accessConflicts:[{place:'King’s Museum',result:'Excluded from scored attractions: closed since 2020 and no dependable reopening notice found.'},{place:'Zoology Museum',result:'Excluded from regular scored attractions: tourism listing says weekday opening, but current 2026 Doors Open page says it is still gearing up to reopen safely.'}],parking:parking.map(f=>({name:f.name,detail:f.shortDescription,source:f.visitorWebsiteUrl})),toilets:toilets.map(f=>({name:f.name,detail:f.shortDescription,source:f.visitorWebsiteUrl})),picnic:picnic.map(f=>({name:f.name,detail:f.shortDescription,source:f.visitorWebsiteUrl})),verification:{heritagePinsDated:`${hp.length-undated.length}/${hp.length}`,undatedHistoricPins:undated.length}},null,2)}\n`); console.log(`Old Aberdeen audit complete: ${highlights.length} See, ${foods.length} Eats, ${trails.length} Trails, ${picnic.length} Picnic, ${parking.length} Parking, ${toilets.length} Toilets; ${hp.length-undated.length}/${hp.length} heritage pins dated.`);
