import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const projectId = 'torry-aberdeen-scotland';
const reviewedDate = '2026-08-27';
const reviewedAt = '2026-08-27T23:58:00Z';
const projectPath = resolve('data/projects/torry-aberdeen.json');
const plannerPath = resolve('data/aberdeen-north-visitor-planner-curation.json');
const dogPath = resolve('data/aberdeen-north-dog-access-curation.json');
const reportPath = resolve('data/review/torry-full-visitor-audit-2026-08-27.json');
type F = HeritageFeature & Record<string, any>;
type P = ProjectPackage & { project: ProjectPackage['project'] & Record<string, any>; features: F[] };

const urls = {
  visit: 'https://www.greyhopebay.com/visit',
  battery: 'https://www.greyhopebay.com/torry-battery',
  visitAberdeenshire: 'https://visitabdn.com/businesses/greyhope-bay-centre',
  hesBattery: 'https://portal.historicenvironment.scot/designation/SM9215',
  hesLights: 'https://portal.historicenvironment.scot/designation/LB52520',
  hesVictoria: 'https://portal.historicenvironment.scot/designation/LB20072',
  hesStPeter: 'https://portal.historicenvironment.scot/designation/LB19972',
  victoriaHistory: 'https://emuseum.aberdeencity.gov.uk/sites/258/victoria-bridge',
  trails: 'https://sites.aberdeencity.gov.uk/AAGM/local-history/heritage-trails',
  churchesTrail: 'https://sites.aberdeencity.gov.uk/sites/default/files/2020-09/Torry%20Churches%20Trail.pdf',
  coastalTrail: 'https://sites.aberdeencity.gov.uk/sites/default/files/2020-09/Torry%20Coastal%20Trail.pdf',
  industrialTrail: 'https://sites.aberdeencity.gov.uk/sites/default/files/2020-09/Torry%20Industrial%20and%20Maritime%20Trail.pdf',
  urbanTrail: 'https://sites.aberdeencity.gov.uk/sites/default/files/2020-09/Torry%20Urban%20Trail.pdf',
  treasure: 'https://www.treasuretrails.co.uk/products/what-to-do-aberdeen-aberdeenshire',
  curious: 'https://curiousabout.co.uk/',
  mystery: 'https://www.mysteryguides.co.uk/',
  goQuest: 'https://goquestadventures.com/',
  rise: 'https://risetorry.shop/',
  jgRoss: 'https://deliveroo.co.uk/menu/Aberdeen/kincorth/j-g-ross-bakers-torry',
  bridgeCafe: 'https://connectedaberdeen.org/torry/',
  dogCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
};
const hesBalnagaskUrl = 'https://portal.historicenvironment.scot/designation/SM10403';

const pkg = JSON.parse(await readFile(projectPath, 'utf8')) as P;
const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as any;
const dog = JSON.parse(await readFile(dogPath, 'utf8')) as any;
const assess = (score: number) => ({ experienceDepth: Math.round(score * .3), distinctiveness: Math.round(score * .2), presentation: Math.round(score * .2), journeyWorth: Math.round(score * .15), accessAndReliability: Math.round(score * .1), evidenceConfidence: score - Math.round(score * .3) - Math.round(score * .2) - Math.round(score * .2) - Math.round(score * .15) - Math.round(score * .1), visitability: 'full_visitor_experience' as const });
const foodAssess = (score: number) => ({ foodAndDrinkQuality: Math.round(score * .29), daytimeRelevance: Math.round(score * .21), distinctiveness: Math.round(score * .15), consistency: Math.round(score * .14), visitorFit: Math.round(score * .11), evidenceConfidence: score - Math.round(score * .29) - Math.round(score * .21) - Math.round(score * .15) - Math.round(score * .14) - Math.round(score * .11) });
const src = (name: string, org: string, url: string, notes: string, reliability: any = 'official_non_statutory') => ({ sourceName: name, sourceOrganisation: org, sourceUrl: url, accessedAt: reviewedAt, reliability, licence: 'Source-linked editorial evidence; verify time-sensitive details before travel.', notes });
const review = (category: 'attraction' | 'trail' | 'food', score: number, reason: string, evidenceUrls: string[]) => ({ status: 'editorially_researched', category, methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: reason, evidenceUrls, ...(category === 'food' ? { foodAssessment: foodAssess(score) } : { attractionAssessment: assess(score) }) });
const make = (s: Record<string, any>): F => ({
  id: s.id, projectId, name: s.name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Aberdeen City', locality: 'Torry', featureType: s.featureType,
  significance: s.significance ?? 'local', geometry: { type: 'Point', coordinates: s.coordinates }, locationType: s.locationType ?? 'exact', locationConfidence: 'high',
  dateBasis: s.dateBasis ?? 'unknown', dateConfidence: s.dateConfidence ?? 'unknown', survival: s.survival ?? 'substantially_intact', documentedDateText: s.dateText,
  earliestPossibleYear: s.earliest, latestPossibleYear: s.latest, datePrecision: s.datePrecision, shortDescription: s.description, visitorWebsiteUrl: s.website,
  attractionGuide: s.guide, editorialReview: s.category ? review(s.category, s.score, s.reason, s.evidenceUrls) : undefined,
  sourceRecords: s.evidenceUrls.map((url: string, i: number) => src(i ? `${s.name} supporting evidence` : s.sourceName, i ? 'Supporting publisher' : s.sourceOrganisation, url, `Current-place curation: visitor_place_type=${s.placeType}; ${s.score ? `visit_score=${s.score}; ` : ''}${s.details ?? ''}; description=${s.description}`, url.includes('historicenvironment.scot') ? 'official_statutory' : url.includes('aberdeencity.gov.uk') ? 'local_authority' : 'official_non_statutory')),
  tags: s.tags, createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence',
}) as F;

const heritage = [
  make({ id: 'hes-scheduled-monument:SM9215', name: 'Torry Battery', featureType: 'fortification', coordinates: [-2.0591332, 57.1415966], website: urls.hesBattery, dateText: 'Constructed from 1857 to 1861; re-used in both world wars and the 1956 Suez Crisis; partially demolished in 1959', earliest: 1857, latest: 1959, dateBasis: 'documented_date_range', dateConfidence: 'high', datePrecision: 'multi_period', description: 'The surviving walls, gateway, guardhouse, gun mounts and building footings of Aberdeen’s coastal battery.', evidenceUrls: [urls.hesBattery], sourceName: 'Torry Battery scheduled monument', sourceOrganisation: 'Historic Environment Scotland', placeType: 'Heritage', tags: ['hes-scheduled-monument', 'date-reviewed'] }),
  make({ id: 'hes-scheduled-monument:SM10403', name: 'Balnagask Motte', featureType: 'fortification', coordinates: [-2.0719149, 57.1368634], website: hesBalnagaskUrl, dateText: 'Motte constructed in the 12th or 13th century; summit remodelled in the early 20th century', earliest: 1100, latest: 1299, dateBasis: 'documented_date_range', dateConfidence: 'high', datePrecision: 'century_range', description: 'A substantial grass-covered medieval castle mound surviving within the Balnagask housing estate.', evidenceUrls: [hesBalnagaskUrl], sourceName: 'Balnagask motte scheduled monument', sourceOrganisation: 'Historic Environment Scotland', placeType: 'Heritage', tags: ['hes-scheduled-monument', 'date-reviewed'] }),
  make({ id: 'hes-listed-building:LB52520', name: 'Aberdeen Harbour Leading Lights', featureType: 'lighthouse', coordinates: [-2.0694, 57.1408], website: urls.hesLights, dateText: 'First erected in 1842; heightened in 1886–87; repositioned in 1874, 1896 and 2013; electrified in 1928', earliest: 1842, latest: 2013, dateBasis: 'documented_date_range', dateConfidence: 'high', datePrecision: 'multi_period', description: 'A rare matching pair of cast-iron lighthouse-style leading lights, among the oldest surviving examples in the world.', evidenceUrls: [urls.hesLights], sourceName: 'Aberdeen Harbour leading lights listing', sourceOrganisation: 'Historic Environment Scotland', placeType: 'Heritage', tags: ['hes-listed-building', 'date-reviewed'] }),
  make({ id: 'hes-listed-building:LB20072', name: 'Victoria Bridge', featureType: 'bridge', coordinates: [-2.0874, 57.1404], website: urls.hesVictoria, dateText: 'Built and formally opened on 2 July 1881 following the Dee ferry disaster of 5 April 1876', earliest: 1881, latest: 1881, dateBasis: 'documented_construction', dateConfidence: 'high', datePrecision: 'exact_year', description: 'A five-span bridge built to connect fast-growing Torry directly with central Aberdeen.', evidenceUrls: [urls.hesVictoria, urls.victoriaHistory], sourceName: 'Victoria Bridge listing', sourceOrganisation: 'Historic Environment Scotland', placeType: 'Heritage', tags: ['hes-listed-building', 'date-reviewed'] }),
  make({ id: 'hes-listed-building:LB19972', name: 'Former St Peter’s Episcopal Church', featureType: 'church', coordinates: [-2.0818, 57.1349], website: urls.hesStPeter, dateText: 'Designed by Harold Ogle Tarbolton and built in 1898; converted to sheltered housing in 1985', earliest: 1898, latest: 1985, dateBasis: 'documented_date_range', dateConfidence: 'high', datePrecision: 'multi_period', description: 'A red-granite late-Gothic former church, now St Peter’s Court and viewed from the street.', evidenceUrls: [urls.hesStPeter, urls.churchesTrail], sourceName: 'St Peter’s Court listing', sourceOrganisation: 'Historic Environment Scotland', placeType: 'Heritage', tags: ['hes-listed-building', 'date-reviewed'] }),
];
const h = (id: string) => heritage.find((feature) => feature.id === id)!;
const attractions = [
  { f: h('hes-scheduled-monument:SM9215'), score: 88, tag: 'Dolphin watching from a Victorian battery', reason: 'Torry’s defining experience combines a nationally important coastal battery, a staffed marine visitor centre, exceptional harbour views and one of Scotland’s best-known urban dolphin viewpoints.', web: urls.visit, time: '1.5–3 hours', open: 'Battery and outdoor viewpoint are open-air; Greyhope Bay Café Wed–Mon 10:00–16:30', admission: 'Free', guide: { headline: 'Watch dolphins and ships from a harbour-defence headland', parking: 'Three parking areas adjoin the Battery, plus an overflow further along Greyhope Road. Disabled bays are in the upper car park; total capacity is not published.', toilets: 'Two accessible dry composting toilets are open during centre hours.', picnic: 'Outdoor picnic benches and grass are available; table count is not published.', foodNote: 'Greyhope Bay Café serves drinks and light food six days a week.' } },
  { f: h('hes-listed-building:LB20072'), score: 70, tag: '1881 bridge born from tragedy', reason: 'The bridge is an important and legible Torry landmark with a strong human story and river views, though it remains a short open-air stop on a working road.', web: urls.victoriaHistory, time: '15–30 minutes', open: 'Public road bridge; pavements remain accessible subject to works', admission: 'Free', guide: { headline: 'The bridge that transformed Torry after the 1876 ferry disaster', parking: 'No dedicated visitor parking; use signed legal parking in Torry.', toilets: 'No dedicated facility.', picnic: 'No picnic provision on the bridge.', foodNote: 'Victoria Road bakeries and cafés are a short walk south.' } },
  { f: h('hes-listed-building:LB52520'), score: 66, tag: 'Rare cast-iron harbour lights from 1842', reason: 'The matched active leading lights are unusually early and distinctive industrial heritage, but they are exterior-only working-harbour landmarks best seen as part of a trail.', web: urls.industrialTrail, time: '15–30 minutes', open: 'Exterior viewing from public routes; do not enter operational harbour land', admission: 'Free exterior', guide: { headline: 'Two small cast-iron lighthouses that still align ships', parking: 'No dedicated visitor parking; approach on foot as part of the industrial trail.', toilets: 'No dedicated facility.', picnic: 'No dedicated provision.', foodNote: 'Use Victoria Road or Greyhope Bay.' } },
];
for (const a of attractions) Object.assign(a.f, { visitorWebsiteUrl: a.web, attractionGuide: a.guide, editorialReview: review('attraction', a.score, a.reason, [a.web, a.f.sourceRecords[0].sourceUrl]), tags: [...new Set([...a.f.tags, 'curated-visitor', 'home-standalone-place'])] });

const trailData = [
  ['curated-trails:torry-coastal', 'Torry Coastal Trail', 78, [-2.058, 57.1415], urls.coastalTrail, 'A free council PDF trail covering the Battery, breakwaters, wartime defences, wildlife and the coast; some later stops continue beyond Torry towards Nigg and Cove.'],
  ['curated-trails:torry-industrial-maritime', 'Torry Industrial and Maritime Trail', 74, [-2.073, 57.139], urls.industrialTrail, 'A free council PDF route through fishing, granite, foundry, timber-yard and harbour-service history.'],
  ['curated-trails:torry-urban', 'Torry Urban Trail', 70, [-2.0835, 57.1358], urls.urbanTrail, 'A free council PDF introduction to Torry’s streets, planned expansion, public buildings and independent community identity.'],
  ['curated-trails:torry-churches', 'Torry Churches Trail', 68, [-2.082, 57.1348], urls.churchesTrail, 'A free council PDF visiting eleven current and former places of worship; St Fittick’s and Nigg Kirk are boundary-crossing extensions rather than Torry town sights.'],
] as const;
const trails = trailData.map(([id, name, score, coordinates, website, description]) => make({ id, name, score, coordinates, website, featureType: 'walking_route', locationType: 'representative_point', description, reason: 'A verified Torry-specific council route with a working downloadable guide.', evidenceUrls: [website, urls.trails], sourceName: name, sourceOrganisation: 'Aberdeen City Council', placeType: 'Trail', details: 'Route link checked; follow current access notices and remain on public routes', category: 'trail', tags: ['curated-visitor', 'service-context-trail', 'visitor-context-trail', 'current-context'] }));

const foodData = [
  ['curated-eat:torry-greyhope-bay', 'Greyhope Bay Café', 86, [-2.0591332, 57.1415966], urls.visit, 'Coffee with dolphins: An off-grid marine café serving seasonal drinks, bakes and light food above the harbour entrance.', 'opening_hours:description=Wed–Mon 10:00–16:30; Tue closed; check event closures; price_band=££; cuisine=Speciality drinks, home baking and light café food'],
  ['curated-eat:torry-shot-n-roll', 'Shot ’n’ Roll Torry', 72, [-2.0836, 57.136], 'https://www.facebook.com/shotnroll/', 'Cinnamon rolls and coffee: A grab-and-go Victoria Road bakery specialising in cinnamon rolls, bakes and hot drinks.', 'opening_hours:description=Current hours not reliably published outside social channels; confirm before travel; price_band=££; cuisine=Cinnamon rolls, sweet bakes and coffee'],
  ['curated-eat:torry-rise', 'RISE Torry', 68, [-2.0828, 57.1348], urls.rise, 'Affordable brews and bakes: A community-focused pay-what-you-can takeaway with coffee, pastries, breakfast rolls, soup and baked potatoes.', 'opening_hours:description=Check the live order page before travel; price_band=£; cuisine=Coffee, pastries, breakfast, soup and light hot food'],
  ['curated-eat:torry-jg-ross', 'J. G. Ross Bakers, Torry', 64, [-2.0837, 57.1362], urls.jgRoss, 'Traditional bakery stop: Cakes, traybakes, sandwiches, panini, breakfast rolls and hot drinks for a quick light lunch or picnic supply.', 'opening_hours:description=Delivery listing opens from 07:30; shop hours can differ and should be confirmed; price_band=£; cuisine=Bakery, cakes, sandwiches and hot drinks'],
] as const;
const foods = foodData.map(([id, name, score, coordinates, website, description, details]) => make({ id, name, score, coordinates, website, featureType: 'commercial_building', description, reason: 'A current Torry option centred on coffee, baking, breakfast or a light lunch rather than a full restaurant meal.', evidenceUrls: [website], sourceName: name, sourceOrganisation: name, placeType: 'Eat', details, category: 'food', tags: ['curated-visitor', 'service-context-food', 'visitor-context-food', 'current-context'] }));

const parking = [make({ id: 'curated-parking:torry-battery', name: 'Torry Battery Parking Areas', coordinates: [-2.0591332, 57.1415966], locationType: 'representative_point', website: urls.visit, featureType: 'other', description: 'Three parking areas beside Torry Battery plus an overflow farther along Greyhope Road. Disabled bays are in the upper area; the operator does not publish total spaces, tariffs, payment methods, maximum stay or overnight rules, so check signs.', evidenceUrls: [urls.visit], sourceName: 'Greyhope Bay visit information', sourceOrganisation: 'Greyhope Bay', placeType: 'Parking', details: 'amenity=parking; areas=3 plus overflow; capacity=Not published; capacity:disabled=Present, count not published; fee=Not published; payment_methods=Not published; maxstay=Not published; overnight=Not published; restrictions=Check signs on arrival', tags: ['service-context-parking', 'current-context'] })];
const toilets = [make({ id: 'curated-toilets:torry-greyhope-bay', name: 'Greyhope Bay Accessible Toilets', coordinates: [-2.0591332, 57.1415966], website: urls.visit, featureType: 'toilets', description: 'Two accessible off-grid dry composting toilets maintained by Greyhope Bay and open during centre hours.', evidenceUrls: [urls.visit], sourceName: 'Greyhope Bay visit information', sourceOrganisation: 'Greyhope Bay', placeType: 'Public toilets', details: 'amenity=toilets; capacity=2; toilets:wheelchair=yes; opening_hours:description=During Greyhope Bay Centre hours, Wed–Mon 10:00–16:30; access=visitor', tags: ['service-context-toilets', 'current-context'] })];
const picnic = [make({ id: 'curated-picnic:torry-battery', name: 'Torry Battery Picnic Viewpoint', coordinates: [-2.0591332, 57.1415966], locationType: 'representative_point', website: urls.battery, featureType: 'other', description: 'Outdoor benches and grass around the Battery provide an informal picnic stop with harbour and coastal views; no table count or reservable provision is published.', evidenceUrls: [urls.battery, urls.visit], sourceName: 'Greyhope Bay Torry Battery guide', sourceOrganisation: 'Greyhope Bay', placeType: 'Picnic area', details: 'tourism=picnic_site; fee=no; table_count=Not published; shelter=Greyhope Bay Centre during opening hours; restrictions=Protect the scheduled monument and remove litter', tags: ['service-context-picnic', 'current-context'] })];

const auditedFeatures = [...heritage, ...trails, ...foods, ...parking, ...toilets, ...picnic];
const auditedFeatureIds = new Set(auditedFeatures.map((feature) => feature.id));
pkg.features = [...auditedFeatures, ...pkg.features.filter((feature) => feature.tags.includes('hes-listed-building') && !auditedFeatureIds.has(feature.id))];
const highlights: VisitorHighlight[] = attractions.map((a, i) => ({ rank: i + 1, featureId: a.f.id, name: a.f.name, reason: a.reason, tagline: a.tag, visitorScore: a.score, timeToSpend: a.time, openingTimes: a.open, admission: a.admission, freeAdmission: /^Free/.test(a.admission), visitorWebsiteUrl: a.web, attractionGuide: a.guide, editorialReview: a.f.editorialReview, sourceName: a.f.sourceRecords[0].sourceName, sourceUrl: a.web, verifiedInBoundaryAt: reviewedDate }));
pkg.project.preferredBasemap = 'voyager';
pkg.project.boundary = { type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates: [[[-2.099, 57.128], [-2.099, 57.142], [-2.087, 57.145], [-2.046, 57.145], [-2.046, 57.139], [-2.058, 57.130], [-2.079, 57.126], [-2.099, 57.128]]] } };
pkg.project.boundarySource = 'Explicit Torry visitor district covering the urban settlement, River Dee edge, Torry Battery and harbour approach; central Aberdeen, Nigg, St Fittick’s Park and Girdle Ness remain separate records';
pkg.project.boundaryConfidence = 'medium';
pkg.project.touristAppeal = { score: 76, dogOwnerScore: 75, dogAccessScoreAdjustment: -1, rating: 1, label: 'Worth a Visit', summary: 'A distinctive maritime district whose own draw combines Torry Battery, dolphin watching, harbour heritage and four unusually detailed local trails.', dogAccessRating: 3, dogAccessSummary: 'Greyhope Bay explicitly welcomes well-behaved dogs and the main experiences are outdoors; use close control around wildlife, roads, harbour operations and shared paths.', methodVersion: '2026-08-27-strict-settlement-full-audit-v2', reviewedAt: reviewedDate, sourceUrls: Object.values(urls) };
pkg.project.visitorHighlights = highlights;
pkg.project.townGuide = { characterTag: 'Maritime community and dolphin-watching headland', headline: 'A working harbour district with a remarkable coastal finale', intro: 'Torry is a 76% Worth a Visit destination on its own merits. Its strongest experience is Torry Battery and Greyhope Bay, backed by rare harbour lights, the historic Victoria Bridge and four council trails rooted in the district’s own story.', bestFor: ['Dolphin and ship watching', 'Military and maritime heritage', 'Coffee with a coastal view', 'Self-guided local trails'], perfectFor: ['A coastal half day', 'A dog-friendly outdoor visit', 'An industrial-heritage walk'], suggestedFirstVisit: { title: 'Start at Victoria Bridge and finish at the Battery', summary: 'Follow Torry’s urban or industrial story east along the harbour edge, then allow time for the Battery, Greyhope Bay Café and dolphin watching.' }, dontMiss: ['Torry Battery and Greyhope Bay', 'Victoria Bridge', 'Aberdeen Harbour Leading Lights', 'Torry Coastal Trail'], suggestedTime: 'Half day; longer for a full trail', visitorMood: 'Working, weather-exposed and deeply connected to Aberdeen’s fishing, harbour and defence history.', practicalNote: 'The Battery has three parking areas, accessible bays, two accessible toilets during centre hours and an informal picnic viewpoint. Unknown parking capacities, tariffs and time limits are left explicit.', transportNote: 'First Bus route 12 and Stagecoach route 59 serve the wider Torry/Balnagask area; the Greyhope Bay walk from the nearest stop is about ten minutes over grass.', accessibilityNote: 'Greyhope Bay publishes accessible parking and two accessible toilets. Historic paths, grass and the Battery’s scheduled-monument fabric can be uneven; the urban trails include working roads and harbour edges.', sourceUrls: Object.values(urls), lastReviewedAt: reviewedDate };
pkg.project.visualIdentity = {
  theme: 'torry-battery-coastal-watercolour',
  badgeImage: '/town-guides/torry-battery-coastal-watercolour-guide-v1.png',
  badgeAlt: 'Ink-and-watercolour illustration of Torry Battery overlooking the coastal headland, sea and distant lighthouse',
  heroImage: '/town-guides/torry-battery-coastal-watercolour-guide-v1.png',
  heroAlt: 'Ink-and-watercolour illustration of Torry Battery overlooking the coastal headland, sea and distant lighthouse',
  heroObjectPosition: '50% 58%',
  motifs: ['Torry Battery', 'Greyhope headland', 'North Sea', 'Harbour skyline'],
  primaryColour: '#294F55',
  accentColour: '#B8842E',
  backgroundColour: '#EDF2EA',
};

planner.projects[projectId] = { eat: foods.map((f) => f.id), trails: trails.map((f) => f.id), parking: parking.map((f) => f.id), toilets: toilets.map((f) => f.id), picnic: picnic.map((f) => f.id) };
const dr = (rating: number, status: string, label: string, summary: string, sourceUrl: string) => ({ rating, status, label, summary, sourceName: 'Torry dog-access audit', sourceUrl, reviewedAt: reviewedDate });
dog.reviewedAt = reviewedDate;
dog.projects[projectId] = {
  attraction: Object.fromEntries(attractions.map((a) => [a.f.id, a.f.id.includes('SM9215') ? dr(3, 'welcoming', 'Well-behaved dogs explicitly welcome', 'Greyhope Bay welcomes well-behaved four-legged visitors; keep close control around the scheduled monument, wildlife and café.', urls.visit) : dr(2, 'restricted', 'Outdoor landmark with close control', 'Dogs can accompany the open-air stop, with a short lead around roads, harbour operations and other visitors.', urls.dogCode)])),
  trail: Object.fromEntries(trails.map((f) => [f.id, dr(2, 'restricted', 'Public outdoor route with close control', 'Dogs can accompany the route, but roads, harbour activity, wildlife and boundary-crossing sections require responsible close control.', urls.dogCode)])),
  eat: Object.fromEntries(foods.map((f) => [f.id, f.id.includes('greyhope') ? dr(3, 'welcoming', 'Well-behaved dogs welcome', 'The operator explicitly welcomes well-behaved four-legged visitors.', urls.visit) : dr(1, 'unknown', 'Pet policy not established', 'No dependable current operator statement on ordinary pet-dog access was found; confirm before entering.', f.visitorWebsiteUrl!)])),
};

pkg.validation = validateFeatures(pkg.project, pkg.features);
const errors = pkg.validation.filter((entry: any) => entry.severity === 'error');
if (errors.length) throw new Error(errors.map((entry: any) => entry.message).join('; '));
const historicPins = pkg.features.filter((feature) => feature.tags.some((tag: string) => ['hes-listed-building', 'hes-scheduled-monument'].includes(tag)) && !feature.tags.includes('map-hidden'));
const undated = historicPins.filter((feature) => !feature.documentedDateText?.trim() || feature.earliestPossibleYear == null || feature.latestPossibleYear == null || feature.dateBasis === 'unknown');
if (undated.length) throw new Error(`Undated Torry pins: ${undated.map((feature) => feature.id).join(', ')}`);
await writeFile(projectPath, `${JSON.stringify(pkg, null, 2)}\n`);
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`);
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`);
await writeFile(reportPath, `${JSON.stringify({ reviewedAt, townScore: 76, dogOwnerScore: 75, dogAccessRating: 3, categoryCounts: { see: highlights.length, eat: foods.length, trails: trails.length, picnic: picnic.length, parking: parking.length, toilets: toilets.length, heritage: historicPins.length }, heritageDateAudit: { visiblePins: historicPins.length, dated: historicPins.length - undated.length, undated: undated.map((feature) => feature.id), dateRule: 'Construction, opening and material alteration dates, never designation dates.' }, trailProviderSearches: [{ provider: 'Aberdeen City Council', result: 'Four exact Torry guides verified: Churches, Coastal, Industrial and Maritime, and Urban.' }, { provider: 'TreasureTrails.co.uk', result: 'Aberdeen city-centre product found; no exact Torry product established, so none published.' }, { provider: 'Curious About', result: 'No exact Torry route established.' }, { provider: 'Mystery Guides', result: 'No exact Torry product established.' }, { provider: 'Go Quest Adventures', result: 'No exact Torry product established.' }], boundaryExclusions: [{ place: 'Girdle Ness Lighthouse and Torry Coo', result: 'Excluded from Torry town scoring and See publication because they sit in the Nigg/Girdle Ness record.' }, { place: 'St Fittick’s Park, old church and Nigg Kirk', result: 'Acknowledged only where council trails cross the boundary; excluded from Torry settlement scoring and standalone See pins.' }, { place: 'Central Aberdeen and Footdee attractions', result: 'Excluded from Torry scoring and publication.' }], parking: parking.map((feature) => ({ name: feature.name, detail: feature.shortDescription, source: feature.visitorWebsiteUrl })), toilets: toilets.map((feature) => ({ name: feature.name, detail: feature.shortDescription, source: feature.visitorWebsiteUrl })), picnic: picnic.map((feature) => ({ name: feature.name, detail: feature.shortDescription, source: feature.visitorWebsiteUrl })), verification: { heritagePinsDated: `${historicPins.length - undated.length}/${historicPins.length}`, undatedHistoricPins: undated.length } }, null, 2)}\n`);
console.log(`Torry audit complete: ${highlights.length} See, ${foods.length} Eats, ${trails.length} Trails, ${picnic.length} Picnic, ${parking.length} Parking, ${toilets.length} Toilets; ${historicPins.length - undated.length}/${historicPins.length} heritage pins dated.`);
