import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const id = 'east-cairnbeg-scotland', day = '2026-08-30', at = '2026-08-30T23:59:00Z';
const projectPath = resolve('data/projects/east-cairnbeg.json');
const plannerPath = resolve('data/cairn-o-mount-visitor-planner-curation.json');
const dogPath = resolve('data/cairn-o-mount-dog-access-curation.json');
const reportPath = resolve('data/review/east-cairnbeg-full-visitor-audit-2026-08-30.json');
const correctionPath = resolve('data/review/strict-settlement-score-correction-2026-08-30.json');
const urls = { settlement: 'https://www.openstreetmap.org/?mlat=56.8827877&mlon=-2.4815884#map=16/56.8827877/-2.4815884', enclosure: 'https://www.trove.scot/place/36451', farmstead: 'https://www.trove.scot/place/168380', cropmarks: 'https://www.trove.scot/place/331380', treasure: 'https://www.treasuretrails.co.uk/collections/aberdeenshire', curious: 'https://www.curiousabout.co.uk/', mystery: 'https://www.mysteryguides.co.uk/', goQuest: 'https://goquestadventures.com/', toilets: 'https://www.aberdeenshire.gov.uk/local/public-toilets', outdoor: 'https://www.outdooraccess-scotland.scot/dog-owners' };
const pkg: any = JSON.parse(await readFile(projectPath, 'utf8'));
const planner: any = JSON.parse(await readFile(plannerPath, 'utf8'));
const dog: any = JSON.parse(await readFile(dogPath, 'utf8'));
const correction: any = JSON.parse(await readFile(correctionPath, 'utf8'));

for (const feature of pkg.features) {
  if (!feature.tags.includes('nrhe')) continue;
  feature.reviewed = true; feature.updatedAt = at; feature.tags = [...new Set(feature.tags.concat('heritage-record-retained'))];
  if (feature.id === 'nrhe:36451') {
    Object.assign(feature, { documentedDateText: 'Prehistoric palisaded enclosure', earliestPossibleYear: -4000, latestPossibleYear: 400, dateBasis: 'estimated_from_authoritative_source', dateConfidence: 'medium' });
    feature.tags = [...new Set(feature.tags.filter((tag: string) => tag !== 'map-hidden').concat('date-reviewed'))];
    feature.reviewNotes = 'The local HES NRHE classification explicitly identifies a prehistoric palisaded enclosure. The broad period is shown without claiming an exact year; map name unchanged.';
  } else {
    feature.tags = [...new Set(feature.tags.concat('map-hidden'))];
    feature.reviewNotes = 'Retained from the local HES NRHE source but map-hidden because the official classification is period unassigned and no defensible material date was verified.';
  }
}
pkg.features = pkg.features.filter((feature: any) => !feature.id.startsWith('curated-'));
pkg.project.visitorHighlights = [];
pkg.project.preferredBasemap = 'voyager';
pkg.project.touristAppeal = { score: 20, dogOwnerScore: 18, dogAccessScoreAdjustment: -2, rating: 0, label: 'Minor Interest', summary: 'A dispersed rural locality without a verified independent visitor experience or public facility cluster.', dogAccessRating: 1, dogAccessSummary: 'No dedicated dog destination, published dog route or dog facility is verified here.', methodVersion: '2026-08-30-strict-settlement-full-audit-v3', reviewedAt: day, sourceUrls: Object.values(urls) };
pkg.project.townGuide = { characterTag: 'Dispersed rural Mearns locality', headline: 'A map reference rather than a visitor destination', intro: 'East Cairnbeg scores 20% and remains in the selector but not on the town map. Its prehistoric enclosure is retained as historic evidence rather than promoted as a managed attraction.', bestFor: ['Regional orientation', 'Archaeological landscape research'], perfectFor: ['Locating the locality during a wider Mearns journey'], suggestedFirstVisit: { title: 'Treat it as a route reference', summary: 'No verified public itinerary or visitor facility exists inside the strict study area.' }, dontMiss: [], suggestedTime: 'Pass-through only', visitorMood: 'Scattered rural properties with buried archaeological evidence, not a visitable village centre.', sourceUrls: Object.values(urls), lastReviewedAt: day };
pkg.project.researchNotes = 'Full sequential audit. Local HES checks found no listed buildings or scheduled monuments and retained all three NRHE records. The prehistoric palisaded enclosure is visible as a broadly dated heat pin; two period-unassigned records remain map-hidden. No qualifying See, café-led Eat, named trail, picnic place, public parking or public toilet was verified inside the strict boundary. Nearby Fettercairn and Laurencekirk offers are not borrowed.';
planner.projects[id] = { eat: [], trails: [], picnic: [], parking: [], toilets: [] };
dog.projects[id] = {};
const heritage = pkg.features.filter((feature: any) => feature.tags.includes('nrhe') || feature.tags.includes('hes-listed-building') || feature.tags.includes('hes-scheduled-monument'));
const statutory = heritage.filter((feature: any) => feature.tags.includes('hes-listed-building') || feature.tags.includes('hes-scheduled-monument'));
const visible = heritage.filter((feature: any) => !feature.tags.includes('map-hidden'));
const report = { reviewedAt: at, projectId: id, status: 'verified', settlementScore: 20, previousScore: 24, independentlyWorthwhile: false, publishOnTownMap: false, scoreRationale: 'A dispersed rural locality with no independently visitable centre, attraction or visitor-service cluster.', publication: { see: 0, eat: 0, trails: 0, picnic: 0, parking: 0, toilets: 0 }, heritage: { expectedStatutoryRecords: 0, representedStatutoryRecords: statutory.length, nrheRecordsRetained: heritage.filter((feature: any) => feature.tags.includes('nrhe')).length, visibleDatedHeritagePins: visible.length, visibleUndatedHeritagePins: visible.filter((feature: any) => !feature.documentedDateText).length, hiddenUndatedRecords: heritage.filter((feature: any) => feature.tags.includes('map-hidden')).map((feature: any) => feature.id) }, namedTrailSearch: { TreasureTrails: 'The live Aberdeenshire catalogue has no East Cairnbeg product.', CuriousAbout: 'No East Cairnbeg product found.', MysteryGuides: 'No East Cairnbeg product found.', GoQuestAdventures: 'No East Cairnbeg product found.', retained: [] }, practicalAudit: { see: 'The prehistoric enclosure is an archaeological record without verified managed access or interpretation, so it remains a heat pin rather than a See card.', eat: 'No café, coffee-and-cake outlet, tearoom, bakery or light-lunch venue was verified inside the strict boundary.', picnic: 'No managed public picnic facility was verified.', parking: 'No dedicated public visitor parking was verified; private farm and residential access is not parking.', toilets: 'No local public toilet was verified and East Cairnbeg is absent from the council directory.', accessibility: 'No managed visitor facility publishes accessibility information.', transport: 'Dispersed rural locality with no attraction-specific arrival provision.' }, exclusions: ['Nearby Fettercairn and Laurencekirk attractions and facilities are outside the boundary.', 'Private farm access is not a visitor facility.', 'The NRHE enclosure is not converted into a tourist attraction without managed access.'], verification: { localListedBuildingImport: { added: 0, refreshed: 0, bufferCandidates: 0 }, localNrheImport: { added: 0, linked: 0, excludedCandidates: 0 }, statutoryDatasetComplete: statutory.length === 0, allVisibleHeritagePinsDated: visible.every((feature: any) => feature.documentedDateText && feature.dateBasis !== 'unknown'), datesStoredWithoutChangingMapNames: visible.every((feature: any) => !feature.name.includes(feature.documentedDateText)), trailLinksChecked: [urls.treasure, urls.curious, urls.mystery, urls.goQuest], allCuratedCoordinatesCheckedAgainstBoundary: true } };
const row = correction.results.find((value: any) => value.projectId === id); if (row) { row.correctedScore = 20; row.changed = row.previousScore !== 20; row.publishOnTownMap = false; row.rationale = pkg.project.touristAppeal.summary; row.sourceUrls = [urls.settlement, urls.enclosure, urls.treasure]; }
correction.changedScores = correction.results.filter((value: any) => value.changed).length; correction.mappedAfterCorrection = correction.results.filter((value: any) => value.correctedScore >= 60).map((value: any) => ({ projectId: value.projectId, name: value.name, score: value.correctedScore }));
await writeFile(projectPath, `${JSON.stringify(pkg, null, 2)}\n`); await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`); await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`); await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`); await writeFile(correctionPath, `${JSON.stringify(correction, null, 2)}\n`); console.log(JSON.stringify(report, null, 2));
