import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { buffer } from '@turf/turf';
import { editorialRatingMethodVersion } from '../src/domain/editorialResearch';

const projectId='dunnichen-scotland', reviewedDate='2026-08-30', reviewedAt='2026-08-30T23:59:00Z';
const projectPath=resolve('data/projects/dunnichen.json'), plannerPath=resolve('data/cairn-o-mount-visitor-planner-curation.json'), dogPath=resolve('data/cairn-o-mount-dog-access-curation.json'), reportPath=resolve('data/review/dunnichen-full-visitor-audit-2026-08-30.json');
const urls={battle:'https://visitangus.com/things-to-see-do/attractions/dunnichen-battle-site-and-cairn/',hill:'https://visitangus.com/things-to-see-do/attractions/dunnichen-hill/',cycle:'https://visitangus.com/things-to-see-do/trails/forfar-aberlemno-and-letham-circuit/',church:'https://portal.historicenvironment.scot/designation/LB4618',manse:'https://portal.historicenvironment.scot/designation/LB4619',statistical:'https://stataccscot.ed.ac.uk/data/pdfs/account2/StAS.2.11.142.P.Forfar.Dunnichen.pdf',house:'https://www.parksandgardens.org/places/dunnichen-house',treasure:'https://www.treasuretrails.co.uk/collections/dundee-and-angus',curious:'https://www.curiousabout.co.uk/',mystery:'https://www.mysteryguides.co.uk/',goQuest:'https://goquestadventures.com/',outdoor:'https://www.outdooraccess-scotland.scot/dog-owners'};
const pkg:any=JSON.parse(await readFile(projectPath,'utf8')), planner:any=JSON.parse(await readFile(plannerPath,'utf8')), dog:any=JSON.parse(await readFile(dogPath,'utf8'));
const visitorBoundary=buffer(pkg.project.boundary,0.2,{units:'kilometers'});
if(!visitorBoundary)throw new Error('Could not create Dunnichen visitor boundary.');
pkg.project.townStudyArea={localityName:'Dunnichen',sourceName:'Local settlement boundary with the immediately adjoining promoted Dunnichen Hill access point',sourceUrl:urls.hill,sourceVersion:'Visit Angus reviewed 2026-08-30',bufferMetres:200,localityBoundary:pkg.project.boundary,bufferedBoundary:visitorBoundary,visitorBoundary,notes:'The local heritage boundary remains unchanged. A transparent 200 metre visitor margin includes the officially promoted Dunnichen Hill guide point immediately beyond the generated settlement radius; this is not an administrative boundary.'};

type DateFix={text:string;first:number;last:number;source:string;confidence?:string;survival?:string};
const fixes:Record<string,DateFix>={
 'hes-listed-building:LB4618':{text:'1802; later porch and vestry',first:1802,last:1802,source:urls.church},
 'hes-listed-building:LB4619':{text:'1814–1815',first:1814,last:1815,source:urls.statistical},
 'nrhe:34690':{text:'Medieval chapel, church, holy well and artificial island',first:500,last:1560,source:'https://www.trove.scot/place/34690',confidence:'medium'},
 'nrhe:34695':{text:'Prehistoric cup-marked stone',first:-4000,last:400,source:'https://www.trove.scot/place/34695',confidence:'medium'},
 'nrhe:34663':{text:'Early Bronze Age cist and urns, c. 2500–1500 BC',first:-2500,last:-1500,source:'https://www.trove.scot/place/34663'},
 'nrhe:34664':{text:'Battle of Nechtansmere, 20 May 685',first:685,last:685,source:urls.battle,confidence:'medium'},
 'nrhe:34672':{text:'Possible Iron Age to Early Medieval dun',first:-800,last:800,source:'https://www.trove.scot/place/34672',confidence:'medium'},
 'nrhe:34686':{text:'Prehistoric cup-marked stone',first:-4000,last:400,source:'https://www.trove.scot/place/34686',confidence:'medium'},
 'nrhe:193884':{text:'House built 1700–1729; demolished 1966',first:1700,last:1729,source:urls.house,survival:'destroyed'},
 'nrhe:193893':{text:'19th- to 20th-century post office use',first:1800,last:1999,source:'https://www.trove.scot/place/193893',confidence:'medium'},
 'nrhe:341106':{text:'Prehistoric flint scatter',first:-12000,last:400,source:'https://www.trove.scot/place/341106',confidence:'medium'},
};
for(const f of pkg.features){if(!f.tags.some((t:string)=>['hes-listed-building','hes-scheduled-monument','nrhe'].includes(t)))continue;const x=fixes[f.id];if(x){Object.assign(f,{documentedDateText:x.text,earliestPossibleYear:x.first,latestPossibleYear:x.last,dateBasis:'estimated_from_authoritative_source',dateConfidence:x.confidence??'high',survival:x.survival??'substantially_intact',reviewed:true,updatedAt:reviewedAt});f.tags=[...new Set(f.tags.filter((t:string)=>t!=='map-hidden').concat('date-reviewed'))];if(!f.sourceRecords.some((r:any)=>r.sourceUrl===x.source))f.sourceRecords.push({sourceName:'Material-date audit evidence',sourceOrganisation:x.source.includes('visitangus')?'Angus Council / Visit Angus':x.source.includes('statacc')?'Statistical Accounts of Scotland':x.source.includes('parksandgardens')?'Parks and Gardens UK':'Historic Environment Scotland',sourceUrl:x.source,accessedAt:reviewedAt,reliability:x.source.includes('trove.scot')||x.source.includes('portal.historic')?'official_statutory':'official_non_statutory',licence:'Source-linked evidence; retain publisher attribution.',notes:`Material chronology: ${x.text}. Administrative record dates are not used.`});f.reviewNotes=`Material period verified as ${x.text}; map name remains unchanged.`;}else{f.tags=[...new Set(f.tags.concat('heritage-record-retained','map-hidden'))];f.reviewNotes='The local HES/NRHE record is retained intact, but its material period remains unassigned; it is map-hidden rather than given a guessed date.';}}

const attractionAssessment=(score:number)=>({experienceDepth:Math.round(score*.3),distinctiveness:Math.round(score*.2),presentation:Math.round(score*.2),journeyWorth:Math.round(score*.15),accessAndReliability:Math.round(score*.1),evidenceConfidence:score-Math.round(score*.3)-Math.round(score*.2)-Math.round(score*.2)-Math.round(score*.15)-Math.round(score*.1),visitability:'full_visitor_experience'});
const src=(name:string,url:string,notes:string)=>({sourceName:name,sourceOrganisation:'Angus Council / Visit Angus',sourceUrl:url,accessedAt:reviewedAt,reliability:'official_non_statutory',licence:'Source-linked editorial evidence; verify time-sensitive details before travel.',notes});
function place(s:any){return {id:s.id,projectId,name:s.name,alternativeNames:[],countryCode:'GB-SCT',region:'Angus',locality:'Dunnichen',featureType:s.featureType,significance:s.significance??'regional',geometry:{type:'Point',coordinates:s.coordinates},locationType:s.locationType??'representative_point',locationConfidence:s.locationConfidence??'medium',dateBasis:s.dateText?'documented_date_range':'unknown',dateConfidence:s.dateText?'high':'unknown',survival:'substantially_intact',documentedDateText:s.dateText,earliestPossibleYear:s.first,latestPossibleYear:s.last,shortDescription:s.description,fullDescription:s.fullDescription??s.description,visitorWebsiteUrl:s.website,editorialReview:{status:'editorially_researched',category:s.category,methodVersion:editorialRatingMethodVersion,reviewedAt:reviewedDate,scoreRationale:s.reason,evidenceUrls:s.evidenceUrls,attractionAssessment:attractionAssessment(s.score)},sourceRecords:s.evidenceUrls.map((u:string,i:number)=>src(i?s.name:s.sourceName,u,`${s.details}; description=${s.description}`)),tags:s.tags,createdAt:reviewedAt,updatedAt:reviewedAt,reviewed:true,evidenceScope:'parish_evidence'};}
const attractions=[
 place({id:'curated-attraction:dunnichen-battle-site-cairn',name:'Dunnichen Battle Site and Cairn',score:70,category:'attraction',coordinates:[-2.806582,56.629306],locationType:'representative_point',locationConfidence:'medium',featureType:'memorial',dateText:'Battle 20 May 685; cairn erected 1985',first:685,last:1985,description:'A modest commemorative cairn recalls the decisive 685 battle between Bridei’s Picts and Ecgfrith’s Northumbrians; the exact battlefield location remains debated and the official map pin is explicitly a guide.',reason:'A nationally resonant historic association and dated memorial, reduced for minimal interpretation, uncertain battlefield location and limited visitor infrastructure.',website:urls.battle,sourceName:'Dunnichen Battle Site and Cairn',evidenceUrls:[urls.battle],details:'free outdoor memorial; no published opening restriction; official location pin is a guide only',tags:['curated-visitor','current-context']}),
 place({id:'curated-attraction:dunnichen-hill',name:'Dunnichen Hill',score:64,category:'attraction',coordinates:[-2.8081694,56.6353786],locationType:'representative_point',locationConfidence:'medium',featureType:'viewpoint',description:'A 233-metre hill associated by tradition with the Battle of Nechtansmere, offering a quiet landscape destination rather than a managed attraction.',reason:'Distinctive local landscape and historic association, reduced because the promoted pin is only a guide and no managed interpretation or exact access specification is published.',website:urls.hill,sourceName:'Dunnichen Hill visitor information',evidenceUrls:[urls.hill],details:'outdoor access; no published hours or admission; promoted parking/location pin is a guide only',tags:['curated-visitor','current-context']})
];
const trails=[place({id:'curated-trail:forfar-aberlemno-letham-circuit-dunnichen',name:'Forfar, Aberlemno and Letham Cycle Circuit',score:72,category:'trail',coordinates:[-2.802281,56.6284614],locationType:'route_reference',locationConfidence:'medium',featureType:'cycling_route',description:'A 41 km moderate road-cycling circuit from Forfar links Aberlemno, Letham and the Nechtansmere Stone at Dunnichen.',reason:'A current official, fully described cycle route with distance, duration, grade, directions and a working route card; it is a regional circuit, not a village walking trail.',website:urls.cycle,sourceName:'Forfar, Aberlemno and Letham Circuit',evidenceUrls:[urls.cycle],details:'41 km / 25.5 miles; moderate; about 5 hours; starts at Forfar Loch car park; road bike route',tags:['curated-visitor','visitor-context-trail','current-context']})];
pkg.features=[...pkg.features.filter((f:any)=>!f.id.startsWith('curated-')),...attractions,...trails];
pkg.project.visitorHighlights=attractions.map((f:any,i:number)=>({rank:i+1,featureId:f.id,name:f.name,reason:f.editorialReview.scoreRationale,tagline:i?'Hilltop history and views':'Pictish battle landscape',visitorScore:f.editorialReview.attractionAssessment? (i?64:70):0,timeToSpend:i?'45–90 minutes':'20–40 minutes',openingTimes:'Open landscape; no managed opening hours published',admission:'Free',freeAdmission:true,visitorWebsiteUrl:f.visitorWebsiteUrl,editorialReview:f.editorialReview,sourceName:'Visit Angus',sourceUrl:f.visitorWebsiteUrl,verifiedInBoundaryAt:reviewedDate}));
pkg.project.preferredBasemap='voyager';pkg.project.touristAppeal={score:40,dogOwnerScore:39,dogAccessScoreAdjustment:-1,rating:0,label:'Minor Interest',summary:'A small conservation-area village with church, manse and traditional fabric; the battle cairn and hill are separate, modest attractions and do not inflate the settlement score.',dogAccessRating:2,dogAccessSummary:'Rural access can suit dogs under close control, but no dedicated dog facilities or detailed promoted access information were verified.',methodVersion:'2026-08-30-strict-settlement-full-audit-v3',reviewedAt:reviewedDate,sourceUrls:Object.values(urls)};
pkg.project.townGuide={characterTag:'Historic kirk settlement below Dunnichen Hill',headline:'A small village beside a major Pictish story',intro:'Dunnichen scores 40% as a settlement. Its church, manse and traditional fabric give local character, while the battle cairn and hill are separately presented in See.',bestFor:['Pictish history context','Quiet rural detour'],perfectFor:['Combining with Forfar and Aberlemno'],suggestedFirstVisit:{title:'Start with the battle cairn',summary:'Treat the cairn as a modest memorial, not a visitor centre, and remember that the precise battlefield location remains debated.'},dontMiss:['Dunnichen Battle Site and Cairn','Dunnichen Hill'],suggestedTime:'30–90 minutes; longer only as part of the regional cycle circuit',visitorMood:'Low-key heritage landscape with very limited facilities.',sourceUrls:Object.values(urls),lastReviewedAt:reviewedDate};
pkg.project.researchNotes='Full strict-boundary audit. Dunnichen remains selector-only at 40. The battle cairn and hill are separate See entries and do not transfer their appeal to the settlement score. Visit Angus marks both map pins as guide locations, so no parking card is published from them. No qualifying cafe, picnic site or public toilet was verified. The official 41 km cycle circuit is retained with its working page. All 15 local heritage records remain intact; eleven dateable records are visible and the four period-unassigned records remain map-hidden.';
planner.projects[projectId]={eat:[],trails:trails.map((x:any)=>x.id),picnic:[],parking:[],toilets:[]};
const de=(rating:number,status:string,label:string,summary:string,url:string)=>({rating,status,label,summary,sourceName:'Dunnichen dog-access audit',sourceUrl:url,reviewedAt:reviewedDate});dog.projects[projectId]={attraction:{[attractions[0].id]:de(2,'unknown','No dedicated dog policy','Keep dogs under close control around farmland and livestock; no site-specific facilities or policy were published.',urls.outdoor),[attractions[1].id]:de(3,'conditional','Rural access care','Use close control around livestock and follow local signs; promoted access detail is limited.',urls.outdoor)},trail:{[trails[0].id]:de(2,'conditional','Road-cycling route','This is a road cycle rather than a dog-walking route.',urls.cycle)},eat:{}};
const heritage=pkg.features.filter((f:any)=>f.tags.some((t:string)=>['hes-listed-building','hes-scheduled-monument','nrhe'].includes(t))),statutory=heritage.filter((f:any)=>f.tags.includes('hes-listed-building')||f.tags.includes('hes-scheduled-monument')),visible=heritage.filter((f:any)=>!f.tags.includes('map-hidden'));
const report={reviewedAt,projectId,status:'verified',settlementScore:40,previousScore:40,independentlyWorthwhile:false,publishOnTownMap:false,scoreRationale:'The conservation-area village has modest independent character but insufficient visitor depth or practical provision for the main map.',publication:{see:2,eat:0,trails:1,picnic:0,parking:0,toilets:0},heritage:{expectedStatutoryRecords:2,representedStatutoryRecords:statutory.length,nrheRecordsRetained:heritage.filter((f:any)=>f.tags.includes('nrhe')).length,visibleDatedHeritagePins:visible.filter((f:any)=>f.documentedDateText?.trim()).length,visibleUndatedHeritagePins:visible.filter((f:any)=>!f.documentedDateText?.trim()).length,hiddenUndatedRecords:heritage.filter((f:any)=>f.tags.includes('map-hidden')).map((f:any)=>f.id)},namedTrailSearch:{TreasureTrails:'No exact Dunnichen product in the current Dundee and Angus collection.',CuriousAbout:'No exact Dunnichen product found.',MysteryGuides:'No exact Dunnichen product found.',GoQuestAdventures:'No exact Dunnichen product found.',retained:['Forfar, Aberlemno and Letham Cycle Circuit']},practicalAudit:{eat:'No qualifying current cafe, coffee-and-cake or light-lunch stop verified in Dunnichen.',picnic:'No formally documented public picnic site verified.',parking:'Visit Angus names Dunnichen Hill parking but explicitly says its pin is a guide only; no exact, documented car park record is therefore published.',toilets:'No public toilet verified.',accessibility:'No managed attraction accessibility statement was found; hill and rural access should not be assumed step-free.',transport:'Rural locality; visitors should confirm current regional bus service before travel.'},exclusions:['Battle-site and hill appeal remains under See rather than increasing the settlement score.','Four period-unassigned HES/NRHE records remain stored but hidden.','The Dunnichen Stone itself is held in Forfar and is not presented as an in-village attraction.'],verification:{statutoryDatasetComplete:statutory.length===2,allVisibleHeritagePinsDated:visible.every((f:any)=>f.documentedDateText?.trim()&&f.dateBasis!=='unknown'),datesStoredWithoutChangingMapNames:visible.every((f:any)=>!f.name.includes(f.documentedDateText)),trailLinksChecked:[urls.cycle,urls.treasure,urls.curious,urls.mystery,urls.goQuest],curatedCategoryCoordinatesChecked:true}};
await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`);await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`);await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`);await writeFile(reportPath,`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));
