import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { townDogAccessScoreAdjustment, townScoreAfterDogAccess, townScoreBand } from '../src/domain/tourism';
import { validateFeatures } from '../src/domain/validation';

/* eslint-disable @typescript-eslint/no-explicit-any -- one-off data migration over versioned JSON packages */

const reviewedDate = '2026-09-02';
const reviewedAt = '2026-09-02T18:00:00.000Z';
const auditTag = 'woodside-leven-full-audit-2026-09-02';
const plannerPath = resolve('data/east-neuk-visitor-planner-curation.json');
const dogPath = resolve('data/east-neuk-dog-access-curation.json');
const treasure = 'https://www.treasuretrails.co.uk/products/things-to-do-lower-largo-fife';
const treasureCollection = 'https://www.treasuretrails.co.uk/collections/fife';
const curious = 'https://curiousabout.co.uk/';
const mystery = 'https://www.mysteryguides.co.uk/';
const goQuest = 'https://goquestadventures.com/';
const coastalPath = 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/buckhaven-to-elie/';
const levenLowerLargo = 'https://trails.welcometofife.com/levenmouth/leven-to-lower-largo/';

type Kind = 'attraction' | 'food' | 'trail' | 'picnic' | 'parking' | 'toilets';
type Feature = {
  id: string; name: string; kind: Kind; type: string; coordinates: [number, number]; description: string;
  tagline: string; url: string; source: string; organisation: string; opening: string; price: string;
  score: number; foodStyle?: string; details?: string[]; significance?: string; visitability?: string;
  dog?: { rating: 0 | 1 | 2 | 3; status: 'welcoming' | 'restricted' | 'not-allowed' | 'unconfirmed'; label: string; summary: string };
};
type Audit = {
  file: string; id: string; name: string; score: number; dogRating: number; summary: string; character: string;
  headline: string; intro: string; bestFor: string[]; perfectFor: string[]; time: string; mood: string;
  features: Feature[]; planner: Record<'eat' | 'trails' | 'picnic' | 'parking' | 'toilets', string[]>;
  providers: Record<string, string>; checks: Array<{ url: string; outcome: 'verified' | 'no_result' | 'excluded'; note: string }>;
  exclusions: string[]; notes?: Partial<Record<Kind, string>>;
};

const dogOutdoor = { rating: 2 as const, status: 'restricted' as const, label: 'Responsible outdoor access', summary: 'Dogs can accompany this outdoor visit but should be controlled around wildlife, livestock, roads and other visitors.' };
const dogUnknown = { rating: 0 as const, status: 'unconfirmed' as const, label: 'Dog policy not published', summary: 'No reliable current dog policy is published; contact the operator before visiting with a dog.' };
const noNamedTrail = (official: string): Record<string, string> => ({
  TreasureTrails: 'Current Fife catalogue checked; no live place-specific product.',
  CuriousAbout: 'Provider catalogue checked; no place-specific route.',
  MysteryGuides: 'Provider catalogue checked; no place-specific route.',
  GoQuestAdventures: 'Provider catalogue checked; no place-specific route.',
  officialRoutes: official,
});

const audits: Audit[] = [
  {
    file: 'woodside-largo.json', id: 'woodside-largo-scotland', name: 'Woodside (Largo)', score: 18, dogRating: 1,
    summary: 'Woodside is a tiny rural hamlet west of New Gilston. Current research found no independently visitable attraction, café-led daytime stop, maintained place-specific trail or public visitor facility inside its strict boundary.',
    character: 'Tiny rural hamlet', headline: 'A locality reference, not a visitor destination', intro: 'Woodside remains selectable for regional completeness without borrowing the attractions and services of Lundin Links, Lower Largo or New Gilston.',
    bestFor: ['Regional reference'], perfectFor: ['Locating the Largo-area hamlet'], time: 'Pass-through only', mood: 'Selector-only locality with no mapped visitor category.', features: [],
    planner: { eat: [], trails: [], picnic: [], parking: [], toilets: [] }, providers: noNamedTrail('No conventional place-specific visitor route was found.'),
    checks: [{ url: 'https://mapcarta.com/38899920', outcome: 'verified', note: 'Current gazetteer and OSM-linked record resolve the Fife hamlet west of New Gilston.' }, { url: treasureCollection, outcome: 'no_result', note: 'No Woodside (Largo) product.' }],
    exclusions: ['The same-name Aberdeen locality is a different place.', 'Lundin Links, Lower Largo and New Gilston attractions and services are outside the strict hamlet boundary.'],
  },
  {
    file: 'new-gilston.json', id: 'new-gilston-scotland', name: 'New Gilston', score: 30, dogRating: 1,
    summary: 'New Gilston has genuine early-18th-century mining-settlement history, but no current independently visitable attraction, café, promoted local trail or public visitor facility was verified in the village itself.',
    character: 'Historic linear mining village', headline: 'Settlement history without a visitor offer', intro: 'The village history is retained in the guide and heritage layer, but historic origin alone does not create a map-worthy visitor destination.',
    bestFor: ['Local-history context'], perfectFor: ['Passing through the Largo hinterland'], time: 'Pass-through only', mood: 'Selector-only village.', features: [],
    planner: { eat: [], trails: [], picnic: [], parking: [], toilets: [] }, providers: noNamedTrail('No conventional place-specific visitor route was found.'),
    checks: [{ url: 'https://fife-placenames.glasgow.ac.uk/placename/?id=1342', outcome: 'verified', note: 'Academic place-name record confirms the road settlement developed around 1700 for coal mining.' }, { url: treasureCollection, outcome: 'no_result', note: 'No New Gilston product.' }],
    exclusions: ['Heritage records are not promoted as visitor attractions without lawful access and an experience.', 'Nearby coastal villages and their facilities are not transferred.'],
  },
  {
    file: 'wester-newburn.json', id: 'wester-newburn-scotland', name: 'Wester Newburn', score: 14, dogRating: 1,
    summary: 'Wester Newburn resolves to a farm locality rather than a visitor village. No public attraction, café, trailhead, picnic site, visitor car park or public toilet was found inside its strict boundary.',
    character: 'Farm locality', headline: 'A named farm locality, not a visitor destination', intro: 'Wester Newburn remains available in the selector but receives no score from the wider Newburn parish or nearby Drumeldrie.',
    bestFor: ['Regional reference'], perfectFor: ['Locating the farm locality'], time: 'Pass-through only', mood: 'Selector-only locality.', features: [],
    planner: { eat: [], trails: [], picnic: [], parking: [], toilets: [] }, providers: noNamedTrail('No conventional place-specific visitor route was found.'),
    checks: [{ url: 'https://mapcarta.com/W516494991', outcome: 'verified', note: 'Current OSM-linked record resolves Wester Newburn as the farm locality.' }, { url: 'https://fife-placenames.glasgow.ac.uk/placename/?id=1585', outcome: 'verified', note: 'Academic record supplies wider Newburn name context only.' }, { url: treasureCollection, outcome: 'no_result', note: 'No Wester Newburn product.' }],
    exclusions: ['Newburn Old Parish Church and Drumeldrie services are outside Wester Newburn and do not support this score.'],
  },
  {
    file: 'lundin-links.json', id: 'lundin-links-scotland', name: 'Lundin Links', score: 78, dogRating: 2,
    summary: 'Lundin Links is a strong coastal stop: nationally important standing stones, shoreline, visitor golf, two credible coffee-and-cake options and three verified routes including a live Treasure Trail. The lack of a verified general public car park and public toilet keeps it below the top tier.',
    character: 'Coastal village, ancient stones and classic links', headline: 'Standing stones, shore walking and a live treasure hunt', intro: 'The score uses only visitor experiences and services in Lundin Links or routes that explicitly start in or pass through it; Lower Largo facilities are not borrowed.',
    bestFor: ['Prehistoric standing stones', 'Coastal walking', 'Coffee and scones', 'Visitor golf'], perfectFor: ['A half-day coast-and-heritage stop'], time: '3–5 hours', mood: 'A distinctive compact coastal destination with limited public facilities.',
    features: [
      { id: 'curated-attraction:lundin-standing-stones', name: 'Standing Stones of Lundin', kind: 'attraction', type: 'scheduled_monument', coordinates: [-2.9611735, 56.2133194], description: 'Three tall prehistoric standing stones, surviving from an original group and protected as a scheduled monument.', tagline: 'Prehistoric giants beside the links', url: 'https://www.welcometofife.com/destination/lundin-links', source: 'Lundin Links destination guide', organisation: 'Welcome to Fife', opening: 'Outdoor monument visible from the golf-course area; respect play, access signage and ground conditions.', price: 'Free', score: 82, significance: 'national', dog: dogOutdoor },
      { id: 'curated-attraction:lundin-shore', name: 'Lundin Links Shore and Largo Bay', kind: 'attraction', type: 'beach', coordinates: [-2.9517, 56.2068], description: 'A broad Forth shoreline on the official coastal route, with views across Largo Bay and onward walking to Lower Largo and Leven.', tagline: 'Open Forth views and coastal walking', url: coastalPath, source: 'Buckhaven to Elie', organisation: 'Fife Coast & Countryside Trust', opening: 'Open coast; check tides, weather and current path notices.', price: 'Free', score: 76, dog: dogOutdoor },
      { id: 'curated-attraction:lundin-golf', name: 'Lundin Golf Club', kind: 'attraction', type: 'outdoor_activity', coordinates: [-2.95545, 56.20966], description: 'A historic links course with current visitor and society booking information and clubhouse catering.', tagline: 'Visitor golf on the Forth links', url: 'https://lundingolfclub.co.uk/societies-and-outings/', source: 'Societies and Outings', organisation: 'Lundin Golf Club', opening: 'Visitor play by advance booking and current availability.', price: 'Green fees apply', score: 74, dog: dogUnknown },
      { id: 'curated-food:lundin-coffee-co', name: 'Lundin Coffee Co', kind: 'food', type: 'cafe', coordinates: [-2.9525962, 56.2138423], description: 'An independent village coffee stop in the former Lily’s Larder premises, focused on coffee, baking and light daytime food.', tagline: 'Village coffee and baking', url: 'https://www.largoct.org.uk/wp-content/uploads/Issue-16-Final-v-email.pdf', source: 'Largo Links', organisation: 'Largo Communities Together', opening: 'No reliable current opening hours are published; telephone before visiting.', price: '£', score: 72, foodStyle: 'coffee, cake and light lunch', dog: dogUnknown },
      { id: 'curated-food:lundin-old-manor', name: 'Old Manor Coffee and Scones', kind: 'food', type: 'cafe', coordinates: [-2.9613084, 56.2121443], description: 'Hotel lounge coffee and homemade scones served through the day, with bookable afternoon tea.', tagline: 'Sea-view coffee and scones', url: 'https://www.theoldmanorhotel.co.uk/menus/', source: 'Menus', organisation: 'The Old Manor Hotel', opening: 'Coffee and scones served all day; lounge menu advertised 10am–5pm; confirm current hours.', price: '££', score: 70, foodStyle: 'coffee, scones and afternoon tea', dog: dogUnknown },
      { id: 'curated-trail:lundin-treasure', name: 'Largo & Lundin Links – Harbour & Coast Path Treasure Trail', kind: 'trail', type: 'walking_route', coordinates: [-2.9544, 56.2126], description: 'A live 2.5-mile, roughly 2.5-hour self-guided detective mystery using village landmarks and the coast.', tagline: 'Clues across coast and village', url: treasure, source: 'Largo & Lundin Links Treasure Trail', organisation: 'Treasure Trails', opening: 'Self-guided download or printed route; complete in daylight and suitable weather.', price: '£10.99 per trail', score: 84 },
      { id: 'curated-trail:lundin-discovery', name: 'Leven to Lower Largo Discovery Trail', kind: 'trail', type: 'walking_route', coordinates: [-2.9544, 56.2126], description: 'A 5.4 km, roughly 1.5-hour official route through Leven, Silverburn, Lundin Links and Lower Largo.', tagline: 'Coast and villages in 5.4 km', url: levenLowerLargo, source: 'Leven to Lower Largo', organisation: 'Welcome to Fife Discovery Trails', opening: 'Open route; consult current trail information and conditions.', price: 'Free', score: 78 },
      { id: 'curated-trail:lundin-coastal-path', name: 'Fife Coastal Path at Lundin Links', kind: 'trail', type: 'walking_route', coordinates: [-2.9517, 56.2068], description: 'The official Buckhaven-to-Elie coastal stage follows the Largo Bay shore through Lundin Links.', tagline: 'Long-distance coast path', url: coastalPath, source: 'Buckhaven to Elie', organisation: 'Fife Coast & Countryside Trust', opening: 'Open route; consult current path notices and weather.', price: 'Free', score: 80 },
    ],
    planner: { eat: ['curated-food:lundin-coffee-co', 'curated-food:lundin-old-manor'], trails: ['curated-trail:lundin-treasure', 'curated-trail:lundin-discovery', 'curated-trail:lundin-coastal-path'], picnic: [], parking: [], toilets: [] },
    providers: { TreasureTrails: 'Live Largo & Lundin Links product verified: 2.5 miles and about 2.5 hours.', CuriousAbout: 'No Lundin Links route.', MysteryGuides: 'No Lundin Links route.', GoQuestAdventures: 'No Lundin Links route.', officialRoutes: 'Fife Discovery Trail and Fife Coastal Path pages verified.' },
    checks: [{ url: 'https://portal.historicenvironment.scot/designation/SM797', outcome: 'verified', note: 'HES confirms the protected prehistoric standing stones.' }, { url: treasure, outcome: 'verified', note: 'Live product confirms route, format, distance, duration and current price.' }, { url: levenLowerLargo, outcome: 'verified', note: 'Official trail confirms Lundin Links lies on the 5.4 km route.' }, { url: coastalPath, outcome: 'verified', note: 'Official coastal route serves the shoreline.' }, { url: 'https://lundingolfclub.co.uk/societies-and-outings/', outcome: 'verified', note: 'Operator publishes visitor and society booking information.' }, { url: 'https://www.theoldmanorhotel.co.uk/menus/', outcome: 'verified', note: 'Operator advertises coffee, homemade scones and afternoon tea.' }],
    exclusions: ['Lower Largo car parks and public toilets are not transferred to Lundin Links.', 'Golf-club and hotel parking are customer facilities, not published as general public parking.'], notes: { picnic: 'No dedicated public picnic facility was verified.', parking: 'No general public visitor car park was verified inside the boundary.', toilets: 'No always-open public toilet was verified inside the boundary.' },
  },
  {
    file: 'lower-largo.json', id: 'lower-largo-scotland', name: 'Lower Largo', score: 86, dogRating: 2,
    summary: 'Lower Largo is an excellent small coastal destination: historic harbour and waterfront, Alexander Selkirk associations, beach, a current café, four verified trails including Treasure Trails, two free council car parks, a public toilet and an informal beach picnic option.',
    character: 'Historic fishing village and Robinson Crusoe coast', headline: 'Harbour history, Selkirk and coast-path exploration', intro: 'The score is supported by a rounded experience inside Lower Largo itself, with no need to borrow Lundin Links or Leven attractions.',
    bestFor: ['Historic harbour streets', 'Alexander Selkirk history', 'Coastal trails', 'Coffee and cake'], perfectFor: ['A full half-day heritage-and-coast visit'], time: '4–6 hours', mood: 'A highly rewarding compact coastal village.',
    features: [
      { id: 'curated-attraction:lower-largo-harbour', name: 'Lower Largo Harbour', kind: 'attraction', type: 'harbour', coordinates: [-2.9411911, 56.2126977], description: 'The small historic harbour anchors the conservation-village waterfront and the fishing and maritime character of Lower Largo.', tagline: 'Historic harbour at the village heart', url: 'https://www.welcometofife.com/fife-icons/nostalgic-escapes', source: 'Nostalgic Escapes', organisation: 'Welcome to Fife', opening: 'Open waterfront; working-harbour, tide and weather cautions apply.', price: 'Free', score: 82, dog: dogOutdoor },
      { id: 'curated-attraction:lower-largo-selkirk', name: 'Alexander Selkirk Memorial', kind: 'attraction', type: 'memorial', coordinates: [-2.9355991, 56.2130405], description: 'A prominent memorial above Main Street marks the birthplace of Alexander Selkirk, whose castaway story inspired Robinson Crusoe.', tagline: 'The real castaway behind Crusoe', url: 'https://www.welcometofife.com/highlight/an-a-z-guide-to-visiting-levenmouth', source: 'A–Z Guide to Levenmouth', organisation: 'Welcome to Fife', opening: 'Outdoor street-side memorial, viewable at any reasonable time.', price: 'Free', score: 80, dog: dogOutdoor },
      { id: 'curated-attraction:lower-largo-waterfront', name: 'Lower Largo Beach and Historic Waterfront', kind: 'attraction', type: 'beach', coordinates: [-2.9385, 56.2119], description: 'A sandy Forth shore backed by the stone-built conservation village and linked directly to the coast path and harbour.', tagline: 'Sand, sea and conservation-village streets', url: 'https://www.welcometofife.com/destination/lower-largo', source: 'Lower Largo destination guide', organisation: 'Welcome to Fife', opening: 'Open coast; check tides and weather.', price: 'Free', score: 82, dog: dogOutdoor },
      { id: 'curated-food:lower-largo-aurrie', name: 'The Aurrie', kind: 'food', type: 'cafe', coordinates: [-2.936752, 56.2126143], description: 'A community arts venue with a year-round café serving coffee, breakfast, home baking and light meals in the village centre.', tagline: 'Creative-hub coffee and baking', url: 'https://www.theaurrie.com/', source: 'The Aurrie', organisation: 'The Aurrie', opening: 'No reliable current opening hours are published; telephone before visiting.', price: '£', score: 78, foodStyle: 'coffee, home baking, breakfast and light meals', dog: dogUnknown },
      { id: 'curated-trail:lower-largo-treasure', name: 'Largo & Lundin Links – Harbour & Coast Path Treasure Trail', kind: 'trail', type: 'walking_route', coordinates: [-2.9412, 56.2127], description: 'A live 2.5-mile, roughly 2.5-hour self-guided detective trail using the harbour, village features and coast path.', tagline: 'Harbour clues and coastal mystery', url: treasure, source: 'Largo & Lundin Links Treasure Trail', organisation: 'Treasure Trails', opening: 'Self-guided download or printed route; complete in daylight and suitable weather.', price: '£10.99 per trail', score: 84 },
      { id: 'curated-trail:lower-largo-crusoe', name: 'Crusoe’s Footsteps', kind: 'trail', type: 'walking_route', coordinates: [-2.9384, 56.2128], description: 'A short 0.8 km, roughly 20-minute official village trail exploring the places and stories associated with Alexander Selkirk.', tagline: 'Twenty minutes with the real Crusoe story', url: 'https://trails.welcometofife.com/levenmouth/crusoess-footsteps/', source: 'Crusoe’s Footsteps', organisation: 'Welcome to Fife Discovery Trails', opening: 'Self-guided outdoor route.', price: 'Free', score: 82 },
      { id: 'curated-trail:lower-largo-discovery', name: 'Leven to Lower Largo Discovery Trail', kind: 'trail', type: 'walking_route', coordinates: [-2.9412, 56.2127], description: 'A 5.4 km, roughly 1.5-hour official route linking Leven, Silverburn, Lundin Links and Lower Largo.', tagline: 'A coast-and-villages link from Leven', url: levenLowerLargo, source: 'Leven to Lower Largo', organisation: 'Welcome to Fife Discovery Trails', opening: 'Open route; check current conditions.', price: 'Free', score: 78 },
      { id: 'curated-trail:lower-largo-coastal-path', name: 'Fife Coastal Path at Lower Largo', kind: 'trail', type: 'walking_route', coordinates: [-2.9412, 56.2127], description: 'The official Buckhaven-to-Elie stage passes the harbour and village waterfront.', tagline: 'Coast path through the harbour village', url: coastalPath, source: 'Buckhaven to Elie', organisation: 'Fife Coast & Countryside Trust', opening: 'Open route; consult current path notices.', price: 'Free', score: 80 },
      { id: 'curated-picnic:lower-largo-beach', name: 'Largo Bay Beach Picnic', kind: 'picnic', type: 'picnic_site', coordinates: [-2.9385, 56.2119], description: 'An informal picnic on the beach beside the historic village; no dedicated tables or shelter are claimed.', tagline: 'A simple beach picnic', url: 'https://www.welcometofife.com/fife-icons/nostalgic-escapes', source: 'Nostalgic Escapes', organisation: 'Welcome to Fife', opening: 'Open coast; take litter home and check weather and tides.', price: 'Free', score: 70, details: ['informal_beach_picnic=yes'] },
      { id: 'curated-parking:lower-largo-old-station', name: 'Old Station Car Park', kind: 'parking', type: 'parking', coordinates: [-2.9400314, 56.2129012], description: 'Free council surface car park close to the harbour and western village centre.', tagline: 'Free harbour-side village parking', url: 'https://www.fife.gov.uk/facilities/car-park/old-station-car-park,-lower-largo', source: 'Old Station Car Park, Lower Largo', organisation: 'Fife Council', opening: 'Public surface car park.', price: 'Free', score: 80, details: ['fee=no'] },
      { id: 'curated-parking:lower-largo-temple', name: 'Temple Car Park', kind: 'parking', type: 'parking', coordinates: [-2.9325869, 56.2128356], description: 'Free council surface car park at the eastern side of the village, near the beach and public toilet.', tagline: 'Free east-village parking', url: 'https://www.fife.gov.uk/facilities/car-park/temple-car-park,-lower-largo', source: 'Temple Car Park, Lower Largo', organisation: 'Fife Council', opening: 'Public surface car park.', price: 'Free', score: 78, details: ['fee=no'] },
      { id: 'curated-toilets:lower-largo-temple', name: 'Temple Public Toilets', kind: 'toilets', type: 'toilets', coordinates: [-2.932912, 56.2127176], description: 'Public toilets beside Temple Car Park. The separately announced Changing Places proposal is not represented as complete without confirmation.', tagline: 'Public toilet by Temple Car Park', url: 'https://www.openstreetmap.org/node/2383376571', source: 'OpenStreetMap toilet record', organisation: 'OpenStreetMap contributors', opening: 'Check local signage for current opening and any seasonal closure.', price: 'Free according to current mapped record', score: 68, details: ['amenity=toilets', 'fee=no'] },
    ],
    planner: { eat: ['curated-food:lower-largo-aurrie'], trails: ['curated-trail:lower-largo-treasure', 'curated-trail:lower-largo-crusoe', 'curated-trail:lower-largo-discovery', 'curated-trail:lower-largo-coastal-path'], picnic: ['curated-picnic:lower-largo-beach'], parking: ['curated-parking:lower-largo-old-station', 'curated-parking:lower-largo-temple'], toilets: ['curated-toilets:lower-largo-temple'] },
    providers: { TreasureTrails: 'Live Largo & Lundin Links product verified.', CuriousAbout: 'No Lower Largo route.', MysteryGuides: 'No Lower Largo route.', GoQuestAdventures: 'No Lower Largo route.', officialRoutes: 'Crusoe’s Footsteps, Leven-to-Lower-Largo and Fife Coastal Path pages verified.' },
    checks: [{ url: treasure, outcome: 'verified', note: 'Live trail confirms format, distance, duration and price.' }, { url: 'https://trails.welcometofife.com/levenmouth/crusoess-footsteps/', outcome: 'verified', note: 'Official short Selkirk-themed route verified.' }, { url: 'https://www.theaurrie.com/', outcome: 'verified', note: 'Operator confirms a year-round café and daytime food.' }, { url: 'https://www.fife.gov.uk/facilities/car-park/old-station-car-park,-lower-largo', outcome: 'verified', note: 'Council car-park record verified.' }, { url: 'https://www.fife.gov.uk/facilities/car-park/temple-car-park,-lower-largo', outcome: 'verified', note: 'Council car-park record verified.' }, { url: 'https://www.openstreetmap.org/node/2383376571', outcome: 'verified', note: 'Current mapped toilet record verified; no unconfirmed Changing Places completion is claimed.' }],
    exclusions: ['Lundin Links venues are outside the village and not added to Lower Largo Eat.', 'The proposed Changing Places toilet is not presented as completed without current confirmation.'],
  },
  {
    file: 'drumeldrie.json', id: 'drumeldrie-scotland', name: 'Drumeldrie', score: 46, dogRating: 1,
    summary: 'Drumeldrie has meaningful parish history centred on the late-medieval remains of Newburn Old Parish Church and the nearby 1815 church, but no reliably open attraction interior, café, promoted village trail or public visitor facilities. It remains below the map threshold.',
    character: 'Small historic parish settlement', headline: 'Medieval church remains without visitor infrastructure', intro: 'The old church is a legitimate visible heritage stop, but it does not turn the settlement into a rounded visitor destination.',
    bestFor: ['Specialist church history'], perfectFor: ['A brief, respectful heritage stop'], time: '20–45 minutes', mood: 'A small heritage locality with no visitor hub.',
    features: [{ id: 'curated-attraction:drumeldrie-newburn-old-church', name: 'Newburn Old Parish Church', kind: 'attraction', type: 'church_ruin', coordinates: [-2.8836251, 56.2211149], description: 'Late-medieval parish-church remains with documented 12th-century origins and rebuilding between 1522 and 1539.', tagline: 'Medieval Newburn parish history', url: 'https://powis.scot/sites/newburn-ruins-parish-church-8137/', source: 'Newburn Ruins, Parish Church', organisation: 'Places of Worship in Scotland', opening: 'Outdoor graveyard setting; visit respectfully and observe access conditions.', price: 'Free', score: 66, significance: 'national', visitability: 'substantial_visible_remains', dog: dogOutdoor }],
    planner: { eat: [], trails: [], picnic: [], parking: [], toilets: [] }, providers: noNamedTrail('No maintained place-specific visitor route was verified.'),
    checks: [{ url: 'https://portal.historicenvironment.scot/designation/SM9848', outcome: 'verified', note: 'HES confirms late-medieval fabric and earlier origins.' }, { url: 'https://catalogue.nrscotland.gov.uk/nrsonlinecatalogue/browseDetails.aspx?reference=CH2%2F278', outcome: 'verified', note: 'NRS confirms rebuilding between 1522 and 1539 and replacement in 1815.' }, { url: 'https://www.fife.gov.uk/facilities/cemetery/newburn-graveyard', outcome: 'verified', note: 'Council facility record confirms the graveyard location.' }, { url: treasureCollection, outcome: 'no_result', note: 'No Drumeldrie product.' }],
    exclusions: ['The historic church is not treated as a staffed attraction.', 'No church parking or toilet is represented as a general public visitor facility without published evidence.'],
  },
  {
    file: 'leven-fife.json', id: 'leven-fife-scotland', name: 'Leven', score: 88, dogRating: 2,
    summary: 'Leven is a rounded coastal destination with a managed beach and promenade, heritage railway, two substantial parks, a family activity hub, five verified café-led daytime stops, four documented trails, picnic tables, two practical car parks and three public toilets.',
    character: 'Levenmouth coast, parks and railway heritage', headline: 'Beach, railway, parks and a strong café circuit', intro: 'Leven’s score is based on current experiences and facilities inside the town boundary, with attraction-only places elsewhere kept separate.',
    bestFor: ['Beach and promenade', 'Railway heritage', 'Woodland parks', 'Coffee and light lunches', 'Family activities'], perfectFor: ['A varied full day on the Levenmouth coast'], time: 'A full day', mood: 'A practical, well-supported coastal town with several distinct reasons to visit.',
    features: [
      { id: 'curated-attraction:leven-beach', name: 'Leven Beach and Promenade', kind: 'attraction', type: 'beach', coordinates: [-2.9876, 56.1982], description: 'A managed sandy beach with promenade, summer lifeguard service, play area, outdoor gym, putting green, picnic tables and coastal-path access.', tagline: 'A well-equipped Levenmouth beach', url: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-beaches/leven-beach/', source: 'Leven Beach', organisation: 'Fife Coast & Countryside Trust', opening: 'Open coast; lifeguard cover and facilities are seasonal, so check current notices.', price: 'Free', score: 86, dog: dogOutdoor },
      { id: 'curated-attraction:leven-heritage-railway', name: 'Fife Heritage Railway', kind: 'attraction', type: 'museum_railway', coordinates: [-3.0113868, 56.1955887], description: 'A volunteer-run railway heritage centre with operating days, restored stock, workshops and advertised guided tours.', tagline: 'Working railway history in Leven', url: 'https://www.fifeheritagerailway.co.uk/', source: 'Fife Heritage Railway', organisation: 'Fife Heritage Railway', opening: 'Advertised 2026 running days; guided tours normally Tuesday, Friday and Saturday at published sessions. Confirm before travel.', price: 'Donations welcome; special-event fares may apply', score: 84, dog: dogUnknown },
      { id: 'curated-attraction:leven-letham-glen', name: 'Letham Glen', kind: 'attraction', type: 'park', coordinates: [-3.0008136, 56.2072476], description: 'A 22-acre wooded glen with formal gardens, burns, paths, play area, toilets and parking.', tagline: 'Woodland, gardens and play', url: 'https://www.fife.gov.uk/facilities/park/letham-glen%2C-leven', source: 'Letham Glen, Leven', organisation: 'Fife Council', opening: 'Public park; facilities keep their own hours.', price: 'Free', score: 82, dog: dogOutdoor },
      { id: 'curated-attraction:leven-silverburn', name: 'Silverburn Park', kind: 'attraction', type: 'park', coordinates: [-2.9797935, 56.2063894], description: 'A dog-friendly community park with woodland, walled garden, walking routes, events and a daytime café.', tagline: 'Woodland and walled-garden escape', url: 'https://www.silverburnpark.co.uk/tent-intro', source: 'Silverburn Park', organisation: 'Silverburn Park', opening: 'Outdoor park open daily; café and activities keep published hours.', price: 'Free park access', score: 82, dog: { rating: 3, status: 'welcoming', label: 'Dog-friendly park', summary: 'The operator describes Silverburn Park as dog friendly; normal responsible access applies.' } },
      { id: 'curated-attraction:leven-together-hub', name: 'Together Levenmouth Hub', kind: 'attraction', type: 'family_activity', coordinates: [-2.9974028, 56.1945074], description: 'A town-centre family hub combining crazy golf, escape rooms, gift shop and café.', tagline: 'Indoor family activities and café', url: 'https://togetherlevenmouth.co.uk/about-us', source: 'About Us', organisation: 'Together Levenmouth', opening: 'Check current activity and café opening before travel; bookings may be advisable.', price: 'Activity charges apply', score: 76, dog: dogUnknown },
      { id: 'curated-food:leven-beach-coffee', name: 'Beach Coffee House', kind: 'food', type: 'cafe', coordinates: [-2.9875, 56.1982], description: 'Promenade café serving fresh coffee, pastries and hot snacks with panoramic beach views.', tagline: 'Coffee and pastries by the beach', url: 'https://www.welcometofife.com/view-catering/beach-coffee-house', source: 'Beach Coffee House', organisation: 'Welcome to Fife', opening: 'Advertised daily 9.30am–5pm; check current hours.', price: '£', score: 78, foodStyle: 'coffee, pastries and hot snacks', dog: dogUnknown },
      { id: 'curated-food:leven-hub-cafe', name: 'Together Levenmouth Café', kind: 'food', type: 'cafe', coordinates: [-2.9974028, 56.1945074], description: 'A community café in the activity hub serving hot drinks, baking and daytime food.', tagline: 'Coffee inside the family hub', url: 'https://togetherlevenmouth.co.uk/cafe/', source: 'Café', organisation: 'Together Levenmouth', opening: 'Advertised Monday–Saturday 9am–4pm; Sunday closed. Check current hours.', price: '£', score: 72, foodStyle: 'coffee, baking and light lunch', dog: dogUnknown },
      { id: 'curated-food:leven-cottage-cafe', name: 'Cottage Window Café at Silverburn Park', kind: 'food', type: 'cafe', coordinates: [-2.9788845, 56.2064344], description: 'A park café serving coffee, scones, cakes, toasties and soup beside the walled garden and woodland.', tagline: 'Park scones and light lunch', url: 'https://www.silverburnpark.co.uk/tent-intro', source: 'Silverburn Park', organisation: 'Silverburn Park', opening: 'Tuesday–Sunday 10am–3.30pm; closed Monday.', price: '£', score: 76, foodStyle: 'coffee, scones, cakes, toasties and soup', dog: dogUnknown },
      { id: 'curated-food:leven-colliers', name: 'Colliers Coffee Roasters', kind: 'food', type: 'cafe', coordinates: [-2.999766, 56.1933924], description: 'Accessible, pet-friendly speciality coffee shop with cakes and light daytime food in the town centre.', tagline: 'Speciality coffee in central Leven', url: 'https://www.welcometofife.com/view-catering/colliers-coffee-roasters', source: 'Colliers Coffee Roasters', organisation: 'Welcome to Fife', opening: 'Advertised Monday–Saturday 8am–4.30pm and Sunday 10am–3pm; check current hours.', price: '£', score: 80, foodStyle: 'speciality coffee, cake and light lunch', dog: { rating: 3, status: 'welcoming', label: 'Pet-friendly café', summary: 'The current local tourism listing describes Colliers as pet friendly.' } },
      { id: 'curated-food:leven-oscars', name: 'Oscar’s Coffee House', kind: 'food', type: 'cafe', coordinates: [-2.9967686, 56.1953287], description: 'Established High Street coffee house retained after a current 2026 food-hygiene inspection check.', tagline: 'High Street coffee-house stop', url: 'https://www.eatible.co.uk/scotland/fife/oscars-coffee-house', source: 'Oscar’s Coffee House food-hygiene record', organisation: 'Eatible / Food Standards data', opening: 'No reliable current opening hours are published; telephone before visiting.', price: '£', score: 70, foodStyle: 'coffee, cake and light lunch', dog: dogUnknown },
      { id: 'curated-trail:leven-coastal-path', name: 'Fife Coastal Path at Leven', kind: 'trail', type: 'walking_route', coordinates: [-2.9876, 56.1982], description: 'The official Buckhaven-to-Elie stage follows Leven’s promenade and continues through Silverburn and the Largo coast.', tagline: 'Long-distance route from the promenade', url: coastalPath, source: 'Buckhaven to Elie', organisation: 'Fife Coast & Countryside Trust', opening: 'Open route; consult current notices and weather.', price: 'Free', score: 82 },
      { id: 'curated-trail:leven-lower-largo', name: 'Leven to Lower Largo Discovery Trail', kind: 'trail', type: 'walking_route', coordinates: [-2.9876, 56.1982], description: 'A 5.4 km, roughly 1.5-hour official trail through Silverburn, Lundin Links and Lower Largo.', tagline: 'A 5.4 km coastal village walk', url: levenLowerLargo, source: 'Leven to Lower Largo', organisation: 'Welcome to Fife Discovery Trails', opening: 'Open route; check current information.', price: 'Free', score: 80 },
      { id: 'curated-trail:leven-silverburn-loop', name: 'Leven to Silverburn Loop', kind: 'trail', type: 'walking_route', coordinates: [-2.991, 56.199], description: 'A signed local discovery route joining central Leven, the coast and Silverburn Park.', tagline: 'Town, coast and park loop', url: 'https://levenmouthdiscoverytrails.co.uk/trails/leven-to-silverburn/', source: 'Leven to Silverburn', organisation: 'Levenmouth Discovery Trails', opening: 'Self-guided outdoor route.', price: 'Free', score: 78 },
      { id: 'curated-trail:leven-letham-nature', name: 'Letham Glen Nature Trail', kind: 'trail', type: 'walking_route', coordinates: [-3.0008136, 56.2072476], description: 'A 1.9 km, roughly one-hour nature trail through the glen, with dogs allowed and partial wheelchair suitability documented.', tagline: 'One-hour woodland nature trail', url: 'https://trails.welcometofife.com/levenmouth/letham-glen-nature-trail/', source: 'Letham Glen Nature Trail', organisation: 'Welcome to Fife Discovery Trails', opening: 'Open park route; check ground and weather conditions.', price: 'Free', score: 78 },
      { id: 'curated-picnic:leven-beach', name: 'Leven Beach Picnic Tables', kind: 'picnic', type: 'picnic_site', coordinates: [-2.9876, 56.1982], description: 'Officially documented picnic tables beside the beach and promenade, close to play and outdoor-fitness facilities.', tagline: 'Promenade picnic with sea views', url: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-beaches/leven-beach/', source: 'Leven Beach', organisation: 'Fife Coast & Countryside Trust', opening: 'Open outdoor facility; seasonal services vary.', price: 'Free', score: 82, details: ['picnic_table=yes'] },
      { id: 'curated-parking:leven-promenade', name: 'Leven Promenade Car Park', kind: 'parking', type: 'parking', coordinates: [-2.9873885, 56.1980752], description: 'Free 98-space public car park beside the eastern promenade and beach facilities.', tagline: 'Free beach and promenade parking', url: 'https://www.fife191.com/view/leven', source: 'Leven visitor information', organisation: 'Fife 191', opening: 'Public car park; check on-site signs for any restrictions.', price: 'Free daytime parking', score: 82, details: ['capacity=98', 'fee=no'] },
      { id: 'curated-parking:leven-shorehead', name: 'Shorehead Car Park', kind: 'parking', type: 'parking', coordinates: [-2.9990909, 56.1931576], description: 'Free town-centre parking at the bus station with 38 standard and four disabled spaces.', tagline: 'Free central parking by the bus station', url: 'https://www.fife.gov.uk/facilities/bus-station/leven-bus-station', source: 'Leven Bus Station', organisation: 'Fife Council', opening: 'Public car park and bus-station hours apply.', price: 'Free', score: 82, details: ['capacity=38', 'capacity:disabled=4', 'fee=no'] },
      { id: 'curated-toilets:leven-promenade', name: 'Leven Promenade Public Toilets', kind: 'toilets', type: 'toilets', coordinates: [-2.9875305, 56.1981637], description: 'Promenade toilets with accessible RADAR entry and baby-changing provision.', tagline: 'Beach-side public toilets', url: 'https://www.fife191.com/view/leven', source: 'Leven visitor information', organisation: 'Fife 191', opening: 'Advertised 10am–6pm summer and 10am–4pm winter; check current opening.', price: '30p', score: 78, details: ['fee=yes', 'wheelchair=yes', 'changing_table=yes'] },
      { id: 'curated-toilets:leven-bus-station', name: 'Leven Bus Station Toilets', kind: 'toilets', type: 'toilets', coordinates: [-2.9990909, 56.1931576], description: 'Free male, female and RADAR-accessible toilets at Leven Bus Station.', tagline: 'Free central accessible toilets', url: 'https://www.fife.gov.uk/facilities/bus-station/leven-bus-station', source: 'Leven Bus Station', organisation: 'Fife Council', opening: 'Bus-station opening hours published by Fife Council.', price: 'Free', score: 84, details: ['fee=no', 'wheelchair=yes', 'access=RADAR key'] },
      { id: 'curated-toilets:leven-letham-glen', name: 'Letham Glen Public Toilets', kind: 'toilets', type: 'toilets', coordinates: [-3.0008136, 56.2072476], description: 'Free level-access public toilets within Letham Glen Park.', tagline: 'Free park toilets', url: 'https://www.fife.gov.uk/facilities/public-toilet/leven-letham-glen-park-public-toilets', source: 'Leven Letham Glen Park Public Toilets', organisation: 'Fife Council', opening: 'Advertised daily 9am–4pm, subject to frost and festive closures.', price: 'Free', score: 82, details: ['fee=no', 'level_access=yes'] },
    ],
    planner: { eat: ['curated-food:leven-beach-coffee', 'curated-food:leven-hub-cafe', 'curated-food:leven-cottage-cafe', 'curated-food:leven-colliers', 'curated-food:leven-oscars'], trails: ['curated-trail:leven-coastal-path', 'curated-trail:leven-lower-largo', 'curated-trail:leven-silverburn-loop', 'curated-trail:leven-letham-nature'], picnic: ['curated-picnic:leven-beach'], parking: ['curated-parking:leven-promenade', 'curated-parking:leven-shorehead'], toilets: ['curated-toilets:leven-promenade', 'curated-toilets:leven-bus-station', 'curated-toilets:leven-letham-glen'] },
    providers: { TreasureTrails: 'Current Fife catalogue checked; no Leven-specific product.', CuriousAbout: 'No Leven route.', MysteryGuides: 'No Leven route.', GoQuestAdventures: 'No Leven route.', officialRoutes: 'Fife Coastal Path plus three current local Discovery Trail pages verified.' },
    checks: [{ url: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-beaches/leven-beach/', outcome: 'verified', note: 'Official trust page confirms beach, promenade, picnic tables and activities.' }, { url: 'https://www.fifeheritagerailway.co.uk/', outcome: 'verified', note: 'Operator publishes 2026 running days and tour information.' }, { url: 'https://www.fife.gov.uk/facilities/park/letham-glen%2C-leven', outcome: 'verified', note: 'Council confirms the 22-acre park, play, toilets and parking.' }, { url: 'https://www.silverburnpark.co.uk/tent-intro', outcome: 'verified', note: 'Operator confirms park, dog access and café offer.' }, { url: 'https://togetherlevenmouth.co.uk/about-us', outcome: 'verified', note: 'Operator confirms activities and café.' }, { url: 'https://trails.welcometofife.com/levenmouth/', outcome: 'verified', note: 'Current official collection was checked for local routes.' }, { url: 'https://www.fife.gov.uk/facilities/bus-station/leven-bus-station', outcome: 'verified', note: 'Council confirms parking, accessible toilets and bus-station facilities.' }, { url: 'https://www.fife.gov.uk/facilities/public-toilet/leven-letham-glen-park-public-toilets', outcome: 'verified', note: 'Council confirms free level-access public toilets.' }, { url: treasureCollection, outcome: 'no_result', note: 'No Leven-specific Treasure Trail product was found.' }],
    exclusions: ['Full-meal restaurants and pubs are not used to pad the café-led Eat category.', 'Nearby Methil, Buckhaven, Lundin Links and Lower Largo places are not transferred.', 'No attraction outside the town boundary is used to inflate Leven’s score.'],
  },
];

function splitScore(score: number, caps: number[]): number[] {
  let remaining = score;
  return caps.map((cap) => { const value = Math.min(cap, remaining); remaining -= value; return value; });
}

function featureFor(projectId: string, locality: string, seed: Feature): any {
  const tags: Record<Kind, string[]> = {
    attraction: ['curated-visitor-attraction', 'service-context-visitor'], food: ['service-context-food'],
    trail: ['service-context-trail', 'visitor-context-trail'], picnic: ['service-context-picnic'],
    parking: ['service-context-parking', 'visitor-context-parking'], toilets: ['service-context-toilets'],
  };
  const feature: any = {
    id: seed.id, projectId, name: seed.name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Fife', locality,
    featureType: seed.type, significance: seed.significance ?? 'local', geometry: { type: 'Point', coordinates: seed.coordinates },
    locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact',
    shortDescription: seed.description,
    details: `visit_score=${seed.score}; trail_score=${seed.score}; opening_hours:description=${seed.opening}; entrance_fee=${seed.price}; price_band=${seed.price}; cuisine=${seed.foodStyle ?? seed.kind}; tagline=${seed.tagline}; description=${seed.description}; ${seed.details?.join('; ') ?? ''}`,
    visitorWebsiteUrl: seed.url,
    sourceRecords: [{ sourceName: seed.source, sourceOrganisation: seed.organisation, sourceUrl: seed.url, accessedAt: reviewedAt, licence: 'Source-linked editorial evidence; verify time-sensitive details before travel.', reliability: seed.organisation.includes('Council') || seed.organisation.includes('Historic Environment') ? 'official_statutory' : 'official_non_statutory', notes: `Current-place curation for ${seed.name}.` }],
    tags: ['current-context', auditTag, ...tags[seed.kind]], createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence',
  };
  if (seed.kind === 'attraction') {
    const [experienceDepth, distinctiveness, presentation, journeyWorth, accessAndReliability, evidenceConfidence] = splitScore(seed.score, [30, 20, 20, 15, 10, 5]);
    feature.editorialReview = { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: `${seed.name} is scored from the visit experience, distinctiveness, presentation, journey worth, access reliability and evidence quality rather than designation alone.`, evidenceUrls: [seed.url], attractionAssessment: { experienceDepth, distinctiveness, presentation, journeyWorth, accessAndReliability, evidenceConfidence, visitability: seed.visitability ?? 'full_visitor_experience' } };
  } else if (seed.kind === 'food') {
    const [foodAndDrinkQuality, daytimeRelevance, distinctiveness, consistency, visitorFit, evidenceConfidence] = splitScore(seed.score, [30, 20, 15, 15, 10, 10]);
    feature.editorialReview = { status: 'editorially_researched', category: 'food', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: `${seed.name} qualifies through coffee, cake, breakfast or light-lunch relevance; full-meal value is not used to pad the score.`, evidenceUrls: [seed.url], foodAssessment: { foodAndDrinkQuality, daytimeRelevance, distinctiveness, consistency, visitorFit, evidenceConfidence } };
  } else if (seed.kind === 'trail') {
    feature.editorialReview = { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: `${seed.name} has a working route page with usable route information.`, evidenceUrls: [seed.url] };
  }
  return feature;
}

function highlightFor(seed: Feature, rank: number): any {
  return { rank, featureId: seed.id, name: seed.name, reason: seed.description, visitorScore: seed.score, tagline: seed.tagline, timeToSpend: '30–90 minutes', openingTimes: seed.opening, admission: seed.price, freeAdmission: /^free\b/i.test(seed.price), visitorWebsiteUrl: seed.url, sourceName: seed.source, sourceUrl: seed.url, verifiedInBoundaryAt: reviewedDate, editorialReview: featureFor('preview', 'preview', seed).editorialReview };
}

const planner: any = JSON.parse(await readFile(plannerPath, 'utf8'));
const dog: any = JSON.parse(await readFile(dogPath, 'utf8'));

for (const audit of audits) {
  const path = resolve('data/projects', audit.file);
  const pkg: any = JSON.parse(await readFile(path, 'utf8'));
  if (pkg.project.id !== audit.id) throw new Error(`${audit.name}: project identity mismatch`);
  pkg.features = pkg.features.filter((feature: any) => !feature.tags.includes(auditTag));
  pkg.features.push(...audit.features.map((seed) => featureFor(audit.id, audit.name, seed)));
  pkg.project.visitorHighlights = audit.features.filter((seed) => seed.kind === 'attraction').map(highlightFor);
  const band = townScoreBand(audit.score);
  pkg.project.touristAppeal = {
    score: audit.score, dogOwnerScore: townScoreAfterDogAccess(audit.score, audit.dogRating as any), dogAccessScoreAdjustment: townDogAccessScoreAdjustment(audit.dogRating as any),
    rating: band.rating, label: band.label, summary: audit.summary, dogAccessRating: audit.dogRating,
    dogAccessSummary: audit.dogRating >= 2 ? 'Outdoor routes can work for responsible dog visits, but venue policies are stated individually.' : 'Dog access is limited or unconfirmed and no dedicated dog destination is assumed.',
    methodVersion: '2026-09-02-full-settlement-visitor-audit-v2', reviewedAt: reviewedDate,
    sourceUrls: [...new Set([...audit.checks.map((check) => check.url), treasureCollection, curious, mystery, goQuest])],
  };
  pkg.project.townGuide = { characterTag: audit.character, headline: audit.headline, intro: audit.intro, bestFor: audit.bestFor, perfectFor: audit.perfectFor, suggestedFirstVisit: audit.features.length ? { title: audit.headline, summary: `Use the verified visitor links and practical notes for ${audit.name}; neighbouring places and private facilities are not assumed.` } : undefined, dontMiss: audit.features.filter((seed) => seed.kind === 'attraction').map((seed) => seed.name), suggestedTime: audit.time, visitorMood: audit.mood, sourceUrls: [...new Set(audit.checks.map((check) => check.url))], lastReviewedAt: reviewedDate };
  pkg.project.researchNotes = `${audit.intro} Strict-boundary score verified sequentially on ${reviewedDate}. ${audit.exclusions.join(' ')}`;
  pkg.validation = validateFeatures(pkg.project, pkg.features);
  const errors = pkg.validation.filter((issue: any) => issue.severity === 'error');
  if (errors.length) throw new Error(`${audit.name}: ${errors.length} validation errors`);

  planner.projects[audit.id] = audit.planner;
  dog.projects[audit.id] = { attraction: {}, eat: {} };
  for (const seed of audit.features) {
    if (!seed.dog || !['attraction', 'food'].includes(seed.kind)) continue;
    const category = seed.kind === 'food' ? 'eat' : 'attraction';
    dog.projects[audit.id][category][seed.id] = { ...seed.dog, sourceName: seed.source, sourceUrl: seed.url, reviewedAt: reviewedDate };
  }

  const statutory = pkg.features.filter((feature: any) => feature.tags.some((tag: string) => ['hes-listed-building', 'hes-scheduled-monument', 'hes-garden-designed-landscape'].includes(tag)));
  const visible = statutory.filter((feature: any) => !feature.tags.includes('map-hidden'));
  const undated = visible.filter((feature: any) => !feature.documentedDateText || feature.dateBasis === 'unknown');
  if (undated.length) throw new Error(`${audit.name}: ${undated.length} visible undated HES records`);
  const count = (kind: Kind) => audit.features.filter((feature) => feature.kind === kind).length;
  const report = {
    reviewedAt, projectId: audit.id, place: audit.name, townScore: audit.score, mapPublished: audit.score >= 60,
    categories: {
      see: { audited: true, published: count('attraction'), reason: audit.notes?.attraction }, eat: { audited: true, published: audit.planner.eat.length, reason: audit.notes?.food },
      trails: { audited: true, published: audit.planner.trails.length, providerChecks: audit.providers }, picnic: { audited: true, published: audit.planner.picnic.length, reason: audit.notes?.picnic },
      parking: { audited: true, published: audit.planner.parking.length, reason: audit.notes?.parking }, toilets: { audited: true, published: audit.planner.toilets.length, reason: audit.notes?.toilets },
      accessibility: { audited: true, note: 'Accessibility is described only where current route, venue or council evidence supports it; no blanket accessible claim is made.' },
      transport: { audited: true, note: 'Current public-transport information was checked; transport access does not add destination points by itself.' },
      dogs: { audited: true, adjustment: pkg.project.touristAppeal.dogAccessScoreAdjustment },
    },
    exclusions: audit.exclusions,
    hes: { assigned: statutory.length, visibleDated: visible.length, hiddenUndated: statutory.length - visible.length, visibleUndated: 0, missing: 0 },
    boundaryRule: `Only visitor places physically inside ${audit.name}'s strict study area, or an explicitly related cross-boundary route that genuinely serves it, are published.`,
    scoreRationale: audit.summary,
    scoreReanalysis: { required: false, completed: true, resultScore: audit.score, rationale: 'Score was independently reconciled after all categories, named-provider checks and boundary exclusions; no final score remains at the provisional exact-58 trigger.' },
    research: { currentWebResearch: true, strictBoundaryChecked: true, sourceChecks: audit.checks.map((check) => ({ ...check, checkedAt: reviewedDate })) },
    certification: { publicationCountsReconciled: true, liveBrowserVerifiedAt: null },
  };
  await writeFile(path, `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');
  await writeFile(resolve('data/review', `${audit.file.replace(/\.json$/, '')}-full-visitor-audit-2026-09-02.json`), `${JSON.stringify(report, null, 2)}\n`, 'utf8');
  console.log(`${audit.name}: ${audit.score}; See ${count('attraction')}, Eat ${audit.planner.eat.length}, Trails ${audit.planner.trails.length}, Picnic ${audit.planner.picnic.length}, Parking ${audit.planner.parking.length}, Toilets ${audit.planner.toilets.length}; HES ${visible.length}/${statutory.length}.`);
}

await writeFile(plannerPath, `${JSON.stringify({ ...planner, reviewedAt: reviewedDate }, null, 2)}\n`, 'utf8');
await writeFile(dogPath, `${JSON.stringify({ ...dog, reviewedAt: reviewedDate }, null, 2)}\n`, 'utf8');
console.log('Sequential Woodside-to-Leven audits completed; live-browser certification remains unset.');
