import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { editorialRatingMethodVersion } from '../src/domain/editorialResearch';

const projectId = 'carmyllie-scotland';
const reviewedDate = '2026-08-30';
const reviewedAt = '2026-08-30T23:59:00Z';
const projectPath = resolve('data/projects/carmyllie.json');
const plannerPath = resolve('data/cairn-o-mount-visitor-planner-curation.json');
const dogPath = resolve('data/cairn-o-mount-dog-access-curation.json');
const reportPath = resolve('data/review/carmyllie-full-visitor-audit-2026-08-30.json');
const urls = {
  circular: 'https://visitangus.com/things-to-see-do/trails/walking-trail-carmyllie-circular-trail/',
  circularPdf: 'https://d1ssu070pg2v9i.cloudfront.net/visit-angus/2024/12/09170605/Carmyllie-Circular-Trail.pdf',
  cafe: 'https://visitangus.com/things-to-see-do/food-drink/cornkist-coffee-shop/',
  cafeOfficial: 'https://www.miltonhaugh.com/',
  cafeFacilities: 'https://www.miltonhaugh.com/the-corn-kist-coffee-shop/cornkistfacilities/',
  church: 'https://portal.historicenvironment.scot/designation/LB4577',
  hearse: 'https://portal.historicenvironment.scot/designation/LB4578',
  manse: 'https://portal.historicenvironment.scot/designation/LB4579',
  beadle: 'https://portal.historicenvironment.scot/designation/LB4580',
  bridge: 'https://portal.historicenvironment.scot/designation/LB4582',
  school: 'https://portal.historicenvironment.scot/designation/LB4587',
  treasure: 'https://www.treasuretrails.co.uk/pages/search-results-page?q=Carmyllie',
  outdoorAccess: 'https://www.outdooraccess-scotland.scot/dog-owners',
};
const pkg: any = JSON.parse(await readFile(projectPath, 'utf8'));
const planner: any = JSON.parse(await readFile(plannerPath, 'utf8'));
const dog: any = JSON.parse(await readFile(dogPath, 'utf8'));
const attractionAssessment = (score: number) => ({ experienceDepth: Math.round(score*.3), distinctiveness: Math.round(score*.2), presentation: Math.round(score*.2), journeyWorth: Math.round(score*.15), accessAndReliability: Math.round(score*.1), evidenceConfidence: score-Math.round(score*.3)-Math.round(score*.2)-Math.round(score*.2)-Math.round(score*.15)-Math.round(score*.1), visitability:'full_visitor_experience' });
const foodAssessment = (score: number) => ({ foodAndDrinkQuality:Math.round(score*.29), daytimeRelevance:Math.round(score*.21), distinctiveness:Math.round(score*.15), consistency:Math.round(score*.14), visitorFit:Math.round(score*.11), evidenceConfidence:score-Math.round(score*.29)-Math.round(score*.21)-Math.round(score*.15)-Math.round(score*.14)-Math.round(score*.11) });
function make(spec: any) {
  const foodNotes = spec.category === 'food' ? `amenity=cafe; food_score=${spec.score}; cuisine=${spec.cuisine}; price_band=${spec.price}; opening_hours:description=${spec.opening}; description=${spec.tagline}. ${spec.description}; ` : '';
  return { id:spec.id, projectId, name:spec.name, alternativeNames:[], countryCode:'GB-SCT', region:'Angus', locality:'Carmyllie', featureType:spec.featureType, significance:'local', geometry:{type:'Point',coordinates:spec.coordinates}, locationType:'exact', locationConfidence:'high', dateBasis:'unknown', dateConfidence:'unknown', survival:'substantially_intact', shortDescription:spec.description, visitorWebsiteUrl:spec.website,
    editorialReview:spec.score?{status:'editorially_researched',category:spec.category,methodVersion:editorialRatingMethodVersion,reviewedAt:reviewedDate,scoreRationale:spec.reason,evidenceUrls:spec.evidenceUrls,...(spec.category==='food'?{foodAssessment:foodAssessment(spec.score)}:{attractionAssessment:attractionAssessment(spec.score)})}:undefined,
    sourceRecords:spec.evidenceUrls.map((url:string,index:number)=>({sourceName:index?`${spec.name} supporting evidence`:spec.sourceName,sourceOrganisation:index?'Supporting publisher':spec.sourceOrganisation,sourceUrl:url,accessedAt:reviewedAt,reliability:'official_non_statutory',licence:'Source-linked editorial evidence; verify time-sensitive details before travel.',notes:`Current-place curation: visitor_place_type=${spec.placeType}; ${spec.score?`visit_score=${spec.score}; `:''}${foodNotes}${spec.details??''}`})),
    tags:[...new Set([...spec.tags,...(spec.category==='food'?['service-context-food','visitor-context-food']:[])])],createdAt:reviewedAt,updatedAt:reviewedAt,reviewed:true,evidenceScope:'strict_boundary' };
}
const food = [make({ id:'curated-food:carmyllie-corn-kist', name:'Cornkist Coffee Shop at Milton Haugh', tagline:'Farm baking, coffee and light lunches', opening:'Tuesday to Friday 10.30am–3.30pm; Saturday and Sunday 10am–4pm; Monday closed', score:76, coordinates:[-2.732475,56.569473], featureType:'food_drink', description:'A farm coffee shop specialising in home baking, scones, soups, toasties, paninis and seasonal light dishes made with locally sourced and farm-shop produce.', reason:'A destination-worthy rural café and ideal start or finish for the official circular trail, with current hours and accessibility information.', website:urls.cafe, sourceName:'Visit Angus Cornkist listing', sourceOrganisation:'Visit Angus', evidenceUrls:[urls.cafe,urls.cafeOfficial,urls.cafeFacilities], placeType:'Eat', category:'food', cuisine:'coffee, home baking, soup, toasties and light lunches', price:'££', tags:['curated-visitor','current-context'], details:'42 seats published by the venue; full level access; accessible toilets and baby changing; no bookings; dog policy not published' })];
const trails = [
  make({ id:'curated-trails:carmyllie-circular', name:'Carmyllie Circular Heritage Trail', score:74, coordinates:[-2.732475,56.569473], featureType:'walking_route', description:'An official 7.5 km easy circular from Milton Haugh through Carmyllie, Graystone, quiet roads and farm tracks, passing the church and local heritage.', reason:'A current, downloadable, named village trail with a clear route, distance, duration and in-boundary start beside refreshments.', website:urls.circular, sourceName:'Visit Angus walking route', sourceOrganisation:'Visit Angus', evidenceUrls:[urls.circular,urls.circularPdf], placeType:'Trail', category:'trail', tags:['curated-visitor','visitor-context-trail','current-context'], details:'trail_type=Official circular heritage walk; distance=7.5 km / 4.7 miles; duration=about 2 hours; grade=easy; can be impassable northeast of Greystone after heavy rain; link checked 2026-08-30' }),
  make({ id:'curated-trails:carmyllie-milton-haugh-ponds', name:'Milton Haugh Ponds Walk', score:61, coordinates:[-2.732475,56.569473], featureType:'walking_route', description:'A short countryside stroll behind the farm shop, winding through fir trees, meadow planting and two small ponds.', reason:'A genuine venue-published short walk that complements the café, though less substantial and potentially wet.', website:urls.cafeFacilities, sourceName:'Milton Haugh facilities', sourceOrganisation:'Milton Haugh Farm Shop', evidenceUrls:[urls.cafeFacilities], placeType:'Trail', category:'trail', tags:['curated-visitor','visitor-context-trail','current-context'], details:'trail_type=Short on-site countryside stroll; distance and duration not published; lower corner can be wet after rain; link checked 2026-08-30' }),
];
const parking = [make({ id:'curated-parking:carmyllie-milton-haugh', name:'Milton Haugh Customer Parking', coordinates:[-2.732475,56.569473], featureType:'parking', description:'Customer parking for the farm shop, coffee shop and official trail start, including accessible parking or drop-off.', website:urls.cafe, sourceName:'Visit Angus accessibility listing', sourceOrganisation:'Visit Angus', evidenceUrls:[urls.cafe,urls.circular], placeType:'Parking', tags:['service-context-parking','current-context'], details:'access=Coffee-shop and farm-shop customers; fee=not published; payment_required=unknown; price_display=Check locally; opening_hours:description=coffee-shop and farm-shop access; capacity=not published; accessible parking or drop-off published' })];
const toilets = [make({ id:'curated-toilets:carmyllie-corn-kist', name:'Cornkist Customer Toilets', coordinates:[-2.732475,56.569473], featureType:'toilets', description:'Customer toilets at the coffee shop, with accessible provision and baby-changing facilities.', website:urls.cafeFacilities, sourceName:'Milton Haugh facilities', sourceOrganisation:'Milton Haugh Farm Shop', evidenceUrls:[urls.cafeFacilities,urls.cafe], placeType:'Public toilets', tags:['service-context-toilets','current-context'], details:'access=customers; opening_hours:description=coffee-shop opening hours; accessible toilet=yes; baby changing=yes; not a public 24-hour facility' })];
const fixes:Record<string,any> = {
  'hes-listed-building:LB4577':{text:'1609; altered 1780s, 1836 and 1874',first:1609,last:1874,confidence:'high',evidence:urls.church},
  'hes-listed-building:LB4578':{text:'first half of the 19th century',first:1800,last:1849,confidence:'medium',evidence:urls.hearse},
  'hes-listed-building:LB4579':{text:'1820; altered c.1870',first:1820,last:1870,confidence:'high',evidence:urls.manse},
  'hes-listed-building:LB4580':{text:'early 19th century',first:1800,last:1839,confidence:'medium',evidence:urls.beadle},
  'hes-listed-building:LB4582':{text:'1789',first:1789,last:1789,confidence:'high',evidence:urls.bridge},
  'hes-listed-building:LB4587':{text:'1804',first:1804,last:1804,confidence:'high',evidence:urls.school},
};
for(const feature of pkg.features){const fix=fixes[feature.id];if(!fix)continue;feature.documentedDateText=fix.text;feature.earliestPossibleYear=fix.first;feature.latestPossibleYear=fix.last;feature.dateBasis=fix.first===fix.last?'documented_exact_year':'documented_date_range';feature.dateConfidence=fix.confidence;feature.tags=feature.tags.filter((tag:string)=>tag!=='map-hidden');feature.reviewed=true;feature.updatedAt=reviewedAt;feature.reviewNotes=`${feature.reviewNotes??''} Construction period transcribed from the HES designation; the listing date is not used as the building date.`.trim();}
pkg.features=[...pkg.features.filter((feature:any)=>!feature.id.startsWith('curated-')),...food,...trails,...parking,...toilets];
pkg.project.visitorHighlights=[];
pkg.project.preferredBasemap='voyager';
pkg.project.touristAppeal={score:64,dogOwnerScore:61,dogAccessScoreAdjustment:-3,rating:1,label:'Worth a Stop',summary:'A compact rural heritage stop built around a current 7.5 km circular, a destination farm café and a notably intact historic church group.',dogAccessRating:3,dogAccessSummary:'The circular offers a worthwhile countryside walk, but it uses roads and farm tracks and the café dog policy is not published; keep dogs controlled around livestock.',methodVersion:'2026-08-30-strict-settlement-full-audit-v3',reviewedAt:reviewedDate,sourceUrls:Object.values(urls)};
pkg.project.townGuide={characterTag:'Farm café, heritage trail and church hamlet',headline:'A genuine rural stop with a walk and excellent café pairing',intro:'Carmyllie now scores 64%. Its official circular starts at the Cornkist Coffee Shop, loops through the village heritage landscape and passes the 1609 church group.',bestFor:['An easy two-hour heritage walk','Coffee, cake and farm-shop browsing','Historic rural architecture'],perfectFor:['A half-day countryside stop','Pairing a walk with light lunch','A quieter Angus detour'],suggestedFirstVisit:{title:'Start at Milton Haugh',summary:'Use the customer parking during opening hours, take the official 7.5 km circular, then return for coffee, baking or a light lunch. Check conditions after heavy rain.'},dontMiss:['Carmyllie Circular Heritage Trail','Cornkist Coffee Shop','Carmyllie Parish Kirk exterior and heritage setting'],suggestedTime:'2–4 hours',visitorMood:'A small but coherent destination: trail, café and historic village landscape reinforce one another.',sourceUrls:Object.values(urls),lastReviewedAt:reviewedDate};
pkg.project.researchNotes='Full strict-boundary audit. Carmyllie rises from 36 to 64 because the official 7.5 km circular, its in-boundary farm café start, historic church group and supporting customer facilities form a coherent village visit rather than an unrelated standalone attraction. The church is not published as a regular-access See card because current routine interior opening is not verified; its six HES records remain visible and accurately dated in the historic heat layer. No managed picnic facility was verified. Direct checks found no dedicated Treasure Trails, Curious About, Mystery Guides or Go Quest product.';
planner.projects[projectId]={eat:food.map((x:any)=>x.id),trails:trails.map((x:any)=>x.id),picnic:[],parking:parking.map((x:any)=>x.id),toilets:toilets.map((x:any)=>x.id)};
const dogEntry=(rating:number,status:string,label:string,summary:string,sourceUrl:string)=>({rating,status,label,summary,sourceName:'Carmyllie dog-access audit',sourceUrl,reviewedAt:reviewedDate});
dog.projects[projectId]={eat:{[food[0].id]:dogEntry(0,'unconfirmed','Dog policy not published','No reliable current dog policy is published; contact the venue before relying on indoor access.',urls.cafeOfficial)},trail:{[trails[0].id]:dogEntry(3,'allowed','Road and farm-track control','Suitable for controlled dogs, with care around traffic, livestock and wet ground.',urls.outdoorAccess),[trails[1].id]:dogEntry(3,'allowed','Short countryside stroll','Keep dogs controlled around ponds, wildlife, farm activity and other visitors.',urls.outdoorAccess)}};
const statutory=pkg.features.filter((f:any)=>f.tags.includes('hes-listed-building')||f.tags.includes('hes-scheduled-monument'));const visible=statutory.filter((f:any)=>!f.tags.includes('map-hidden'));const dated=visible.filter((f:any)=>f.documentedDateText&&f.earliestPossibleYear!=null&&f.latestPossibleYear!=null&&f.dateBasis!=='unknown');
const report={reviewedAt,projectId,status:'verified',settlementScore:64,previousScore:36,independentlyWorthwhile:true,publishOnTownMap:true,scoreRationale:'The village supports a coherent, current half-day visit through its official circular, destination café and historic settlement fabric.',publication:{see:0,eat:1,trails:2,picnic:0,parking:1,toilets:1},heritage:{expectedStatutoryRecords:6,representedStatutoryRecords:statutory.length,visibleDatedStatutoryPins:dated.length,visibleUndatedStatutoryPins:visible.length-dated.length,hiddenStatutoryPins:statutory.length-visible.length,manualDateRepairs:Object.keys(fixes)},namedTrailSearch:{TreasureTrails:'No dedicated Carmyllie product found after direct search',CuriousAbout:'No dedicated product found',MysteryGuides:'No dedicated product found',GoQuestAdventures:'No dedicated product found',retained:['Carmyllie Circular Heritage Trail','Milton Haugh Ponds Walk'],officialSource:urls.circular},practicalAudit:{eat:'Cornkist prioritises coffee, home baking, soups, toasties, paninis and light lunches; current hours published by Visit Angus.',picnic:'No managed or expressly permitted public picnic facility verified.',parking:'Customer parking and accessible parking/drop-off published; fee and capacity not published.',toilets:'Customer toilets, accessible toilet and baby changing published; access follows café opening.',accessibility:'Level access, accessible parking/drop-off and accessible toilets published for Cornkist.',transport:'Rural destination; the official trail starts at the café and parking area.'},exclusions:['Carmyllie Parish Kirk interior: no current routine opening verified, so retained as historic context rather than a managed See card.','Nearby regional parks and attractions: outside the strict boundary.','General roadside stopping: not presented as visitor parking.'],verification:{allCuratedCoordinatesCheckedAgainstBoundary:true,trailLinksChecked:[urls.circular,urls.circularPdf,urls.cafeFacilities],allStatutoryHesRecordsVisibleAndDated:dated.length===6&&visible.length===6,datesStoredWithoutChangingMapNames:statutory.every((f:any)=>!f.name.includes(f.documentedDateText))}};
await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`);await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`);await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`);await writeFile(reportPath,`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));
