import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const reviewedAt = '2026-09-01T12:20:00.000Z';
const reviewedDate = '2026-09-01';
const projectPath = resolve('data/projects/tayport.json');
const plannerPath = resolve('data/east-neuk-visitor-planner-curation.json');
const dogPath = resolve('data/east-neuk-dog-access-curation.json');
const reportPath = resolve('data/review/tayport-full-visitor-audit-2026-09-01.json');
const pkg = JSON.parse(await readFile(projectPath, 'utf8')) as ProjectPackage;
const urls = {
  harbour: 'https://www.tayportharbour.org/info',
  harbourHistory: 'https://www.tayportharbour.org/about',
  eastCommon: 'https://www.fife.gov.uk/facilities/park/east-common%2C-tayport',
  heritageTrail: 'https://tayportheritage.com/trail-guide/',
  coastalPath: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/',
  tayportLoop: 'https://www.walkfife.org/maps-routes/tayport-loop/',
  northFifeGuide: 'https://industry.welcometofife.com/wp-content/uploads/2022/09/WTF_NorthFife_Zcard-2023.pdf',
  treasureSearch: 'https://www.treasuretrails.co.uk/collections/fife',
  curious: 'https://curiousabout.co.uk/', mystery: 'https://www.mysteryguides.co.uk/', quest: 'https://goquestadventures.com/',
  harbourCafe: 'https://tayportct.org.uk/harbourcafe/', larickCafe: 'https://tayportct.org.uk/communityhub/larickcafe/',
  larickHub: 'https://tayportct.org.uk/communityhub/', localFood: 'https://larickcampsite.org.uk/feeling-peckish-food-and-drink-near-the-larick-campsite-no-washing-up-required/',
  toilets: 'https://www.fife.gov.uk/facilities/public-toilet/public-toilets',
  parking: 'https://www.fife.gov.uk/roads-travel-parking/parking-and-car-parks',
  evStrategy: 'https://www.fife.gov.uk/__data/assets/pdf_file/0023/626162/Fife-Council-EV-Strategy-10-February-2025.pdf',
  dogCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
};
type F = HeritageFeature & Record<string, any>;
const source = (name: string, organisation: string, url: string, notes: string, reliability: any = 'official_non_statutory') => ({ sourceName: name, sourceOrganisation: organisation, sourceUrl: url, accessedAt: reviewedAt, licence: 'Source-linked editorial evidence; verify time-sensitive details before travel.', reliability, notes });
const make = (spec: Record<string, any>): F => ({
  id: spec.id, projectId: pkg.project.id, name: spec.name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Fife', locality: 'Tayport', featureType: spec.featureType,
  significance: spec.significance ?? 'local', geometry: { type: 'Point', coordinates: spec.coordinates }, locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact',
  shortDescription: spec.description, visitorWebsiteUrl: spec.website, attractionGuide: spec.guide,
  sourceRecords: [
    ...spec.evidence.map((e: any) => source(e.name, e.organisation, e.url, e.notes, e.reliability)),
    ...(spec.currentDetails ? [source(`${spec.name} visitor details`, spec.organisation ?? spec.name, spec.website, `Current-place curation: ${spec.currentDetails}`)] : []),
  ],
  tags: ['current-context', ...(spec.tags ?? [])], createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence',
  editorialReview: spec.score ? { status: 'editorially_researched', category: spec.category, methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: spec.reason, evidenceUrls: spec.evidence.map((e: any) => e.url), ...(spec.category === 'food' ? { foodAssessment: spec.assessment } : spec.category === 'attraction' ? { attractionAssessment: { ...spec.assessment, visitability: 'full_visitor_experience' } } : {}) } : undefined,
});
const upsert = (feature: F) => { pkg.features = pkg.features.filter((item) => item.id !== feature.id).concat(feature); return feature; };
const evidence = (name: string, organisation: string, url: string, notes: string, reliability = 'official_non_statutory') => ({ name, organisation, url, notes, reliability });

const harbour = upsert(make({ id: 'curated-attraction:tayport-harbour', name: 'Tayport Harbour and Waterfront', featureType: 'harbour', coordinates: [-2.88095, 56.4510], score: 78, category: 'attraction', significance: 'regional', description: 'A compact working leisure harbour on the former railway and ferry waterfront, with close Tay views and a café in the old harbour setting.', website: urls.harbour, reason: 'The waterfront is distinctive, legible and easy to combine with the town trail and East Common; reduced because it is a small operational harbour rather than a major all-weather attraction.', assessment: { experienceDepth: 23, distinctiveness: 17, presentation: 15, journeyWorth: 11, accessAndReliability: 7, evidenceConfidence: 5 }, evidence: [evidence('Visitor information', 'Tayport Harbour Trust', urls.harbour, 'Current visitor berths, facilities and waterfront context.'), evidence('Harbour history', 'Tayport Harbour Trust', urls.harbourHistory, 'Official harbour history and former ferry and railway role.')], tags: ['curated-visitor-attraction'], guide: { headline: 'Walk the former ferry and railway waterfront', parking: 'Use only signed public or venue parking; no council-owned Tayport car park is claimed.', toilets: 'Fife Council lists Tayport Public Toilets beside the waterfront.', picnic: 'A mapped public picnic table sits by the harbour promenade.', foodNote: 'Harbour Café is at 10 Broad Street.' } }));
const common = upsert(make({ id: 'curated-attraction:tayport-east-common', name: 'East Common and Tay Promenade', featureType: 'park', coordinates: [-2.8722, 56.4450], score: 74, category: 'attraction', significance: 'regional', description: 'An 8.2-hectare public coastal park with promenade, estuary views, wildlife pond, play park and football pitch.', website: urls.eastCommon, reason: 'A spacious, free and well-evidenced waterfront park that supports wildlife watching and family use; reduced for limited shelter and its essentially local-park scale.', assessment: { experienceDepth: 22, distinctiveness: 14, presentation: 15, journeyWorth: 10, accessAndReliability: 8, evidenceConfidence: 5 }, evidence: [evidence('East Common', 'Fife Council', urls.eastCommon, 'Official park area, facilities, wildlife and car-park-location evidence.', 'local_authority')], tags: ['curated-visitor-attraction'], guide: { headline: 'Follow the promenade and watch the Tay', parking: 'Use the signed East Common/Larick access identified by Fife Council; capacity and tariff are not published.', toilets: 'Tayport Public Toilets are at the west end; the Larick Centre has customer facilities.', picnic: 'Use the audited tables near the Larick Centre and harbour; no barbecue permission is claimed.', foodNote: 'Larick Café is beside the eastern common.' } }));

const heritageTrail = upsert(make({ id: 'curated-trail:tayport-heritage-trail', name: 'Tayport Heritage Trail', featureType: 'walking_route', coordinates: [-2.8810, 56.4509], score: 82, category: 'trail', description: 'A free 4-mile / 6.5 km circular town trail linking 24 interpretation panels, with shorter connecting options.', website: urls.heritageTrail, reason: 'A complete, place-specific and freely accessible interpretation trail with exact length and 24 panels.', currentDetails: 'trail_score=82; opening_hours:description=Open route; check current path conditions; entrance_fee=Free; time_to_spend=2–3 hours; description=Twenty-four-panel town trail. A 4-mile / 6.5 km interpreted circuit with shorter linking options.', evidence: [evidence('Trail Guide', 'Tayport Heritage Trail', urls.heritageTrail, 'Official 24-panel route, 4-mile / 6.5 km distance and shorter links.')], tags: ['service-context-trail', 'visitor-context-trail'] }));
const coastalPath = upsert(make({ id: 'curated-trail:fife-coastal-path-tayport', name: 'Fife Coastal Path at Tayport', featureType: 'walking_route', coordinates: [-2.8764, 56.4519], score: 76, category: 'trail', description: 'The signed long-distance coast path follows Tayport waterfront and East Common before continuing beyond the settlement.', website: urls.coastalPath, reason: 'A high-quality, official through-route with excellent water views, explicitly labelled cross-boundary rather than scored as a separate town attraction.', currentDetails: 'trail_score=76; opening_hours:description=Open route; check current path notices; entrance_fee=Free; time_to_spend=Choose a local section or longer stage; description=Signed estuary through-route. The official coastal path follows Tayport waterfront and East Common.', evidence: [evidence('Fife Coastal Path', 'Fife Coast and Countryside Trust', urls.coastalPath, 'Official route hub and current notices.'), evidence('North Fife visitor guide', 'Welcome to Fife', urls.northFifeGuide, 'Official guide confirms Tayport services and path context.')], tags: ['service-context-trail', 'visitor-context-trail', 'cross-boundary-trail'] }));
const tayportLoop = upsert(make({ id: 'curated-trail:tayport-loop', name: 'Tayport Loop', featureType: 'walking_route', coordinates: [-2.8717, 56.4423], score: 74, category: 'trail', description: 'An 11.35 km / 2 hour 50 minute family-friendly Walk Fife circuit beginning and ending in Tayport and continuing through Tentsmuir Forest.', website: urls.tayportLoop, reason: 'A complete downloadable Tayport-starting circuit with distance, duration and route file; substantial overlap with the coastal and forest network limits distinctiveness.', currentDetails: 'trail_score=74; opening_hours:description=Open route; check forestry and path notices; entrance_fee=Free; time_to_spend=About 2 hours 50 minutes; description=Tayport and Tentsmuir circuit. An 11.35 km family-friendly route with GPX and KML downloads.', evidence: [evidence('Tayport Loop', 'Walk Fife', urls.tayportLoop, 'Working route page verifies Tayport start and finish, 11.35 km distance, 2 hour 50 minute duration and downloadable GPX/KML files.')], tags: ['service-context-trail', 'visitor-context-trail', 'cross-boundary-trail'] }));

const harbourCafe = upsert(make({ id: 'curated-food:tayport-harbour-cafe', name: 'Harbour Café', featureType: 'cafe', coordinates: [-2.8810315, 56.4505639], score: 82, category: 'food', organisation: 'Tayport Community Enterprises', description: 'Community-run waterfront café for coffee, house-baked cakes, breakfast rolls, toasties, sandwiches, panini, baked potatoes and salads.', website: urls.harbourCafe, reason: 'Excellent fit for coffee, cake and a light lunch in the defining harbour setting, with dependable seven-day opening.', currentDetails: 'visit_score=82; opening_hours:description=Open daily 10:00–16:00; price_band=££; cuisine=coffee_cake_light_lunch; description=Coffee and cake by the harbour. A community café with breakfast rolls, toasties, sandwiches, panini, baked potatoes, salads and house-baked cakes.', assessment: { foodAndDrinkQuality: 24, daytimeRelevance: 19, distinctiveness: 13, consistency: 11, visitorFit: 9, evidenceConfidence: 6 }, evidence: [evidence('Harbour Café', 'Tayport Community Enterprises', urls.harbourCafe, 'Official menu summary, address and daily 10:00-16:00 opening.')], tags: ['service-context-food', 'visitor-context-food'] }));
const larickCafe = upsert(make({ id: 'curated-food:tayport-larick-cafe', name: 'Larick Café', featureType: 'cafe', coordinates: [-2.8713281, 56.4418048], score: 80, category: 'food', organisation: 'Tayport Community Trust', description: 'Community café serving coffee, cakes, breakfast rolls, soup, sandwiches, panini and baked potatoes, with indoor and outdoor seating.', website: urls.larickCafe, reason: 'A reliable seven-day café at the East Common end of town with strong light-lunch breadth, dietary choices and explicit dog welcome.', currentDetails: 'visit_score=80; opening_hours:description=Open daily 10:00–16:00; price_band=££; cuisine=coffee_cake_light_lunch; description=Community café by East Common. Coffee, cakes, breakfast rolls, soup, sandwiches, panini and baked potatoes with indoor and outdoor seating.', assessment: { foodAndDrinkQuality: 23, daytimeRelevance: 19, distinctiveness: 12, consistency: 11, visitorFit: 9, evidenceConfidence: 6 }, evidence: [evidence('Larick Café', 'Tayport Community Trust', urls.larickCafe, 'Official current menu scope and daily 10:00-16:00 opening.'), evidence('The Larick Centre', 'Tayport Community Trust', urls.larickHub, 'Official venue and opening information.')], tags: ['service-context-food', 'visitor-context-food'] }));

const harbourPicnic = upsert(make({ id: 'curated-picnic:tayport-harbour', name: 'Tayport Harbour Picnic Table', featureType: 'picnic_site', coordinates: [-2.88145, 56.45114], description: 'A mapped public picnic table on the harbour promenade, close to the café and public toilets.', website: urls.harbour, evidence: [evidence('Harbour visitor information', 'Tayport Harbour Trust', urls.harbour, 'Waterfront context; furniture location cross-checked against local OpenStreetMap.'), evidence('OpenStreetMap picnic table', 'OpenStreetMap contributors', 'https://www.openstreetmap.org/node/4092653152', 'Exact mapped picnic-table location.', 'discovery_only')], tags: ['service-context-picnic', 'visitor-context-picnic'] }));
const commonPicnic = upsert(make({ id: 'curated-picnic:tayport-east-common', name: 'East Common Picnic Tables', featureType: 'picnic_site', coordinates: [-2.8721, 56.4426], description: 'Public picnic tables beside East Common and the Larick Centre; no shelter or barbecue permission is claimed.', website: urls.eastCommon, evidence: [evidence('East Common', 'Fife Council', urls.eastCommon, 'Official public-park setting and facilities.', 'local_authority'), evidence('OpenStreetMap picnic tables', 'OpenStreetMap contributors', 'https://www.openstreetmap.org/node/12496598950', 'Exact mapped picnic-table location.', 'discovery_only')], tags: ['service-context-picnic', 'visitor-context-picnic'] }));
const eastParking = upsert(make({ id: 'curated-parking:tayport-east-common', name: 'East Common / Larick Centre Parking', featureType: 'parking', coordinates: [-2.8717077, 56.4422552], description: 'Signed venue and park-access parking beside the Larick Centre. Fife Council links to this car-park location; capacity, tariff and accessible-bay count are not published.', website: urls.eastCommon, evidence: [evidence('East Common', 'Fife Council', urls.eastCommon, 'Official park page links a visitor car-park location.', 'local_authority'), evidence('Larick Centre parking', 'OpenStreetMap contributors', 'https://www.openstreetmap.org/way/1123968367', 'Exact operator-tagged car-park geometry.', 'discovery_only')], tags: ['service-context-parking', 'visitor-context-parking'] }));
const toilets = upsert(make({ id: 'curated-toilets:tayport-public', name: 'Tayport Public Toilets', featureType: 'toilets', coordinates: [-2.8813178, 56.4513835], description: 'Fife Council-listed public toilets beside the harbour and Inn Street. Current opening hours, charge, baby-changing and RADAR details are not published on the directory entry.', website: urls.toilets, evidence: [evidence('Public Toilets', 'Fife Council', urls.toilets, 'Current council directory explicitly lists Tayport Public Toilets; unlisted facility details are withheld.', 'local_authority'), evidence('OpenStreetMap public toilets', 'OpenStreetMap contributors', 'https://www.openstreetmap.org/way/50059409', 'Exact mapped toilet building, tagged wheelchair accessible.', 'discovery_only')], tags: ['service-context-toilets', 'visitor-context-toilets'] }));

const highlights: VisitorHighlight[] = [
  { rank: 1, featureId: harbour.id, name: harbour.name, reason: 'The former ferry and railway harbour is Tayport’s most distinctive and coherent visitor setting.', visitorScore: 78, tagline: 'Historic harbour and Tay views', timeToSpend: '45–90 minutes', openingTimes: 'Open-air working waterfront; daylight recommended.', admission: 'Free to visit; boating charges are separate.', freeAdmission: true, visitorWebsiteUrl: urls.harbour, sourceName: 'Tayport Harbour Trust', sourceUrl: urls.harbour, verifiedInBoundaryAt: reviewedDate, editorialReview: harbour.editorialReview },
  { rank: 2, featureId: common.id, name: common.name, reason: 'A spacious waterfront common with wildlife, play, promenade and estuary views.', visitorScore: 74, tagline: 'Promenade, pond and wildlife', timeToSpend: '45–120 minutes', openingTimes: 'Open-air public park.', admission: 'Free.', freeAdmission: true, visitorWebsiteUrl: urls.eastCommon, sourceName: 'Fife Council', sourceUrl: urls.eastCommon, verifiedInBoundaryAt: reviewedDate, editorialReview: common.editorialReview },
];
pkg.project.visitorHighlights = highlights;
pkg.project.touristAppeal = { score: 76, dogOwnerScore: 72, dogAccessScoreAdjustment: -4, rating: 1, label: 'Worth a Visit', summary: 'Tayport earns a visit through its historic harbour, broad East Common, a strong 24-panel heritage trail, waterfront walking and two well-matched community cafés.', dogAccessRating: 2, dogAccessSummary: 'The waterfront, common and trails work with a controlled dog, and the Larick Café explicitly welcomes dogs; the Harbour Café does not, wildlife and working-waterfront hazards require care, and not every facility publishes a pet policy.', methodVersion: '2026-08-31-full-settlement-visitor-audit-v1', reviewedAt: reviewedDate, sourceUrls: Object.values(urls) };
pkg.project.townGuide = { characterTag: 'Historic Tay harbour and waterfront common', headline: 'A harbour town with a rewarding interpreted waterfront', intro: 'Tayport links its former ferry and railway harbour to East Common through an unusually complete local heritage trail, estuary views and two useful community cafés.', bestFor: ['Harbour history', 'Estuary walks', 'Local heritage', 'Coffee and cake'], perfectFor: ['A half-day waterfront stop', 'Walkers using the Fife Coastal Path'], suggestedFirstVisit: { title: 'Harbour to East Common', summary: 'Start at the harbour, follow the heritage panels and promenade east to the pond and Larick Centre, then return by the town streets.' }, dontMiss: ['Tayport Harbour', 'East Common', 'Tayport Heritage Trail'], suggestedTime: '3–5 hours', visitorMood: 'A modest but coherent estuary town whose strongest features reinforce one another.', sourceUrls: Object.values(urls), lastReviewedAt: reviewedDate };

const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as any;
planner.reviewedAt = reviewedDate;
planner.projects[pkg.project.id] = { eat: [harbourCafe.id, larickCafe.id], trails: [heritageTrail.id, coastalPath.id, tayportLoop.id], parking: [eastParking.id], toilets: [toilets.id], picnic: [harbourPicnic.id, commonPicnic.id] };
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`);
const dog = JSON.parse(await readFile(dogPath, 'utf8')) as any;
dog.reviewedAt = reviewedDate;
dog.projects[pkg.project.id] = { attraction: {
  [harbour.id]: { rating: 2, status: 'restricted', label: 'Good with waterfront care', summary: 'Keep dogs controlled around boats, open water, food areas and other harbour users.', sourceName: 'Scottish Outdoor Access Code', sourceUrl: urls.dogCode, reviewedAt: reviewedDate },
  [common.id]: { rating: 2, status: 'restricted', label: 'Good with wildlife care', summary: 'The open common suits dog walking; close control is needed around nesting birds, pond wildlife, play and sports areas.', sourceName: 'Fife Council and Scottish Outdoor Access Code', sourceUrl: urls.dogCode, reviewedAt: reviewedDate },
  [heritageTrail.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable town circuit', summary: 'Public streets and waterfront can be followed with normal lead, road, wildlife and harbour care.', sourceName: 'Tayport Heritage Trail and Scottish Outdoor Access Code', sourceUrl: urls.dogCode, reviewedAt: reviewedDate },
  [tayportLoop.id]: { rating: 2, status: 'restricted', label: 'Longer coast and forest circuit', summary: 'The route is suitable for a controlled dog, with wildlife, forestry, coast and road care required.', sourceName: 'Walk Fife and Scottish Outdoor Access Code', sourceUrl: urls.tayportLoop, reviewedAt: reviewedDate },
}, eat: {
  [harbourCafe.id]: { rating: 1, status: 'restricted', label: 'No dogs indoors', summary: 'The local operator guide explicitly says dogs are not admitted; use nearby outdoor waterfront space without obstructing the café.', sourceName: 'Larick Campsite local food guide', sourceUrl: urls.localFood, reviewedAt: reviewedDate },
  [larickCafe.id]: { rating: 1, status: 'unconfirmed', label: 'Indoor dog policy unconfirmed', summary: 'A reliable current indoor dog policy is not published on the operator pages; confirm before relying on access.', sourceName: 'Tayport Community Trust', sourceUrl: urls.larickHub, reviewedAt: reviewedDate },
} };
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`);

const hes = pkg.features.filter((f: any) => f.tags?.includes('hes-listed-building') || f.tags?.includes('hes-scheduled-monument') || f.tags?.includes('hes-garden-designed-landscape'));
const visibleUndated = hes.filter((f: any) => !f.tags?.includes('map-hidden') && !(Number.isFinite(f.earliestPossibleYear) && Number.isFinite(f.latestPossibleYear)));
if (hes.length !== 39 || visibleUndated.length) throw new Error(`Tayport HES gate failed: ${hes.length} assigned, ${visibleUndated.length} visible undated.`);
pkg.validation = validateFeatures(pkg.project, pkg.features);
const errors = pkg.validation.filter((item) => item.severity === 'error');
if (errors.length) throw new Error(`Tayport audit introduced ${errors.length} validation errors.`);
await writeFile(projectPath, `${JSON.stringify(pkg, null, 2)}\n`);
await writeFile(reportPath, `${JSON.stringify({ reviewedAt, place: 'Tayport', townScore: 76, mapPublished: true, categories: { see: { audited: true, published: highlights.length, rejected: ['Tentsmuir Forest and other out-of-boundary attractions', 'Individual heritage records below the independent 60-point attraction threshold'] }, eat: { audited: true, published: 2, rejected: ['Dinner-led pubs and restaurants', 'Unverified or closed café listings'] }, trails: { audited: true, published: 3, providerChecks: { TreasureTrails: 'Current Fife catalogue checked; no live Tayport product found', CuriousAbout: 'Checked; no Tayport route found', MysteryGuides: 'Checked; no Tayport route found', GoQuestAdventures: 'Checked; no Tayport route found', WalkFife: 'Tayport Loop verified with working route page, distance, duration and route downloads', officialRoutes: 'Tayport Heritage Trail and Fife Coastal Path checked on responsible provider pages' } }, picnic: { audited: true, published: 2 }, parking: { audited: true, published: 1, rejected: 'Unnamed, residential, golf-club or otherwise unverified OSM parking geometries were withheld; the retained East Common/Larick parking is tied to park and venue access.' }, toilets: { audited: true, published: 1, withheldDetails: ['Opening hours', 'Charge', 'Baby changing', 'RADAR access'] }, accessibility: { audited: true, notes: 'Only sourced level, wheelchair or venue access is stated; no route-wide accessibility grade is invented.' }, transport: { audited: true, notes: 'Bus and long-distance path context checked; volatile timetables are not copied into static data.' }, dogs: { audited: true, townAdjustment: -4 } }, hes: { assigned: hes.length, visibleDated: hes.filter((f: any) => !f.tags?.includes('map-hidden')).length, hiddenUndated: hes.filter((f: any) => f.tags?.includes('map-hidden')).length, visibleUndated: visibleUndated.length, missing: 0, designationDatesUsedAsConstructionDates: 0 }, boundaryRule: 'No attraction, service or score has been borrowed from outside Tayport’s strict settlement study area; the cross-boundary routes start or pass through Tayport and are labelled accordingly.', research: { currentWebResearch: true, strictBoundaryChecked: true, sourceChecks: [{ url: urls.harbourCafe, checkedAt: reviewedDate, outcome: 'verified', note: 'Operator page confirms daily opening, coffee, cakes and light lunches.' }, { url: urls.larickCafe, checkedAt: reviewedDate, outcome: 'verified', note: 'Operator page confirms daily opening and the daytime menu.' }, { url: urls.toilets, checkedAt: reviewedDate, outcome: 'verified', note: 'Current Fife Council directory lists Tayport Public Toilets.' }, { url: urls.tayportLoop, checkedAt: reviewedDate, outcome: 'verified', note: 'Walk Fife route page works and confirms Tayport start/end, distance and duration.' }] }, certification: { publicationCountsReconciled: false, liveBrowserVerifiedAt: null } }, null, 2)}\n`);
console.log('Tayport re-audit complete: score 76; 2 See, 2 Eat, 3 Trails, 2 Picnic, 1 Parking, 1 Toilet; HES 39/39 represented and 0 visible undated.');
