import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';
import { attractionEditorialScore, foodEditorialScore } from '../src/domain/editorialResearch';

const reviewedDate = '2026-08-31';
const reviewedAt = '2026-08-31T23:30:00.000Z';
const projectPath = resolve('data/projects/st-andrews.json');
const plannerPath = resolve('data/east-neuk-visitor-planner-curation.json');
const dogPath = resolve('data/east-neuk-dog-access-curation.json');
const reportPath = resolve('data/review/st-andrews-full-visitor-audit-2026-08-31.json');
const pkg = JSON.parse(await readFile(projectPath, 'utf8')) as ProjectPackage;

const urls = {
  destination: 'https://www.welcometofife.com/destination/st-andrews?parentcID=150',
  castle: 'https://www.historicenvironment.scot/visit/all/st-andrews-castle/plan-your-visit/',
  cathedral: 'https://www.historicenvironment.scot/visit/all/st-andrews-cathedral/plan-your-visit/',
  links: 'https://www.standrews.com/Play/Courses/Old-course',
  golfMuseum: 'https://www.worldgolfmuseum.com/',
  wardlaw: 'https://www.st-andrews.ac.uk/museums/wardlaw-museum/',
  townMuseum: 'https://www.onfife.com/visit-explore/museums-galleries/st-andrews-museum/',
  heritageMuseum: 'https://standrewspreservationtrust.com/',
  botanic: 'https://www.standrewsbotanic.org/visit/',
  aquarium: 'https://shop.standrewsaquarium.co.uk/buy-All-Day-Pass-id1',
  westSands: 'https://www.fife.gov.uk/facilities/beaches-and-harbours/west-sands%2C-st-andrews',
  eastSands: 'https://www.fife.gov.uk/facilities/beaches-and-harbours/east-sands',
  harbour: 'https://www.standrewsharbourtrust.org/',
  harbourHistory: 'https://www.standrewsharbourtrust.org/gallery',
  coast: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/',
  pilgrim: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-pilgrim-way/',
  euro: 'https://www.visitscotland.com/info/tours/st-andrews-eurowalk-f1a2b9bb',
  treasureTown: 'https://www.treasuretrails.co.uk/products/things-to-do-st-andrews-fife',
  treasureWest: 'https://www.treasuretrails.co.uk/products/days-out-st-andrews-fife',
  treasureEast: 'https://www.treasuretrails.co.uk/products/what-to-do-st-andrews-fife',
  curious: 'https://curiousabout.co.uk/', mystery: 'https://www.mysteryguides.co.uk/', quest: 'https://goquestadventures.com/',
  zest: 'https://wearezest.co.uk/', cottage: 'https://www.cottkitch.co.uk/', jannettas: 'https://jannettas.co.uk/', fisher: 'https://www.fisheranddonaldson.com/our-stores/st-andrews-south-street/',
  northpoint: 'https://northpointcafe.weebly.com/', universityCafes: 'https://www.st-andrews.ac.uk/community/cafes/', unionCafes: 'https://www.yourunion.net/spaces/cafes/',
  parkingList: 'https://www.fife.gov.uk/roads-travel-parking/parking-and-car-parks/car-park-list', parkingCharges: 'https://www.fife.gov.uk/roads-travel-parking/parking-and-car-parks/car-parks-and-car-parking-charges/parking-charges',
  petheram: 'https://www.fife.gov.uk/facilities/car-park/petheram-bridge-car-park%2C-st-andrews', argyle: 'https://www.fife.gov.uk/facilities/car-park/argyle-street-north-car-park%2C-st-andrews', bruceParking: 'https://www.fife.gov.uk/facilities/car-park/bruce-embankment-car-park%2C-st-andrews',
  toilets: 'https://www.fife.gov.uk/facilities/public-toilet', bruceToilets: 'https://www.fife.gov.uk/facilities/public-toilet/st-andrews-bruce-embankment-public-toilets', harbourToilets: 'https://www.fife.gov.uk/facilities/public-toilet/st-andrews-harbour-public-toilets',
  bus: 'https://www.fife.gov.uk/facilities/bus-station/st-andrews-bus-station', dog: 'https://www.outdooraccess-scotland.scot/dog-owners',
};

type F = HeritageFeature & Record<string, any>;
const ev = (name: string, organisation: string, url: string, notes: string, reliability: any = 'official_non_statutory') => ({ name, organisation, url, notes, reliability });
const source = (e: any) => ({ sourceName: e.name, sourceOrganisation: e.organisation, sourceUrl: e.url, accessedAt: reviewedAt, licence: 'Source-linked editorial evidence; verify time-sensitive details before travel.', reliability: e.reliability, notes: e.notes });
const make = (spec: any): F => ({
  id: spec.id, projectId: pkg.project.id, name: spec.name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Fife', locality: 'St Andrews', featureType: spec.featureType,
  significance: spec.significance ?? 'regional', geometry: { type: 'Point', coordinates: spec.coordinates }, locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact',
  shortDescription: spec.description, visitorWebsiteUrl: spec.website, attractionGuide: spec.guide, sourceRecords: spec.evidence.map(source), tags: ['current-context', ...(spec.tags ?? [])],
  createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence',
  editorialReview: spec.score ? { status: 'editorially_researched', category: spec.category, methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: spec.reason, evidenceUrls: spec.evidence.map((e: any) => e.url), ...(spec.category === 'food' ? { foodAssessment: spec.assessment } : { attractionAssessment: { ...spec.assessment, visitability: 'full_visitor_experience' } }) } : undefined,
});
const upsert = (f: F) => { pkg.features = pkg.features.filter((x) => x.id !== f.id).concat(f); return f; };
const attraction = (id: string, name: string, type: string, coordinates: [number, number], score: number, description: string, website: string, reason: string, evidence: any[], assessment: any, guide?: any) => upsert(make({ id, name, featureType: type, coordinates, score, category: 'attraction', description, website, reason, evidence, assessment, guide, tags: ['curated-visitor-attraction'] }));
const service = (id: string, name: string, type: string, coordinates: [number, number], description: string, website: string, evidence: any[], tags: string[]) => upsert(make({ id, name, featureType: type, coordinates, description, website, evidence, tags }));

const see = [
  attraction('curated-attraction:st-andrews-cathedral', 'St Andrews Cathedral and St Rule\'s Tower', 'cathedral', [-2.7871, 56.3406], 94, 'The monumental remains of Scotland\'s medieval ecclesiastical headquarters, with free cathedral grounds and guided-tour opportunities; the museum is currently closed during conservation work.', urls.cathedral, 'A nationally exceptional, highly legible historic site with substantial open-air depth; the temporary museum closure is reflected rather than concealed.', [ev('Plan your visit', 'Historic Environment Scotland', urls.cathedral, 'Current conservation notice, opening, free grounds, tours, access and parking.')], { experienceDepth: 29, distinctiveness: 20, presentation: 17, journeyWorth: 15, accessAndReliability: 7, evidenceConfidence: 6 }),
  attraction('curated-attraction:st-andrews-castle', 'St Andrews Castle', 'castle', [-2.7911, 56.3420], 92, 'A coastal bishop\'s palace and Reformation fortress with courtyards, towers and exhibitions; the mine, countermine and Bishop\'s Apartments are currently closed.', urls.castle, 'A nationally important paid attraction with a deep, well-presented visit. Current partial closures reduce access and reliability but do not erase the experience.', [ev('Plan your visit', 'Historic Environment Scotland', urls.castle, 'Current opening, prices, partial closures, facilities and accessibility.')], { experienceDepth: 28, distinctiveness: 20, presentation: 17, journeyWorth: 15, accessAndReliability: 6, evidenceConfidence: 6 }),
  attraction('curated-attraction:st-andrews-old-course', 'Old Course and Swilcan Bridge', 'historic_landscape', [-2.8026, 56.3434], 91, 'The world-famous Home of Golf landscape, centred on the first and eighteenth holes and the Swilcan Bridge; visitors must respect play and use the recommended bridge approach.', urls.links, 'An internationally distinctive sporting landscape with exceptional recognition and strong visit value, balanced by live-course access constraints.', [ev('Old Course', 'St Andrews Links Trust', urls.links, 'Official course and guided-walk context.'), ev('St Andrews destination', 'Welcome to Fife', urls.destination, 'Official destination evidence for the Old Course and Swilcan Bridge.')], { experienceDepth: 26, distinctiveness: 20, presentation: 17, journeyWorth: 16, accessAndReliability: 6, evidenceConfidence: 6 }),
  attraction('curated-attraction:st-andrews-west-sands', 'West Sands Beach', 'beach', [-2.8100, 56.3510], 88, 'A broad two-mile sandy beach beside the links, internationally familiar from Chariots of Fire and supported by waterfront parking and accessible-beach initiatives.', urls.westSands, 'A large, iconic and freely accessible coastal experience with high repeat value; exposed conditions and variable sand access limit universal accessibility.', [ev('West Sands', 'Fife Council', urls.westSands, 'Official beach listing.'), ev('St Andrews destination', 'Welcome to Fife', urls.destination, 'Official destination description and accessible beach-wheelchair context.')], { experienceDepth: 27, distinctiveness: 18, presentation: 16, journeyWorth: 14, accessAndReliability: 7, evidenceConfidence: 6 }),
  attraction('curated-attraction:st-andrews-world-golf-museum', 'R&A World Golf Museum', 'museum', [-2.80147, 56.34394], 87, 'A five-star museum interpreting more than 400 years of golf through objects, interactive galleries and changing displays.', urls.golfMuseum, 'A polished, internationally relevant museum that gives indoor depth to the Home of Golf.', [ev('World Golf Museum', 'The Royal and Ancient Golf Club of St Andrews Trust', urls.golfMuseum, 'Official collection, visitor and booking information.')], { experienceDepth: 27, distinctiveness: 19, presentation: 17, journeyWorth: 12, accessAndReliability: 7, evidenceConfidence: 5 }),
  attraction('curated-attraction:st-andrews-wardlaw-museum', 'Wardlaw Museum', 'museum', [-2.79399, 56.34293], 85, 'A free university museum with four thematic galleries, temporary exhibitions, interactive experiences and a sea-view terrace.', urls.wardlaw, 'A substantial, current and freely accessible cultural attraction with excellent presentation and a distinctive university story.', [ev('Wardlaw Museum', 'University of St Andrews', urls.wardlaw, 'Official galleries, opening, admission, access and travel information.')], { experienceDepth: 25, distinctiveness: 17, presentation: 18, journeyWorth: 11, accessAndReliability: 8, evidenceConfidence: 6 }),
  attraction('curated-attraction:st-andrews-botanic-garden', 'St Andrews Botanic Garden', 'botanic_garden', [-2.8072, 56.3344], 83, 'An 18-acre garden of woodland, meadows, ponds and living collections, with a signed accessible loop and visitor centre.', urls.botanic, 'A dependable, well-presented half-day garden with strong seasonal depth and unusually clear access information.', [ev('Visit', 'St Andrews Botanic Garden', urls.botanic, 'Official opening, prices, facilities, accessibility, parking and pet policy.')], { experienceDepth: 25, distinctiveness: 15, presentation: 17, journeyWorth: 11, accessAndReliability: 9, evidenceConfidence: 6 }),
  attraction('curated-attraction:st-andrews-aquarium', 'St Andrews Aquarium', 'aquarium', [-2.7992, 56.3441], 81, 'A family aquarium on The Scores offering an all-day re-entry ticket and a varied indoor and outdoor animal visit.', urls.aquarium, 'A substantial all-weather family attraction in a strong coastal setting; the score reflects a current official ticket offer but limited independently published access detail.', [ev('All Day Pass', 'St Andrews Aquarium', urls.aquarium, 'Current 2026 ticket prices, re-entry terms, address and carer ticket.')], { experienceDepth: 25, distinctiveness: 14, presentation: 16, journeyWorth: 11, accessAndReliability: 8, evidenceConfidence: 7 }),
  attraction('curated-attraction:st-andrews-museum', 'St Andrews Museum and Kinburn Park', 'museum', [-2.80533, 56.33968], 78, 'A free local-history and art museum in a Victorian mansion, with changing exhibitions, a light-bite café and accessible facilities in Kinburn Park.', urls.townMuseum, 'A coherent free museum-and-park stop with useful facilities and rotating content, though smaller than the national and university attractions.', [ev('St Andrews Museum', 'OnFife', urls.townMuseum, 'Official displays, exhibitions, opening, café, parking and access information.')], { experienceDepth: 23, distinctiveness: 14, presentation: 16, journeyWorth: 9, accessAndReliability: 10, evidenceConfidence: 6 }),
  attraction('curated-attraction:st-andrews-harbour', 'St Andrews Harbour and Long Pier', 'harbour', [-2.7836, 56.3393], 77, 'A historic working harbour with an inshore fishing fleet, leisure craft, skyline views and a restored Long Pier.', urls.harbour, 'A photogenic, historically important working waterfront that combines naturally with the cathedral and East Sands; operational hazards and weather limit presentation.', [ev('Harbour', 'St Andrews Harbour Trust', urls.harbour, 'Current working-harbour and fleet context.'), ev('Harbour history', 'St Andrews Harbour Trust', urls.harbourHistory, 'Official pier development and historic fabric.')], { experienceDepth: 22, distinctiveness: 17, presentation: 13, journeyWorth: 11, accessAndReliability: 8, evidenceConfidence: 6 }),
  attraction('curated-attraction:st-andrews-east-sands', 'East Sands Beach', 'beach', [-2.7825, 56.3365], 76, 'A sandy family beach beside the harbour with free parking, picnic facilities, play, accessible toilets and a connection to the Fife Coastal Path.', urls.eastSands, 'A well-equipped urban beach with excellent practical visitor support, reduced because it is less distinctive than West Sands.', [ev('East Sands', 'Fife Council', urls.eastSands, 'Official beach, parking, picnic, toilet, play and disabled-facility listing.', 'local_authority')], { experienceDepth: 22, distinctiveness: 13, presentation: 15, journeyWorth: 10, accessAndReliability: 10, evidenceConfidence: 6 }),
  attraction('curated-attraction:st-andrews-heritage-museum', 'St Andrews Heritage Museum and Garden', 'museum', [-2.79037, 56.34049], 72, 'A specialist social-history museum and garden in a historic North Street property, operated by the town preservation trust.', urls.heritageMuseum, 'A place-specific small museum with a strong setting and redeveloped gallery; seasonal programming and modest scale constrain its score.', [ev('Preservation Trust Museum', 'St Andrews Preservation Trust', urls.heritageMuseum, 'Current museum events, admission and opening evidence.'), ev('About the Trust', 'St Andrews Preservation Trust', 'https://standrewspreservationtrust.com/about/', 'Official museum-and-garden operation and redevelopment context.')], { experienceDepth: 20, distinctiveness: 15, presentation: 14, journeyWorth: 8, accessAndReliability: 9, evidenceConfidence: 6 }),
];

const trails = [
  upsert(make({ id: 'curated-trail:st-andrews-treasure-town', name: 'St Andrews Town & Castle Treasure Trail', featureType: 'walking_route', coordinates: [-2.80147, 56.34394], score: 82, category: 'attraction', description: 'A current two-mile, two-hour circular detective trail from Golf Place through the historic centre and castle quarter; wheelchair, pushchair and dog friendly.', website: urls.treasureTown, reason: 'A live, place-specific commercial clue trail with exact start, distance, duration and access status.', evidence: [ev('St Andrews Town & Castle', 'Treasure Trails', urls.treasureTown, 'Current product, start, two-mile distance, two-hour duration and accessibility.')], assessment: { experienceDepth: 25, distinctiveness: 15, presentation: 15, journeyWorth: 10, accessAndReliability: 11, evidenceConfidence: 6 }, tags: ['service-context-trail', 'visitor-context-trail'] })),
  upsert(make({ id: 'curated-trail:st-andrews-treasure-west', name: 'St Andrews West Sands & Course Treasure Trail', featureType: 'walking_route', coordinates: [-2.8014, 56.3445], score: 80, category: 'attraction', description: 'A current two-mile, two-hour circular spy trail from Bruce Embankment around the West Sands and golf setting; dog friendly but not wheelchair or pushchair accessible.', website: urls.treasureWest, reason: 'A live, well-specified clue trail in an iconic landscape, with access limitations stated plainly.', evidence: [ev('St Andrews West Sands & Course', 'Treasure Trails', urls.treasureWest, 'Current product, start, distance, duration, dog and access status.')], assessment: { experienceDepth: 24, distinctiveness: 16, presentation: 15, journeyWorth: 10, accessAndReliability: 9, evidenceConfidence: 6 }, tags: ['service-context-trail', 'visitor-context-trail'] })),
  upsert(make({ id: 'curated-trail:st-andrews-treasure-east', name: 'St Andrews East Sands & Castle Treasure Trail', featureType: 'walking_route', coordinates: [-2.7843, 56.3389], score: 79, category: 'attraction', description: 'A current two-mile, two-hour circular treasure hunt covering East Sands, harbour, graveyard, Byre and castle; dog friendly but not wheelchair or pushchair accessible.', website: urls.treasureEast, reason: 'A live trail that joins several strong visitor settings and publishes honest access limits.', evidence: [ev('St Andrews East Sands & Castle', 'Treasure Trails', urls.treasureEast, 'Current product, start, route highlights, distance, duration and access status.')], assessment: { experienceDepth: 24, distinctiveness: 15, presentation: 15, journeyWorth: 10, accessAndReliability: 9, evidenceConfidence: 6 }, tags: ['service-context-trail', 'visitor-context-trail'] })),
  upsert(make({ id: 'curated-trail:fife-coastal-path-st-andrews', name: 'Fife Coastal Path through St Andrews', featureType: 'walking_route', coordinates: [-2.7870, 56.3400], score: 84, category: 'attraction', description: 'The official 188 km long-distance route links East Sands, harbour, historic centre and the coast north of St Andrews.', website: urls.coast, reason: 'A nationally recognised and well-waymarked cross-boundary trail with exceptional town scenery; it remains a trail rather than being double-counted as a town attraction.', evidence: [ev('Fife Coastal Path', 'Fife Coast and Countryside Trust', urls.coast, 'Official route, sections, planning and current notices.')], assessment: { experienceDepth: 27, distinctiveness: 17, presentation: 14, journeyWorth: 13, accessAndReliability: 7, evidenceConfidence: 6 }, tags: ['service-context-trail', 'visitor-context-trail', 'cross-boundary-trail'] })),
  upsert(make({ id: 'curated-trail:fife-pilgrim-way-st-andrews', name: 'Fife Pilgrim Way finish at St Andrews', featureType: 'walking_route', coordinates: [-2.7890, 56.3400], score: 82, category: 'attraction', description: 'The official 64-mile modern pilgrimage route finishes among the cathedral and medieval streets of St Andrews.', website: urls.pilgrim, reason: 'A well-supported official pilgrimage route with a highly meaningful finish; cross-boundary distance and mixed surfaces require preparation.', evidence: [ev('Fife Pilgrim Way', 'Fife Coast and Countryside Trust', urls.pilgrim, 'Official route hub, stages and planning resources.')], assessment: { experienceDepth: 26, distinctiveness: 17, presentation: 14, journeyWorth: 13, accessAndReliability: 6, evidenceConfidence: 6 }, tags: ['service-context-trail', 'visitor-context-trail', 'cross-boundary-trail'] })),
  upsert(make({ id: 'curated-trail:st-andrews-eurowalk', name: 'St Andrews EuroWalk', featureType: 'walking_route', coordinates: [-2.7943, 56.3410], score: 74, category: 'attraction', description: 'A free self-guided online circular walk from St Salvator\'s Chapel linking the university, castle, cathedral and harbour through their European connections.', website: urls.euro, reason: 'A credible, free and distinctive self-guided interpretation route; reduced because route-wide distance, surface and access data are not published in the listing.', evidence: [ev('St Andrews EuroWalk', 'VisitScotland', urls.euro, 'Current tour description, start and landmark sequence.')], assessment: { experienceDepth: 22, distinctiveness: 15, presentation: 13, journeyWorth: 9, accessAndReliability: 9, evidenceConfidence: 6 }, tags: ['service-context-trail', 'visitor-context-trail'] })),
];

const foodSpecs = [
  ['curated-food:st-andrews-zest', 'Zest', [-2.79453, 56.33958], 88, 'Independent social-enterprise café for specialist coffee, homemade soups, bagels and cakes.', urls.zest, 'Strong coffee-and-cake identity, light-lunch fit and social-enterprise distinctiveness.', { foodAndDrinkQuality: 25, daytimeRelevance: 20, distinctiveness: 15, consistency: 12, visitorFit: 10, evidenceConfidence: 6 }],
  ['curated-food:st-andrews-jannettas', 'Jannettas Gelateria', [-2.79158, 56.33974], 87, 'Fifth-generation St Andrews gelateria making traditional gelato and gelato cakes on site, with coffee and long daily opening.', urls.jannettas, 'An exceptionally distinctive sweet stop with more than a century of place-specific craft.', { foodAndDrinkQuality: 25, daytimeRelevance: 18, distinctiveness: 18, consistency: 11, visitorFit: 9, evidenceConfidence: 6 }],
  ['curated-food:st-andrews-cottage-kitchen', 'The Cottage Kitchen', [-2.79628, 56.33986], 84, 'Independent coffee shop and bistro focused on locally sourced brunch, lunch, teas and coffee.', urls.cottage, 'Excellent daytime fit and local sourcing with enough menu breadth for a light lunch.', { foodAndDrinkQuality: 24, daytimeRelevance: 20, distinctiveness: 13, consistency: 11, visitorFit: 10, evidenceConfidence: 6 }],
  ['curated-food:st-andrews-fisher-donaldson', 'Fisher & Donaldson South Street Café', [-2.79981, 56.33895], 83, 'A fifth-generation Fife bakery café for breakfast pastries, traditional light lunch, coffee and cake.', urls.fisher, 'A strong local bakery identity, dependable seven-day daytime opening and precise coffee-and-cake fit.', { foodAndDrinkQuality: 24, daytimeRelevance: 20, distinctiveness: 14, consistency: 11, visitorFit: 9, evidenceConfidence: 5 }],
  ['curated-food:st-andrews-frankis', 'Franki\'s Café', [-2.795651, 56.341906], 78, 'Community-facing university café for locally sourced coffee and a convenient daytime light lunch.', urls.universityCafes, 'A dependable, central weekday café with current first-party hours and a useful visitor location inside the Main Library.', { foodAndDrinkQuality: 20, daytimeRelevance: 19, distinctiveness: 11, consistency: 11, visitorFit: 11, evidenceConfidence: 6 }],
  ['curated-food:st-andrews-museum-cafe', 'St Andrews Cake Co at St Andrews Museum', [-2.80533, 56.33968], 78, 'Museum café serving cakes and light bites in Kinburn Park.', urls.townMuseum, 'A strong coffee-and-cake stop integrated with a visitor attraction and park, though tied to museum opening days.', { foodAndDrinkQuality: 22, daytimeRelevance: 19, distinctiveness: 12, consistency: 9, visitorFit: 11, evidenceConfidence: 5 }],
  ['curated-food:st-andrews-rectors', 'Rector\'s Café', [-2.80005, 56.34038], 72, 'Public-facing student-union café for coffee, cake, wraps, panini and takeaway sandwiches.', urls.unionCafes, 'Affordable, central and exactly matched to a quick light lunch, but less distinctive as a visitor stop.', { foodAndDrinkQuality: 19, daytimeRelevance: 19, distinctiveness: 8, consistency: 10, visitorFit: 10, evidenceConfidence: 6 }],
] as const;
const foodPublication: Record<string, { tagline: string; opening: string; price: '£' | '££' | '£££'; style: string }> = {
  'curated-food:st-andrews-zest': { tagline: 'Speciality coffee with purpose', opening: 'Daily 07:00–16:00', price: '££', style: 'speciality coffee, cake and light lunch' },
  'curated-food:st-andrews-jannettas': { tagline: 'Five generations of gelato', opening: 'Daily 09:00–22:30', price: '££', style: 'gelato, coffee and cake' },
  'curated-food:st-andrews-cottage-kitchen': { tagline: 'Locally sourced brunch', opening: 'Monday–Saturday 09:00–17:00; Sunday 09:30–17:00', price: '££', style: 'brunch, coffee and light lunch' },
  'curated-food:st-andrews-fisher-donaldson': { tagline: 'Fife bakery and cakes', opening: 'Monday–Saturday 09:00–17:00; Sunday 11:00–16:00', price: '££', style: 'bakery, coffee, cake and light lunch' },
  'curated-food:st-andrews-frankis': { tagline: 'Library coffee stop', opening: 'Monday–Friday 08:00–16:30', price: '£', style: 'coffee and light lunch' },
  'curated-food:st-andrews-museum-cafe': { tagline: 'Cake in Kinburn Park', opening: 'Monday–Saturday 10:30–16:00; hot food until 15:00', price: '££', style: 'cake, coffee and light lunch' },
  'curated-food:st-andrews-rectors': { tagline: 'Affordable community café', opening: 'Monday–Friday 08:00–17:00; Saturday 09:00–17:00; Sunday 10:00–17:00', price: '£', style: 'coffee, cake and light lunch' },
};
pkg.features = pkg.features.filter((feature) => feature.id !== 'curated-food:st-andrews-northpoint');
const eats = foodSpecs.map(([id, name, coordinates, score, description, website, reason, assessment]) => {
  const publication = foodPublication[id];
  const feature = upsert(make({ id, name, featureType: 'cafe', coordinates, score, category: 'food', description: `${publication.tagline}: ${description}`, website, reason, assessment, evidence: [ev(name, name.includes('Museum') ? 'OnFife' : name.includes('Rector') ? 'University of St Andrews Students\' Association' : name.includes('Franki') ? 'University of St Andrews' : name, website, 'Current first-party venue, menu and opening information.')], tags: ['service-context-food', 'visitor-context-food'] }));
  feature.sourceRecords.push(source(ev('Publication details', name.includes('Museum') ? 'OnFife' : name.includes('Rector') ? 'University of St Andrews Students\' Association' : name.includes('Franki') ? 'University of St Andrews' : name, website, `Current-place curation: amenity=cafe; description=${publication.tagline}: ${description}; opening_hours:description=${publication.opening}; price_band=${publication.price}; food_style=${publication.style}; visit_score=${foodEditorialScore(feature.editorialReview.foodAssessment)}.`)));
  return feature;
});
const auditedFoodNames = new Set(eats.map((feature) => feature.name.toLocaleLowerCase('en-GB')));
const auditedFoodIds = new Set(eats.map((feature) => feature.id));
pkg.features = pkg.features.filter(
  (feature) =>
    auditedFoodIds.has(feature.id) ||
    !auditedFoodNames.has(feature.name.toLocaleLowerCase('en-GB')),
);

const parking = [
  service('curated-parking:st-andrews-petheram', 'Petheram Bridge Car Park', 'parking', [-2.8040, 56.3409], 'Free long-stay council car park with about 300 spaces and easy town-centre access; the bus-station access page describes the 150 m inclined route.', urls.petheram, [ev('Petheram Bridge Car Park', 'Fife Council', urls.petheram, 'Official free status, approximate capacity and town-centre access.', 'local_authority'), ev('St Andrews Bus Station', 'Fife Council', urls.bus, 'Official walking gradient and no Blue Badge bays.', 'local_authority')], ['service-context-parking', 'visitor-context-parking']),
  service('curated-parking:st-andrews-argyle-north', 'Argyle Street North Car Park', 'parking', [-2.80266, 56.33881], 'Central pay-and-display council car park with 194 spaces and four disabled bays; seasonal tariffs apply.', urls.argyle, [ev('Argyle Street North', 'Fife Council', urls.argyle, 'Official capacity and disabled-bay count.', 'local_authority'), ev('Parking charges', 'Fife Council', urls.parkingCharges, 'Current seasonal tariff and charging times.', 'local_authority')], ['service-context-parking', 'visitor-context-parking']),
  service('curated-parking:st-andrews-bruce', 'Bruce Embankment Car Park', 'parking', [-2.80145, 56.34451], 'Waterfront council car park with 157 spaces, four disabled bays and seasonal charges, beside the golf museum and public toilets.', urls.bruceParking, [ev('Bruce Embankment Car Park', 'Fife Council', urls.bruceParking, 'Official capacity, disabled bays and seasonal charging.', 'local_authority'), ev('Parking charges', 'Fife Council', urls.parkingCharges, 'Current tariff and charging times.', 'local_authority')], ['service-context-parking', 'visitor-context-parking']),
  service('curated-parking:st-andrews-east-sands', 'East Sands Beach Parking', 'parking', [-2.78254, 56.33666], 'Free beach parking with disabled spaces, beside the path, play area, café and toilets; capacity is not published.', urls.eastSands, [ev('East Sands', 'Fife Council', urls.eastSands, 'Official free and disabled parking evidence; capacity withheld.', 'local_authority')], ['service-context-parking', 'visitor-context-parking']),
];
const toilets = [
  service('curated-toilets:st-andrews-bruce', 'Bruce Embankment Public Toilets', 'toilets', [-2.80194, 56.34484], 'Council toilets open 09:00–19:00 year-round, charge 30p, with level access, baby changing and a Changing Places facility; RADAR key required for the accessible toilet.', urls.bruceToilets, [ev('Bruce Embankment Public Toilets', 'Fife Council', urls.bruceToilets, 'Current hours, charge and facilities.', 'local_authority')], ['service-context-toilets', 'visitor-context-toilets']),
  service('curated-toilets:st-andrews-harbour', 'St Andrews Harbour Public Toilets', 'toilets', [-2.78845, 56.33961], 'Free council toilets at The Pends, open 09:00–17:00 April to October and closed November to March.', urls.harbourToilets, [ev('Harbour Public Toilets', 'Fife Council', urls.harbourToilets, 'Current seasonal opening and free use.', 'local_authority')], ['service-context-toilets', 'visitor-context-toilets']),
  service('curated-toilets:st-andrews-church-square', 'Church Square Public Toilets', 'toilets', [-2.79572, 56.33988], 'Council-listed public toilets in the historic centre. Exact opening, charge and access details are withheld because the current directory does not publish them.', urls.toilets, [ev('Public Toilets', 'Fife Council', urls.toilets, 'Current council directory and location only.', 'local_authority')], ['service-context-toilets', 'visitor-context-toilets']),
];
const picnic = [
  service('curated-picnic:st-andrews-east-sands', 'East Sands Picnic Area', 'picnic_site', [-2.78211, 56.33648], 'Council-confirmed picnic facilities beside the beach, play area and public toilets.', urls.eastSands, [ev('East Sands', 'Fife Council', urls.eastSands, 'Official picnic and adjacent-facility evidence.', 'local_authority')], ['service-context-picnic', 'visitor-context-picnic']),
  service('curated-picnic:st-andrews-harbour', 'St Andrews Harbour Picnic Area', 'picnic_site', [-2.7842, 56.3391], 'Restored harbour picnic space overlooking the working basins and pier; stay clear of operations and quay edges.', urls.harbour, [ev('Harbour news', 'St Andrews Harbour Trust', 'https://www.standrewsharbourtrust.org/news', 'Official confirmation that the picnic area has been restored and expanded.')], ['service-context-picnic', 'visitor-context-picnic']),
  service('curated-picnic:st-andrews-kinburn', 'Kinburn Park Picnic Lawns', 'picnic_site', [-2.8053, 56.3397], 'Public lawns around St Andrews Museum suitable for a packed-lunch stop; no fixed-table or barbecue claim is made.', urls.townMuseum, [ev('St Andrews Museum', 'OnFife', urls.townMuseum, 'Official museum-in-park setting and visitor facilities.')], ['service-context-picnic', 'visitor-context-picnic']),
];

const attractionPublication = [
  { tagline: 'Scotland’s medieval cathedral', opening: 'Cathedral grounds open daily with seasonal HES hours', admission: 'Free grounds; tower and museum currently closed' },
  { tagline: 'Coastal Reformation fortress', opening: 'Open daily with seasonal HES hours', admission: 'Paid; current official HES tariff applies' },
  { tagline: 'The Home of Golf', opening: 'Open landscape; viewing is subject to live play', admission: 'Free public viewing from paths and road edges' },
  { tagline: 'Iconic two-mile beach', opening: 'Open access daily', admission: 'Free' },
  { tagline: 'Four centuries of golf', opening: 'Open daily; seasonal hours are published by the museum', admission: 'Free' },
  { tagline: 'University stories and views', opening: 'Open daily 11:00–19:00', admission: 'Free' },
  { tagline: 'Eighteen acres of gardens', opening: 'Open daily 10:00–16:00', admission: 'Paid; current official garden tariff applies' },
  { tagline: 'Family marine life visit', opening: 'Open daily with seasonal last-entry times', admission: 'Paid; current official online tariff applies' },
  { tagline: 'Local stories in the park', opening: 'Monday–Saturday 10:30–16:00', admission: 'Free' },
  { tagline: 'Harbour and Long Pier', opening: 'Open-air working harbour; access depends on operations and weather', admission: 'Free' },
  { tagline: 'Family beach and harbour', opening: 'Open access daily', admission: 'Free' },
  { tagline: 'Social history and garden', opening: 'Seasonal opening is published by the Preservation Trust', admission: 'Free' },
];
pkg.project.visitorHighlights = see.map((f, index): VisitorHighlight => ({ rank: index + 1, featureId: f.id, name: f.name, reason: f.editorialReview.scoreRationale, visitorScore: attractionEditorialScore(f.editorialReview.attractionAssessment), tagline: attractionPublication[index].tagline, timeToSpend: index < 2 ? '1–2 hours' : index < 8 ? '45–120 minutes' : '30–90 minutes', openingTimes: attractionPublication[index].opening, admission: attractionPublication[index].admission, visitorWebsiteUrl: f.visitorWebsiteUrl, sourceName: f.sourceRecords[0].sourceOrganisation, sourceUrl: f.sourceRecords[0].sourceUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: f.editorialReview }));
pkg.project.touristAppeal = { score: 96, dogOwnerScore: 89, dogAccessScoreAdjustment: -7, rating: 3, label: 'Exceptional Destination', summary: 'An internationally significant historic university city and Home of Golf, combining castle and cathedral ruins, major museums, two contrasting beaches, a working harbour, gardens and an unusually deep verified walking-trail offer.', dogAccessRating: 2, dogAccessSummary: 'West and East Sands, harbour approaches and several self-guided trails support a strong outdoor visit; ordinary dogs are excluded from the principal indoor attractions and Botanic Garden, and control is essential around wildlife, working quays and active golf.', methodVersion: '2026-08-31-full-settlement-visitor-audit-v1', reviewedAt: reviewedDate, sourceUrls: Object.values(urls) };
pkg.project.townGuide = { characterTag: 'Medieval university city and Home of Golf', headline: 'One of Scotland’s richest compact visitor destinations', intro: 'St Andrews supports a full day or short break without borrowing attractions from neighbouring settlements: major heritage, golf, museums, beaches, harbour, gardens, cafés and six verified self-guided routes all sit within the audited boundary.', bestFor: ['Medieval Scotland', 'Golf heritage', 'Museums', 'Beaches', 'Walking trails', 'Coffee and cake'], perfectFor: ['A full day or weekend', 'History and golf enthusiasts', 'Families mixing indoor and outdoor stops'], suggestedFirstVisit: { title: 'Cathedral to the Old Course', summary: 'Begin at the cathedral and harbour, follow The Scores past the castle and Wardlaw Museum, then finish at the World Golf Museum, Old Course and West Sands.' }, dontMiss: ['St Andrews Cathedral', 'St Andrews Castle', 'Old Course and Swilcan Bridge', 'Wardlaw Museum', 'West Sands'], suggestedTime: '1–2 days', visitorMood: 'Internationally famous yet compact enough to explore on foot.', sourceUrls: Object.values(urls), lastReviewedAt: reviewedDate };

const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as any;
planner.reviewedAt = reviewedDate;
planner.projects[pkg.project.id] = { eat: eats.map((x) => x.id), trails: trails.map((x) => x.id), parking: parking.map((x) => x.id), toilets: toilets.map((x) => x.id), picnic: picnic.map((x) => x.id) };
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`);
const dog = JSON.parse(await readFile(dogPath, 'utf8')) as any;
dog.reviewedAt = reviewedDate;
dog.projects[pkg.project.id] = { attraction: Object.fromEntries([...see, ...trails].map((x) => [x.id, { rating: x.id.includes('beach') || x.id.includes('harbour') || x.id.includes('treasure') ? 2 : 1, status: x.id.includes('beach') || x.id.includes('harbour') || x.id.includes('treasure') ? 'restricted' : 'assistance_only', label: x.id.includes('beach') || x.id.includes('harbour') || x.id.includes('treasure') ? 'Outdoor access with close control' : 'Assistance dogs or outdoor viewing', summary: x.id.includes('beach') || x.id.includes('harbour') || x.id.includes('treasure') ? 'Use a lead or close control around wildlife, crowds, traffic, working quays and active golf.' : 'The principal indoor visitor areas do not publish ordinary-pet access; assistance-dog access applies where stated.', sourceName: 'Official venue and Scottish Outdoor Access Code', sourceUrl: x.visitorWebsiteUrl, reviewedAt: reviewedDate }])), eat: Object.fromEntries(eats.map((x) => [x.id, { rating: 1, status: 'unconfirmed', label: 'Dog policy not published', summary: 'No reliable current dog policy is published by the venue; ask the café directly before relying on indoor access.', sourceName: x.name, sourceUrl: x.visitorWebsiteUrl, reviewedAt: reviewedDate }])) };
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`);

const hesReport = JSON.parse(await readFile(resolve('data/review/st-andrews-hes-integrity-2026-08-31.json'), 'utf8')) as any;
if (hesReport.missingStatutoryDesignations || hesReport.undatedVisiblePins) throw new Error('St Andrews HES gate failed.');
pkg.validation = validateFeatures(pkg.project, pkg.features);
const errors = pkg.validation.filter((x) => x.severity === 'error');
if (errors.length) throw new Error(`St Andrews audit introduced ${errors.length} validation errors.`);
await writeFile(projectPath, `${JSON.stringify(pkg, null, 2)}\n`);
await writeFile(reportPath, `${JSON.stringify({ reviewedAt, place: 'St Andrews', townScore: 96, mapPublished: true, categories: { see: { audited: true, published: see.length, rejected: ['Individual listed buildings without an independently visitable 60+ experience', 'Private university interiors without dependable public access', 'Blackfriars Chapel and West Port remain heritage pins rather than inflated standalone attractions'] }, eat: { audited: true, published: eats.length, rejected: ['Dinner-led restaurants, pubs and hotel dining', 'Chains where stronger local café evidence exists', 'Unverified or unnamed OSM food records'] }, trails: { audited: true, published: trails.length, providerChecks: { TreasureTrails: 'Three live direct product pages verified and published', CuriousAbout: 'Checked; no current St Andrews product verified', MysteryGuides: 'Checked; no current St Andrews product verified', GoQuestAdventures: 'Checked; no current St Andrews product verified', officialProviders: 'Fife Coastal Path, Fife Pilgrim Way and VisitScotland EuroWalk verified' } }, picnic: { audited: true, published: picnic.length }, parking: { audited: true, published: parking.length, rejected: '194 raw, unnamed, private, residential, university or otherwise unverified OSM parking geometries withheld.' }, toilets: { audited: true, published: toilets.length, note: 'Craigtoun toilets excluded as outside the strict St Andrews settlement audit.' }, accessibility: { audited: true, notes: 'Venue-specific step, ramp, accessible-toilet, beach and route limitations are retained; no blanket accessible claim is made.' }, transport: { audited: true, notes: 'Council bus-station access and parking approach checked; volatile service timetables are not copied.' }, dogs: { audited: true, townAdjustment: -7 } }, hes: { assigned: hesReport.statutoryDesignationsAssigned, visibleDated: hesReport.visibleHesPins, hiddenUndated: hesReport.hiddenHesPins, visibleUndated: hesReport.undatedVisiblePins, missing: hesReport.missingStatutoryDesignations, designationDatesUsedAsConstructionDates: 0 }, boundaryRule: 'Craigtoun, Dunino Den, the Eden Mill campus and other nearby attractions are not borrowed into St Andrews.' }, null, 2)}\n`);
console.log(`St Andrews full audit complete: score 96; ${see.length} See, ${eats.length} Eat, ${trails.length} Trails, ${picnic.length} Picnic, ${parking.length} Parking, ${toilets.length} Toilets; HES ${hesReport.statutoryDesignationsAssigned} assigned, ${hesReport.undatedVisiblePins} visible undated.`);
