import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const reviewedAt = '2026-08-26T14:00:00.000Z';
const reviewedDate = '2026-08-26';
const projectPath = resolve('data/projects/anstruther.json');
const plannerPath = resolve('data/east-neuk-visitor-planner-curation.json');
const dogPath = resolve('data/east-neuk-dog-access-curation.json');
const project = JSON.parse(await readFile(projectPath, 'utf8')) as ProjectPackage;

for (const item of project.features) item.sourceRecords = item.sourceRecords.filter((record) => record.accessedAt !== reviewedAt);

const museumUrl = 'https://www.scotfishmuseum.org/planning-a-visit.php';
const museumAccessUrl = 'https://www.scotfishmuseum.org/perch/resources/accessstatementsfm.pdf';
const ferryUrl = 'https://www.isleofmayferry.com/info.php';
const ferryTermsUrl = 'https://www.isleofmayferry.com/terms.php';
const harbourUrl = 'https://www.fife.gov.uk/facilities/harbours/anstruther-harbour';
const harbourFactUrl = 'https://www.fife.gov.uk/__data/assets/pdf_file/0019/55243/SP-RTS-SS-02-Fife-Harbours-Fact-Sheet-02-Anstruther.pdf';
const coastalPathUrl = 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/';
const eastStageUrl = 'https://www.walkhighlands.co.uk/fife-stirling/anstruther-crail.shtml';
const westStageUrl = 'https://www.walkhighlands.co.uk/fife-stirling/st-monans-anstruther.shtml';
const townTrailUrl = 'https://www.scotfishmuseum.org/anstruther-town-trail.php';
const treasureTrailUrl = 'https://www.treasuretrails.co.uk/products/things-to-do-anstruther-fife';
const coastCountryCircularUrl = 'https://www.walkfife.org/maps-routes/anstruther-coast-and-country-circular/';
const fishBarUrl = 'https://anstrutherfishbar.co.uk/restaurant/';
const fishBarHoursUrl = 'https://anstrutherfishbar.co.uk/contact-us/';
const fishBarDogUrl = 'https://anstrutherfishbar.co.uk/faqs/';
const weeChippyUrl = 'https://theweechippyanstruther.co.uk/qas/';
const dreelUrl = 'https://www.dreeltavern.co.uk/contact/';
const dreelDogUrl = 'https://www.anstruther.info/food-drink';
const cellarUrl = 'https://cellarat24.co.uk/';
const cellarHoursUrl = 'https://dishcult.com/restaurant/thecellarat24';
const waterfrontUrl = 'https://anstruther-waterfront.co.uk/';
const waterfrontMenuUrl = 'https://www.anstruther-waterfront.co.uk/menus';
const coastUrl = 'https://www.welcometofife.com/inspire-me-post/dog-friendly-cafes-in-fife';
const parkingUrl = 'https://www.fife.gov.uk/roads-travel-parking/parking-and-car-parks/car-park-list';
const parkingChargesUrl = 'https://www.fife.gov.uk/roads-travel-parking/parking-and-car-parks/car-parks-and-car-parking-charges/parking-charges';
const parkingWorksUrl = 'https://www.fife.gov.uk/news/2025/short-stay-parking-restrictions-for-east-basin-car-park-%2C-anstruther%2C-during-summer-months.';
const toiletUrl = 'https://www.fife.gov.uk/facilities/public-toilet/anstruther-public-toilets';
const outdoorCodeUrl = 'https://www.outdooraccess-scotland.scot/dog-owners';

function feature(id: string): HeritageFeature {
  const found = project.features.find((item) => item.id === id);
  if (!found) throw new Error(`Missing Anstruther feature ${id}`);
  return found;
}

function source(sourceName: string, sourceOrganisation: string, sourceUrl: string, notes: string, reliability: 'official_statutory' | 'official_non_statutory' | 'local_authority' | 'secondary' = 'secondary') {
  return { sourceName, sourceOrganisation, sourceUrl, accessedAt: reviewedAt, licence: 'Source-linked editorial record; verify current visitor information before travel.', notes, reliability };
}

function upsert(item: HeritageFeature): HeritageFeature {
  project.features = project.features.filter((existing) => existing.id !== item.id).concat(item);
  return item;
}

function currentFeature(id: string, name: string, featureType: HeritageFeature['featureType'], coordinates: [number, number], shortDescription: string, sources: HeritageFeature['sourceRecords'], tags: string[]): HeritageFeature {
  return {
    id, projectId: project.project.id, name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Fife', locality: 'Anstruther', featureType, significance: 'local',
    geometry: { type: 'Point', coordinates }, locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact',
    shortDescription, sourceRecords: sources, licence: 'Source-linked editorial record; map location may include OpenStreetMap-derived discovery evidence.', tags: [...new Set(['current-context', ...tags])],
    createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence', reviewNotes: 'Current visitor-place record researched in the 2026-08-26 Anstruther full audit.',
  };
}

const museum = feature('curated-attraction:anstruther-1');
Object.assign(museum, {
  name: 'Scottish Fisheries Museum', featureType: 'museum', significance: 'national',
  shortDescription: 'Scotland’s national fishing museum, spread through historic harbour buildings with preserved boats, working collections and the 1903 herring drifter Reaper in high season.',
  fullDescription: 'The museum gives Anstruther a destination-scale indoor experience: galleries cover Scotland’s fishing communities, boats, gear and craft traditions, with the historic boatyard and Reaper adding depth beyond a conventional local museum.',
  visitorWebsiteUrl: museumUrl, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Current operator hours, prices and access statement checked. Pet access is not published; only assistance dogs are confirmed.',
  sourceRecords: [source('Scottish Fisheries Museum visit information', 'Scottish Fisheries Museum', museumUrl, 'Mon–Sat 10:00–16:30; Sun 11:00–16:30; Tuesdays closed November–March; last admission 15:30. Adult £11, concession £8.80, carers free.', 'official_non_statutory'), source('Scottish Fisheries Museum access statement', 'Scottish Fisheries Museum', museumAccessUrl, 'Current access statement confirms assistance dogs and water bowls; it does not publish general pet admission.', 'official_non_statutory')],
  attractionGuide: { headline: 'Step inside Scotland’s fishing story', intro: 'Allow enough time for the galleries, historic boatyard and preserved vessels rather than treating this as a brief local-history room.', bestFor: ['Maritime history', 'Families', 'Historic boats', 'A wet-weather anchor'], parking: 'East Basin and The Folly are closest; St Andrews Road is the free long-stay fallback.', toilets: 'Museum facilities are available to ticket holders; the council harbour toilets are nearby and cost 30p.', picnic: 'Bankie Park has three mapped picnic tables; harbour seating is also close.', foodNote: 'The harbour has an unusually strong cluster of fish-and-chip, café and restaurant options.', trails: [{ name: 'Anstruther Town Trail', summary: 'A museum-researched self-guided map introduces local people and overlooked town stories.', routeType: 'Self-guided heritage walk', duration: 'About 60–90 minutes', difficulty: 'Town streets with some gradients.', externalUrl: townTrailUrl }], thingsToDo: [{ name: 'Explore the galleries', summary: 'Follow fishing from boats and gear to communities and craft.' }, { name: 'See the historic boatyard', summary: 'Look closely at working traditions and preserved vessels.' }, { name: 'Check Reaper access', summary: 'The 1903 herring drifter opens in high season when operational conditions permit.' }] },
});

const ferry = feature('curated-attraction:anstruther-2');
Object.assign(ferry, {
  name: 'Isle of May Ferry – May Princess', featureType: 'other', significance: 'national',
  shortDescription: 'A seasonal wildlife voyage from Anstruther Harbour with a 4½–5 hour landing trip, or selected 2¼-hour cruises around the Isle of May.',
  fullDescription: 'The May Princess sails from April to September. The principal trip includes 2½–3 hours ashore on the National Nature Reserve plus a narrated circuit of the cliffs when conditions allow; selected May and June dates offer a shorter non-landing cruise.',
  visitorWebsiteUrl: ferryUrl, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Current 2026 operator timetable, prices, duration, weather terms and explicit no-dogs rule checked.',
  sourceRecords: [source('May Princess sailing information', 'Anstruther Pleasure Cruises', ferryUrl, 'Landing trip 4.5–5 hours with 2.5–3 hours ashore: adult £40, concession £35, child 3–15 £20, under threes free. Selected cruise-around trip 2.25 hours: adult £30, concession £25, child £15.', 'official_non_statutory'), source('May Princess terms', 'Anstruther Pleasure Cruises', ferryTermsUrl, 'Dogs are not permitted on the boat or island. Sailings and landings are weather-dependent; reasonable agility is required for gangways and steps.', 'official_non_statutory')],
  attractionGuide: { headline: 'Sail to the seabird island', intro: 'Book ahead for the full landing trip, or choose a shorter cruise-around date when offered.', bestFor: ['Puffins and seabirds', 'Boat trips', 'Island history', 'A full half-day experience'], parking: 'Use St Andrews Road for a long visit; East Basin is short-stay during the current harbour works.', toilets: 'Toilets are aboard May Princess and on the island; council harbour toilets are beside Shore Street.', picnic: 'Bring provisions or buy food on Shore Street before boarding.', foodNote: 'Coast Coffee and the harbour takeaways are useful before an early sailing.', trails: [{ name: 'Isle of May paths', summary: 'Landing trips include 2½–3 hours to explore the reserve’s paths.', routeType: 'Island walking', duration: 'Included within the 4½–5 hour trip', difficulty: 'Some rough, steep paths close to cliffs; follow ranger guidance.', externalUrl: ferryUrl }], thingsToDo: [{ name: 'Watch the seabird cliffs', summary: 'Puffins are most likely from April to late July; wildlife is never guaranteed.' }, { name: 'Explore ashore', summary: 'Use the landing time for lighthouses, priory remains and reserve viewpoints.' }, { name: 'Prepare for weather', summary: 'Wear warm waterproof layers and check the sailing before travelling.' }] },
});

const harbour = feature('curated-attraction:anstruther-3');
Object.assign(harbour, {
  name: 'Anstruther Harbour and Waterfront', featureType: 'harbour', significance: 'regional',
  shortDescription: 'A broad two-basin working harbour with four piers, small fishing vessels, leisure craft, museum frontage and an active Shore Street food strip.',
  fullDescription: 'Fife Council records a working harbour of two basins and four piers. The visitor experience is strongest as a free waterfront circuit linking Harbourhead, the museum, Middle Pier, Shore Street and Anstruther Wester Pier.',
  visitorWebsiteUrl: harbourUrl, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Current council harbour page and fact sheet checked; score recognises the working waterfront and unusually complete visitor setting rather than inventing a managed attraction.',
  sourceRecords: [source('Anstruther Harbour', 'Fife Council', harbourUrl, 'Official current record confirms leisure and small fishing use, visitor berths, public and accessible toilets.', 'local_authority'), source('Anstruther Harbour fact sheet', 'Fife Council', harbourFactUrl, 'Official fact sheet documents two basins, four piers, fishing and commercial vessels and the historic Wester Pier.', 'local_authority')],
  attractionGuide: { headline: 'Walk Anstruther’s broad working waterfront', intro: 'Circle the harbour edge from the museum and Middle Pier to Shore Street, while respecting working areas and open water.', bestFor: ['Harbour photography', 'Working boats', 'Food stops', 'A flexible short visit'], parking: 'The Folly is central; East Basin is currently short-stay; St Andrews Road is free for longer visits.', toilets: 'The harbour public toilets open 09:00–20:00 in summer and 09:00–18:00 in winter; charge 30p.', picnic: 'Three mapped tables stand in Bankie Park north of the waterfront.', foodNote: 'Six researched Eats cover destination fish and chips, local small plates, pub food, café stops and harbour dining.', trails: [{ name: 'Fife Coastal Path', summary: 'Continue west to Pittenweem and St Monans or east through Cellardyke towards Crail.', routeType: 'Waymarked linear coast path', duration: '1½–2 hours to either St Monans or Crail', difficulty: 'Generally straightforward coast path; normal outdoor care required.', externalUrl: coastalPathUrl }], thingsToDo: [{ name: 'Watch the working harbour', summary: 'Look for creel boats, visiting craft and the ferry operation.' }, { name: 'Walk to Wester Pier', summary: 'Extend the central waterfront towards the older western harbour structures.' }, { name: 'Pair harbour and museum', summary: 'The national museum turns the waterfront story into a deeper visit.' }] },
});

const coastalTrail = feature('curated-trail:anstruther-fife-coastal-path');
Object.assign(coastalTrail, { name: 'Fife Coastal Path: Anstruther to Crail', shortDescription: 'A popular 6.75 km / 4.25 mile signed stage through Cellardyke and past Caiplie Caves to Crail.', visitorWebsiteUrl: coastalPathUrl, reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Official route hub paired with a current stage description for distance, duration and transport.', sourceRecords: [source('Fife Coastal Path', 'Fife Coast & Countryside Trust', coastalPathUrl, 'Current official long-distance route hub; check live notices before setting out.', 'official_non_statutory'), source('Anstruther to Crail stage', 'Walkhighlands', eastStageUrl, 'Current-place curation: visitor_place_type=Walking route; trail_score=86; trail_type=Linear coastal walk; distance=6.75 km / 4.25 miles; time_to_spend=1.5–2 hours one way; accessibility=Straightforward coastal footpath with exposed and potentially muddy sections; entrance_fee=Free; app=Walkhighlands web app; app_note=Route description and mapping can be saved for use; offline_after_download=Limited; description=Popular coast-path stage from Anstruther Harbour through Cellardyke to Caiplie Caves and Crail.', 'secondary')], tags: [...new Set([...coastalTrail.tags, 'service-context-trail', 'visitor-context-trail'])], editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A highly scenic, waymarked village-to-village stage with clear distance, bus return and strong intermediate interest.', evidenceUrls: [coastalPathUrl, eastStageUrl] } });

const townTrail = upsert(currentFeature('curated-trail:anstruther-town-trail', 'Anstruther Town Trail', 'walking_route', [-2.70054, 56.22273], 'A museum-researched self-guided heritage walk uncovering people and stories around Anstruther’s historic core.', [source('Anstruther Town Trail', 'Scottish Fisheries Museum', townTrailUrl, 'Current-place curation: visitor_place_type=Walking route; trail_score=76; trail_type=Self-guided heritage walk; time_to_spend=60–90 minutes; accessibility=Town streets with some gradients and uneven historic surfaces; entrance_fee=Free; app=Downloadable web map; app_note=Museum page provides the trail resource; offline_after_download=Yes; description=Volunteer-researched town trail created through East Neuk Unearthed with Heritage Lottery Fund and Fife Council support.', 'official_non_statutory')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(townTrail, { visitorWebsiteUrl: townTrailUrl, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A genuine museum-researched heritage route with a downloadable resource and an optional extension to Cellardyke.', evidenceUrls: [townTrailUrl] } });

const treasureTrail = upsert(currentFeature('curated-trail:anstruther-treasure-trail', 'Anstruther – Old Castle & Harbour Treasure Trail', 'walking_route', [-2.7006, 56.2230], 'A family-friendly circular clue trail through the harbour, historic streets and Old Castle, available as an instant download or printed booklet.', [source('Anstruther – Old Castle & Harbour', 'Treasure Trails', treasureTrailUrl, 'Current-place curation: visitor_place_type=Walking route; trail_score=82; trail_type=Self-guided treasure hunt; distance=1.75 miles; time_to_spend=1.5 hours; accessibility=Not wheelchair or pushchair accessible; entrance_fee=£9.99 per trail booklet; app=Instant digital download; app_note=Download the clue booklet before starting; mobile text service supplies clue answers if needed; offline_after_download=Yes; dog_friendly=Yes; start=East Basin Long Stay Car Park, East Shore, KY10 3AB; description=Circular family clue trail around Anstruther Harbour and Old Castle.', 'official_non_statutory')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(treasureTrail, { visitorWebsiteUrl: treasureTrailUrl, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A current bookable/downloadable themed trail with a clear circular route, published duration, distance, access limits and explicit dog policy.', evidenceUrls: [treasureTrailUrl] } });

const coastCountryCircular = upsert(currentFeature('curated-trail:anstruther-coast-country-circular', 'Anstruther Coast and Country Circular', 'walking_route', [-2.7006, 56.2230], 'A long circular walk linking Anstruther, Cellardyke, Kilrenny and Pittenweem by coast path, farmland tracks and minor roads.', [source('Anstruther Coast and Country Circular', 'Walk Fife', coastCountryCircularUrl, 'Current-place curation: visitor_place_type=Walking route; trail_score=79; trail_type=Long circular coast and countryside walk; distance=14.08 km / about 9 miles; time_to_spend=3 hours 31 minutes; accessibility=Grade 3 with tracks, field edges, minor-road sections and a difficult ramshackle bridge; entrance_fee=Free; app=GPX and KML downloads; app_note=Downloadable route files and OS Maps link are provided; offline_after_download=Yes; description=Circular route from Anstruther Harbour through Cellardyke, Kilrenny and Pittenweem.', 'secondary')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(coastCountryCircular, { visitorWebsiteUrl: coastCountryCircularUrl, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A substantial free circular with downloadable GPX/KML and strong four-settlement variety, reduced for dated route notes, road walking and a specifically warned rough bridge.', evidenceUrls: [coastCountryCircularUrl] } });

function curateFood(item: HeritageFeature, name: string, score: number, notes: string, website: string, foodAssessment: NonNullable<HeritageFeature['editorialReview']>['foodAssessment'], openingTimes: string, cuisine: string, priceBand: '£' | '££' | '£££', evidenceUrl = website, coordinates?: [number, number]) {
  item.name = name; if (coordinates) item.geometry = { type: 'Point', coordinates }; item.shortDescription = notes; item.visitorWebsiteUrl = website; item.reviewed = true; item.updatedAt = reviewedAt; item.tags = [...new Set([...item.tags, 'service-context-food', 'visitor-context-food', 'current-context'])];
  item.sourceRecords.push(source(`${name} visitor curation`, 'Townscape Guides source audit', evidenceUrl, `Current daytime food curation: visitor_place_type=${item.featureType === 'restaurant' ? 'Restaurant' : 'Cafe'}; food_score=${score}; visit_score=${score}; price_band=${priceBand}; opening_hours:description=${openingTimes}; cuisine=${cuisine}; description=${notes}`, 'secondary'));
  item.editorialReview = { status: 'editorially_researched', category: 'food', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: notes, evidenceUrls: [website, evidenceUrl], foodAssessment }; return item;
}

const fishBar = curateFood(feature('osm-community:node-7134394557'), 'Anstruther Fish Bar & Restaurant', 90, 'Destination fish and chips: Fresh Scottish fish, restaurant seating and a nationally recognised harbour-front reputation.', fishBarUrl, { foodAndDrinkQuality: 29, daytimeRelevance: 18, distinctiveness: 14, consistency: 14, visitorFit: 9, evidenceConfidence: 6 }, 'Restaurant Sun–Thu 11:30–21:00, Fri–Sat 11:30–21:30; takeaway closes 30 minutes later', 'Scottish fish and chips and seafood', '££', fishBarHoursUrl);
const cellar = curateFood(feature('osm-community:node-6429291103'), 'The Cellar at 24', 84, 'Seasonal Fife small plates: A relaxed wine-bar restaurant using locally caught, grown and made produce.', cellarUrl, { foodAndDrinkQuality: 28, daytimeRelevance: 14, distinctiveness: 14, consistency: 13, visitorFit: 8, evidenceConfidence: 7 }, 'Thu 17:00–22:00; Fri–Sun lunch 12:00–15:00 and evening 17:00–22:00', 'Seasonal Scottish small plates', '£££', cellarHoursUrl);
const dreel = upsert(curateFood(currentFeature('curated-food:anstruther-dreel-tavern', 'The Dreel Tavern', 'restaurant', [-2.7053856, 56.2221547], 'A historic High Street West pub serving locally sourced Scottish food, rotating drinks and a sheltered burn-side beer garden.', [source('The Dreel Tavern contact and hours', 'The Dreel Tavern', dreelUrl, 'Current address, daily 12:00–23:00 except Tuesday closure, and published kitchen times.', 'official_non_statutory')], ['service-context-food', 'visitor-context-food']), 'The Dreel Tavern', 83, 'Historic burn-side pub: Local Scottish food, a strong drinks list, open fire and sunny beer garden.', dreelUrl, { foodAndDrinkQuality: 25, daytimeRelevance: 16, distinctiveness: 13, consistency: 13, visitorFit: 9, evidenceConfidence: 7 }, 'Mon and Wed–Sat food 12:00–14:30 and 17:00–20:30; Sun 12:00–19:00; closed Tue', 'Scottish pub food', '££'));
const weeChippy = upsert(curateFood(currentFeature('curated-food:anstruther-wee-chippy', 'The Wee Chippy', 'restaurant', [-2.7011972, 56.2229392], 'A family-run fish-and-chip restaurant and takeaway with a separate gluten-free preparation area.', [source('The Wee Chippy Q&A', 'The Wee Chippy', weeChippyUrl, 'Operator confirms restaurant 11:30–21:00, takeaway 11:30–22:00 seven days, accessible ramp and toilet, and dogs welcome throughout.', 'official_non_statutory')], ['service-context-food', 'visitor-context-food']), 'The Wee Chippy', 82, 'Dog-welcoming chippy: Fresh Scottish fish, sit-in or takeaway service and a dedicated gluten-free menu.', weeChippyUrl, { foodAndDrinkQuality: 25, daytimeRelevance: 17, distinctiveness: 12, consistency: 13, visitorFit: 9, evidenceConfidence: 6 }, 'Restaurant daily 11:30–21:00; takeaway daily 11:30–22:00', 'Scottish fish and chips', '££'));
const waterfront = curateFood(feature('osm-community:node-7134394515'), 'The Waterfront', 77, 'Harbour dining: Local seafood and Scottish produce served from breakfast through dinner beside the marina.', waterfrontUrl, { foodAndDrinkQuality: 24, daytimeRelevance: 16, distinctiveness: 11, consistency: 12, visitorFit: 8, evidenceConfidence: 6 }, 'Breakfast 08:00–11:45; daily menu 12:00–21:00', 'Scottish seafood and bistro dishes', '££', waterfrontMenuUrl);
const coast = curateFood(feature('osm-community:node-7134353166'), 'Coast Coffee', 75, 'Harbour-view café: Locally sourced coffee, breakfast rolls, panini, toasties and cakes with outdoor tables.', coastUrl, { foodAndDrinkQuality: 22, daytimeRelevance: 18, distinctiveness: 10, consistency: 11, visitorFit: 8, evidenceConfidence: 6 }, 'Daily daytime café; current visitor listing advises checking seasonal hours', 'Coffee, breakfast and light lunches', '£', coastUrl);

const parkingSpecs = [
  { id: 'osm-community:way-290388393', name: 'East Basin Car Park', spaces: 'About 20 during RNLI works (79 published normal capacity)', disabled: 'Harbour inventory records four accessible spaces across East Basin and The Folly', price: '80p for 1 hour / £1.00 for 2 hours', payment: 'Coins or RingGo', hours: 'Daily 08:00–18:00, 1 April–30 September; maximum 2 hours during works', postcode: 'KY10 3AB', url: parkingWorksUrl },
  { id: 'osm-community:way-290388394', name: 'The Folly Car Park', spaces: '32', disabled: 'Harbour inventory records four accessible spaces across The Folly and East Basin', price: 'Up to 4 hours free with ticket; over 4 hours £4.00', payment: 'Ticket machine; coins or RingGo when paying', hours: 'Mon–Sat 08:00–18:00; Sun 13:00–18:00, 1 April–30 September', postcode: 'KY10 3AQ', url: parkingChargesUrl },
  { id: 'osm-community:way-927696440', name: 'St Andrews Road Car Park', spaces: '60', disabled: 'No dedicated accessible spaces recorded in the council asset inventory', price: 'Free', payment: 'None', hours: 'No time restriction published', postcode: 'KY10 3JA', url: 'https://www.fife.gov.uk/facilities/car-park/st-andrews-road-car-park%2C-anstruther', coordinates: [-2.7044236, 56.2241043] as [number, number] },
] as const;
for (const spec of parkingSpecs) {
  const item = feature(spec.id); if ('coordinates' in spec) item.geometry = { type: 'Point', coordinates: spec.coordinates }; item.name = spec.name; item.shortDescription = `${spec.spaces} spaces. ${spec.price}. ${spec.disabled}.`; item.reviewed = true; item.updatedAt = reviewedAt; item.tags = [...new Set([...item.tags, 'service-context-parking', 'visitor-context-parking'])];
  item.sourceRecords.push(source('Fife Council current parking audit', 'Fife Council', spec.url, `Current-place curation: visitor_place_type=Parking; operator=Fife Council; parking=surface; capacity=${spec.spaces}; accessibility=${spec.disabled}; charge=${spec.price}; price_display=${spec.price}; payment_required=${spec.price === 'Free' ? 'No' : 'Yes'}; payment_methods=${spec.payment}; postcode=${spec.postcode}; opening_hours:description=${spec.hours}; confidence=Official current council facility, charges and works information.`, 'local_authority'));
}

const toilet = feature('osm-community:node-11417818487');
Object.assign(toilet, { name: 'Anstruther Harbour Public Toilets', shortDescription: 'Council harbour toilets with male and female WCs, level access, Radar-key accessible toilet, baby changing and Changing Places. Charge 30p.', reviewed: true, updatedAt: reviewedAt, reviewNotes: 'Official location, seasonal hours, charge and accessible facilities checked.', tags: [...new Set([...toilet.tags, 'service-context-toilets', 'visitor-context-toilets'])], sourceRecords: [...toilet.sourceRecords, source('Anstruther Public Toilets', 'Fife Council', toiletUrl, 'Current-context curation: visitor_place_type=Public toilets; opening_hours:description=1 April–31 October 09:00–20:00; 1 November–31 March 09:00–18:00; closed 25–26 December and 1–2 January; charge=30p; wheelchair=Yes; radar_key=Required; baby_changing=Yes; changing_places=Yes; description=Level-access harbour toilet block on Shore Street.', 'local_authority')] });
feature('osm-community:node-3134022496').tags = feature('osm-community:node-3134022496').tags.filter((tag) => !['service-context-toilets', 'visitor-context-toilets'].includes(tag));

for (const [id, number] of [['osm-community:node-3096313449', 'West'], ['osm-community:node-3096313456', 'Centre'], ['osm-community:node-3096313460', 'East']] as const) {
  const item = feature(id); item.name = `Bankie Park Picnic Table – ${number}`; item.shortDescription = 'A mapped public picnic table in Bankie Park, a short uphill walk from the harbour.'; item.reviewed = true; item.updatedAt = reviewedAt; item.tags = [...new Set([...item.tags, 'service-context-picnic', 'visitor-context-picnic'])];
}
feature('osm-community:node-3134022489').tags = feature('osm-community:node-3134022489').tags.filter((tag) => !['service-context-picnic', 'visitor-context-picnic'].includes(tag));

const highlights: VisitorHighlight[] = [
  { rank: 1, featureId: museum.id, name: museum.name, reason: 'A national museum with substantial galleries, historic buildings, a working boatyard and preserved vessels.', visitorScore: 92, tagline: 'Scotland’s national fishing museum', timeToSpend: '1½–2½ hours', openingTimes: 'Mon–Sat 10:00–16:30; Sun 11:00–16:30. Closed Tuesdays November–March. Last entry 15:30.', admission: 'Adult £11; concession £8.80; carers free.', freeAdmission: false, visitorWebsiteUrl: museumUrl, sourceName: 'Scottish Fisheries Museum', sourceUrl: museumUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'National significance, deep collections and unusually strong harbour setting with clear current visit information.', evidenceUrls: [museumUrl, museumAccessUrl], attractionAssessment: { experienceDepth: 30, distinctiveness: 20, presentation: 19, journeyWorth: 15, accessAndReliability: 4, evidenceConfidence: 4, visitability: 'full_visitor_experience' } } },
  { rank: 2, featureId: ferry.id, name: ferry.name, reason: 'A destination-scale wildlife voyage with meaningful island time, ranger welcome, cliff circuit and transparent 2026 booking information.', visitorScore: 91, tagline: 'Land on the Isle of May', timeToSpend: '4½–5 hours landing trip; about 2¼ hours cruise-around', openingTimes: 'Seasonal sailings April–September; times vary with tide and weather. Advance booking strongly advised.', admission: 'Landing trip: adult £40, concession £35, child £20. Cruise-around: adult £30, concession £25, child £15.', freeAdmission: false, visitorWebsiteUrl: ferryUrl, sourceName: 'Anstruther Pleasure Cruises', sourceUrl: ferryUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'An exceptional seasonal wildlife and island-history experience, slightly reduced for weather dependence, seasonality and physical access constraints.', evidenceUrls: [ferryUrl, ferryTermsUrl], attractionAssessment: { experienceDepth: 30, distinctiveness: 20, presentation: 18, journeyWorth: 15, accessAndReliability: 4, evidenceConfidence: 4, visitability: 'full_visitor_experience' } } },
  { rank: 3, featureId: harbour.id, name: harbour.name, reason: 'A large and legible working waterfront where museum, ferry, fishing boats, leisure craft, historic piers and food all reinforce one another.', visitorScore: 84, tagline: 'Two basins and four piers', timeToSpend: '45–90 minutes', openingTimes: 'Open-air waterfront; daylight visit recommended. Respect working areas and harbour instructions.', admission: 'Free.', freeAdmission: true, visitorWebsiteUrl: harbourUrl, sourceName: 'Fife Council', sourceUrl: harbourUrl, verifiedInBoundaryAt: reviewedDate, editorialReview: { status: 'editorially_researched', category: 'attraction', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A strong, active waterfront with multiple linked visitor reasons, reduced because it is a working public harbour rather than a managed attraction.', evidenceUrls: [harbourUrl, harbourFactUrl], attractionAssessment: { experienceDepth: 24, distinctiveness: 17, presentation: 16, journeyWorth: 13, accessAndReliability: 10, evidenceConfidence: 4, visitability: 'full_visitor_experience' } } },
];

project.project.visitorHighlights = highlights;
project.project.touristAppeal = { score: 90, dogOwnerScore: 84, dogAccessScoreAdjustment: -6, rating: 3, label: 'Exceptional Destination', summary: 'Anstruther earns destination status through three mutually reinforcing draws: Scotland’s national fishing museum, seasonal Isle of May landings and a broad working harbour, backed by unusually strong food, four genuine trails and complete practical facilities.', dogAccessRating: 2, dogAccessSummary: 'The harbour, town trail, coast path, Treasure Trail and several excellent Eats work well with a dog, but the two flagship paid experiences do not: the ferry explicitly carries no dogs and the museum only confirms assistance dogs. That materially reduces, but does not erase, the town’s value for dog owners.', methodVersion: '2026-08-26-full-settlement-visitor-audit-v1', reviewedAt: reviewedDate, sourceUrls: [museumUrl, ferryUrl, harbourUrl, coastalPathUrl, townTrailUrl, treasureTrailUrl, coastCountryCircularUrl, fishBarUrl, weeChippyUrl, dreelUrl, cellarUrl, parkingUrl, toiletUrl, outdoorCodeUrl] };
project.project.townGuide = { characterTag: 'National fishing museum and Isle of May harbour', headline: 'The East Neuk’s most complete maritime day out', intro: 'Anstruther is more than a photogenic harbour stop. Scotland’s fishing story fills a national museum at Harbourhead, boats sail to the seabird cliffs of the Isle of May, and Shore Street supplies one of the East Neuk’s deepest clusters of food and practical visitor services.', bestFor: ['Maritime history', 'Isle of May wildlife', 'Harbour food', 'Coastal walking'], perfectFor: ['A full East Neuk day', 'Visitors wanting indoor depth and an outdoor waterfront'], suggestedFirstVisit: { title: 'Build the day around museum or ferry', summary: 'Reserve the seasonal ferry first if it is your priority; otherwise start at the museum, circle the harbour, eat on Shore Street and finish with the town trail or a coast-path section.' }, dontMiss: ['Scottish Fisheries Museum', 'Isle of May Ferry – May Princess', 'Anstruther Harbour and Waterfront', 'Anstruther Fish Bar & Restaurant', 'Anstruther – Old Castle & Harbour Treasure Trail'], suggestedTime: 'Half day without the ferry; a full day with an Isle of May landing', visitorMood: 'A genuinely complete destination rather than a single-view stop: deep maritime interpretation, a major wildlife excursion, strong food and useful facilities all fit within a compact walkable centre.', sourceUrls: [museumUrl, ferryUrl, harbourUrl, coastalPathUrl, eastStageUrl, westStageUrl, townTrailUrl, treasureTrailUrl, coastCountryCircularUrl, fishBarUrl, weeChippyUrl, dreelUrl, cellarUrl, waterfrontUrl, coastUrl, parkingChargesUrl, toiletUrl], lastReviewedAt: reviewedDate };
project.project.visualIdentity = { theme: 'east-neuk-maritime-harbour', badgeImage: '/town-guides/anstruther-working-harbour-watercolour-guide.png', badgeAlt: 'Watercolour illustration of Anstruther’s broad working harbour, museum frontage, fishing boats and Isle of May ferry', heroImage: '/town-guides/anstruther-working-harbour-watercolour-guide.png', heroAlt: 'Watercolour illustration of Anstruther’s broad working harbour, museum frontage, fishing boats and Isle of May ferry', heroObjectPosition: '50% 58%', motifs: ['Working harbour', 'Fishing museum', 'Isle of May ferry', 'East Neuk waterfront'], primaryColour: '#17464A', accentColour: '#B27713', backgroundColour: '#EAF2F0' };

const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as { projects: Record<string, Record<string, string[]>> };
planner.projects[project.project.id] = { eat: [fishBar.id, cellar.id, dreel.id, weeChippy.id, waterfront.id, coast.id], trails: [treasureTrail.id, coastalTrail.id, townTrail.id, coastCountryCircular.id], parking: parkingSpecs.map((item) => item.id), toilets: [toilet.id], picnic: ['osm-community:node-3096313449', 'osm-community:node-3096313456', 'osm-community:node-3096313460'] };
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`, 'utf8');

const dog = JSON.parse(await readFile(dogPath, 'utf8')) as { reviewedAt: string; projects: Record<string, { attraction?: Record<string, unknown>; eat?: Record<string, unknown> }> };
dog.reviewedAt = reviewedDate;
dog.projects[project.project.id] = { attraction: {
  [museum.id]: { rating: 1, status: 'restricted', label: 'Only assistance dogs confirmed', summary: 'The museum’s current access statement welcomes assistance dogs and provides water bowls, but it does not publish admission for pet dogs. Dog owners should treat the indoor museum experience as unavailable unless the museum confirms otherwise.', sourceName: 'Scottish Fisheries Museum access statement', sourceUrl: museumAccessUrl, reviewedAt: reviewedDate },
  [ferry.id]: { rating: 0, status: 'not-allowed', label: 'Dogs prohibited on boat and island', summary: 'The operator explicitly states that dogs are not permitted on the May Princess or the Isle of May. This removes the town’s flagship half-day excursion for visitors who must keep their dog with them.', sourceName: 'Anstruther Pleasure Cruises terms', sourceUrl: ferryTermsUrl, reviewedAt: reviewedDate },
  [harbour.id]: { rating: 3, status: 'welcoming', label: 'Outdoor working-harbour walk', summary: 'Dogs can accompany the outdoor waterfront under responsible-access rules. Keep them close beside working areas, food queues, traffic, piers and open water.', sourceName: 'Fife Council harbour information and Scottish Outdoor Access Code', sourceUrl: outdoorCodeUrl, reviewedAt: reviewedDate },
  [coastalTrail.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable coastal path', summary: 'Dogs can use the coast path under responsible-access rules, with close control around livestock, wildlife, shore and cliff hazards and other walkers.', sourceName: 'Fife Coastal Path and Scottish Outdoor Access Code', sourceUrl: outdoorCodeUrl, reviewedAt: reviewedDate },
  [townTrail.id]: { rating: 3, status: 'welcoming', label: 'Outdoor town circuit', summary: 'The town trail uses public streets and outdoor stops, so dogs can accompany it. Use a lead through the busy harbour and narrow historic streets.', sourceName: 'Scottish Fisheries Museum town trail and Outdoor Access Code', sourceUrl: outdoorCodeUrl, reviewedAt: reviewedDate },
  [treasureTrail.id]: { rating: 3, status: 'welcoming', label: 'Explicitly dog-friendly clue trail', summary: 'Treasure Trails explicitly marks this outdoor circular as dog-friendly. Keep dogs close around the working harbour, roads and busy clue stops.', sourceName: 'Treasure Trails Anstruther product page', sourceUrl: treasureTrailUrl, reviewedAt: reviewedDate },
  [coastCountryCircular.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable long country circuit', summary: 'The route is predominantly outdoors, but crosses farmland, minor roads and a rough bridge. Keep dogs under close control around livestock, wildlife, traffic and other path users.', sourceName: 'Walk Fife route and Scottish Outdoor Access Code', sourceUrl: coastCountryCircularUrl, reviewedAt: reviewedDate },
}, eat: {
  [fishBar.id]: { rating: 0, status: 'not-allowed', label: 'Pet dogs not admitted', summary: 'The operator publishes a no-pets policy for both restaurant and takeaway areas; assistance dogs are permitted. Plan for outdoor takeaway eating if visiting with a pet dog.', sourceName: 'Anstruther Fish Bar FAQ', sourceUrl: fishBarDogUrl, reviewedAt: reviewedDate },
  [cellar.id]: { rating: 2, status: 'restricted', label: 'Dogs in bar at lunch only', summary: 'Dogs are welcome on leads in the bar during lunch service, but the main dining room and all evening services are pet-free.', sourceName: 'The Cellar at 24 dog policy', sourceUrl: cellarUrl, reviewedAt: reviewedDate },
  [dreel.id]: { rating: 3, status: 'welcoming', label: 'Dog-friendly pub and garden', summary: 'Current local visitor information and the venue’s dog page welcome friendly dogs in the pub area and beer garden, with treats available.', sourceName: 'Visit Anstruther and Dreel Tavern dog information', sourceUrl: dreelDogUrl, reviewedAt: reviewedDate },
  [weeChippy.id]: { rating: 3, status: 'welcoming', label: 'Dogs welcome throughout', summary: 'The operator explicitly welcomes well-behaved dogs in both restaurant and takeaway and provides bowls and treats.', sourceName: 'The Wee Chippy Q&A', sourceUrl: weeChippyUrl, reviewedAt: reviewedDate },
  [waterfront.id]: { rating: 0, status: 'unconfirmed', label: 'Restaurant dog policy not published', summary: 'A clear current pet policy for dining is not published on the restaurant or accommodation pages. Confirm directly before relying on indoor access.', sourceName: 'The Waterfront current website review', sourceUrl: waterfrontUrl, reviewedAt: reviewedDate },
  [coast.id]: { rating: 2, status: 'restricted', label: 'Dog-friendly outdoor café stop', summary: 'Welcome to Fife specifically recommends Coast Coffee for visitors with dogs and highlights its outdoor seating; indoor access is not confirmed by that source.', sourceName: 'Welcome to Fife dog-friendly cafés', sourceUrl: coastUrl, reviewedAt: reviewedDate },
} };
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`, 'utf8');

project.validation = validateFeatures(project.project, project.features);
const errors = project.validation.filter((item) => item.severity === 'error');
if (errors.length) throw new Error(`Anstruther audit introduced ${errors.length} validation errors: ${errors.map((item) => item.message).join('; ')}`);
await writeFile(projectPath, `${JSON.stringify(project, null, 2)}\n`, 'utf8');
await writeFile(resolve('data/review/anstruther-full-visitor-audit-2026-08-26.json'), `${JSON.stringify({ reviewedAt, townScore: 90, dogOwnerScore: 84, publicationRule: 'visitor score > 60', attractions: highlights.map(({ name, visitorScore }) => ({ name, score: visitorScore, published: true })), trails: [{ name: treasureTrail.name, score: 82, format: 'Instant digital download or printed booklet', dogFriendly: true }, { name: coastalTrail.name, score: 86 }, { name: townTrail.name, score: 76 }, { name: coastCountryCircular.name, score: 79, downloads: 'GPX and KML' }], facilities: { eat: [{ name: fishBar.name, score: 90 }, { name: cellar.name, score: 84 }, { name: dreel.name, score: 83 }, { name: weeChippy.name, score: 82 }, { name: waterfront.name, score: 77 }, { name: coast.name, score: 75 }], parking: parkingSpecs.map((item) => ({ name: item.name, spaces: item.spaces, price: item.price, payment: item.payment, hours: item.hours, accessibility: item.disabled })), toilets: [{ name: toilet.name, hours: 'Summer 09:00–20:00; winter 09:00–18:00', charge: '30p', accessible: 'Level access, Radar-key toilet and Changing Places' }], picnic: ['Three mapped tables in Bankie Park'] }, dogAudit: { townAdjustment: -6, attractionPolicies: 'Harbour 3 paws; Treasure Trail 3; town trail 3; coast path and coast-country circular 2; museum 1; Isle of May ferry 0', foodPolicies: 'Wee Chippy and Dreel 3 paws; Cellar and Coast 2; Fish Bar 0; Waterfront unconfirmed' }, exclusions: ['Temporary RNLI park-and-ride noted in source review but not published as a permanent library car park', 'East Basin normal capacity superseded by the official works notice while construction continues', 'Lifeboat-station works are not published as a visitor attraction', 'Memorials and churches retained on the heritage map but below the >60 standalone visitor-experience threshold'] }, null, 2)}\n`, 'utf8');
console.log('Anstruther audit complete: 3 attractions, 6 Eats, 4 trails, 3 official car parks, 1 public toilet block and 3 picnic tables.');
