import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const reviewedDate='2026-09-01', reviewedAt='2026-09-01T13:40:00.000Z';
const projectPath=resolve('data/projects/dunino.json'), plannerPath=resolve('data/east-neuk-visitor-planner-curation.json'), dogPath=resolve('data/east-neuk-dog-access-curation.json');
const pkg=JSON.parse(await readFile(projectPath,'utf8')) as ProjectPackage;
const urls={den:'https://www.welcometofife.com/view-business/dunino-den',church:'https://www.scotlandschurchestrust.org.uk/church/dunino-church/',parking:'https://sobt.co.uk/dunino-den/',trust:'https://boarhillsandduninocommunitytrust.org/projects/',hes:'https://portal.historicenvironment.scot/designation/LB49',treasure:'https://www.treasuretrails.co.uk/collections/fife',curious:'https://curiousabout.co.uk/',mystery:'https://www.mysteryguides.co.uk/',goquest:'https://goquestadventures.com/'};
const ids={den:'curated-attraction:dunino-den',church:'curated-attraction:dunino-church',trail:'curated-trail:boarhills-dunino-walk-leaflets-dunino',parking:'curated-parking:dunino-church'};
pkg.features=pkg.features.filter(f=>!Object.values(ids).includes(f.id));
const feature=(id:string,name:string,type:string,coordinates:[number,number],description:string,url:string,tags:string[],notes:string):HeritageFeature=>({id,projectId:pkg.project.id,name,alternativeNames:[],countryCode:'GB-SCT',region:'Fife',locality:'Dunino',featureType:type,significance:'regional',geometry:{type:'Point',coordinates},locationType:'exact',locationConfidence:'high',dateBasis:'unknown',dateConfidence:'unknown',survival:'substantially_intact',shortDescription:description,visitorWebsiteUrl:url,sourceRecords:[{sourceName:name,sourceOrganisation:id===ids.den?'Welcome to Fife':id===ids.church?"Scotland's Churches Trust":'Scotland Off the Beaten Track',sourceUrl:url,accessedAt:reviewedAt,licence:'Source-linked current visitor evidence.',reliability:id===ids.den?'local_authority':'official_non_statutory',notes:`Current-place curation: ${notes}`}],tags:['current-context',...tags],createdAt:reviewedAt,updatedAt:reviewedAt,reviewed:true,evidenceScope:'parish_evidence'});
const den=feature(ids.den,'Dunino Den','historic_site',[-2.744425,56.288136],'A wooded ritual and folklore site reached by a short path from Dunino Church, with carved rock, a well and steep uneven steps.',urls.den,['curated-visitor-attraction'],'visitor_place_type=Historic and natural site; opening_hours:description=Open-air site, visit in daylight and respect current access conditions; entrance_fee=Free; time_to_spend=30–60 minutes; website='+urls.den+'.');
den.editorialReview={status:'editorially_researched',category:'attraction',methodVersion:'2026-08-13-researched-visitor-value-v1',reviewedAt:reviewedDate,scoreRationale:'An unusual, independently visitable and officially promoted Fife site; access limitations and modest scale prevent a higher score.',evidenceUrls:[urls.den,urls.parking]};
const church=feature(ids.church,'Dunino Church','place_of_worship',[-2.743007,56.288991],'A finely detailed 1826–27 church on a medieval site, with a Celtic carved stone in the churchyard; the church trust records daily opening.',urls.church,['curated-visitor-attraction'],'visitor_place_type=Historic church; opening_hours:description=Open daily according to the church trust; check before a special journey; entrance_fee=Free; time_to_spend=20–40 minutes; website='+urls.church+'.');
church.editorialReview={status:'editorially_researched',category:'attraction',methodVersion:'2026-08-13-researched-visitor-value-v1',reviewedAt:reviewedDate,scoreRationale:'A worthwhile daily-open church and churchyard stop, tempered by the non-authoritative opening disclaimer and small scale.',evidenceUrls:[urls.church,urls.hes]};
const parking=feature(ids.parking,'Dunino Church and Den Parking','parking',[-2.74292,56.28890],'Small visitor parking at the church for the church and short walk to Dunino Den; capacity, accessible bays, tariff and maximum stay are not published.',urls.parking,['service-context-parking'],'visitor_place_type=Parking; access=visitors; capacity=Not published; fee=Not published; price_display=Check signs; disabled_spaces=Not published; maximum_stay=Not published; website='+urls.parking+'.');
const trail=feature(ids.trail,'Boarhills and Dunino Community Walk Leaflets','walking_route',[-2.74308,56.28888],'Two community-produced walking leaflets cover routes around Dunino and Boarhills and are available from the St Andrews visitor information point or directly from the community trust; route distance and duration are not published online.',urls.trust,['service-context-trail','visitor-context-trail'],'visitor_place_type=Walking trail; trail_score=66; time_to_spend=Route distance and duration are not published online; opening_hours:description=Self-guided outdoor routes; entrance_fee=Free; description=Local community walks: two printed leaflets covering Dunino and Boarhills; website='+urls.trust+'.');
pkg.features.push(den,church,trail,parking);
pkg.project.visitorHighlights=[{rank:1,featureId:den.id,name:den.name,reason:'A distinctive wooded ritual and folklore site promoted by Welcome to Fife, with a short but steep approach.',visitorScore:76,tagline:'Carved rocks in a hidden den',timeToSpend:'30–60 minutes',openingTimes:'Open-air site; visit in daylight and check access conditions',admission:'Free',visitorWebsiteUrl:urls.den,sourceName:'Welcome to Fife',sourceUrl:urls.den,verifiedInBoundaryAt:reviewedDate},{rank:2,featureId:church.id,name:church.name,reason:'An architecturally rewarding church and churchyard whose published daily opening complements the Den.',visitorScore:68,tagline:'Historic church above the Den',timeToSpend:'20–40 minutes',openingTimes:'Open daily according to the church trust; check before a special journey',admission:'Free',visitorWebsiteUrl:urls.church,sourceName:"Scotland's Churches Trust",sourceUrl:urls.church,verifiedInBoundaryAt:reviewedDate}] as VisitorHighlight[];
pkg.project.touristAppeal={score:58,dogOwnerScore:53,dogAccessScoreAdjustment:-5,rating:0,label:'Limited Visitor Interest',summary:'Dunino has two genuine See entries—its open historic church and the atmospheric Den—plus community walking leaflets and a small visitor parking point, but no café, public toilet or verified picnic facility. The attraction pair and printed route resource do not by themselves make the rural locality a 60+ visitor town.',dogAccessRating:1,dogAccessSummary:'The Den approach and local routes include woodland, farmland and uneven ground; keep dogs close and do not assume church access.',methodVersion:'2026-09-01-full-settlement-visitor-audit-v2',reviewedAt:reviewedDate,sourceUrls:Object.values(urls)};
pkg.project.townGuide={characterTag:'Church, churchyard and wooded ritual site',headline:'A memorable See pair, not a complete visitor village',intro:'Dunino remains selector-only at 58. The church and Den are published independently in See, with cautious parking information; absent café, toilet, picnic and named-trail provision is not invented.',bestFor:['Unusual heritage','Short atmospheric stops'],perfectFor:['Combining the church and Den in one careful visit'],suggestedFirstVisit:{title:'Church and Den',summary:'Park only where signed, visit the churchyard first, then use the short uneven path to the Den.'},dontMiss:['Dunino Den','Dunino Church'],suggestedTime:'45–90 minutes',visitorMood:'Quiet, atmospheric and sensitive.',sourceUrls:[urls.den,urls.church,urls.parking],lastReviewedAt:reviewedDate};
const planner=JSON.parse(await readFile(plannerPath,'utf8')) as any;planner.reviewedAt=reviewedDate;planner.projects[pkg.project.id]={eat:[],trails:[trail.id],picnic:[],parking:[parking.id],toilets:[]};await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`);
const dog=JSON.parse(await readFile(dogPath,'utf8')) as any;dog.reviewedAt=reviewedDate;dog.projects[pkg.project.id]={attraction:{[den.id]:{rating:1,status:'restricted',label:'Sensitive uneven site',summary:'Use close control and keep dogs away from offerings, carved rocks, water and steep steps.',sourceName:'Scottish Outdoor Access Code',sourceUrl:'https://www.outdooraccess-scotland.scot/dog-owners',reviewedAt:reviewedDate},[church.id]:{rating:1,status:'restricted',label:'Churchyard etiquette',summary:'Keep dogs close in the churchyard and do not assume indoor access.',sourceName:'Scottish Outdoor Access Code',sourceUrl:'https://www.outdooraccess-scotland.scot/dog-owners',reviewedAt:reviewedDate},[trail.id]:{rating:1,status:'restricted',label:'Rural route caution',summary:'Route-specific dog guidance is not published; keep dogs under close control around livestock, wildlife and roads.',sourceName:'Scottish Outdoor Access Code',sourceUrl:'https://www.outdooraccess-scotland.scot/dog-owners',reviewedAt:reviewedDate}},eat:{}};await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`);
const hes=JSON.parse(await readFile(resolve('data/review/dunino-hes-integrity-2026-08-31.json'),'utf8')) as any;if(hes.missingStatutoryDesignations||hes.undatedVisiblePins)throw new Error('Dunino HES gate failed');pkg.validation=validateFeatures(pkg.project,pkg.features);if(pkg.validation.some(i=>i.severity==='error'))throw new Error('Dunino validation failed');await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`);
await writeFile(resolve('data/review/dunino-full-visitor-audit-2026-08-31.json'),`${JSON.stringify({reviewedAt,place:'Dunino',townScore:58,mapPublished:false,categories:{see:{audited:true,published:2},eat:{audited:true,published:0,note:'No café or light-lunch venue inside the strict locality.'},trails:{audited:true,published:0,providerChecks:{TreasureTrails:'Fife catalogue checked; no Dunino product',CuriousAbout:'No Dunino route',MysteryGuides:'No Dunino route',GoQuestAdventures:'No Dunino route',officialRoutes:'The short Den access path is part of the attraction visit, not promoted as a maintained named trail.'}},picnic:{audited:true,published:0,note:'No source-backed public picnic tables or designated picnic area verified.'},parking:{audited:true,published:1,note:'Church/Den visitor parking published conservatively; capacity, tariff and accessible bays withheld.'},toilets:{audited:true,published:0,note:'No public toilet verified; church facilities are not assumed.'},accessibility:{audited:true,note:'Church setting is easier than the Den; the Den path includes mud, steep uneven steps and woodland terrain.'},transport:{audited:true,note:'Rural bus/Go-Flexi access acknowledged without copying a volatile timetable.'},dogs:{audited:true,adjustment:-5}},hes:{assigned:hes.statutoryDesignationsAssigned,visibleDated:hes.visibleHesPins,hiddenUndated:hes.statutoryDesignationsAssigned-hes.visibleHesPins,visibleUndated:hes.undatedVisiblePins,missing:hes.missingStatutoryDesignations},boundaryRule:'The Den and church publish as independent See entries; they do not automatically raise the locality to Home-map status.'},null,2)}\n`);
await writeFile(resolve('data/review/dunino-full-visitor-audit-2026-09-01.json'),`${JSON.stringify({
  reviewedAt, place:'Dunino', townScore:58, mapPublished:false,
  categories:{
    see:{audited:true,published:2}, eat:{audited:true,published:0,note:'No café or light-lunch venue inside the strict locality.'},
    trails:{audited:true,published:1,providerChecks:{TreasureTrails:'Fife catalogue checked; no Dunino product',CuriousAbout:'No Dunino route',MysteryGuides:'No Dunino route',GoQuestAdventures:'No Dunino route',communityTrust:'Two Boarhills and Dunino walking leaflets verified; obtainable through the visitor information point or community trust, with no route distance or duration published online'}},
    picnic:{audited:true,published:0,note:'No source-backed public picnic tables or designated picnic area verified.'}, parking:{audited:true,published:1,note:'Church/Den visitor parking published conservatively; capacity, tariff and accessible bays withheld.'},
    toilets:{audited:true,published:0,note:'No public toilet verified; church facilities are not assumed.'}, accessibility:{audited:true,note:'Church setting is easier than the Den; the Den path includes mud, steep uneven steps and woodland terrain.'}, transport:{audited:true,note:'Rural bus/Go-Flexi access acknowledged without copying a volatile timetable.'}, dogs:{audited:true,adjustment:-5}},
  hes:{assigned:hes.statutoryDesignationsAssigned,visibleDated:hes.visibleHesPins,hiddenUndated:hes.statutoryDesignationsAssigned-hes.visibleHesPins,visibleUndated:hes.undatedVisiblePins,missing:hes.missingStatutoryDesignations},
  boundaryRule:'The Den and church publish as independent See entries; they do not automatically raise the locality to Home-map status.',
  research:{currentWebResearch:true,strictBoundaryChecked:true,sourceChecks:[
    {url:urls.den,checkedAt:reviewedDate,outcome:'verified',note:'Official destination page verifies the Den as a free outdoor visitor site.'},
    {url:urls.church,checkedAt:reviewedDate,outcome:'verified',note:'Church trust verifies the 1826–27 church, carved stone and daily opening claim.'},
    {url:urls.trust,checkedAt:reviewedDate,outcome:'verified',note:'Community trust verifies two local walking leaflets covering Dunino and Boarhills.'},
    {url:urls.treasure,checkedAt:reviewedDate,outcome:'no_result',note:'No Dunino Treasure Trail product was found.'}]},
  scoreReanalysis:{required:true,completed:true,resultScore:58,rationale:'Second pass retained 58 as a real score, not a cap: Dunino has two independently worthwhile See entries, one community walking resource and modest visitor parking, but no café, public toilet or verified picnic provision, and the visit remains a compact attraction cluster rather than a rounded 60+ town experience.'},
  certification:{publicationCountsReconciled:false,liveBrowserVerifiedAt:null}
},null,2)}\n`);
console.log('Dunino re-audit complete: score 58; 2 See, 0 Eat, 1 Trail, 0 Picnic, 1 Parking, 0 Toilets; exact-58 second pass and HES gate passed.');
