import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const reviewedAt = '2026-08-26T16:00:00.000Z';
const reviewedDate = '2026-08-26';
const projectPath = resolve('data/projects/pittenweem.json');
const plannerPath = resolve('data/east-neuk-visitor-planner-curation.json');
const dogPath = resolve('data/east-neuk-dog-access-curation.json');
const project = JSON.parse(await readFile(projectPath, 'utf8')) as ProjectPackage;
for (const item of project.features) item.sourceRecords = item.sourceRecords.filter((record) => record.accessedAt !== reviewedAt);

const urls = {
  harbour: 'https://www.fife.gov.uk/facilities/harbours/pittenweem-harbour',
  harbourFact: 'https://www.fife.gov.uk/__data/assets/file/0022/41197/SP-RTS-SS-02-Fife-Harbours-Fact-Sheet-09-Pittenweem.pdf',
  visitor: 'https://pittenweemlibrary.org.uk/pittenweem-visitor-information-2026/',
  westBraes: 'https://thewestbraes.co.uk/',
  westBraesCouncil: 'https://www.fife.gov.uk/facilities/park/west-braes',
  gallery: 'https://www.weemgalleryandframer.co.uk/about/',
  coastalPath: 'https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/',
  coastalStage: 'https://www.walkhighlands.co.uk/fife-stirling/st-monans-anstruther.shtml',
  treasure: 'https://www.treasuretrails.co.uk/products/things-to-do-pittenweem-fife',
  circular: 'https://themackwalks.wordpress.com/2019/03/11/061-pittenweem-st-monans-abercrombie-circular-fife/',
  dory: 'https://www.thedory.co.uk/our-menu/',
  doryDog: 'https://mobile.thegoodfoodguide.co.uk/restaurant/the-dory-bistro/id/49502',
  cocoa: 'https://pittenweemchocolate.co.uk/pages/our-story',
  communityFood: 'https://www.aboutpittenweem.org.uk/shops.html',
  festivalFood: 'https://www.pittenweemartsfestival.co.uk/visit-us/food-and-drink/',
  iceCream: 'https://pittenweemsweetshop.co.uk/',
  westEnd: 'https://www.westendbarpittenweem.co.uk/',
  parkingInventory: 'https://arcgis-live-as.fife.gov.uk/server/rest/services/Assets_CarParking/MapServer/0',
  westBraesParking: 'https://www.searchforsites.co.uk/marker.php?id=48645',
  toilet: 'https://www.fife.gov.uk/facilities/public-toilet/pittenweem-public-toilets',
  outdoorCode: 'https://www.outdooraccess-scotland.scot/dog-owners',
};

function feature(id: string): HeritageFeature {
  const found = project.features.find((item) => item.id === id);
  if (!found) throw new Error(`Missing Pittenweem feature ${id}`);
  return found;
}

function source(sourceName: string, sourceOrganisation: string, sourceUrl: string, notes: string, reliability: 'official_statutory' | 'official_non_statutory' | 'local_authority' | 'secondary' = 'secondary') {
  return { sourceName, sourceOrganisation, sourceUrl, accessedAt: reviewedAt, licence: 'Source-linked editorial record; verify current visitor information before travel.', notes, reliability };
}

function currentFeature(id: string, name: string, featureType: string, coordinates: [number, number], shortDescription: string, sources: HeritageFeature['sourceRecords'], tags: string[]): HeritageFeature {
  return {
    id, projectId: project.project.id, name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Fife', locality: 'Pittenweem', featureType,
    significance: 'local', geometry: { type: 'Point', coordinates }, locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown',
    dateConfidence: 'unknown', survival: 'substantially_intact', shortDescription, sourceRecords: sources,
    licence: 'Source-linked editorial record; map location may include OpenStreetMap-derived discovery evidence.', tags: [...new Set(['current-context', ...tags])],
    createdAt: reviewedAt, updatedAt: reviewedAt, reviewed: true, evidenceScope: 'parish_evidence',
    reviewNotes: 'Current visitor-place record researched in the 2026-08-26 Pittenweem full audit.',
  };
}

function upsert(item: HeritageFeature): HeritageFeature {
  project.features = project.features.filter((existing) => existing.id !== item.id).concat(item);
  return item;
}

function attractionReview(scoreRationale: string, evidenceUrls: string[], scores: [number, number, number, number, number, number]) {
  const [experienceDepth, distinctiveness, presentation, journeyWorth, accessAndReliability, evidenceConfidence] = scores;
  return { status: 'editorially_researched' as const, category: 'attraction' as const, methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale, evidenceUrls, attractionAssessment: { experienceDepth, distinctiveness, presentation, journeyWorth, accessAndReliability, evidenceConfidence, visitability: 'full_visitor_experience' as const } };
}

const harbour = feature('curated-attraction:pittenweem-1');
Object.assign(harbour, {
  name: 'Pittenweem Working Harbour and Wynds', significance: 'regional', visitorWebsiteUrl: urls.harbour, reviewed: true, updatedAt: reviewedAt,
  shortDescription: 'Fife’s principal working fishing harbour, enclosed by stone piers and a steep, compact townscape of historic wynds.',
  fullDescription: 'Pittenweem is still predominantly a commercial fishing harbour. The most rewarding free visit combines the basin and piers with Cove Wynd, Water Wynd and the stepped streets immediately behind the waterfront.',
  reviewNotes: 'Current Fife Council harbour information and official fact sheet checked; score reflects the authentic working setting and townscape rather than inventing a managed attraction.',
  sourceRecords: [source('Pittenweem Harbour', 'Fife Council', urls.harbour, 'Official current harbour record; opening hours Mon–Fri 06:30–21:00 and almost exclusively commercial use.', 'local_authority'), source('Pittenweem Harbour fact sheet', 'Fife Council', urls.harbourFact, 'Official harbour layout and operational context.', 'local_authority')],
  attractionGuide: { headline: 'Walk a genuine East Neuk fishing harbour', intro: 'Follow the public waterfront and climb the adjoining wynds while respecting boats, gear, open water and working areas.', bestFor: ['Working fishing boats', 'Harbour photography', 'Historic wynds', 'A flexible free visit'], parking: 'Market Place is the nearest small official council car park; West Braes is better for a longer visit.', toilets: 'Free council toilets are on Mid Shore, open 09:00–17:00 year-round except published holiday closures.', picnic: 'West Braes has sea-view picnic tables and is about ten minutes west along the coast.', foodNote: 'The Dory sits on East Shore; cafés and pub food cluster uphill and around Mid Shore.', trails: [{ name: 'Pittenweem Treasure Trail', summary: 'A dog-friendly 1.5-mile spy mission through the centre, pier and harbour.', routeType: 'Self-guided clue trail', duration: 'About 1½ hours', difficulty: 'Not wheelchair or pushchair accessible.', externalUrl: urls.treasure }], thingsToDo: [{ name: 'Watch the fishing harbour', summary: 'Look for working boats, creels and activity without obstructing operations.' }, { name: 'Climb the wynds', summary: 'Use Cove Wynd and Water Wynd to read the relationship between harbour and town.' }, { name: 'Pair with St Fillan’s Cave', summary: 'Collect the cave key from the Cocoa Tree during its opening hours.' }] },
});

const cave = feature('curated-attraction:pittenweem-2');
Object.assign(cave, {
  name: 'St Fillan’s Cave', significance: 'regional', visitorWebsiteUrl: urls.visitor, reviewed: true, updatedAt: reviewedAt,
  shortDescription: 'A small historic cave and former devotional site hidden below Cove Wynd, opened with a key collected from the Cocoa Tree café.',
  fullDescription: 'The cave gives Pittenweem a genuinely unusual short heritage experience. Entry depends on collecting and returning the key during Cocoa Tree opening hours; the confined, uneven space is atmospheric but not universally accessible.',
  reviewNotes: 'Current 2026 visitor guide confirms the key arrangement. No current general pet policy is published, so dog admission is not claimed.',
  sourceRecords: [...cave.sourceRecords, source('Pittenweem Visitor Information 2026', 'Pittenweem Community Library & Information Centre', urls.visitor, 'Current guide confirms St Fillan’s Cave in Cove Wynd and collection of the key from the Cocoa Tree.', 'official_non_statutory')],
  attractionGuide: { headline: 'Unlock Pittenweem’s hidden cave', intro: 'Collect the key before descending to this compact devotional and historic space beneath the town.', bestFor: ['Unusual local history', 'Atmospheric interiors', 'A short independent visit'], parking: 'Use Market Place or West Braes; there is no dedicated cave parking.', toilets: 'The free Mid Shore public toilets are close to Cove Wynd.', picnic: 'Continue west to West Braes for tables and sea views.', foodNote: 'The Cocoa Tree holds the key and makes the natural companion stop.', trails: [], thingsToDo: [{ name: 'Collect the key', summary: 'Check Cocoa Tree opening hours and return the key promptly.' }, { name: 'Look at the carved details', summary: 'Allow time for the small cave’s devotional and later historic layers.' }] },
});

const westBraes = feature('curated-attraction:pittenweem-3');
Object.assign(westBraes, {
  name: 'West Braes, Tidal Pool and Crazy Golf', significance: 'regional', visitorWebsiteUrl: urls.westBraes, reviewed: true, updatedAt: reviewedAt,
  shortDescription: 'A clifftop recreation area with sea views, play space, seasonal crazy golf, a volunteer-run refreshment hut and a tidal open-water pool below.',
  fullDescription: 'West Braes combines several modest activities into Pittenweem’s strongest family and outdoor stop. The pool is open at all times but is tidal and unsupervised; the hut and crazy golf depend on volunteers, season and weather.',
  reviewNotes: 'Current project and Fife Council park information checked, including the pool’s tidal character and volunteer-dependent opening.',
  sourceRecords: [source('West Braes Project', 'West Braes Project', urls.westBraes, 'Current pool, hut, crazy golf, safety and volunteer-dependent opening information.', 'official_non_statutory'), source('West Braes', 'Fife Council', urls.westBraesCouncil, 'Official park record confirms play park, car park, coastal path, seasonal crazy golf and route to the tidal pool.', 'local_authority')],
  attractionGuide: { headline: 'Make time for Pittenweem’s outdoor playground', intro: 'Combine the clifftop green, play area and crazy golf with a cautious look at the tidal pool below.', bestFor: ['Families', 'Sea views', 'Outdoor swimming', 'A coast-path break'], parking: 'West Braes car park adjoins the park; current secondary parking data records paid daytime stays and three dedicated overnight motorhome bays.', toilets: 'Basic West Braes toilets are operated by Fife Coast & Countryside Trust; the council’s fully described accessible toilets are at Mid Shore.', picnic: 'A mapped table and further outdoor seating sit beside the hut and clifftop green.', foodNote: 'The volunteer hut serves simple drinks and snacks when open.', trails: [{ name: 'Fife Coastal Path', summary: 'The signed route runs directly through West Braes.', routeType: 'Waymarked coast path', duration: 'Flexible', difficulty: 'Steps, slopes and exposed shore sections.', externalUrl: urls.coastalPath }], thingsToDo: [{ name: 'Play crazy golf', summary: 'Check the hut is open before relying on club hire.' }, { name: 'See the tidal pool', summary: 'The pool is unsupervised and submerged at high tide; assess conditions before swimming.' }, { name: 'Pause on the coast path', summary: 'Use the park as a picnic and refreshment stop between St Monans and Pittenweem.' }] },
});

const gallery = upsert(currentFeature('curated-attraction:pittenweem-weem-gallery', 'Weem Gallery and Framer', 'art_gallery', [-2.72962, 56.21372], 'A year-round High Street gallery mounting changing exhibitions by Scottish artists.', [source('About Weem Gallery', 'Weem Gallery and Framer', urls.gallery, 'Current operator page confirms year-round changing exhibitions and Monday–Saturday 10:00–17:00 opening.', 'official_non_statutory')], ['visitor-context-attraction']));
Object.assign(gallery, { visitorWebsiteUrl: urls.gallery, editorialReview: attractionReview('A credible year-round expression of Pittenweem’s art identity, reduced for modest scale and no published dog policy.', [urls.gallery], [18, 15, 13, 9, 9, 4]) });

const coastalTrail = feature('curated-trail:pittenweem-fife-coastal-path');
Object.assign(coastalTrail, { name: 'Fife Coastal Path: St Monans–Pittenweem–Anstruther', shortDescription: 'A signed 5-mile / 8 km linear coast walk linking three harbour villages, with Pittenweem near the centre.', visitorWebsiteUrl: urls.coastalPath, reviewed: true, updatedAt: reviewedAt, sourceRecords: [source('Fife Coastal Path', 'Fife Coast & Countryside Trust', urls.coastalPath, 'Official route hub and live-notice source.', 'official_non_statutory'), source('St Monans to Anstruther', 'Walkhighlands', urls.coastalStage, 'Current-place curation: visitor_place_type=Walking route; trail_score=86; trail_type=Linear coastal walk; distance=8 km / 5 miles; time_to_spend=2–2.5 hours one way; accessibility=Mostly straightforward, with steps, exposed shore and potentially muddy sections; entrance_fee=Free; app=Walkhighlands web mapping; offline_after_download=Limited; description=Waymarked coast-path stage through Pittenweem.', 'secondary')], tags: [...new Set([...coastalTrail.tags, 'service-context-trail', 'visitor-context-trail'])], editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A highly scenic, waymarked three-village route with strong intermediate interest and bus-return options.', evidenceUrls: [urls.coastalPath, urls.coastalStage] } });

const treasure = upsert(currentFeature('curated-trail:pittenweem-treasure-trail', 'Pittenweem – Centre, Pier & Harbour Treasure Trail', 'walking_route', [-2.73625, 56.2115], 'A dog-friendly circular spy mission through Pittenweem’s centre, historic buildings, pier, harbour and fish market.', [source('Pittenweem – Centre, Pier & Harbour', 'Treasure Trails', urls.treasure, 'Current-place curation: visitor_place_type=Walking route; trail_score=82; trail_type=Self-guided spy mission; distance=1.5 miles; time_to_spend=1.5 hours; accessibility=Not wheelchair or pushchair accessible; entrance_fee=£10.99 download, £12.99 printed or personalised; app=Instant digital download; offline_after_download=Yes; dog_friendly=Yes; start=West Braes, KY10 2PT; route=Circular.', 'official_non_statutory')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(treasure, { visitorWebsiteUrl: urls.treasure, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A current downloadable themed trail with explicit distance, duration, access constraints, circular start and dog policy.', evidenceUrls: [urls.treasure] } });

const circular = upsert(currentFeature('curated-trail:pittenweem-st-monans-abercrombie', 'Pittenweem–St Monans–Abercrombie Circular', 'walking_route', [-2.7298, 56.2134], 'A substantial coast-and-country circuit linking two harbour villages with Abercrombie and inland tracks.', [source('Pittenweem–St Monans–Abercrombie Circular', 'The Mack Walks', urls.circular, 'Current-place curation: visitor_place_type=Walking route; trail_score=76; trail_type=Long circular coast and countryside walk; distance=10.8 km / 6.7 miles; time_to_spend=3–3.5 hours; accessibility=Moderate route with tracks, fields, steps and minor roads; entrance_fee=Free; app=GPX download and route PDF; offline_after_download=Yes.', 'secondary')], ['service-context-trail', 'visitor-context-trail']));
Object.assign(circular, { visitorWebsiteUrl: urls.circular, editorialReview: { status: 'editorially_researched', category: 'trail', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: 'A varied downloadable circular with genuine coast and countryside breadth, reduced for mixed surfaces, roads and secondary-source maintenance.', evidenceUrls: [urls.circular] } });

function curateFood(item: HeritageFeature, name: string, score: number, notes: string, website: string, assessment: [number, number, number, number, number, number], openingTimes: string, cuisine: string, priceBand: '£' | '££' | '£££', evidenceUrl = website) {
  item.name = name; item.shortDescription = notes; item.visitorWebsiteUrl = website; item.reviewed = true; item.updatedAt = reviewedAt; item.tags = [...new Set([...item.tags, 'service-context-food', 'visitor-context-food', 'current-context'])];
  item.sourceRecords.push(source(`${name} visitor curation`, 'Townscape Guides source audit', evidenceUrl, `Current daytime food curation: visitor_place_type=${item.featureType === 'restaurant' ? 'Restaurant' : 'Cafe'}; food_score=${score}; visit_score=${score}; price_band=${priceBand}; opening_hours:description=${openingTimes}; cuisine=${cuisine}; description=${notes}`, 'secondary'));
  const [foodAndDrinkQuality, daytimeRelevance, distinctiveness, consistency, visitorFit, evidenceConfidence] = assessment;
  item.editorialReview = { status: 'editorially_researched', category: 'food', methodVersion: '2026-08-13-researched-visitor-value-v1', reviewedAt: reviewedDate, scoreRationale: notes, evidenceUrls: [website, evidenceUrl], foodAssessment: { foodAndDrinkQuality, daytimeRelevance, distinctiveness, consistency, visitorFit, evidenceConfidence } };
  return item;
}

const dory = curateFood(feature('osm-community:node-11175183157'), 'The Dory Bistro & Gallery', 89, 'Destination harbour dining: locally landed seafood, seasonal Scottish cooking and original art above East Shore.', urls.dory, [29, 16, 15, 14, 9, 6], 'Wed–Sat 12:00–23:00; Sun 12:00–22:00; booking advised', 'Scottish seafood', '£££');
const cocoa = curateFood(feature('osm-community:node-2800985486'), 'The Cocoa Tree Café and Chocolate Shop', 84, 'Distinctive chocolate café: handmade chocolates, rich drinks, soups, focaccia, crêpes and cakes; also holds the St Fillan’s Cave key.', urls.cocoa, [27, 18, 14, 12, 8, 5], 'Daily 10:00–17:00; check seasonal changes', 'Chocolate, café lunches and baking', '££');
const clock = upsert(curateFood(currentFeature('curated-food:pittenweem-clock-tower-cafe', 'Clock Tower Café', 'caf_', [-2.72962, 56.21348], 'A dog-friendly High Street café serving breakfast, brunch, lunches, coffee and home baking.', [source('Pittenweem food and drink', 'Pittenweem Arts Festival', urls.festivalFood, 'Current visitor listing confirms food offer and dog-friendly status.', 'official_non_statutory')], ['service-context-food', 'visitor-context-food']), 'Clock Tower Café', 80, 'Reliable dog-friendly café: breakfast, brunch, lunches and home baking in the centre of town.', urls.festivalFood, [24, 18, 11, 12, 9, 6], 'Daily 09:00–16:00; verify seasonal changes', 'Breakfast, lunch and baking', '££'));
const larachmhor = upsert(curateFood(currentFeature('curated-food:pittenweem-larachmhor-tavern', 'Larachmhor Tavern', 'restaurant', [-2.72893, 56.21226], 'A Mid Shore pub serving meals and sit-in or takeaway fish and chips.', [source('Pittenweem Visitor Information 2026', 'Pittenweem Community Library & Information Centre', urls.visitor, 'Current visitor guide lists the pub and meal/takeaway offer.', 'official_non_statutory')], ['service-context-food', 'visitor-context-food']), 'Larachmhor Tavern', 76, 'Harbour pub stop: meals plus sit-in and takeaway fish and chips on Mid Shore.', urls.visitor, [23, 16, 11, 11, 8, 7], 'Open daily from 10:00 in the festival listing; verify current kitchen hours', 'Pub food and fish and chips', '££', urls.festivalFood));
const iceCream = curateFood(feature('osm-community:node-9014707918'), 'Nicholson’s Sweet and Ice Cream Shop', 73, 'Seasonal sweet-shop stop: artisan ice cream, confectionery and takeaway treats near the harbour.', urls.iceCream, [22, 17, 12, 10, 8, 4], 'Feb–Nov, weather permitting; Jul–Aug usually daily 11:00–19:00', 'Ice cream and confectionery', '£');
const hut = curateFood(feature('osm-community:way-1214825894'), 'West Braes Hut', 66, 'Coastal refreshment hut: Volunteer-run hot and cold drinks, snacks and muffins beside crazy golf and picnic seating.', urls.westBraes, [18, 16, 10, 8, 9, 5], 'Usually 11:00–17:00 in summer when volunteers and weather permit', 'Drinks and snacks', '£');

const highStreet = upsert(currentFeature('curated-parking:pittenweem-market-place', 'High Street / Market Place Car Park', 'parking', [-2.7303617, 56.2129186], '9 car spaces, 1 accessible space and 1 coach/lorry space. Free tarmac surface car park; no payment required.', [source('Fife Council Car Park Inventory', 'Fife Council', urls.parkingInventory, 'Current-place curation: visitor_place_type=Parking; name=High Street/Market Place Carpark; parking=surface; postcode=KY10 2LA; capacity=9 cars, 1 accessible, 1 coach/lorry; charge=Free; price_display=Free; payment_required=No; payment_methods=None; surface=Tarmac; lighting=None; source_record=OBJECTID 130.', 'local_authority')], ['service-context-parking', 'visitor-context-parking']));
const westParking = feature('osm-community:way-480231093');
Object.assign(westParking, { name: 'West Braes Car Park', shortDescription: 'Clifftop visitor car park beside West Braes. Current secondary listing: free up to 2 hours, £2 all day; cash or card; three dedicated overnight motorhome bays at £10.', reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...westParking.tags, 'service-context-parking', 'visitor-context-parking'])], sourceRecords: [...westParking.sourceRecords, source('West Braes park', 'Fife Council', urls.westBraesCouncil, 'Official park page confirms the car park and designated accessible parking area; total capacity is not published.', 'local_authority'), source('Pittenweem West Braes Car Park', 'Search for Sites', urls.westBraesParking, 'Current-place curation: visitor_place_type=Parking; parking=surface; capacity=Total not published; 3 dedicated overnight motorhome bays; accessibility=Designated accessible parking area beside pedestrian exit; charge=Free up to 2 hours / £2 all day / £10 overnight motorhome; price_display=Free up to 2 hours / £2 all day / £10 overnight motorhome; payment_required=Yes beyond 2 hours; payment_methods=Cash or card at machine; postcode=KY10 2PT; opening_hours:description=Open year-round; confidence=Official location and accessible area, secondary current tariff and motorhome-bay details; verify the machine on arrival.', 'secondary')] });
for (const id of ['osm-community:way-490043679', 'osm-community:way-732455988']) feature(id).tags = feature(id).tags.filter((tag) => !['service-context-parking', 'visitor-context-parking'].includes(tag));
Object.assign(feature('osm-community:way-732455988'), { name: 'Parking', shortDescription: 'A small OpenStreetMap street-side parking record retained as map evidence; it is not the official Market Place car park used by the visitor planner.' });

const harbourToilet = feature('osm-community:node-498851014');
Object.assign(harbourToilet, { name: 'Pittenweem Harbour Public Toilets', shortDescription: 'Free male and female council toilets with level access and a Radar-key accessible toilet; open 09:00–17:00 in summer and winter.', reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...harbourToilet.tags, 'service-context-toilets', 'visitor-context-toilets'])], sourceRecords: [...harbourToilet.sourceRecords, source('Pittenweem Public Toilets', 'Fife Council', urls.toilet, 'Current-place curation: visitor_place_type=Public toilets; opening_hours:description=Daily 09:00–17:00 year-round; closed 25–26 December and 1–2 January; charge=Free; wheelchair=Yes; level_access=Yes; radar_key=Required.', 'local_authority')] });
const westToilet = feature('osm-community:way-480231095');
Object.assign(westToilet, { name: 'West Braes Toilets', shortDescription: 'Basic coastal toilets operated by Fife Coast & Countryside Trust beside the car park; current opening hours and accessible provision are not published.', reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...westToilet.tags, 'service-context-toilets', 'visitor-context-toilets'])], sourceRecords: [...westToilet.sourceRecords, source('West Braes', 'Fife Council', urls.westBraesCouncil, 'Official park page confirms a toilet block on the west side; detailed current hours and facilities are not published.', 'local_authority')] });
const picnic = feature('osm-community:node-11080894512');
Object.assign(picnic, { name: 'West Braes Picnic Table', shortDescription: 'A mapped public picnic table beside the West Braes recreation area, hut and sea views.', reviewed: true, updatedAt: reviewedAt, tags: [...new Set([...picnic.tags, 'service-context-picnic', 'visitor-context-picnic'])] });

const highlights: VisitorHighlight[] = [
  { rank: 1, featureId: harbour.id, name: harbour.name, reason: 'An authentic commercial fishing harbour tightly integrated with steep historic wynds and food stops.', visitorScore: 86, tagline: 'Working fishing harbour and wynds', timeToSpend: '45–90 minutes', openingTimes: 'Open-air public waterfront; daylight visit recommended. Harbour operates Mon–Fri 06:30–21:00.', admission: 'Free.', freeAdmission: true, visitorWebsiteUrl: urls.harbour, sourceName: 'Fife Council', sourceUrl: urls.harbour, verifiedInBoundaryAt: reviewedDate, editorialReview: attractionReview('A distinctive, active and visually coherent working harbour with several linked reasons to linger.', [urls.harbour, urls.harbourFact], [26, 18, 16, 12, 10, 4]) },
  { rank: 2, featureId: westBraes.id, name: westBraes.name, reason: 'A useful cluster of coast-path scenery, play, crazy golf, refreshments and tidal swimming rather than one isolated facility.', visitorScore: 79, tagline: 'Tidal pool and family recreation', timeToSpend: '45 minutes–2 hours', openingTimes: 'Park and tidal pool always accessible; hut and crazy golf seasonal and volunteer-dependent.', admission: 'Park and pool free; crazy golf charges apply.', freeAdmission: true, visitorWebsiteUrl: urls.westBraes, sourceName: 'West Braes Project', sourceUrl: urls.westBraes, verifiedInBoundaryAt: reviewedDate, editorialReview: attractionReview('Good outdoor breadth and strong coast-path fit, reduced for tidal swimming risk and volunteer-dependent facilities.', [urls.westBraes, urls.westBraesCouncil], [22, 17, 15, 11, 10, 4]) },
  { rank: 3, featureId: cave.id, name: cave.name, reason: 'A genuinely unusual key-access cave beneath Cove Wynd, albeit compact and physically constrained.', visitorScore: 74, tagline: 'Unlock a hidden historic cave', timeToSpend: '20–40 minutes', openingTimes: 'Key available from the Cocoa Tree during café opening hours; verify before travel.', admission: 'Free; return the key promptly.', freeAdmission: true, visitorWebsiteUrl: urls.visitor, sourceName: 'Pittenweem Community Library', sourceUrl: urls.visitor, verifiedInBoundaryAt: reviewedDate, editorialReview: attractionReview('Unusual and atmospheric local history, reduced for small scale, uneven access and dependence on a third-party key holder.', [urls.visitor], [20, 18, 13, 10, 9, 4]) },
  { rank: 4, featureId: gallery.id, name: gallery.name, reason: 'A year-round changing-exhibition gallery that gives Pittenweem’s art identity a permanent, visitable anchor.', visitorScore: 68, tagline: 'Year-round Scottish exhibitions', timeToSpend: '20–45 minutes', openingTimes: 'Mon–Sat 10:00–17:00; verify holiday opening.', admission: 'Free to browse.', freeAdmission: true, visitorWebsiteUrl: urls.gallery, sourceName: 'Weem Gallery and Framer', sourceUrl: urls.gallery, verifiedInBoundaryAt: reviewedDate, editorialReview: gallery.editorialReview! },
];

project.project.visitorHighlights = highlights;
project.project.touristAppeal = { score: 85, dogOwnerScore: 80, dogAccessScoreAdjustment: -5, rating: 2, label: 'Strong Destination', summary: 'Pittenweem combines one of the East Neuk’s most convincing working harbours with steep wynds, a hidden cave, a permanent art presence, West Braes recreation, strong food and three worthwhile self-guided routes.', dogAccessRating: 2, dogAccessSummary: 'The harbour, West Braes, coast path, Treasure Trail and several outdoor or dog-welcoming food stops make a strong visit with a dog. The cave and gallery do not publish general pet access, however, so the dog-owner score is five points lower rather than being boosted by friendliness.', methodVersion: '2026-08-26-full-settlement-visitor-audit-v1', reviewedAt: reviewedDate, sourceUrls: Object.values(urls) };
project.project.townGuide = { characterTag: 'Working fishing harbour and artists’ wynds', headline: 'A compact harbour town with unusual depth', intro: 'Pittenweem’s commercial fishing basin is only the beginning: steep wynds climb to a hidden cave and permanent galleries, while West Braes adds a tidal pool, family recreation and the coast path.', bestFor: ['Working harbour', 'Art and historic wynds', 'Seafood and cafés', 'Coastal walking'], perfectFor: ['A relaxed half-day East Neuk visit', 'Visitors mixing heritage, food and outdoor time'], suggestedFirstVisit: { title: 'Link harbour, cave and West Braes', summary: 'Start at the working harbour, climb Cove Wynd for St Fillan’s Cave and the High Street, then finish west along the coast at West Braes.' }, dontMiss: ['Pittenweem Working Harbour and Wynds', 'St Fillan’s Cave', 'West Braes, Tidal Pool and Crazy Golf', 'The Dory Bistro & Gallery', 'Pittenweem Treasure Trail'], suggestedTime: '3–5 hours; longer with a full circular walk', visitorMood: 'More layered than its size suggests: a real fishing harbour, intimate streets, distinctive food and art, and easy access to the coast all reinforce one another.', sourceUrls: Object.values(urls), lastReviewedAt: reviewedDate };
project.project.visualIdentity = { theme: 'east-neuk-working-fishing-harbour', badgeImage: '/town-guides/pittenweem-shoreline-watercolour-guide-v2.png', badgeAlt: 'Watercolour illustration of Pittenweem’s curved shoreline, whitewashed waterfront houses and warm pantile roofs', heroImage: '/town-guides/pittenweem-shoreline-watercolour-guide-v2.png', heroAlt: 'Watercolour illustration of Pittenweem’s curved shoreline, whitewashed waterfront houses and warm pantile roofs', heroObjectPosition: '50% 56%', motifs: ['Curved shoreline', 'Whitewashed waterfront', 'Stepped gables', 'Pantiled houses'], primaryColour: '#164D54', accentColour: '#B57224', backgroundColour: '#EAF3F0' };

const planner = JSON.parse(await readFile(plannerPath, 'utf8')) as { projects: Record<string, Record<string, string[]>> };
planner.projects[project.project.id] = { eat: [dory.id, cocoa.id, clock.id, larachmhor.id, iceCream.id, hut.id], trails: [coastalTrail.id, treasure.id, circular.id], parking: [highStreet.id, westParking.id], toilets: [harbourToilet.id, westToilet.id], picnic: [picnic.id] };
await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`, 'utf8');

const dog = JSON.parse(await readFile(dogPath, 'utf8')) as { reviewedAt: string; projects: Record<string, { attraction?: Record<string, unknown>; eat?: Record<string, unknown> }> };
dog.reviewedAt = reviewedDate;
dog.projects[project.project.id] = { attraction: {
  [harbour.id]: { rating: 3, status: 'welcoming', label: 'Outdoor working-harbour walk', summary: 'Dogs can accompany the public waterfront under responsible-access rules. Keep them close beside fishing gear, traffic, piers, food queues and open water.', sourceName: 'Fife Council harbour information and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
  [westBraes.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable outdoor stop', summary: 'Dogs can accompany the park and coast path, but use a lead around play, food, wildlife, cliffs and swimmers and keep dogs out of the tidal pool when people are swimming.', sourceName: 'West Braes and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
  [cave.id]: { rating: 0, status: 'unconfirmed', label: 'Pet access not published', summary: 'General pet admission to the confined historic cave is not published. Confirm with the key holder before relying on access.', sourceName: 'Pittenweem Visitor Information 2026', sourceUrl: urls.visitor, reviewedAt: reviewedDate },
  [gallery.id]: { rating: 0, status: 'unconfirmed', label: 'Gallery dog policy not published', summary: 'A general pet policy for the gallery is not published. Confirm directly before relying on indoor access.', sourceName: 'Weem Gallery current website', sourceUrl: urls.gallery, reviewedAt: reviewedDate },
  [coastalTrail.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable coast path', summary: 'Dogs can use the route under responsible-access rules, with close control around livestock, wildlife, shore hazards and other walkers.', sourceName: 'Fife Coastal Path and Scottish Outdoor Access Code', sourceUrl: urls.outdoorCode, reviewedAt: reviewedDate },
  [treasure.id]: { rating: 3, status: 'welcoming', label: 'Explicitly dog-friendly clue trail', summary: 'Treasure Trails explicitly marks this outdoor circular as dog-friendly. Keep dogs close on roads, the working harbour and busy clue stops.', sourceName: 'Treasure Trails Pittenweem product page', sourceUrl: urls.treasure, reviewedAt: reviewedDate },
  [circular.id]: { rating: 2, status: 'restricted', label: 'Dog-suitable country circuit', summary: 'The route is outdoors but crosses farmland and minor roads. Keep dogs under close control around livestock, wildlife and traffic.', sourceName: 'The Mack Walks and Scottish Outdoor Access Code', sourceUrl: urls.circular, reviewedAt: reviewedDate },
}, eat: {
  [dory.id]: { rating: 2, status: 'restricted', label: 'Dogs at lunch service', summary: 'Current independent guide information describes dog-friendly lunch access; evening access is not confirmed. State that restriction rather than assuming all-service admission.', sourceName: 'The Good Food Guide', sourceUrl: urls.doryDog, reviewedAt: reviewedDate },
  [cocoa.id]: { rating: 2, status: 'restricted', label: 'Dogs at staff discretion', summary: 'The operator welcomes dogs at its discretion. Space and service conditions may therefore affect access.', sourceName: 'Pittenweem Chocolate', sourceUrl: urls.cocoa, reviewedAt: reviewedDate },
  [clock.id]: { rating: 3, status: 'welcoming', label: 'Dog-friendly café', summary: 'Current town and festival visitor information identifies the café as dog friendly.', sourceName: 'Pittenweem Arts Festival food guide', sourceUrl: urls.festivalFood, reviewedAt: reviewedDate },
  [larachmhor.id]: { rating: 0, status: 'unconfirmed', label: 'Pub dog policy not published', summary: 'A current operator pet policy for indoor meal service is not published. Confirm directly before relying on access.', sourceName: 'Pittenweem visitor information review', sourceUrl: urls.visitor, reviewedAt: reviewedDate },
  [iceCream.id]: { rating: 2, status: 'restricted', label: 'Straightforward takeaway stop', summary: 'The shop is suitable for takeaway treats with a dog, but indoor pet access is not published.', sourceName: 'Nicholson’s current website', sourceUrl: urls.iceCream, reviewedAt: reviewedDate },
  [hut.id]: { rating: 3, status: 'welcoming', label: 'Outdoor dog-friendly stop', summary: 'The hut serves through an outdoor recreation and picnic area, so dogs can accompany visitors under normal close-control rules.', sourceName: 'West Braes Project', sourceUrl: urls.westBraes, reviewedAt: reviewedDate },
} };
await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`, 'utf8');

project.validation = validateFeatures(project.project, project.features);
const errors = project.validation.filter((item) => item.severity === 'error');
if (errors.length) throw new Error(`Pittenweem audit introduced ${errors.length} validation errors: ${errors.map((item) => item.message).join('; ')}`);
await writeFile(projectPath, `${JSON.stringify(project, null, 2)}\n`, 'utf8');
await writeFile(resolve('data/review/pittenweem-full-visitor-audit-2026-08-26.json'), `${JSON.stringify({ reviewedAt, townScore: 85, dogOwnerScore: 80, publicationRule: 'visitor score > 60', attractions: highlights.map(({ name, visitorScore }) => ({ name, score: visitorScore, published: true })), trails: [{ name: coastalTrail.name, score: 86 }, { name: treasure.name, score: 82, format: 'Instant digital download or printed booklet', dogFriendly: true }, { name: circular.name, score: 76, downloads: 'GPX and PDF' }], facilities: { eat: [{ name: dory.name, score: 89 }, { name: cocoa.name, score: 84 }, { name: clock.name, score: 80 }, { name: larachmhor.name, score: 76 }, { name: iceCream.name, score: 73 }, { name: hut.name, score: 66 }], parking: [{ name: highStreet.name, capacity: '9 cars, 1 accessible, 1 coach/lorry', price: 'Free', payment: 'None' }, { name: westParking.name, capacity: 'Total not published; 3 dedicated overnight motorhome bays', price: 'Free 2 hours / £2 all day / £10 overnight motorhome', payment: 'Cash or card at machine; verify on arrival' }], toilets: [{ name: harbourToilet.name, hours: 'Daily 09:00–17:00', charge: 'Free', accessible: 'Level access and Radar-key toilet' }, { name: westToilet.name, hours: 'Not currently published', charge: 'Not currently published', accessible: 'Not currently published' }], picnic: [picnic.name] }, dogAudit: { townAdjustment: -5, attractionPolicies: 'Harbour and Treasure Trail 3 paws; West Braes, coast path and circular 2; cave and gallery unconfirmed', foodPolicies: 'Clock Tower and West Braes Hut 3 paws; Dory, Cocoa Tree and Nicholson’s 2; Larachmhor unconfirmed' }, exclusions: ['The 2026 Arts Festival ended on 8 August and is retained as seasonal identity rather than a permanent attraction', 'West End Bar excluded from Eats because its operator states the kitchen is closed in 2026', 'Unverified on-street and harbour-edge parking omitted from the practical planner', 'Heritage buildings remain on the map but are not promoted as standalone attractions below the >60 visitor-experience threshold'] }, null, 2)}\n`, 'utf8');
console.log('Pittenweem audit complete: 4 attractions, 6 Eats, 3 trails, 2 car parks, 2 toilet blocks and 1 picnic table.');
