import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { HeritageFeature, ProjectPackage, VisitorHighlight } from '../src/domain/models';
import { validateFeatures } from '../src/domain/validation';

const reviewedDate='2026-09-01', reviewedAt='2026-09-01T13:25:00.000Z';
const projectPath=resolve('data/projects/boarhills.json'), plannerPath=resolve('data/east-neuk-visitor-planner-curation.json'), dogPath=resolve('data/east-neuk-dog-access-curation.json');
const pkg=JSON.parse(await readFile(projectPath,'utf8')) as ProjectPackage;
const trustUrl='https://boarhillsandduninocommunitytrust.org/projects/';
const coastUrl='https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/';
const planUrl='https://www.fife.gov.uk/__data/assets/pdf_file/0032/682475/Boarhills-and-Dunino-Local-Place-Plan.pdf';
const ids={see:'curated-attraction:boarhills-doocot-green',trail:'curated-trail:fife-coastal-path-boarhills',localTrail:'curated-trail:boarhills-dunino-walk-leaflets-boarhills',picnic:'curated-picnic:boarhills-community-green'};
pkg.features=pkg.features.filter(f=>!Object.values(ids).includes(f.id));
const feature=(id:string,name:string,type:string,coordinates:[number,number],description:string,url:string,tags:string[],details:string):HeritageFeature=>({id,projectId:pkg.project.id,name,alternativeNames:[],countryCode:'GB-SCT',region:'Fife',locality:'Boarhills',featureType:type,significance:'regional',geometry:{type:'Point',coordinates},locationType:'exact',locationConfidence:'high',dateBasis:'unknown',dateConfidence:'unknown',survival:'substantially_intact',shortDescription:description,visitorWebsiteUrl:url,sourceRecords:[{sourceName:name,sourceOrganisation:id===ids.trail?'Fife Coast and Countryside Trust':'Boarhills and Dunino Community Trust',sourceUrl:url,accessedAt:reviewedAt,licence:'Source-linked visitor evidence.',reliability:'official_non_statutory',notes:`Current-place curation: ${details}`}],tags:['current-context',...tags],createdAt:reviewedAt,updatedAt:reviewedAt,reviewed:true,evidenceScope:'parish_evidence'});
const see=feature(ids.see,'Boarhills Doocot and Community Green','historic_site',[-2.70294,56.31931],'A restored 17th-century doocot in an accessible free community green with interpretation, orchard planting and links to the coast path.',trustUrl,['curated-visitor-attraction'],'visitor_place_type=Historic site; opening_hours:description=Open-air community green with free access; entrance_fee=Free; website='+trustUrl+'.');
const trail=feature(ids.trail,'Fife Coastal Path at Boarhills','walking_route',[-2.70276,56.31910],'The official 117-mile Fife Coastal Path passes the community green and provides the village’s strongest walking connection; it is a cross-boundary trail, not a compact village loop.',coastUrl,['service-context-trail','visitor-context-trail','cross-boundary-trail'],'visitor_place_type=Walking trail; trail_score=78; time_to_spend=Allow several hours for an adjacent section; opening_hours:description=Open route subject to weather and path notices; entrance_fee=Free; description=Coastal route hub: official long-distance path through Boarhills; website='+coastUrl+'.');
const localTrail=feature(ids.localTrail,'Boarhills and Dunino Community Walk Leaflets','walking_route',[-2.70288,56.31920],'Two community-produced walking leaflets cover routes around Boarhills and Dunino and are available from the St Andrews visitor information point or directly from the community trust; the trust does not publish route distance or duration online.',trustUrl,['service-context-trail','visitor-context-trail'],'visitor_place_type=Walking trail; trail_score=66; time_to_spend=Route distance and duration are not published online; opening_hours:description=Self-guided outdoor routes; entrance_fee=Free; description=Local community walks: two printed leaflets covering Boarhills and Dunino; website='+trustUrl+'.');
const picnic=feature(ids.picnic,'Boarhills Community Green Picnic Tables','picnic_site',[-2.70295,56.31912],'Public picnic tables and benches beside the restored doocot, verified by the community trust rather than inferred from a proposed plan.',trustUrl,['service-context-picnic','visitor-context-picnic'],'tourism=picnic_site; access=public; website='+trustUrl+'.');
pkg.features.push(see,trail,localTrail,picnic);
pkg.project.visitorHighlights=[{rank:1,featureId:see.id,name:see.name,reason:'A genuinely public, restored and interpreted heritage stop directly beside a major trail, but modest in scale and without dependable indoor opening.',visitorScore:69,tagline:'Restored village doocot',timeToSpend:'20–40 minutes',openingTimes:'Open-air community green with free access',admission:'Free',visitorWebsiteUrl:trustUrl,sourceName:'Boarhills and Dunino Community Trust',sourceUrl:trustUrl,verifiedInBoundaryAt:reviewedDate} as VisitorHighlight];
pkg.project.touristAppeal={score:58,dogOwnerScore:57,dogAccessScoreAdjustment:-1,rating:0,label:'Limited Visitor Interest',summary:'Boarhills has a coherent rural village, a restored free doocot green, two locally produced walk leaflets and a useful Fife Coastal Path connection, but no qualifying café or dependable public parking/toilets and too little visit depth for Home-map publication.',dogAccessRating:2,dogAccessSummary:'The community green and walking routes support an outdoor dog visit; close control is essential around farmland, wildlife, roads and any golf crossing.',methodVersion:'2026-09-01-full-settlement-visitor-audit-v2',reviewedAt:reviewedDate,sourceUrls:[trustUrl,coastUrl,planUrl,'https://www.treasuretrails.co.uk/collections/fife','https://curiousabout.co.uk/','https://www.mysteryguides.co.uk/','https://goquestadventures.com/']};
pkg.project.townGuide={characterTag:'Rural village, doocot green and coast-path hub',headline:'Worth a short trail stop, not a standalone day out',intro:'Boarhills remains selector-only at 58. Its restored doocot green, picnic tables and Fife Coastal Path access are published, while event-only refreshments/WC and still-proposed visitor parking are withheld.',bestFor:['Coastal walkers','Small heritage stops','Picnic breaks'],perfectFor:['A pause while walking the coast path'],suggestedFirstVisit:{title:'Doocot and community green',summary:'Use the community green as a short heritage and picnic pause; plan any longer walk from the official coastal-path page.'},dontMiss:['Boarhills Doocot and Community Green'],suggestedTime:'30–60 minutes, excluding a coast-path section',visitorMood:'Quiet rural heritage beside a major path.',sourceUrls:[trustUrl,coastUrl,planUrl],lastReviewedAt:reviewedDate};
const planner=JSON.parse(await readFile(plannerPath,'utf8')) as any;planner.reviewedAt=reviewedDate;planner.projects[pkg.project.id]={eat:[],trails:[trail.id,localTrail.id],picnic:[picnic.id],parking:[],toilets:[]};await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`);
const dog=JSON.parse(await readFile(dogPath,'utf8')) as any;dog.reviewedAt=reviewedDate;dog.projects[pkg.project.id]={attraction:{[see.id]:{rating:2,status:'restricted',label:'Outdoor access with close control',summary:'Dogs can accompany an outdoor visit but must be controlled around roads, wildlife and neighbouring farmland.',sourceName:'Scottish Outdoor Access Code',sourceUrl:'https://www.outdooraccess-scotland.scot/dog-owners',reviewedAt:reviewedDate},[trail.id]:{rating:2,status:'restricted',label:'Trail access with close control',summary:'Use close control around livestock, wildlife, golf activity and road sections.',sourceName:'Scottish Outdoor Access Code',sourceUrl:'https://www.outdooraccess-scotland.scot/dog-owners',reviewedAt:reviewedDate},[localTrail.id]:{rating:2,status:'restricted',label:'Local walks with close control',summary:'Use close control around livestock, wildlife and road sections; route-specific dog guidance is not published.',sourceName:'Scottish Outdoor Access Code',sourceUrl:'https://www.outdooraccess-scotland.scot/dog-owners',reviewedAt:reviewedDate}},eat:{}};await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`);
const hes=JSON.parse(await readFile(resolve('data/review/boarhills-hes-integrity-2026-08-31.json'),'utf8')) as any;if(hes.missingStatutoryDesignations||hes.undatedVisiblePins)throw new Error('Boarhills HES gate failed');pkg.validation=validateFeatures(pkg.project,pkg.features);if(pkg.validation.some(i=>i.severity==='error'))throw new Error('Boarhills validation failed');await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`);
await writeFile(resolve('data/review/boarhills-full-visitor-audit-2026-08-31.json'),`${JSON.stringify({reviewedAt,place:'Boarhills',townScore:58,mapPublished:false,categories:{see:{audited:true,published:1},eat:{audited:true,published:0,note:'No café; Doors Open refreshments are event-only.'},trails:{audited:true,published:1,providerChecks:{TreasureTrails:'Fife catalogue checked; no Boarhills product',CuriousAbout:'No Boarhills route',MysteryGuides:'No Boarhills route',GoQuestAdventures:'No Boarhills route',officialRoutes:'Fife Coastal Path verified; trust leaflets noted but no direct downloadable route URL is published'}},picnic:{audited:true,published:1},parking:{audited:true,published:0,note:'Local Place Plan still calls for visitor parking to be assessed/developed; event parking is not a dependable public car park.'},toilets:{audited:true,published:0,note:'Village-hall WC is evidenced for Doors Open events only.'},accessibility:{audited:true,note:'Trust states the restored doocot and green are accessible; no whole-route accessibility claim.'},transport:{audited:true,note:'Public transport is referenced but weekend provision is identified as weak; no volatile timetable copied.'},dogs:{audited:true,adjustment:-1}},hes:{assigned:hes.statutoryDesignationsAssigned,visibleDated:hes.visibleHesPins,hiddenUndated:hes.statutoryDesignationsAssigned-hes.visibleHesPins,visibleUndated:hes.undatedVisiblePins,missing:hes.missingStatutoryDesignations},boundaryRule:'Cambo, Kingsbarns, St Andrews, coastal geology beyond the settlement and hotel/golf facilities are not borrowed.'},null,2)}\n`);
await writeFile(resolve('data/review/boarhills-full-visitor-audit-2026-09-01.json'),`${JSON.stringify({
  reviewedAt, place:'Boarhills', townScore:58, mapPublished:false,
  categories:{
    see:{audited:true,published:1}, eat:{audited:true,published:0,note:'No café; Doors Open refreshments are event-only.'},
    trails:{audited:true,published:2,providerChecks:{TreasureTrails:'Fife catalogue checked; no Boarhills product',CuriousAbout:'No Boarhills route',MysteryGuides:'No Boarhills route',GoQuestAdventures:'No Boarhills route',officialRoutes:'Fife Coastal Path verified',communityTrust:'Two Boarhills and Dunino walking leaflets verified; obtainable through the visitor information point or community trust, with no route distance or duration published online'}},
    picnic:{audited:true,published:1}, parking:{audited:true,published:0,note:'Local Place Plan still calls for visitor parking to be assessed/developed; event parking is not a dependable public car park.'},
    toilets:{audited:true,published:0,note:'Village-hall WC is evidenced for Doors Open events only.'}, accessibility:{audited:true,note:'Trust states the restored doocot and green are accessible; no whole-route accessibility claim.'}, transport:{audited:true,note:'Public transport is referenced but weekend provision is identified as weak; no volatile timetable copied.'}, dogs:{audited:true,adjustment:-1}},
  hes:{assigned:hes.statutoryDesignationsAssigned,visibleDated:hes.visibleHesPins,hiddenUndated:hes.statutoryDesignationsAssigned-hes.visibleHesPins,visibleUndated:hes.undatedVisiblePins,missing:hes.missingStatutoryDesignations},
  boundaryRule:'Cambo, Kingsbarns, St Andrews, coastal geology beyond the settlement and hotel/golf facilities are not borrowed.',
  research:{currentWebResearch:true,strictBoundaryChecked:true,sourceChecks:[
    {url:trustUrl,checkedAt:reviewedDate,outcome:'verified',note:'Community trust verifies the restored doocot green, picnic provision and two local walking leaflets.'},
    {url:coastUrl,checkedAt:reviewedDate,outcome:'verified',note:'Official trust page verifies the Fife Coastal Path.'},
    {url:'https://www.treasuretrails.co.uk/collections/fife',checkedAt:reviewedDate,outcome:'no_result',note:'No Boarhills Treasure Trail product was found.'},
    {url:planUrl,checkedAt:reviewedDate,outcome:'verified',note:'Local plan supports withholding unbuilt visitor parking and event-only facilities.'}]},
  scoreReanalysis:{required:true,completed:true,resultScore:58,rationale:'Second pass retained 58 as a real score, not a cap: the restored doocot green, picnic stop, two community walk leaflets and coastal path create a worthwhile short stop, but the settlement still lacks a qualifying café, dependable general visitor parking and public toilets, and does not offer enough independent visit depth for the 60-point map threshold.'},
  certification:{publicationCountsReconciled:false,liveBrowserVerifiedAt:null}
},null,2)}\n`);
console.log('Boarhills re-audit complete: score 58; 1 See, 0 Eat, 2 Trails, 1 Picnic, 0 Parking, 0 Toilets; exact-58 second pass and HES gate passed.');
