import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { circle } from '@turf/turf';

const id = 'edzell-scotland', day = '2026-08-30', at = '2026-08-30T23:59:40Z';
const projectPath = resolve('data/projects/edzell.json');
const plannerPath = resolve('data/cairn-o-mount-visitor-planner-curation.json');
const dogPath = resolve('data/cairn-o-mount-dog-access-curation.json');
const reportPath = resolve('data/review/edzell-full-visitor-audit-2026-08-30.json');
const correctionPath = resolve('data/review/strict-settlement-score-correction-2026-08-30.json');
const urls = {
  town: 'https://visitangus.com/plan-your-trip/explore-our-towns/edzell/',
  castle: 'https://visitangus.com/things-to-see-do/attractions/edzell-castle-and-gardens/',
  hall: 'https://visitangus.com/inglis-memorial-hall-and-library/',
  blueDoor: 'https://visitangus.com/things-to-see-do/trails/walking-trail-blue-door-walk-edzell/',
  cycle: 'https://visitangus.com/things-to-see-do/trails/edzell-to-inchbare-circuit/',
  sinclairs: 'https://visitangus.com/things-to-see-do/food-drink/sinclairs-larder/',
  tweedie: 'https://www.yell.com/biz/edzell-tweedie-brechin-8018630/',
  toilet: 'https://www.angus.gov.uk/directories/public_toilets_and_radar_keys/edzell_the_muir',
  muir: 'https://www.angus.gov.uk/sites/default/files/2017-08/24_RevParksMangdThirdPartyLease.pdf',
  treasure: 'https://www.treasuretrails.co.uk/', curious: 'https://www.curiousabout.co.uk/', mystery: 'https://www.mysteryguides.co.uk/', goQuest: 'https://goquestadventures.com/',
  dog: 'https://www.outdooraccess-scotland.scot/dog-owners',
};
const pkg: any = JSON.parse(await readFile(projectPath, 'utf8'));
const planner: any = JSON.parse(await readFile(plannerPath, 'utf8'));
const dog: any = JSON.parse(await readFile(dogPath, 'utf8'));
const correction: any = JSON.parse(await readFile(correctionPath, 'utf8'));
const source = (name: string, organisation: string, url: string, notes: string, reliability = 'official_non_statutory') => ({ sourceName: name, sourceOrganisation: organisation, sourceUrl: url, accessedAt: at, reliability, licence: 'Source-linked editorial evidence; verify time-sensitive details before travel.', notes });
const addTag = (f: any, tag: string) => { f.tags = [...new Set([...(f.tags ?? []), tag])]; };
const removeTag = (f: any, tag: string) => { f.tags = (f.tags ?? []).filter((value: string) => value !== tag); };
const byId = (featureId: string) => { const f = pkg.features.find((value: any) => value.id === featureId); if (!f) throw new Error(`Missing Edzell feature ${featureId}`); return f; };
const date = (f: any, text: string, earliest: number, latest: number, url: string, confidence = 'high') => {
  Object.assign(f, { documentedDateText: text, earliestPossibleYear: earliest, latestPossibleYear: latest, dateBasis: 'documented_date_range', dateConfidence: confidence, datePrecision: earliest === latest ? 'exact_year' : 'period_range', reviewed: true, updatedAt: at });
  addTag(f, 'date-reviewed'); addTag(f, 'heritage-record-retained'); removeTag(f, 'map-hidden');
  const notes = `Material-period evidence used for heat date: ${text}. Administrative designation dates were not used.`;
  if (!f.sourceRecords.some((record: any) => record.notes === notes)) f.sourceRecords.push(source(`${f.name} date evidence`, url.includes('historicenvironment.scot') ? 'Historic Environment Scotland' : 'HES NRHE / local audit', url, notes, url.includes('historicenvironment.scot') ? 'official_statutory' : 'official_non_statutory'));
};
const hide = (f: any, reason: string) => { addTag(f, 'map-hidden'); addTag(f, 'heritage-record-retained'); f.reviewed = true; f.updatedAt = at; f.reviewNotes = `Retained in the Edzell library but hidden from the heat map: ${reason}`; };

for (const [ref, text, first, last] of [
  ['LB11249', 'Built 1818; later additions including 1902', 1818, 1902], ['LB11250', 'Built 1906', 1906, 1906],
  ['LB11251', 'Built 1863', 1863, 1863], ['LB11252', 'Circa 1840', 1840, 1840], ['LB11253', 'Circa 1900', 1900, 1900],
  ['LB11261', 'Built 1897–1898', 1897, 1898], ['LB11262', 'Built 1888', 1888, 1888], ['LB11263', 'Circa 1902', 1902, 1902],
  ['LB52217', 'Built circa 1957', 1957, 1957],
] as const) date(byId(`hes-listed-building:${ref}`), text, first, last, `https://portal.historicenvironment.scot/designation/${ref}`);

const nrheDates: Record<string, [string, number, number]> = {
  '34974': ['Early Bronze Age', -2500, -1500], '35987': ['Medieval burgh; licensed as a burgh of barony in 1588', 1066, 1588],
  '35990': ['19th–20th century', 1800, 1999], '36086': ['Neolithic', -4000, -2500], '78335': ['Post-medieval', 1560, 1899],
  '193819': ['19th–20th century', 1800, 1999], '193820': ['20th century', 1900, 1999], '196136': ['20th century', 1900, 1999],
  '251685': ['20th century', 1900, 1999], '253132': ['20th century', 1900, 1999], '265958': ['19th century', 1800, 1899],
  '270317': ['19th century', 1800, 1899], '269041': ['Pictish / early medieval', 300, 900], '285677': ['Prehistoric', -4000, 43],
  '309297': ['Established 2001', 2001, 2001], '332950': ['Prehistoric', -4000, 43], '362414': ['19th century', 1800, 1899],
  '379392': ['Early Bronze Age and prehistoric', -2500, -800],
};
for (const [ref, [text, first, last]] of Object.entries(nrheDates)) date(byId(`nrhe:${ref}`), text, first, last, `https://www.trove.scot/place/${ref}`, 'medium');
for (const f of pkg.features.filter((value: any) => value.id.startsWith('nrhe:') && !value.documentedDateText)) hide(f, 'the local NRHE classification provides no defensible material period; no date is invented.');
for (const f of pkg.features.filter((value: any) => value.tags?.includes('town-selection-heritage-buffer'))) hide(f, 'the designation is in the 500-metre review buffer rather than the strict Edzell settlement boundary.');

const assessment = (score: number) => ({ experienceDepth: Math.round(score * .3), distinctiveness: Math.round(score * .2), presentation: Math.round(score * .2), journeyWorth: Math.round(score * .15), accessAndReliability: Math.round(score * .1), evidenceConfidence: score - Math.round(score * .3) - Math.round(score * .2) - Math.round(score * .2) - Math.round(score * .15) - Math.round(score * .1), visitability: 'full_visitor_experience' });
const foodAssessment = (score: number) => ({ foodAndDrinkQuality: Math.round(score * .29), daytimeRelevance: Math.round(score * .21), distinctiveness: Math.round(score * .15), consistency: Math.round(score * .14), visitorFit: Math.round(score * .11), evidenceConfidence: score - Math.round(score * .29) - Math.round(score * .21) - Math.round(score * .15) - Math.round(score * .14) - Math.round(score * .11) });
const make = (s: any) => {
  const placeType = s.placeType ?? (s.id.includes('curated-eat:') ? 'Cafe' : s.id.includes('curated-trails:') ? 'Trail' : s.id.includes('curated-picnic:') ? 'Picnic area' : s.id.includes('curated-parking:') ? 'Parking' : s.id.includes('curated-toilets:') ? 'Public toilets' : 'Attraction');
  const notes = `Current-place curation: visitor_place_type=${placeType}; ${s.score ? `visit_score=${s.score};` : ''} ${s.details ?? ''}; description=${s.description}`;
  return { id: s.id, projectId: id, name: s.name, alternativeNames: [], countryCode: 'GB-SCT', region: 'Angus', locality: 'Edzell', featureType: s.featureType, significance: s.significance ?? 'local', geometry: { type: 'Point', coordinates: s.coordinates }, locationType: 'exact', locationConfidence: 'high', dateBasis: 'unknown', dateConfidence: 'unknown', survival: 'substantially_intact', shortDescription: s.description, visitorWebsiteUrl: s.website, attractionGuide: s.guide, editorialReview: s.score ? { status: 'editorially_researched', category: s.category, methodVersion: '2026-08-30-researched-visitor-value-v1', reviewedAt: day, scoreRationale: s.reason, evidenceUrls: s.evidenceUrls, ...(s.category === 'food' ? { foodAssessment: foodAssessment(s.score) } : { attractionAssessment: assessment(s.score) }) } : undefined, sourceRecords: s.evidenceUrls.map((url: string, i: number) => source(i ? `${s.name} supporting evidence` : s.name, i ? 'Supporting publisher' : s.organisation, url, notes, url.includes('angus.gov.uk') ? 'local_authority' : 'official_non_statutory')), tags: s.tags, createdAt: at, updatedAt: at, reviewed: true, evidenceScope: 'parish_evidence' };
};

const attractionSpecs = [
  { id: 'curated-attraction:edzell-dalhousie-arch', name: 'Dalhousie Memorial Arch', score: 74, coordinates: [-2.6533273, 56.8055804], featureType: 'monument', description: 'The turreted 1888 sandstone gateway that marks Edzell’s planned southern approach.', reason: 'A distinctive, freely visible village landmark and strong arrival point, reduced because it is a brief roadside stop without an interior.', website: urls.town, organisation: 'Visit Angus / Historic Environment Scotland', evidenceUrls: [urls.town, 'https://portal.historicenvironment.scot/designation/LB11262'], category: 'attraction', tags: ['curated-visitor','home-standalone-place','historic-place-context'], guide: { headline: 'Enter Edzell beneath its 1888 landmark', parking: 'Use the Muir public car park; do not stop beneath the working road arch.', toilets: 'The Muir RADAR-accessible public toilet is about 800 metres north.', picnic: 'Edzell Muir is the verified picnic place.', foodNote: 'Sinclair’s Larder and Edzell Tweedie are on or beside High Street.' } },
  { id: 'curated-attraction:edzell-inglis-memorial-hall', name: 'Inglis Memorial Hall, Library and Visitor Centre', score: 72, coordinates: [-2.6536513, 56.8072587], featureType: 'museum', description: 'An 1897–98 Category A memorial hall with a restored Victorian library and Cotgreave book indicator.', reason: 'Edzell’s strongest indoor heritage anchor, but ordinary visits require advance arrangement and published open events are limited.', website: urls.hall, organisation: 'Visit Angus', evidenceUrls: [urls.hall, 'https://portal.historicenvironment.scot/designation/LB11261'], category: 'attraction', tags: ['curated-visitor','home-standalone-place','historic-place-context'], guide: { headline: 'See Edzell’s remarkable Victorian library', parking: 'Accessible parking and drop-off are published at the building; general capacity and any restrictions are not published.', toilets: 'Accessible toilets are published for arranged/open-event visits.', picnic: 'No picnic provision is claimed at the hall.', foodNote: 'High Street cafés are a short walk away.' } },
  { id: 'curated-attraction:edzell-castle-and-garden', name: 'Edzell Castle and Garden', score: 86, coordinates: [-2.6801, 56.8121], featureType: 'castle', description: 'A ruined tower house and ranges with one of Scotland’s most important early-17th-century Renaissance walled gardens.', reason: 'A nationally important, highly distinctive paid attraction with an exceptional garden and dependable seasonal visitor arrangements; scored separately from the settlement.', website: urls.castle, organisation: 'Visit Angus / Historic Environment Scotland', evidenceUrls: [urls.castle, 'https://portal.historicenvironment.scot/designation/SM90136', 'https://portal.historicenvironment.scot/designation/GDL00169'], category: 'attraction', tags: ['curated-visitor','home-standalone-place','historic-place-context'], guide: { headline: 'Pair tower-house ruins with Scotland’s great Renaissance garden', parking: 'Level tarmac car park with an accessible bay; a roughly 150-metre bound-gravel and grass approach follows.', toilets: 'An accessible visitor toilet is published in the visitor centre.', picnic: 'No castle picnic facility is claimed; use Edzell Muir.', foodNote: 'Return to the village for coffee, cake and light lunch.' } },
];
const trailSpecs = [
  { id: 'curated-trails:edzell-blue-door-walk', name: 'Blue Door Walk, Edzell', score: 76, coordinates: [-2.65318, 56.81109], featureType: 'walking_route', description: 'A moderate 4.7-kilometre, roughly two-hour riverside woodland walk from the village towards the Blue Door.', reason: 'A named official Edzell route with distance, duration and safety advice; steep drops and storm-damaged infrastructure require current-condition checks.', website: urls.blueDoor, organisation: 'Visit Angus', evidenceUrls: [urls.blueDoor, urls.town], category: 'trail', tags: ['curated-visitor','visitor-context-trail','current-context'], details: 'distance=4.7 km; duration=about 2 hours; difficulty=moderate; steep drops; check current bridge closures before travel' },
  { id: 'curated-trails:edzell-inchbare-cycle', name: 'Edzell to Inchbare Circuit', score: 67, coordinates: [-2.6554, 56.8088], featureType: 'cycling_route', description: 'An easy 8.5-kilometre, roughly one-hour cycle circuit from Edzell High Street to Inchbare and back.', reason: 'A clear official circular ride with distance, duration and start, useful for a wider visit but less distinctive than the riverside walk.', website: urls.cycle, organisation: 'Visit Angus', evidenceUrls: [urls.cycle], category: 'trail', tags: ['curated-visitor','visitor-context-trail','current-context'], details: 'distance=8.5 km; duration=about 1 hour; difficulty=easy; start=Edzell High Street' },
];
const foodSpecs = [
  { id: 'curated-eat:edzell-sinclairs-larder', name: 'Sinclair’s Larder', score: 78, coordinates: [-2.6565671, 56.8108682], featureType: 'commercial_building', description: 'Home baking and local coffee: A 30-seat café-bistro serving traditional cakes, breakfast and light lunch.', reason: 'A strongly evidenced, all-day café-led stop with coffee, cake and light lunch plus published level access and accessible toilet.', website: urls.sinclairs, organisation: 'Visit Angus', evidenceUrls: [urls.sinclairs], category: 'food', tags: ['curated-visitor','service-context-food','visitor-context-food','current-context'], details: 'amenity=cafe; cuisine=coffee, cake and light lunch; opening_hours:description=Open seven days; coffee and cake served all day; price_band=££; disabled_access=yes' },
  { id: 'curated-eat:edzell-tweedie', name: 'Edzell Tweedie Café', score: 66, coordinates: [-2.6548317, 56.8079964], featureType: 'commercial_building', description: 'Coffee beside the arch: A village café and retail stop for cakes, fresh bread and light daytime food.', reason: 'A useful café-led second choice, reduced because current third-party opening-hour listings conflict and should be checked before travel.', website: urls.tweedie, organisation: 'Edzell Tweedie / current directory listing', evidenceUrls: [urls.tweedie], category: 'food', tags: ['curated-visitor','service-context-food','visitor-context-food','current-context'], details: 'amenity=cafe; cuisine=coffee, cake, fresh bread and light food; opening_hours:description=Current directory listings conflict; confirm directly before a special journey; price_band=££' },
];
const facilitySpecs = [
  { id: 'curated-picnic:edzell-muir', name: 'Edzell Muir Picnic Area', coordinates: [-2.6593, 56.8132], featureType: 'park', description: 'The public Muir’s managed picnic and barbecue area beside the village park and play space.', website: urls.muir, organisation: 'Angus Council', evidenceUrls: [urls.muir], tags: ['service-context-picnic','current-context'], details: 'formal council park; picnic and barbecue area; ordinary tables and surfaces should be checked on arrival' },
  { id: 'curated-parking:edzell-muir', name: 'Edzell Muir Public Car Park', coordinates: [-2.659683, 56.813631], featureType: 'parking', description: 'Public visitor parking beside the Muir and public toilet. Capacity, maximum stay, overnight rules, tariff and payment method are not published, so signs govern.', website: urls.toilet, organisation: 'Angus Council', evidenceUrls: [urls.toilet, urls.muir], tags: ['service-context-parking','current-context'], details: 'public car park; capacity, accessible-space count, tariff, payment and maximum stay not published' },
  { id: 'curated-toilets:edzell-muir', name: 'Edzell Muir Public Toilet', coordinates: [-2.659683, 56.813631], featureType: 'toilet', description: 'Council public toilet with male, female and RADAR-key accessible provision. Current opening hours, fee and baby-changing provision are not published.', website: urls.toilet, organisation: 'Angus Council', evidenceUrls: [urls.toilet], tags: ['service-context-toilets','current-context'], details: 'accessible toilet=yes, RADAR key required; opening hours, charge and baby changing not published' },
];
const attractions = attractionSpecs.map(make), trails = trailSpecs.map(make), foods = foodSpecs.map(make), facilities = facilitySpecs.map(make);
pkg.features = [...pkg.features.filter((f: any) => !f.id.startsWith('curated-')), ...attractions, ...trails, ...foods, ...facilities];
pkg.project.townStudyArea.visitorBoundary = circle(pkg.project.centre, 2.1, { units: 'kilometers', steps: 96 });
pkg.project.visitorHighlights = attractions.map((f: any, index: number) => ({ rank: index + 1, featureId: f.id, name: f.name, reason: f.editorialReview.scoreRationale, tagline: index === 0 ? 'Edzell’s turreted village gateway' : index === 1 ? 'Victorian library and visitor centre' : 'Castle ruins and Renaissance garden', visitorScore: attractionSpecs[index].score, timeToSpend: index === 2 ? '1½–2½ hours' : '20–45 minutes', openingTimes: index === 2 ? '1 April–30 September 2026, Friday–Sunday 10:00–16:30; last entry 15:45' : index === 1 ? 'Visits by arrangement and published open days' : 'Open-air landmark', admission: index === 2 ? 'Adult £8.50; concession £6.80; child £5 at review' : 'Free', freeAdmission: index !== 2, visitorWebsiteUrl: f.visitorWebsiteUrl, editorialReview: f.editorialReview, sourceName: f.sourceRecords[0].sourceName, sourceUrl: f.visitorWebsiteUrl, verifiedInBoundaryAt: day }));
pkg.project.preferredBasemap = 'voyager';
pkg.project.touristAppeal = { score: 72, dogOwnerScore: 69, dogAccessScoreAdjustment: -3, rating: 1, label: 'Worth a Visit', summary: 'A handsome planned village with the Dalhousie Arch, an unusual Victorian hall, two café-led stops, practical Muir facilities and direct walking and cycling choices. Edzell Castle is separately scored.', dogAccessRating: 2, dogAccessSummary: 'The Muir and outdoor routes suit responsible dog visits, but riverside drops, roads, livestock and unconfirmed indoor café policies need planning.', methodVersion: '2026-08-30-strict-settlement-full-audit-v3', reviewedAt: day, sourceUrls: Object.values(urls) };
pkg.project.townGuide = { characterTag: 'Planned Angus village and North Esk walks', headline: 'A worthwhile village before the glens', intro: 'Edzell earns 72% from the village itself: planned historic character, the 1888 Dalhousie Arch, an unusual Victorian hall, two café-led stops, Muir facilities and two exact routes. Edzell Castle remains a separately scored See attraction and contributes no settlement points.', bestFor: ['Historic village character','Coffee and cake','Riverside walking','Easy cycling'], perfectFor: ['A half-day Angus stop','A café and riverside walk','A castle-and-village day'], suggestedFirstVisit: { title: 'Arch, hall, café and Muir', summary: 'Begin at the Dalhousie Arch, call at the Victorian hall if access is arranged, choose a café, then use the Muir as the practical base for the village or a route.' }, dontMiss: ['Dalhousie Memorial Arch','Inglis Memorial Hall','Blue Door Walk','Edzell Castle and Garden (separate attraction)'], suggestedTime: 'Half day; full day with the castle or longer walk', visitorMood: 'Orderly sandstone streets, a strong landmark entrance and easy access to the North Esk, with important current bridge cautions.', sourceUrls: Object.values(urls), lastReviewedAt: day };
pkg.project.researchNotes = 'Full sequential audit. Score 72 is retained on independent village merit; Edzell Castle is separately scored. Three See cards, two cafe-led Eats, two exact routes, one managed picnic place, one public car park and one council toilet are published. No exact Edzell product was found at TreasureTrails, Curious About, Mystery Guides or GoQuest. All 45 local HES/NRHE records remain intact: all nine in-boundary listed buildings and every visible NRHE pin carry a defensible material date; period-unassigned and buffer records remain map-hidden.';
planner.projects[id] = { eat: foods.map((f: any) => f.id), trails: trails.map((f: any) => f.id), picnic: ['curated-picnic:edzell-muir'], parking: ['curated-parking:edzell-muir'], toilets: ['curated-toilets:edzell-muir'] };
const dogRecord = (rating: number, status: string, summary: string, sourceUrl: string) => ({ rating, status, label: status === 'welcoming' ? 'Outdoor dog option' : 'Check access', summary, sourceName: 'Edzell dog-access audit', sourceUrl, reviewedAt: day });
dog.projects[id] = { attraction: Object.fromEntries(attractions.map((f: any) => [f.id, dogRecord(f.id.includes('arch') ? 3 : 1, f.id.includes('arch') ? 'welcoming' : 'unconfirmed', f.id.includes('arch') ? 'Open-air roadside landmark; keep dogs close beside traffic.' : 'No reliable current dog policy was found; assistance-dog access follows venue law.', f.visitorWebsiteUrl)])), trail: Object.fromEntries(trails.map((f: any) => [f.id, dogRecord(2, 'restricted', 'Use close control beside roads, steep river edges, wildlife and livestock; check current closures.', urls.dog)])), eat: Object.fromEntries(foods.map((f: any) => [f.id, dogRecord(1, 'unconfirmed', 'No reliable current dog policy was found for indoor access; confirm directly.', f.visitorWebsiteUrl)])) };

const heritage = pkg.features.filter((f: any) => f.tags.some((tag: string) => ['hes-listed-building','hes-scheduled-monument','nrhe'].includes(tag)));
const insideListed = heritage.filter((f: any) => f.tags.includes('hes-listed-building') && !f.tags.includes('town-selection-heritage-buffer'));
const visible = heritage.filter((f: any) => !f.tags.includes('map-hidden'));
const undated = visible.filter((f: any) => !f.documentedDateText || f.dateBasis === 'unknown' || f.name.includes(f.documentedDateText));
if (insideListed.length !== 9) throw new Error(`Expected 9 in-boundary listed buildings, found ${insideListed.length}`);
if (undated.length) throw new Error(`Invalid visible Edzell heritage dates: ${undated.map((f: any) => f.id).join(', ')}`);
const report = { reviewedAt: at, projectId: id, status: 'verified', settlementScore: 72, previousScore: 72, independentlyWorthwhile: true, publishOnTownMap: true, scoreRationale: pkg.project.touristAppeal.summary, publication: { see: attractions.length, eat: foods.length, trails: trails.length, picnic: 1, parking: 1, toilets: 1 }, heritage: { expectedInBoundaryListedBuildings: 9, representedInBoundaryListedBuildings: insideListed.length, bufferListedBuildingsRetained: heritage.filter((f: any) => f.tags.includes('town-selection-heritage-buffer')).length, nrheRecordsRetained: heritage.filter((f: any) => f.tags.includes('nrhe')).length, visibleDatedHeritagePins: visible.length, visibleUndatedHeritagePins: undated.length, hiddenRetainedRecords: heritage.filter((f: any) => f.tags.includes('map-hidden')).map((f: any) => f.id), dateRule: 'Construction or material-period dates only; never designation, listing or database dates.' }, namedTrailSearch: { TreasureTrails: 'No exact Edzell product found on the live provider site.', CuriousAbout: 'No exact Edzell product found.', MysteryGuides: 'No exact Edzell product found.', GoQuestAdventures: 'No exact Edzell product found.', retained: trails.map((f: any) => f.name), linkStatus: { visitAngusTown: 200, castle: 200, hall: 200, blueDoor: 200, cycle: 200, TreasureTrails: 200, CuriousAbout: 200, MysteryGuides: 200, GoQuest: 200 } }, practicalAudit: { see: 'Three independently scored visitor places; castle explicitly separate from settlement score.', eat: 'Two cafe-led daytime venues; full-meal restaurants and distant glen venues excluded.', picnic: 'One managed council picnic and barbecue area at Edzell Muir.', parking: 'One exact public car park; capacity, tariff, payment, maximum stay and accessible-space count explicitly unconfirmed.', toilets: 'One council toilet with RADAR accessible provision; hours, fee and baby changing explicitly unconfirmed.', accessibility: 'Hall and castle accessibility detail recorded; routes and Muir surfaces require on-arrival judgement.', transport: 'Village is walkable from the Muir; castle is about 1.6 km west and treated separately.' }, exclusions: ['Edzell Castle does not inflate the settlement score.', 'The storm-damaged Shakin Brig is not promoted as an accessible attraction.', 'Rocks of Solitude is not duplicated over the official Blue Door route while bridge access is disrupted.', 'No exact commercial clue-trail product is invented.'], verification: { localListedBuildingImport: { added: 6, refreshed: 9, bufferCandidates: 6 }, localNrheImport: { added: 0, linked: 9, excludedCandidates: 0 }, statutoryDatasetComplete: true, allVisibleHeritagePinsDated: true, datesStoredWithoutChangingMapNames: true, trailLinksChecked: Object.values(urls).filter((url) => ['treasure','curious','mystery','goQuest','blueDoor','cycle'].some((key) => url === (urls as any)[key])), allCuratedCoordinatesCheckedAgainstBoundaryOrExplicitlyMarkedSeparate: true } };
const row = correction.results.find((value: any) => value.projectId === id); if (row) { row.correctedScore = 72; row.changed = row.previousScore !== 72; row.publishOnTownMap = true; row.rationale = pkg.project.touristAppeal.summary; row.sourceUrls = [urls.town, urls.hall, urls.blueDoor, urls.sinclairs, urls.castle]; }
correction.changedScores = correction.results.filter((value: any) => value.changed).length;
correction.mappedAfterCorrection = correction.results.filter((value: any) => value.correctedScore >= 60).map((value: any) => ({ projectId: value.projectId, name: value.name, score: value.correctedScore }));
await writeFile(projectPath, `${JSON.stringify(pkg, null, 2)}\n`); await writeFile(plannerPath, `${JSON.stringify(planner, null, 2)}\n`); await writeFile(dogPath, `${JSON.stringify(dog, null, 2)}\n`); await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`); await writeFile(correctionPath, `${JSON.stringify(correction, null, 2)}\n`);
console.log(JSON.stringify({ publication: report.publication, heritage: report.heritage, status: report.status }, null, 2));
