import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { editorialRatingMethodVersion } from '../src/domain/editorialResearch';

const projectId='denhead-of-arbirlot-scotland', reviewedDate='2026-08-30', reviewedAt='2026-08-30T23:59:00Z';
const projectPath=resolve('data/projects/denhead-of-arbirlot.json'), plannerPath=resolve('data/cairn-o-mount-visitor-planner-curation.json'), dogPath=resolve('data/cairn-o-mount-dog-access-curation.json'), reportPath=resolve('data/review/denhead-of-arbirlot-full-visitor-audit-2026-08-30.json');
const urls={settlement:'https://www.openstreetmap.org/node/5846489555',railway:'https://www.trove.scot/place/169715',route:'https://visitangus.com/things-to-see-do/trails/circuit-through-rural-angus/',routePdf:'https://d1ssu070pg2v9i.cloudfront.net/visit-angus/2024/12/09132211/Biking-Trail-Circuit-through-Rural-Angus.pdf',treasure:'https://www.treasuretrails.co.uk/collections/dundee-and-angus',curious:'https://www.curiousabout.co.uk/',outdoorAccess:'https://www.outdooraccess-scotland.scot/dog-owners'};
const pkg:any=JSON.parse(await readFile(projectPath,'utf8')), planner:any=JSON.parse(await readFile(plannerPath,'utf8')), dog:any=JSON.parse(await readFile(dogPath,'utf8'));
pkg.features=pkg.features.filter((f:any)=>!f.id.startsWith('curated-'));
for(const feature of pkg.features){feature.sourceRecords=feature.sourceRecords.filter((r:any)=>r.accessedAt!==reviewedAt);feature.tags=[...new Set(feature.tags.concat('heritage-record-retained'))];feature.reviewed=true;feature.updatedAt=reviewedAt;}
const railway=pkg.features.find((f:any)=>f.id==='nrhe:169715');
Object.assign(railway,{documentedDateText:'19th-century railway',earliestPossibleYear:1800,latestPossibleYear:1899,dateBasis:'documented_period',dateConfidence:'high',datePrecision:'century'});
railway.tags=railway.tags.filter((tag:string)=>tag!=='map-hidden');railway.tags.push('date-reviewed');
railway.sourceRecords.push({sourceName:'Trove NRHE 169715',sourceOrganisation:'Historic Environment Scotland',sourceUrl:urls.railway,accessedAt:reviewedAt,reliability:'official_non_statutory',licence:'Open Government Licence',notes:'The official NRHE classification is Railway (19th Century).'});
railway.reviewNotes='The official 19th-century material period is stored in the date fields and is not added to the map name.';
for(const feature of pkg.features.filter((f:any)=>f.id!=='nrhe:169715')){feature.tags=[...new Set(feature.tags.concat('map-hidden'))];feature.reviewNotes='The local NRHE record is retained, but its official classification is period-unassigned; it remains map-hidden rather than receiving an invented date.';}
const route:any={id:'curated-trails:denhead-circuit-rural-angus',projectId,name:'Circuit through Rural Angus',alternativeNames:[],countryCode:'GB-SCT',region:'Angus',locality:'Denhead of Arbirlot',featureType:'cycling_route',significance:'local',geometry:{type:'Point',coordinates:[-2.687456,56.570564]},locationType:'representative',locationConfidence:'high',dateBasis:'unknown',dateConfidence:'unknown',survival:'substantially_intact',shortDescription:'An official easy 27.5 km road-cycling circuit from Arbroath Harbour that passes through the Denhead of Arbirlot countryside.',visitorWebsiteUrl:urls.route,editorialReview:{status:'editorially_researched',category:'trail',methodVersion:editorialRatingMethodVersion,reviewedAt:reviewedDate,scoreRationale:'A current official route with clear distance, duration, grade and downloadable card; Denhead is a through-section rather than the start or principal destination.',evidenceUrls:[urls.route,urls.routePdf],attractionAssessment:{experienceDepth:17,distinctiveness:14,presentation:12,journeyWorth:9,accessAndReliability:9,evidenceConfidence:5,visitability:'full_visitor_experience'}},sourceRecords:[{sourceName:'Visit Angus Circuit through Rural Angus',sourceOrganisation:'Visit Angus',sourceUrl:urls.route,accessedAt:reviewedAt,reliability:'official_non_statutory',licence:'Source-linked visitor evidence; verify road conditions before travel.',notes:'Current-place curation: visitor_place_type=Trail; visit_score=66; trail_type=Official road-cycle circuit passing through Denhead; distance=27.5 km / 17.1 miles; duration=4 hours; grade=easy; start=Arbroath Harbour; on-road route; link checked 2026-08-30'},{sourceName:'Official downloadable route card',sourceOrganisation:'Visit Angus',sourceUrl:urls.routePdf,accessedAt:reviewedAt,reliability:'official_non_statutory',licence:'Source-linked visitor evidence.',notes:'PDF route map identifies Denhead of Arbirlot on the circuit; HTTP 200 checked 2026-08-30.'}],tags:['curated-visitor','visitor-context-trail','current-context'],createdAt:reviewedAt,updatedAt:reviewedAt,reviewed:true,evidenceScope:'strict_boundary'};
pkg.features.push(route);pkg.project.visitorHighlights=[];pkg.project.preferredBasemap='voyager';
pkg.project.touristAppeal={score:20,dogOwnerScore:18,dogAccessScoreAdjustment:-2,rating:0,label:'Minor Interest',summary:'A working farm locality rather than an independently visitable settlement; the regional cycle circuit is represented separately.',dogAccessRating:1,dogAccessSummary:'No destination-scale dog visit or dedicated dog facilities are verified; rural roads and farmland require close control.',methodVersion:'2026-08-30-strict-settlement-full-audit-v3',reviewedAt:reviewedDate,sourceUrls:Object.values(urls)};
pkg.project.townGuide={characterTag:'Working Angus farm locality',headline:'A route waypoint rather than a visitor destination',intro:'Denhead of Arbirlot remains a 20% selector-only locality. The official Circuit through Rural Angus passes here and is available as a trail card, but it starts in Arbroath and does not turn the farm locality into a town destination.',bestFor:['A rural section of a longer cycle ride'],perfectFor:['Route context on the official Angus circuit'],suggestedFirstVisit:{title:'Treat Denhead as a through-point',summary:'Start the signed ride from Arbroath Harbour using the official route card; there is no verified visitor parking, café or toilet at Denhead itself.'},dontMiss:[],suggestedTime:'Pass-through on the 4-hour cycle circuit',visitorMood:'Open farmland and quiet rural-road scenery.',sourceUrls:Object.values(urls),lastReviewedAt:reviewedDate};
pkg.project.researchNotes='Full strict-boundary audit. Denhead of Arbirlot remains selector-only at 20 because it is a farm locality, not an independently worthwhile settlement. The official 27.5 km Circuit through Rural Angus is published separately as a trail that passes through, without inflating the settlement score. Local HES reconciliation found no statutory designations and retained all three NRHE records. The Carmyllie Light Railway record has an official 19th-century classification and is visible; the cist and possible promontory fort remain period-unassigned and map-hidden. No qualifying café-led eat stop, managed picnic place, dedicated public visitor parking or public toilet was verified. No exact Denhead product was found at Treasure Trails, Curious About, Mystery Guides or GoQuest.';
planner.projects[projectId]={eat:[],trails:[route.id],picnic:[],parking:[],toilets:[]};dog.projects[projectId]={};
const heritage=pkg.features.filter((f:any)=>f.tags.includes('hes-listed-building')||f.tags.includes('hes-scheduled-monument')||f.tags.includes('nrhe')),visible=heritage.filter((f:any)=>!f.tags.includes('map-hidden'));
const report={reviewedAt,projectId,status:'verified',settlementScore:20,previousScore:20,independentlyWorthwhile:false,publishOnTownMap:false,scoreRationale:'A working farm locality with no public visitor-service cluster; the regional cycle route is represented separately.',publication:{see:0,eat:0,trails:1,picnic:0,parking:0,toilets:0},heritage:{expectedStatutoryRecords:0,representedStatutoryRecords:0,nrheRecordsRetained:heritage.length,visibleDatedHeritagePins:visible.filter((f:any)=>f.documentedDateText?.trim()).length,visibleUndatedHeritagePins:visible.filter((f:any)=>!f.documentedDateText?.trim()).length,hiddenUndatedNrheRecords:heritage.filter((f:any)=>f.tags.includes('map-hidden')&&!f.documentedDateText?.trim()).map((f:any)=>f.id)},namedTrailSearch:{TreasureTrails:'No exact Denhead of Arbirlot product in the current Dundee and Angus collection; link returned HTTP 200.',CuriousAbout:'No exact product found; provider link returned HTTP 200.',MysteryGuides:'No exact product found.',GoQuestAdventures:'No exact product found.',retained:[route.name]},practicalAudit:{see:'No public attraction meeting the 60-point threshold verified inside the locality.',eat:'No qualifying café, coffee-and-cake stop, tearoom or light-lunch venue verified.',picnic:'No managed or expressly promoted visitor picnic facility verified.',parking:'No dedicated public visitor car park verified; farm and roadside access are not published as parking.',toilets:'No public toilet verified.',accessibility:'The retained cycle route is on roads; no settlement-level accessibility facility is published.',transport:'The cycle route starts at Arbroath Harbour; Denhead is not presented as its access hub.'},exclusions:['Arbirlot Falls and its natural trail belong to Arbirlot/Elliot, not Denhead.','Private farm access is not visitor parking.','Two period-unassigned NRHE records remain intact but hidden.'],verification:{statutoryDatasetComplete:true,allVisibleHeritagePinsDated:visible.every((f:any)=>f.documentedDateText?.trim()&&f.dateBasis!=='unknown'),datesStoredWithoutChangingMapNames:visible.every((f:any)=>!f.name.includes(f.documentedDateText)),trailLinksChecked:[urls.route,urls.routePdf,urls.treasure,urls.curious],curatedCategoryCoordinatesChecked:true}};
await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`);await writeFile(plannerPath,`${JSON.stringify(planner,null,2)}\n`);await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`);await writeFile(reportPath,`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));
