import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type { AttractionEditorialAssessment, EditorialRecordReview, HeritageFeature, ProjectPackage, SourceRecord, VisitorHighlight } from '../src/domain/models';
import { attractionEditorialScore } from '../src/domain/editorialResearch';
import { validateFeatures } from '../src/domain/validation';

const projectPath = resolve('data/projects/crail.json');
const dogPath = resolve('data/crail-dog-access-curation.json');
const assessmentPath = resolve('data/review/crail-attraction-assessment-2026-08-25.json');
const reviewedAt = '2026-08-25';
const updatedAt = `${reviewedAt}T22:15:00.000Z`;
const methodVersion = '2026-08-13-researched-visitor-value-v1';

type CandidateStatus = 'published' | 'combined' | 'kept_in_trails' | 'excluded';
interface CandidateAssessment { candidate: string; score: number; status: CandidateStatus; publishedAs?: string; rationale: string }

const candidates: CandidateAssessment[] = [
  ['Crail Harbour',86,'published','Crail Harbour and Shoregate','Crail’s defining working-harbour scene, with a substantial foreshore and old-burgh approach.'],
  ['Crail Museum & Heritage Centre',72,'published','Crail Museum and Heritage Centre','A genuine museum visit with locally specific displays, current opening information and free admission.'],
  ['Crail Parish Church',80,'published','Crail Parish Church and Kirkyard','A nationally significant medieval church-and-kirkyard ensemble with an online tour and a dependable outdoor visit.'],
  ['Crail Priory Doocot',74,'published','Crail Priory Doocot','A restored 16th-century beehive doocot with reconstructed potence, hundreds of nest boxes and interpretation.'],
  ['Roome Bay',83,'published','Roome Bay and Rock Pools','An award-recognised sandy cove with rock pools, wildlife, play space, coastal-path access and public facilities.'],
  ['Crail Pottery',69,'published','Crail Pottery','A distinctive working pottery and courtyard shopping experience, though less journey-worthy than Crail’s coast and major heritage.'],
  ['Castle Walk & Castle Garden',75,'published','Castle Walk and Viewpoint','A coherent open-air walk around the castle walls with harbour approaches, fossil interest and a panoramic indicator.'],
  ['Site of Crail Castle',44,'combined','Castle Walk and Viewpoint','The castle itself is a site with very limited remains; its visitor value comes from the surrounding walk and viewpoint.'],
  ['Crail Tolbooth / Town Hall',65,'published','Crail Tolbooth and Marketgate','A visually prominent 1598 civic landmark with an unusually rich clock, bell and burgh story, best experienced from Marketgate.'],
  ['Crail Harbour Gallery & Tearoom',78,'published','Crail Harbour Gallery','A working local-art gallery in a restored harbour cottage, with a sea-view courtyard and dependable operator information.'],
  ['Fife Coastal Path – Crail',84,'kept_in_trails','Fife Coastal Path','A high-value waymarked coastal experience already presented in Trails; duplicating it in See would distort the attraction list.'],
  ['Mercat Cross',56,'combined','Crail Tolbooth and Marketgate','Historically relevant but a brief exterior detail; it strengthens the Marketgate ensemble rather than supporting a separate visit.'],
  ['Dead House',60,'combined','Crail Parish Church and Kirkyard','A distinctive 1826 mort house and excellent story, but too brief for a separate attraction card.'],
  ['Sauchope Standing Stone',58,'excluded',undefined,'An important relocated Pictish stone, but a short standalone stop with limited presentation and journey value.'],
  ['Mural Tombs',60,'combined','Crail Parish Church and Kirkyard','A nationally interesting collection which materially deepens the churchyard visit but is best presented as part of that ensemble.'],
  ['Church Kirkyard',60,'combined','Crail Parish Church and Kirkyard','The accessible setting for the mural monuments and Dead House; combined to prevent several cards for one compact visit.'],
  ['War Memorial Gateway',48,'combined','Crail Parish Church and Kirkyard','A worthwhile entrance detail but not a substantial visitor experience by itself.'],
  ['Blue Stane',42,'excluded',undefined,'A small heritage detail with low experience depth and limited interpretation.'],
  ['Priory Walls',49,'combined','Crail Priory Doocot','Fragmentary context for the doocot rather than a separate attraction.'],
  ['Denburn Wood',55,'excluded',undefined,'A pleasant short local green-space link but insufficient distinctiveness and destination value for See.'],
  ['Shoregate',68,'combined','Crail Harbour and Shoregate','A highly characterful historic approach which is already integral to the harbour card.'],
  ['Marketgate',58,'combined','Crail Tolbooth and Marketgate','An attractive historic space whose individual details work better as one civic ensemble.'],
  ['Auld House',43,'excluded',undefined,'An exterior architectural detail on the heritage walk, not a sustained visit.'],
  ['Kirkmay House',45,'excluded',undefined,'A private listed house viewed externally, with limited access and experience depth.'],
  ['Forelands/Kingo House',42,'excluded',undefined,'A private architectural stop with low access and limited standalone interpretation.'],
  ['Downies Terrace',44,'excluded',undefined,'A streetscape detail rather than a discrete visitor experience.'],
  ['Mackinnon’s School/British Legion',43,'excluded',undefined,'A heritage-walk exterior without dependable visitor access.'],
  ['King’s Mill site',34,'excluded',undefined,'A historic site with little legible fabric and low standalone visitability.'],
  ['King’s Mill Watch House',46,'excluded',undefined,'A minor visible survival which does not sustain a separate visitor stop.'],
  ['King’s Mill millstone',40,'excluded',undefined,'A single object with limited presentation and experience depth.'],
  ['St Adrians',42,'excluded',undefined,'A brief heritage-walk point with limited visitor infrastructure or interpretation.'],
  ['Harbour Master’s Office',48,'combined','Crail Harbour and Shoregate','Useful harbour context but inseparable from the main harbour experience.'],
  ['Custom House',49,'combined','Crail Harbour and Shoregate','An exterior harbour component which enriches, rather than duplicates, the main card.'],
  ['Hen’s Ladder',51,'combined','Crail Harbour and Shoregate','A memorable access feature, but too short and physically integrated with the harbour to list separately.'],
  ['Maltings',43,'excluded',undefined,'A historic building detail without a dependable public visitor experience.'],
  ['Little Houses 14–16 High Street',47,'excluded',undefined,'Interesting conservation history but principally private façades viewed from the street.'],
  ['Golf Hotel',0,'excluded',undefined,'A food-and-drink business already assessed under Eat; it is not an attraction.'],
  ['Memorial/Jubilee Fountain',41,'combined','Crail Tolbooth and Marketgate','Useful civic detail within Marketgate, but not a standalone attraction.'],
  ['Holy Trinity RC Church',48,'excluded',undefined,'Architectural interest but no sufficiently strong, researched visitor proposition for a separate card.'],
  ['Former Roome Bay pool',52,'combined','Roome Bay and Rock Pools','Now a wildlife haven and a useful part of the bay story, not a separate attraction.'],
  ['Roome Bay rock pools',72,'combined','Roome Bay and Rock Pools','A substantial family and wildlife experience which is inseparable from Roome Bay.'],
  ['Victoria Gardens',55,'excluded',undefined,'A pleasant local garden and setting for the standing stone, but limited destination value by itself.'],
  ['Historic High Street',58,'excluded',undefined,'Strong town character but no discrete attraction boundary; it is already explored through the Heritage Walk.'],
  ['Castle/harbour viewpoints',66,'combined','Castle Walk and Viewpoint','The views are a qualifying experience when presented as part of the signed Castle Walk, not as an unlocated duplicate card.'],
].map(([candidate, score, status, publishedAs, rationale]) => ({ candidate, score, status, publishedAs, rationale } as CandidateAssessment));

interface HighlightSeed { featureId: string; name: string; visitorScore: number; tagline: string; reason: string; timeToSpend: string; openingTimes: string; admission: string; sourceName: string; sourceUrl: string; assessment: AttractionEditorialAssessment; attractionGuide?: VisitorHighlight['attractionGuide'] }
const newHighlights: HighlightSeed[] = [
  { featureId:'curated-attraction:crail-roome-bay', name:'Roome Bay and Rock Pools', visitorScore:83, tagline:'Beach, rock pools and wildlife', reason:'A south-facing sandy cove with extensive rock pools, a wildlife-rich former bathing pool, play space, public toilets and direct access to the Fife Coastal Path.', timeToSpend:'1–2 hours; longer with children', openingTimes:'Open-air beach and greenspace; visit in daylight and check tides and current water-quality advice.', admission:'Free.', sourceName:'Fife Council – Crail Roome Bay', sourceUrl:'https://www.fife.gov.uk/facilities/beaches-and-harbours/crail-roome-bay', assessment:{experienceDepth:27,distinctiveness:17,presentation:16,journeyWorth:12,accessAndReliability:7,evidenceConfidence:4,visitability:'full_visitor_experience'}, attractionGuide:{headline:'Rock pools, wildlife and coastal air',intro:'A compact south-facing bay for low-tide exploring, family time and a gentle coast-path stop.',bestFor:['Rock pooling','Families','Coastal walking','Wildlife'],parking:'Free parking facilities are listed by Fife Council; spaces, bay layout and maximum stay are not published for this beach facility.',toilets:'Public toilets are listed by Fife Council at Roome Bay.',picnic:'No dedicated picnic tables are confirmed; the sloping grass and benches provide informal outdoor stopping places.',foodNote:'No on-site café is confirmed; use Crail’s separately researched Eat choices.',trails:[{name:'Fife Coastal Path at Roome Bay',summary:'The waymarked coast path crosses the greenspace above the bay.',routeType:'Coastal path',distance:'Choose a short Crail section or continue towards Anstruther or Fife Ness.',duration:'Flexible',difficulty:'Steps and sloping paths around the beach.',externalUrl:'https://fifecoastandcountrysidetrust.co.uk/walks/fife-coastal-path/'}],thingsToDo:[{name:'Explore the rock pools',summary:'Visit around low tide and avoid disturbing wildlife.'},{name:'See the former bathing pool',summary:'The disused pool at the west end is now a wildlife haven.'},{name:'Use the play space',summary:'A children’s play area sits above the beach.'}]} },
  { featureId:'hes-listed-building:crail-lb23244', name:'Crail Parish Church and Kirkyard', visitorScore:80, tagline:'Medieval kirk and mural tombs', reason:'A medieval church ensemble with a Pictish cross slab, a nationally notable group of mural monuments and the unusual 1826 Dead House in its historic kirkyard.', timeToSpend:'45–75 minutes', openingTimes:'Kirkyard open during normal daylight access; church interior is available at services, published openings or by local arrangement.', admission:'Free; donations welcome when the church is open.', sourceName:'Crail Parish Church and Crail Museum', sourceUrl:'https://www.crailchurch.com/', assessment:{experienceDepth:27,distinctiveness:18,presentation:15,journeyWorth:12,accessAndReliability:4,evidenceConfidence:4,visitability:'full_visitor_experience'} },
  { featureId:'hes-listed-building:crail-lb23402', name:'Castle Walk and Viewpoint', visitorScore:75, tagline:'Castle walls and harbour panorama', reason:'A short signed walk around the former castle site, with surviving walls, a fossil-mounted sundial, a panoramic indicator and steps towards the harbour.', timeToSpend:'30–60 minutes', openingTimes:'Open-air public walk; daylight visit recommended.', admission:'Free.', sourceName:'Crail Museum Heritage Walk', sourceUrl:'https://www.crailmuseum.uk/home/walk/castle-walk', assessment:{experienceDepth:23,distinctiveness:16,presentation:15,journeyWorth:10,accessAndReliability:7,evidenceConfidence:4,visitability:'full_visitor_experience'} },
  { featureId:'hes-listed-building:crail-lb23445', name:'Crail Priory Doocot', visitorScore:74, tagline:'Restored 16th-century doocot', reason:'A restored beehive doocot with a reconstructed potence ladder, lighting, interpretation and around 700 nest boxes beside Roome Bay.', timeToSpend:'20–40 minutes', openingTimes:'Exterior and surrounding coastal greenspace open in daylight; interior access is subject to the door being open.', admission:'Free.', sourceName:'Crail Museum – Crail Priory Doocot', sourceUrl:'https://www.crailmuseum.uk/home/walk/crail-priory-doocot', assessment:{experienceDepth:20,distinctiveness:18,presentation:16,journeyWorth:9,accessAndReliability:7,evidenceConfidence:4,visitability:'full_visitor_experience'} },
  { featureId:'hes-listed-building:crail-lb23287', name:'Crail Tolbooth and Marketgate', visitorScore:65, tagline:'Burgh tower, bell and market', reason:'Crail’s 1598 civic landmark anchors Marketgate with an early burgh coat of arms, a 1520 bell, clock tower, mercat cross and memorial fountain.', timeToSpend:'20–40 minutes', openingTimes:'Exterior and Marketgate open at all times; Town Hall interior is event-dependent.', admission:'Free exterior visit.', sourceName:'Crail Museum – Crail Tolbooth', sourceUrl:'https://www.crailmuseum.uk/home/walk/crail-tolbooth', assessment:{experienceDepth:18,distinctiveness:15,presentation:13,journeyWorth:7,accessAndReliability:8,evidenceConfidence:4,visitability:'full_visitor_experience'} },
];

function review(seed: HighlightSeed): EditorialRecordReview { const calculated=attractionEditorialScore(seed.assessment); if(calculated!==seed.visitorScore) throw new Error(`${seed.name}: calculated ${calculated}, expected ${seed.visitorScore}`); return {status:'editorially_researched',category:'attraction',methodVersion,reviewedAt,scoreRationale:seed.reason,evidenceUrls:[seed.sourceUrl],attractionAssessment:seed.assessment}; }
function source(seed: HighlightSeed): SourceRecord { return {sourceName:'Crail attraction visitor-value research',sourceOrganisation:seed.sourceName,sourceUrl:seed.sourceUrl,accessedAt:updatedAt,reliability:'secondary',licence:'Source-linked editorial record; verify time-sensitive details before travel.',notes:`Current-place curation: visitor_place_type=Attraction; visit_score=${seed.visitorScore}; description=${seed.reason}`}; }
function roomeFeature(): HeritageFeature { return {id:'curated-attraction:crail-roome-bay',projectId:'crail-scotland',name:'Roome Bay and Rock Pools',alternativeNames:['Crail Roome Bay'],countryCode:'GB-SCT',region:'Fife',locality:'Crail',featureType:'beach',geometry:{type:'Point',coordinates:[-2.61795,56.25882]},locationType:'representative',locationConfidence:'high',dateBasis:'unknown',dateConfidence:'unknown',significance:'regional',survival:'substantially_intact',shortDescription:'South-facing sand-and-rock cove with rock pools, a wildlife-rich former bathing pool, grass slopes and play space.',visitorWebsiteUrl:'https://www.fife.gov.uk/facilities/beaches-and-harbours/crail-roome-bay',sourceRecords:[],tags:['current-context','service-context-visitor','curated-visitor-attraction'],createdAt:updatedAt,updatedAt,reviewed:true,evidenceScope:'parish_evidence'}; }

const pkg=JSON.parse(await readFile(projectPath,'utf8')) as ProjectPackage;
const byId=new Map(pkg.features.map((feature)=>[feature.id,feature]));
if(!byId.has('curated-attraction:crail-roome-bay')) { const feature=roomeFeature(); pkg.features.push(feature); byId.set(feature.id,feature); }
for(const seed of newHighlights){ const feature=byId.get(seed.featureId); if(!feature) throw new Error(`Missing ${seed.featureId}`); feature.tags=[...new Set([...feature.tags,'service-context-visitor','curated-visitor-attraction'])]; feature.visitorWebsiteUrl=seed.sourceUrl; feature.editorialReview=review(seed); feature.attractionGuide=seed.attractionGuide; feature.sourceRecords=[...feature.sourceRecords.filter((record)=>record.sourceName!=='Crail attraction visitor-value research'),source(seed)]; feature.updatedAt=updatedAt; feature.reviewed=true; }
const replacementIds=new Set(newHighlights.map((seed)=>seed.featureId));
const expanded: VisitorHighlight[]=[...(pkg.project.visitorHighlights??[]).filter((item)=>!replacementIds.has(item.featureId)),...newHighlights.map((seed)=>({rank:0,featureId:seed.featureId,name:seed.name,reason:seed.reason,visitorScore:seed.visitorScore,tagline:seed.tagline,timeToSpend:seed.timeToSpend,openingTimes:seed.openingTimes,admission:seed.admission,freeAdmission:true,sourceName:seed.sourceName,sourceUrl:seed.sourceUrl,visitorWebsiteUrl:seed.sourceUrl,verifiedInBoundaryAt:reviewedAt,editorialReview:review(seed),attractionGuide:seed.attractionGuide}))].filter((item)=>(item.visitorScore??0)>60).sort((a,b)=>(b.visitorScore??0)-(a.visitorScore??0)||a.name.localeCompare(b.name)).map((item,index)=>({...item,rank:index+1}));
pkg.project.visitorHighlights=expanded;
pkg.sources=[{id:'crail-attraction-threshold-research-2026-08-25',name:'Crail attraction visitor-value assessment',organisation:'Crail Museum, Fife Council, Crail Parish Church and attraction operators',coverage:'All 44 user-supplied Crail attraction candidates; publication threshold strictly above 60',accessMethod:'Opened current primary, council, church, museum and operator visitor pages, then scored the experience using the saved attraction method.',sourceUrl:'https://www.crailmuseum.uk/home/map',reliability:'official_non_statutory',limitations:'Private façades and brief details remain heritage pins or trail stops rather than inflated attraction cards; current opening and pet policies can change.'},...pkg.sources.filter((item)=>item.id!=='crail-attraction-threshold-research-2026-08-25')];
pkg.validation=validateFeatures(pkg.project,pkg.features); if(pkg.validation.some((item)=>item.severity==='error')) throw new Error('Validation errors after Crail attraction expansion.');
await writeFile(projectPath,`${JSON.stringify(pkg,null,2)}\n`,'utf8');

type DogRecord={rating:0|1|2|3;status:'unconfirmed'|'restricted'|'welcoming';label:string;summary:string;sourceName:string;sourceUrl:string;reviewedAt:string};
const dog=JSON.parse(await readFile(dogPath,'utf8')) as {reviewedAt:string;projects:Record<string,{attraction:Record<string,DogRecord>;eat:Record<string,DogRecord>}>};
Object.assign(dog.projects['crail-scotland'].attraction,{
  'curated-attraction:crail-roome-bay':{rating:3,status:'welcoming',label:'Dogs welcome all year',summary:'Two dog-specific Crail guides identify Roome Bay as a year-round dog-friendly beach. Keep dogs controlled around children, wildlife, rock pools and any temporary local signs.',sourceName:'Roome Bay dog-access cross-check',sourceUrl:'https://www.thegooddogguide.com/fife/crail/dog-friendly-beaches/roome-bay/25586',reviewedAt},
  'hes-listed-building:crail-lb23244':{rating:1,status:'restricted',label:'Kirkyard works; church unconfirmed',summary:'The open-air kirkyard can be visited with a controlled dog, but no reliable current policy for ordinary pet dogs inside the church could be confirmed; assistance dogs are unaffected.',sourceName:'Crail Parish Church visitor-information review',sourceUrl:'https://www.crailchurch.com/',reviewedAt},
  'hes-listed-building:crail-lb23402':{rating:3,status:'welcoming',label:'Excellent open-air dog stop',summary:'Castle Walk is an open-air link within Crail’s dog-friendly coastal walking network. Keep dogs close on steps, near roads and around other visitors.',sourceName:'Castle Walk and dog-friendly Crail cross-check',sourceUrl:'https://honeypotcrail.co.uk/dog-friendly-crail/',reviewedAt},
  'hes-listed-building:crail-lb23445':{rating:2,status:'restricted',label:'Grounds good; interior unconfirmed',summary:'The doocot stands in dog-walkable Roome Bay greenspace, but no reliable policy for pet dogs inside the small restored structure could be confirmed.',sourceName:'Fife Council Roome Bay and doocot visitor-information review',sourceUrl:'https://www.fife.gov.uk/facilities/park/roome-bay',reviewedAt},
  'hes-listed-building:crail-lb23287':{rating:2,status:'restricted',label:'Marketgate good; hall unconfirmed',summary:'The exterior and Marketgate form an easy open-air stop with a dog. No reliable current pet-dog policy for event-dependent Town Hall interiors could be confirmed.',sourceName:'Crail Tolbooth visitor-information review',sourceUrl:'https://www.crailmuseum.uk/home/walk/crail-tolbooth',reviewedAt},
});
dog.reviewedAt=reviewedAt; await writeFile(dogPath,`${JSON.stringify(dog,null,2)}\n`,'utf8');
await mkdir(dirname(assessmentPath),{recursive:true}); await writeFile(assessmentPath,`${JSON.stringify({schemaVersion:1,projectId:'crail-scotland',reviewedAt,publicationRule:'visitor score > 60',candidateCount:candidates.length,publishedSeeCount:expanded.length,candidates},null,2)}\n`,'utf8');
console.log(`Assessed ${candidates.length} Crail candidates and published ${expanded.length} See cards above 60.`);
