// Generated by scripts/create-cambridgeshire-settlement-batch.ts. Do not edit by hand.
import type { ProjectPackage } from '../domain/models';
import package0 from '../../data/projects/abbots-ripton-england.json';
import package1 from '../../data/projects/abington-pigotts-england.json';
import package2 from '../../data/projects/ailsworth-england.json';
import package3 from '../../data/projects/arrington-england.json';
import package4 from '../../data/projects/babraham-england.json';
import package5 from '../../data/projects/bainton-england.json';
import package6 from '../../data/projects/balsham-england.json';
import package7 from '../../data/projects/barnack-england.json';
import package8 from '../../data/projects/barrington-england.json';
import package9 from '../../data/projects/bartlow-england.json';
import package10 from '../../data/projects/bassingbourn-england.json';
import package11 from '../../data/projects/bluntisham-england.json';
import package12 from '../../data/projects/bottisham-england.json';
import package13 from '../../data/projects/bourn-england.json';
import package14 from '../../data/projects/buckden-england.json';
import package15 from '../../data/projects/burwell-england.json';
import package16 from '../../data/projects/cambourne-england.json';
import package17 from '../../data/projects/cambridge-england.json';
import package18 from '../../data/projects/castle-camps-england.json';
import package19 from '../../data/projects/castor-england.json';
import package20 from '../../data/projects/chatteris-england.json';
import package21 from '../../data/projects/chippenham-england.json';
import package22 from '../../data/projects/coton-england.json';
import package23 from '../../data/projects/cottenham-england.json';
import package24 from '../../data/projects/doddington-england.json';
import package25 from '../../data/projects/duxford-england.json';
import package26 from '../../data/projects/earith-england.json';
import package27 from '../../data/projects/elm-england.json';
import package28 from '../../data/projects/eltisley-england.json';
import package29 from '../../data/projects/elton-england.json';
import package30 from '../../data/projects/ely-england.json';
import package31 from '../../data/projects/etton-england.json';
import package32 from '../../data/projects/fen-ditton-england.json';
import package33 from '../../data/projects/fen-drayton-england.json';
import package34 from '../../data/projects/fenstanton-england.json';
import package35 from '../../data/projects/fordham-england.json';
import package36 from '../../data/projects/fowlmere-england.json';
import package37 from '../../data/projects/foxton-england.json';
import package38 from '../../data/projects/fulbourn-england.json';
import package39 from '../../data/projects/gamlingay-england.json';
import package40 from '../../data/projects/glinton-england.json';
import package41 from '../../data/projects/godmanchester-england.json';
import package42 from '../../data/projects/grafham-england.json';
import package43 from '../../data/projects/grantchester-england.json';
import package44 from '../../data/projects/great-abington-england.json';
import package45 from '../../data/projects/great-chishill-england.json';
import package46 from '../../data/projects/great-eversden-england.json';
import package47 from '../../data/projects/great-gidding-england.json';
import package48 from '../../data/projects/great-gransden-england.json';
import package49 from '../../data/projects/great-shelford-england.json';
import package50 from '../../data/projects/guyhirn-england.json';
import package51 from '../../data/projects/haddenham-england.json';
import package52 from '../../data/projects/haslingfield-england.json';
import package53 from '../../data/projects/helpston-england.json';
import package54 from '../../data/projects/hemingford-abbots-england.json';
import package55 from '../../data/projects/hemingford-grey-england.json';
import package56 from '../../data/projects/hildersham-england.json';
import package57 from '../../data/projects/hilton-england.json';
import package58 from '../../data/projects/hinxton-england.json';
import package59 from '../../data/projects/histon-england.json';
import package60 from '../../data/projects/holme-england.json';
import package61 from '../../data/projects/holywell-england.json';
import package62 from '../../data/projects/horningsea-england.json';
import package63 from '../../data/projects/houghton-england.json';
import package64 from '../../data/projects/ickleton-england.json';
import package65 from '../../data/projects/impington-england.json';
import package66 from '../../data/projects/isleham-england.json';
import package67 from '../../data/projects/kimbolton-england.json';
import package68 from '../../data/projects/kingston-england.json';
import package69 from '../../data/projects/landbeach-england.json';
import package70 from '../../data/projects/leverington-england.json';
import package71 from '../../data/projects/linton-england.json';
import package72 from '../../data/projects/little-abington-england.json';
import package73 from '../../data/projects/little-eversden-england.json';
import package74 from '../../data/projects/little-gidding-england.json';
import package75 from '../../data/projects/little-gransden-england.json';
import package76 from '../../data/projects/little-shelford-england.json';
import package77 from '../../data/projects/littleport-england.json';
import package78 from '../../data/projects/lode-england.json';
import package79 from '../../data/projects/longstanton-england.json';
import package80 from '../../data/projects/madingley-england.json';
import package81 from '../../data/projects/manea-england.json';
import package82 from '../../data/projects/march-england.json';
import package83 from '../../data/projects/marholm-england.json';
import package84 from '../../data/projects/maxey-england.json';
import package85 from '../../data/projects/melbourn-england.json';
import package86 from '../../data/projects/meldreth-england.json';
import package87 from '../../data/projects/milton-england.json';
import package88 from '../../data/projects/needingworth-england.json';
import package89 from '../../data/projects/northstowe-england.json';
import package90 from '../../data/projects/old-hurst-england.json';
import package91 from '../../data/projects/orwell-england.json';
import package92 from '../../data/projects/pampisford-england.json';
import package93 from '../../data/projects/parson-drove-england.json';
import package94 from '../../data/projects/peakirk-england.json';
import package95 from '../../data/projects/prickwillow-england.json';
import package96 from '../../data/projects/ramsey-england.json';
import package97 from '../../data/projects/reach-england.json';
import package98 from '../../data/projects/sawston-england.json';
import package99 from '../../data/projects/shepreth-england.json';
import package100 from '../../data/projects/soham-england.json';
import package101 from '../../data/projects/somersham-england.json';
import package102 from '../../data/projects/st-ives-england.json';
import package103 from '../../data/projects/st-neots-england.json';
import package104 from '../../data/projects/stibbington-england.json';
import package105 from '../../data/projects/stilton-england.json';
import package106 from '../../data/projects/stow-cum-quy-england.json';
import package107 from '../../data/projects/stretham-england.json';
import package108 from '../../data/projects/sutton-england.json';
import package109 from '../../data/projects/swaffham-bulbeck-england.json';
import package110 from '../../data/projects/swaffham-prior-england.json';
import package111 from '../../data/projects/swavesey-england.json';
import package112 from '../../data/projects/thorney-england.json';
import package113 from '../../data/projects/thriplow-england.json';
import package114 from '../../data/projects/tydd-st-giles-england.json';
import package115 from '../../data/projects/ufford-england.json';
import package116 from '../../data/projects/wansford-england.json';
import package117 from '../../data/projects/water-newton-england.json';
import package118 from '../../data/projects/waterbeach-england.json';
import package119 from '../../data/projects/whittlesey-england.json';
import package120 from '../../data/projects/whittlesford-england.json';
import package121 from '../../data/projects/wicken-england.json';
import package122 from '../../data/projects/willingham-england.json';
import package123 from '../../data/projects/wimblington-england.json';
import package124 from '../../data/projects/wimpole-england.json';
import package125 from '../../data/projects/wisbech-england.json';
import package126 from '../../data/projects/wisbech-st-mary-england.json';
import package127 from '../../data/projects/woodwalton-england.json';
import package128 from '../../data/projects/yaxley-england.json';

export const cambridgeshireSettlementPackages: ProjectPackage[] = [
  package0 as unknown as ProjectPackage,
  package1 as unknown as ProjectPackage,
  package2 as unknown as ProjectPackage,
  package3 as unknown as ProjectPackage,
  package4 as unknown as ProjectPackage,
  package5 as unknown as ProjectPackage,
  package6 as unknown as ProjectPackage,
  package7 as unknown as ProjectPackage,
  package8 as unknown as ProjectPackage,
  package9 as unknown as ProjectPackage,
  package10 as unknown as ProjectPackage,
  package11 as unknown as ProjectPackage,
  package12 as unknown as ProjectPackage,
  package13 as unknown as ProjectPackage,
  package14 as unknown as ProjectPackage,
  package15 as unknown as ProjectPackage,
  package16 as unknown as ProjectPackage,
  package17 as unknown as ProjectPackage,
  package18 as unknown as ProjectPackage,
  package19 as unknown as ProjectPackage,
  package20 as unknown as ProjectPackage,
  package21 as unknown as ProjectPackage,
  package22 as unknown as ProjectPackage,
  package23 as unknown as ProjectPackage,
  package24 as unknown as ProjectPackage,
  package25 as unknown as ProjectPackage,
  package26 as unknown as ProjectPackage,
  package27 as unknown as ProjectPackage,
  package28 as unknown as ProjectPackage,
  package29 as unknown as ProjectPackage,
  package30 as unknown as ProjectPackage,
  package31 as unknown as ProjectPackage,
  package32 as unknown as ProjectPackage,
  package33 as unknown as ProjectPackage,
  package34 as unknown as ProjectPackage,
  package35 as unknown as ProjectPackage,
  package36 as unknown as ProjectPackage,
  package37 as unknown as ProjectPackage,
  package38 as unknown as ProjectPackage,
  package39 as unknown as ProjectPackage,
  package40 as unknown as ProjectPackage,
  package41 as unknown as ProjectPackage,
  package42 as unknown as ProjectPackage,
  package43 as unknown as ProjectPackage,
  package44 as unknown as ProjectPackage,
  package45 as unknown as ProjectPackage,
  package46 as unknown as ProjectPackage,
  package47 as unknown as ProjectPackage,
  package48 as unknown as ProjectPackage,
  package49 as unknown as ProjectPackage,
  package50 as unknown as ProjectPackage,
  package51 as unknown as ProjectPackage,
  package52 as unknown as ProjectPackage,
  package53 as unknown as ProjectPackage,
  package54 as unknown as ProjectPackage,
  package55 as unknown as ProjectPackage,
  package56 as unknown as ProjectPackage,
  package57 as unknown as ProjectPackage,
  package58 as unknown as ProjectPackage,
  package59 as unknown as ProjectPackage,
  package60 as unknown as ProjectPackage,
  package61 as unknown as ProjectPackage,
  package62 as unknown as ProjectPackage,
  package63 as unknown as ProjectPackage,
  package64 as unknown as ProjectPackage,
  package65 as unknown as ProjectPackage,
  package66 as unknown as ProjectPackage,
  package67 as unknown as ProjectPackage,
  package68 as unknown as ProjectPackage,
  package69 as unknown as ProjectPackage,
  package70 as unknown as ProjectPackage,
  package71 as unknown as ProjectPackage,
  package72 as unknown as ProjectPackage,
  package73 as unknown as ProjectPackage,
  package74 as unknown as ProjectPackage,
  package75 as unknown as ProjectPackage,
  package76 as unknown as ProjectPackage,
  package77 as unknown as ProjectPackage,
  package78 as unknown as ProjectPackage,
  package79 as unknown as ProjectPackage,
  package80 as unknown as ProjectPackage,
  package81 as unknown as ProjectPackage,
  package82 as unknown as ProjectPackage,
  package83 as unknown as ProjectPackage,
  package84 as unknown as ProjectPackage,
  package85 as unknown as ProjectPackage,
  package86 as unknown as ProjectPackage,
  package87 as unknown as ProjectPackage,
  package88 as unknown as ProjectPackage,
  package89 as unknown as ProjectPackage,
  package90 as unknown as ProjectPackage,
  package91 as unknown as ProjectPackage,
  package92 as unknown as ProjectPackage,
  package93 as unknown as ProjectPackage,
  package94 as unknown as ProjectPackage,
  package95 as unknown as ProjectPackage,
  package96 as unknown as ProjectPackage,
  package97 as unknown as ProjectPackage,
  package98 as unknown as ProjectPackage,
  package99 as unknown as ProjectPackage,
  package100 as unknown as ProjectPackage,
  package101 as unknown as ProjectPackage,
  package102 as unknown as ProjectPackage,
  package103 as unknown as ProjectPackage,
  package104 as unknown as ProjectPackage,
  package105 as unknown as ProjectPackage,
  package106 as unknown as ProjectPackage,
  package107 as unknown as ProjectPackage,
  package108 as unknown as ProjectPackage,
  package109 as unknown as ProjectPackage,
  package110 as unknown as ProjectPackage,
  package111 as unknown as ProjectPackage,
  package112 as unknown as ProjectPackage,
  package113 as unknown as ProjectPackage,
  package114 as unknown as ProjectPackage,
  package115 as unknown as ProjectPackage,
  package116 as unknown as ProjectPackage,
  package117 as unknown as ProjectPackage,
  package118 as unknown as ProjectPackage,
  package119 as unknown as ProjectPackage,
  package120 as unknown as ProjectPackage,
  package121 as unknown as ProjectPackage,
  package122 as unknown as ProjectPackage,
  package123 as unknown as ProjectPackage,
  package124 as unknown as ProjectPackage,
  package125 as unknown as ProjectPackage,
  package126 as unknown as ProjectPackage,
  package127 as unknown as ProjectPackage,
  package128 as unknown as ProjectPackage,
];
